### ISSUE TITLE
Unable to find handler for (GET) /wd/hub/status for StandaloneChrome

### ISSUE THREAD

**Issue by szamacz** [SeleniumHQ/docker-selenium#1025]
## 🐛 Bug Report

When using latest selenium 4 docker image for standalone chrome(selenium/standalone-chrome:4.0.0-alpha-5-20200326) after running them on docker using command 
`docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-alpha-5-20200326` and trying to check grid availability using http://localhost:4444/wd/hub/status getting error as in the title.

Also when trying to run any tests on this grid getting similar error
[0000 ERR] System.NotImplementedException: Unable to find handler for (POST) /wd/hub/session
  Stack Trace:
     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)

Using selenium 4 alpha 05 as a nuget package in tests (C#) and its working fine with selenium docker 3 images and when running on local browsers. Problem exists only on selenium 4 docker image.

## To Reproduce

1. Run standalone chrome docker image for 4.0.0-alpha-5-20200326
2. Check grid status http://localhost:4444/wd/hub/status
3. Run test against this image

## Expected behavior

Grid returns its availability and tests are running.

## Environment

OS:  Windows 10
Docker-Selenium image version: standalone-chrome:4.0.0-alpha-5-20200326
Also provide the docker image id: 05085a824c64
-->
Docker version: 2.2.0.4

Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-alpha-5-20200326

**Comment by szamacz** [comment]
Looks that Selenium 4 needs to point to different urls
For grid http://localhost:4444/
and for grid status http://localhost:4444/status
