### ISSUE TITLE
Nodes should automatically deregister when receiving SIGTERM

### ISSUE THREAD

**Issue by bergenbrendanPFG** [SeleniumHQ/docker-selenium#1030]
## 🚀 Feature Proposal

When a Node is intentionally torn down permanently via SIGTERM, that Node does not deregister itself from it's associated Hub - the Hub still thinks it exists and will attempt to schedule jobs to it, resulting in Hub failure. In short: **`entry_point.sh` is not robust enough to deregister a Node from it's Hub, this can bring down a Grid temporarily and kill all active tests.**

Example logs from Hub after a Node was torn down with SIGTERM, and then Hub attempted to send a test to that Node:
```
16:57:13.506 ERROR [RequestHandler.process] - cannot forward the request Failed to connect to /{{ NODE-IP }}:5555
java.net.ConnectException: Failed to connect to /{{ NODE-IP }}:5555
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
        at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:99)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:133)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:63)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        ... 56 more
Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2020-04-09 16:57:27,048 WARN received SIGTERM indicating exit request
2020-04-09 16:57:27,048 INFO waiting for selenium-hub to die
2020-04-09 16:57:27,048 INFO stopped: selenium-hub (terminated by SIGTERM)
Shutdown complete
```

## Motivation

I want to automatically scale up/down Nodes using Horizontal Pod Autoscaling in Kubernetes and to do this without having Hub crash each time HPA removes a Node and Hub subsequently attempts to schedule a job to that Node.

Moreover, architecturally, the current CMD of Nodes and the Hub make assumptions about the current state of the Grid. It's best to have each component manage and clean up after itself on death - there is the possibility that a container can receive a SIGTERM for other reasons besides HPA, (like manually deleted Pods) this update would solve those too :)

## Example

With the above updates, users would be capable of creating automatically scaling Node pools! Nice!

In Kubernetes, that would look like:
```
helm install grid selenium/stable --set chrome.enabled=true
kubectl autoscale deployment grid-selenium-chrome --cpu-percent=50 --min=1 --max=10
```

## Solution Ideas

1. Modifying the CMD of Node images (or adding a file like `sigterm_entry_point.sh` as an alternative option that's linked in the README) that makes a REST call to localhost to deregister the Node from it's Hub on trapped SIGTERM.

2. An alternative would be to update the Hub jar so it doesn't die when it can't connect to 1-of-many-available Nodes. This seems more complex, but is probably the "right" choice from an architecture stance, especially since Hub cannot run in High Availability (in which case, I can close out this idea and move it to the Selenium repo)... Doing so would also solve problems like a new firewall appearing between a Hub and Node, or a Node dying for ANY reason... I'm not sure if this problem is specific enough to docker to warrant a docker-level solution or not... what do ya'll think?

**Comment by diemol** [comment]
@bergenbrendanPFG thanks for proposing this.
We are not touching Grid 3.x anymore, in fact, the code does not exist anymore in the tree.
For this case, what we are doing in Grid 4 (under development, and available in the alpha releases right now) is:
- We are implementing a retrial system for some cases when failed connections happen.
- Hub and nodes will have a health endpoint, that can be used in environments like Kubernetes to tear down a node when the health check does not pass.
- In addition, Grid 4 has a different architecture. It will have a router, a distributor, a session map, which allows to have a more distributed load. Documentation on this is being done as well.
So if a node dies, the environment should notice and take it down (pod/container etc...), and the hub should also retry somewhere else (but only for new test sessions, if the node dies in the middle of the test session, there is nothing to do there).

I am going to close this since it is already being addressed/planned in Grid 4.
