### ISSUE TITLE
Getting some error while using selenium grid

### ISSUE THREAD

**Issue by rijoparakkal** [SeleniumHQ/docker-selenium#1036]
## 🐛 Bug Report

When we use remote web driver using selenium grid, I'm getting following error sometime,
Most of the executions are success, but some of them are failing

org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'jenkins.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.104-78.84.amzn1.x86_64', java.version: '1.8.0_91'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:121)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:137)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:123)
	at org.openqa.selenium.json.Json.toType(Json.java:60)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:485)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.bfountain.page.CTLFlowPage.setRequiredYear(CTLFlowPage.groovy:306)
	at com.bfountain.page.CTLFlowPage$setRequiredYear$13.callCurrent(Unknown Source)
	at com.bfountain.page.CTLFlowTestPage.selectCustomYear(CTLFlowTestPage.groovy:169)
	at com.bfountain.page.CTLFlowTestPage$selectCustomYear.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.bfountain.page.CTLFilterTestPage.verifySource(CTLFilterTestPage.groovy:351)
	at com.bfountain.page.CTLFilterTestPage$verifySource$39.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:1

## To Reproduce

We are using docker containers for hub and nodes
Version: v.3.141.59

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: v.3.141.59
-->
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
@rijoparakkal how can we reproduce the issue? Which versions are you using of the docker images? Seems the issue template is not completely filled out.

**Comment by rijoparakkal** [comment]
In some scenarios, it failing and in selenium grid, we can see enough free slots.
Docker selenium version : Grid Console v.3.141.59
node docker : selenium/node-chrome:3.141.59-xenon
hub docker : Selenium/hub:3.141.59

**Comment by diemol** [comment]
Can you please provide the code you used to bump into this error?

**Comment by rijoparakkal** [comment]
@diemol It is not stable. Scripts are working with normal browser stack. But when we use the selenium grid it is failing for almost all scenarios. It is failing in different places

**Comment by diemol** [comment]
Sorry @rijoparakkal, I am not following...
Without the code used to bump into this error, we cannot really find a way to help you out 🤷

**Comment by ddavison** [comment]
One thing I'd add is you should strive to achieve 1 test per 1 node.  Right now you are running 20:1 which is a ratio that might cripple containers that are already supposed to be smaller.

I'd certainly try that, but pertaining to your issue - there doesn't seem to be anything more that we can do.  One thing to look at is your `jenkins.localdomain` instance.  Could "that" be failing?

Closing.
