### ISSUE TITLE
selenium grid 4 issue

### ISSUE THREAD

**Issue by minhnguyenvan95** [SeleniumHQ/docker-selenium#1160]
## 🐛 Bug Report

Get an error when trying to execute remote selenium grid 4 in k8s

## To Reproduce

- kubectl apply k8s...fullgrid.yaml
- Setup webdriver remote to selenium-router:4444

## k8s log
```
selenium-chrome-node-deployment-85d87d4469-zclj7
selenium-distributor-deployment-5bb84bf6fc-9q6zh
selenium-event-bus-deployment-6df4767b9c-dtnsq
selenium-ff-node-deployment-8659d66c4-gwx2x
selenium-router-deployment-8498b59594-h9bjc
selenium-session-queuer-deployment-7bc66946b6-j8wvm
selenium-sessions-deployment-5d4b8cbb44-x6dbv
[selenium-router-deployment-8498b59594-h9bjc] 03:22:23.867 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "bb1fb3efef31088e3d36ed5f86fcfc35","spanId": "97c71185d48b3d83","spanKind": "INTERNAL","eventTime": 1607916143845262135,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.target": "\u002fsession","http.flavor": 1,"http.user_agent": "selenium\u002f3.141.59 (java unix)","http.handler_class": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer","http.method": "POST","http.host": "selenium-router:4444","http.request_content_length": "1107","http.scheme": "HTTP"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7] Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 2473 
[selenium-router-deployment-8498b59594-h9bjc]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] Only local connections are allowed. 
[selenium-sessions-deployment-5d4b8cbb44-x6dbv] 03:22:23.627 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "f2481a147f7fb54ef1706ea0d32642f4","spanId": "25aa93b95d989f46","spanKind": "INTERNAL","eventTime": 1607916143615163434,"eventName": "Added session into local session map","attributes": {"logger": "org.openqa.selenium.grid.sessionmap.local.LocalSessionMap","session.id": "63824c49d5751347005cc8e2ceb90fec"}} 
[selenium-session-queuer-deployment-7bc66946b6-j8wvm] 03:22:15.486 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "bb1fb3efef31088e3d36ed5f86fcfc35","spanId": "1a9728f134b02509","spanKind": "INTERNAL","eventTime": 1607916135482573220,"eventName": "Add new session request to the queue","attributes": {"request.added": true,"logger": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","request.id": "3e5df234-550f-4273-a833-08983ddff7d4"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe. 
[selenium-distributor-deployment-5bb84bf6fc-9q6zh] 03:22:23.741 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "f2481a147f7fb54ef1706ea0d32642f4","spanId": "2dbd039e66213394","spanKind": "INTERNAL","eventTime": 1607916135754619316,"eventName": "Session request received by the distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"chrome\",\n    \"acceptSslCerts\": true,\n    \"goog:chromeOptions\": {\n      \"args\": [\n        \"--disable-extensions\",\n        \"--disable-infobars\",\n        \"--start-maximized\",\n        \"--disable-notifications\",\n        \"--disable-geolocation\"\n      ],\n      \"extensions\": [\n      ],\n      \"prefs\": {\n        \"profile.default_content_settings.popups\": 0,\n        \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n      }\n    },\n    \"acceptInsecureCerts\": true\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"acceptInsecureCerts\": true,\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"args\": [\n            \"--disable-extensions\",\n            \"--disable-infobars\",\n            \"--start-maximized\",\n            \"--disable-notifications\",\n            \"--disable-geolocation\"\n          ],\n          \"extensions\": [\n          ],\n          \"prefs\": {\n            \"profile.default_content_settings.popups\": 0,\n            \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n          }\n        }\n      }\n    ]\n  }\n}"}} 
[selenium-sessions-deployment-5d4b8cbb44-x6dbv]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] ChromeDriver was started successfully. 
[selenium-session-queuer-deployment-7bc66946b6-j8wvm]  
[selenium-distributor-deployment-5bb84bf6fc-9q6zh]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] [1607916136.641][SEVERE]: bind() failed: Cannot assign requested address (99) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: No SLF4J providers were found. 
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: Defaulting to no-operation (NOP) logger implementation 
[selenium-distributor-deployment-5bb84bf6fc-9q6zh] 03:22:23.742 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "f2481a147f7fb54ef1706ea0d32642f4","spanId": "2dbd039e66213394","spanKind": "INTERNAL","eventTime": 1607916143735664501,"eventName": "Session created by the distributor","attributes": {"session.uri": "http:\u002f\u002f10.233.125.104:5555","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"chrome\",\n    \"acceptSslCerts\": true,\n    \"goog:chromeOptions\": {\n      \"args\": [\n        \"--disable-extensions\",\n        \"--disable-infobars\",\n        \"--start-maximized\",\n        \"--disable-notifications\",\n        \"--disable-geolocation\"\n      ],\n      \"extensions\": [\n      ],\n      \"prefs\": {\n        \"profile.default_content_settings.popups\": 0,\n        \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n      }\n    },\n    \"acceptInsecureCerts\": true\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"acceptInsecureCerts\": true,\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"args\": [\n            \"--disable-extensions\",\n            \"--disable-infobars\",\n            \"--start-maximized\",\n            \"--disable-notifications\",\n            \"--disable-geolocation\"\n          ],\n          \"extensions\": [\n          ],\n          \"prefs\": {\n            \"profile.default_content_settings.popups\": 0,\n            \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n          }\n        }\n      }\n    ]\n  }\n}","session.capabilities": "Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 87.0.4280.88, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: \u002ftmp\u002f.com.google.Chrome.eG9jzA}, goog:chromeOptions: {debuggerAddress: localhost:34893}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:options: {cdp: http:\u002f\u002f10.233.125.104:5555\u002f...}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}","session.id": "63824c49d5751347005cc8e2ceb90fec"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details. 
[selenium-distributor-deployment-5bb84bf6fc-9q6zh]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8. 
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: Ignoring binding found at [jar:file:/opt/selenium/selenium-server.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
[selenium-chrome-node-deployment-85d87d4469-zclj7] SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation. 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 03:22:23.190 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 03:22:23.265 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "f2481a147f7fb54ef1706ea0d32642f4","spanId": "209e700c48bf57d4","spanKind": "INTERNAL","eventTime": 1607916143193657941,"eventName": "Driver service created session","attributes": {"upstream.dialect": "W3C","driver.url": "http:\u002f\u002flocalhost:2473","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","downstream.dialect": "W3C","session.capabilities": "Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-extensions, --disable-infobars, --start-maximized, --disable-notifications, --disable-geolocation], extensions: [], prefs: {download.default_directory: \u002fapp\\fileDownloaded, profile.default_content_settings.popups: 0}}}","driver.response": "(Response: SessionID: 63824c49d5751347005cc8e2ceb90fec, Status: 0, Value: {acceptInsecureCerts=true, browserName=chrome, browserVersion=87.0.4280.88, chrome={chromedriverVersion=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs\u002fbranch-heads\u002f4280@{#1761}), userDataDir=\u002ftmp\u002f.com.google.Chrome.eG9jzA}, goog:chromeOptions={debuggerAddress=localhost:34893}, networkConnectionEnabled=false, pageLoadStrategy=normal, platformName=linux, proxy=Proxy(), setWindowRect=true, strictFileInteractability=false, timeouts={implicit=0, pageLoad=300000, script=30000}, unhandledPromptBehavior=dismiss and notify, webauthn:virtualAuthenticators=true})"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] 03:22:23.300 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "f2481a147f7fb54ef1706ea0d32642f4","spanId": "0919fa3c9a9700f4","spanKind": "INTERNAL","eventTime": 1607916143299501927,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.target": "\u002fse\u002fgrid\u002fnode\u002fsession","http.flavor": 1,"http.user_agent": "selenium\u002f4.0.0-beta-1 (java unix)","http.handler_class": "org.openqa.selenium.grid.security.RequiresSecretFilter$$Lambda$309\u002f584508804","http.method": "POST","http.host": "10.233.125.104:5555","http.scheme": "HTTP"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7]  









[selenium-distributor-deployment-5bb84bf6fc-9q6zh] 03:23:24.341 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "08544e5a3fd2d990121f14f279e8270d","spanId": "d800f3d8b42fa523","spanKind": "INTERNAL","eventTime": 1607916204329715819,"eventName": "Session request received by the distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "{\n  \"desiredCapabilities\": {\n    \"browserName\": \"chrome\",\n    \"acceptSslCerts\": true,\n    \"goog:chromeOptions\": {\n      \"args\": [\n        \"--disable-extensions\",\n        \"--disable-infobars\",\n        \"--start-maximized\",\n        \"--disable-notifications\",\n        \"--disable-geolocation\"\n      ],\n      \"extensions\": [\n      ],\n      \"prefs\": {\n        \"profile.default_content_settings.popups\": 0,\n        \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n      }\n    },\n    \"acceptInsecureCerts\": true\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"acceptInsecureCerts\": true,\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"args\": [\n            \"--disable-extensions\",\n            \"--disable-infobars\",\n            \"--start-maximized\",\n            \"--disable-notifications\",\n            \"--disable-geolocation\"\n          ],\n          \"extensions\": [\n          ],\n          \"prefs\": {\n            \"profile.default_content_settings.popups\": 0,\n            \"download.default_directory\": \"\\u002fapp\\\\fileDownloaded\"\n          }\n        }\n      }\n    ]\n  }\n}"}} 
[selenium-distributor-deployment-5bb84bf6fc-9q6zh]  
[selenium-distributor-deployment-5bb84bf6fc-9q6zh] 03:23:24.382 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "08544e5a3fd2d990121f14f279e8270d","spanId": "278438e8d6b2ca59","spanKind": "INTERNAL","eventTime": 1607916204381563664,"eventName": "Retry adding to front of queue. All slots are busy.","attributes": {"request.retry_add": true,"request": "(POST) \u002fsession","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.id": "e68c68e1-2a06-48e3-b3b7-c527ffcde95d"}} 
[selenium-distributor-deployment-5bb84bf6fc-9q6zh]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] 03:23:24.377 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: NettyHttpHandler request execution error 
[selenium-chrome-node-deployment-85d87d4469-zclj7] java.lang.RuntimeException: NettyHttpHandler request execution error 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:60) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:115) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:317) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.node.Node.execute(Node.java:202) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.lang.Thread.run(Thread.java:748) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:2473 after 60000 ms 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	... 30 more 
[selenium-chrome-node-deployment-85d87d4469-zclj7] Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:2473 after 60000 ms 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) 
[selenium-session-queuer-deployment-7bc66946b6-j8wvm] 03:23:24.288 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "322a42c62346d92c6432dfa172a9ed04","spanId": "ae11d3406bf9bf49","spanKind": "INTERNAL","eventTime": 1607916204287467640,"eventName": "Add new session request to the queue","attributes": {"request.added": true,"logger": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","request.id": "e68c68e1-2a06-48e3-b3b7-c527ffcde95d"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) 
[selenium-session-queuer-deployment-7bc66946b6-j8wvm]  
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) 
[selenium-session-queuer-deployment-7bc66946b6-j8wvm] 03:23:29.361 INFO [LocalNewSessionQueue.retryRequest] - Adding request back to the queue. All slots are busy. Request: e68c68e1-2a06-48e3-b3b7-c527ffcde95d 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 	... 1 more 
[selenium-chrome-node-deployment-85d87d4469-zclj7] 03:23:24.378 WARN [LoggingOptions$1.lambda$export$0] - {"traceId": "5dff77096661d7ac115dd88ee1a67c87","spanId": "d2e8f761112da486","spanKind": "INTERNAL","eventTime": 1607916204377417823,"eventName": "exception","attributes": {"http.target": "\u002fsession\u002f63824c49d5751347005cc8e2ceb90fec\u002furl","exception.type": "java.lang.RuntimeException","http.flavor": 1,"http.user_agent": "selenium\u002f3.141.59 (java unix)","exception.message": "Unable to execute request: NettyHttpHandler request execution error","http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","exception.stacktrace": "java.lang.RuntimeException: NettyHttpHandler request execution error\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:60)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)\n\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:115)\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:317)\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:202)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)\n\tat org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost\u002f127.0.0.1:2473 after 60000 ms\n\tat java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)\n\t... 30 more\nCaused by: java.util.concurrent.TimeoutException: Request timeout to localhost\u002f127.0.0.1:2473 after 60000 ms\n\tat org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)\n\tat org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)\n\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\n","http.method": "POST","http.host": "selenium-router:4444","http.request_content_length": "76","http.scheme": "HTTP"}} 
[selenium-chrome-node-deployment-85d87d4469-zclj7]  

```

**Comment by minhnguyenvan95** [comment]
Look like we have mistake , image selenium/session-queuer:4.0.0-beta-1-prerelease-20201208 should open 5559 port k8s-deploy..fullgrid.yaml row 165, and port 5900 in row 341 and 408

**Comment by minhnguyenvan95** [comment]
selenium-session-queuer was killed but selenium-router-deployment still remember its ip address ( how about impl adaptive refresh? ) 

```
[selenium-router-deployment-6dc58c7995-qq4qk] Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer/10.233.31.181:5559 after 60000 ms 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	... 30 more 
[selenium-router-deployment-6dc58c7995-qq4qk] Caused by: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer/10.233.31.181:5559 after 60000 ms 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
[selenium-router-deployment-6dc58c7995-qq4qk] 	... 1 more 
```

**Comment by EIrwin** [comment]
@minhnguyenvan95 what was the outcome of this? Were you able to get it fixed and running? I have the same error and trying to understand the fix?

**Comment by zzvara** [comment]
@EIrwin I have the same problem but could not fix it. The IP address is correct in my case.

**Comment by wzlee** [comment]
this proplem is still exsit in version 4.0.0-beta-4-20210608，is there any outcome?
