### ISSUE TITLE
Unable to see Grid UI when running docker-full on swarm

### ISSUE THREAD

**Issue by mcopjan** [SeleniumHQ/docker-selenium#1186]
## 🐛 Bug Report
**4.0.0-beta-1-prerelease-20210114**
When running the following docker full model on swarm using 

[compose.zip](https://github.com/SeleniumHQ/docker-selenium/files/5867070/compose.zip)

![image](https://user-images.githubusercontent.com/20699180/105715870-069ffe80-5f16-11eb-83e7-8e56c25f8fbb.png)
 I am able to run tests but I am also expecting to display Grid ui on http:/<selenium/router IP>:4444/ui/index.html (this url works when running https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v2.yml) instead I am getting
`
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002fui\u002findex.html",
    "stacktrace": ""
  }
}
`

**Comment by diemol** [comment]
Thank you for reporting this, @mcopjan!

We just fixed it and there will be soon a new docker-selenium release.

**Comment by diemol** [comment]
Reopening as we missed a case that is throwing an error:

```
selenium-router            | 17:58:11.858 WARN [SimpleDataFetcherExceptionHandler.onException] - Exception while fetching data (/grid/sessionQueueSize) : java.lang.reflect.InvocationTargetException
selenium-router            | graphql.GraphQLException: java.lang.reflect.InvocationTargetException
selenium-router            | 	at graphql.schema.PropertyFetchingImpl.invokeMethod(PropertyFetchingImpl.java:254)
selenium-router            | 	at graphql.schema.PropertyFetchingImpl.getPropertyViaGetterUsingPrefix(PropertyFetchingImpl.java:145)
selenium-router            | 	at graphql.schema.PropertyFetchingImpl.getPropertyViaGetterMethod(PropertyFetchingImpl.java:138)
selenium-router            | 	at graphql.schema.PropertyFetchingImpl.getPropertyValue(PropertyFetchingImpl.java:96)
selenium-router            | 	at graphql.schema.PropertyDataFetcherHelper.getPropertyValue(PropertyDataFetcherHelper.java:19)
selenium-router            | 	at graphql.schema.PropertyDataFetcher.get(PropertyDataFetcher.java:120)
selenium-router            | 	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
selenium-router            | 	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
selenium-router            | 	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
selenium-router            | 	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:646)
selenium-router            | 	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438)
selenium-router            | 	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390)
selenium-router            | 	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:205)
selenium-router            | 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
selenium-router            | 	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
selenium-router            | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
selenium-router            | 	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:204)
selenium-router            | 	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
selenium-router            | 	at graphql.execution.Execution.executeOperation(Execution.java:165)
selenium-router            | 	at graphql.execution.Execution.execute(Execution.java:104)
selenium-router            | 	at graphql.GraphQL.execute(GraphQL.java:557)
selenium-router            | 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
selenium-router            | 	at graphql.GraphQL.executeAsync(GraphQL.java:446)
selenium-router            | 	at graphql.GraphQL.execute(GraphQL.java:377)
selenium-router            | 	at org.openqa.selenium.grid.graphql.GraphqlHandler.execute(GraphqlHandler.java:147)
selenium-router            | 	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
selenium-router            | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router            | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router            | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router            | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
selenium-router            | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router            | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router            | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router            | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router            | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium-router            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
selenium-router            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
selenium-router            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
selenium-router            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
selenium-router            | 	at java.lang.Thread.run(Thread.java:748)
selenium-router            | Caused by: java.lang.reflect.InvocationTargetException
selenium-router            | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
selenium-router            | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
selenium-router            | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
selenium-router            | 	at java.lang.reflect.Method.invoke(Method.java:498)
selenium-router            | 	at graphql.schema.PropertyFetchingImpl.invokeMethod(PropertyFetchingImpl.java:251)
selenium-router            | 	... 39 more
selenium-router            | Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
selenium-router            | 	at org.openqa.selenium.grid.graphql.Grid.getSessionQueueSize(Grid.java:127)
selenium-router            | 	... 44 more
```
