### ISSUE TITLE
RuntimeException: Unexpected result for screenshot command: null

### ISSUE THREAD

**Issue by ValorHeart** [SeleniumHQ/docker-selenium#1214]
## 🐛 Bug Report

Hello, Weird issue going on, it's not reproducible easily, happened only twice for me in a month distance between each other.
I'm not sure it is related, but first i get stale element exception which i'm catching and trying catching the element again, the i'm getting stale element again for the second time and the test fails, for the test finalization step i'm trying to take a screen shot and getting this weird exception:

```
java.lang.RuntimeException: Unexpected result for screenshot command: null
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:304)
at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
at com.sun.proxy.$Proxy25.getScreenshotAs(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.getScreenshotAs(EventFiringWebDriver.java:302)
at skywalker.auto.infra.web.ScreenshotTaker.takeScreenshotAddToReport(ScreenshotTaker.java:41)
at skywalker.auto.tests.ui.AbstractUiTest.takeScreenshot(AbstractUiTest.java:218)
at skywalker.auto.tests.ui.AbstractUiTest.finalizeTest(AbstractUiTest.java:257)
at skywalker.auto.tests.ui.PB.daily.todayView.gridView._XXXX_UI_PB_Daily_Today_GridView_DevelopersApiLinkTest.finalizeTest(_XXXX_UI_PB_Daily_Today_GridView_DevelopersApiLinkTest.java:35)
at skywalker.auto.tests.ui.AbstractUiTest.runTest(AbstractUiTest.java:249)
at skywalker.auto.tests.ui.AbstractUiTest.runTest(AbstractUiTest.java:233)
at skywalker.auto.tests.ui.PB.daily.todayView.gridView._XXXX_UI_PB_Daily_Today_GridView_DevelopersApiLinkTest._XXXX_UI_PB_Daily_Today_GridView_DevelopersApiLink(_XXXX_UI_PB_Daily_Today_GridView_DevelopersApiLinkTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

After this issue occured, the browser session seems to be lost and the rest of the tests that are trying to use the session are getting:
org.openqa.selenium.WebDriverException: Session [d7981b7d05f6cbbbe39c3fe598c1d536] was terminated due to SO_TIMEOUT

## To Reproduce

Try to click on URL link (href) while it is being staled, try again and get stale again, take a screen shot

## Expected behavior

To take the screen shot as normal behavior

## Environment

OS: Ubuntu 20.04.02
Docker-Selenium image version: 3, 3.141
Docker image: Grid latest, Chrome latest.

Docker version: 20.10.2, build 2291f61
Docker-Compose version (if applicable): 3
Exact Docker command to start the containers:
```
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    restart: always
    environment:
      - GRID_BROWSER_TIMEOUT=120
      - GRID_TIMEOUT=1200
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  node-chrome-1:
    image: selenium/node-chrome-debug:latest
    container_name: node-chrome-1
    restart: always
    volumes:
      - /dev/shm:/dev/shm
      - /home/ubuntu/browser_downloads:/var/tmp/browser_downloads
    depends_on:
      - selenium-hub
    environment:
      - NODE_APPLICATION_NAME=chrome
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - TZ=Asia/Jerusalem
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    ports:
      - "5910:5900"
    networks:
      - selenium-grid

networks:
  selenium-grid:
    external: true
```

**Comment by diemol** [comment]
Not sure how we can help without a way to reproduce the issue.

If you can find a way to share a test case for us to look at, we'd be happy to dig into it and see if this is a Selenium issue or not.

**Comment by ValorHeart** [comment]
> Not sure how we can help without a way to reproduce the issue.
> 
> If you can find a way to share a test case for us to look at, we'd be happy to dig into it and see if this is a Selenium issue or not.

Thanks, i've added for now try/catch so this issue won't happen again so i'm not sure i'll be able to reproduce it soon.
i'll close the issue for now,
Adi
