### ISSUE TITLE
issue when using different machines/VMs with selenium-hub 4.0.0-beta-1-20210215

### ISSUE THREAD

**Issue by idexlab** [SeleniumHQ/docker-selenium#1218]
## 🐛 Bug Report

I'm trying to deploy on several selenium-hub servers with docker but I have a problem with the configuration of the chrome node.
My chrome node connects well to the remote server but the node communicates the local docker ip address of machine 2 but it should be the ip of machine 2.

INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.7:5555

## To Reproduce

docker-compose machine 1
```
  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    container_name: selenium-hub
    environment:
      - "JAVA_OPTS=-Xms5g -Xmx5g"
      - SE_HUB_HOST=<ip-from-machine-1>
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

docker-compose machine 2
```
chrome:
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=<ip-from-machine-1>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - START_XVFB=false
      - SE_NODE_MAX_CONCURRENT_SESSIONS=5
      - SE_NODE_HOST=<ip-from-machine-2>
    ports:
      - "5555:5555"
```

logs after selenium hub started:
```
selenium-hub    | 2021-02-23 10:20:19,077 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub    | 2021-02-23 10:20:19,081 INFO supervisord started with pid 7
selenium-hub    | 2021-02-23 10:20:20,085 INFO spawned: 'selenium-grid-hub' with pid 9
selenium-hub    | Using SE_HUB_HOST: <ip-from-machine-1>
selenium-hub    | 2021-02-23 10:20:20,096 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 10:20:20.794 INFO [LogManager$RootLogger.log] - Using the system default encoding
selenium-hub    | 10:20:20.803 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 10:20:20.951 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.18.0.17:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.18.0.17:4443]
selenium-hub    | 10:20:21.070 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.18.0.17:4442 and tcp://172.18.0.17:4443
selenium-hub    | 10:20:21.096 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub    | 10:20:21.198 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub    | 10:20:22.308 INFO [Hub.execute] - Started Selenium Hub 4.0.0-beta-1 (revision Unknown): http://<ip-from-machine-1>:4444
```

logs after chrome started:
```
chrome_1        | 2021-02-23 09:28:59,756 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1        | 2021-02-23 09:28:59,759 INFO supervisord started with pid 7
chrome_1        | 2021-02-23 09:29:00,762 INFO spawned: 'xvfb' with pid 9
chrome_1        | 2021-02-23 09:29:00,764 INFO spawned: 'vnc' with pid 10
chrome_1        | 2021-02-23 09:29:00,766 INFO spawned: 'selenium-node' with pid 11
chrome_1        | 2021-02-23 09:29:00,768 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2021-02-23 09:29:00,768 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2021-02-23 09:29:00,768 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2021-02-23 09:29:00,768 INFO exited: xvfb (exit status 0; expected)
chrome_1        | 2021-02-23 09:29:00,769 INFO exited: vnc (exit status 0; expected)
chrome_1        | Configuring server...
chrome_1        | Setting up SE_NODE_PORT...
chrome_1        | Starting Selenium Grid Node with configuration: 
chrome_1        | [events]
chrome_1        | publish = "tcp://<ip-from-machine-2>:4442"
chrome_1        | subscribe = "tcp://<ip-from-machine-2>:4443"
chrome_1        | 
chrome_1        | hostname = "<ip-from-machine-2>"
chrome_1        | [node]
chrome_1        | max-concurrent-sessions = 5
chrome_1        | 
chrome_1        | 09:29:01.463 INFO [LogManager$RootLogger.log] - Using the system default encoding
chrome_1        | 09:29:01.486 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
chrome_1        | 09:29:01.567 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://<ip-from-machine-1>:4442 and tcp://<ip-from-machine-1>:4443
chrome_1        | 09:29:01.611 INFO [UnboundZmqEventBus.<init>] - Sockets created
chrome_1        | 09:29:01.728 INFO [UnboundZmqEventBus.<init>] - Event bus ready
chrome_1        | 09:29:01.838 INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.7:5555
chrome_1        | 09:29:01.890 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 4 times
chrome_1        | 09:29:01.902 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
chrome_1        | 09:29:02.080 INFO [NodeServer$1.start] - Starting registration process for node id 298c4a95-5ae4-4718-9ac0-e4d1f2d50bca
chrome_1        | 09:29:02.081 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-1 (revision Unknown): http://172.18.0.7:5555
```
logs selenium-hub after chrome started:
```
selenium-hub    | 10:24:11.808 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
selenium-hub    | 10:24:12.221 INFO [LocalDistributor.add] - Added node 59478d3f-26ef-4a6f-9389-b4ca422b8ba8 at http://172.18.0.7:5555.
selenium-hub    | 10:24:12.284 WARN [UnboundZmqEventBus.lambda$notifyListeners$10] - Caught exception from listener: org.openqa.selenium.events.EventListener@62f43cc5
selenium-hub    | java.io.UncheckedIOException: java.net.ConnectException: Connection refused: /172.18.0.7:5555
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
selenium-hub    | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium-hub    | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
selenium-hub    | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium-hub    | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-hub    | 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:93)
selenium-hub    | 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:56)
selenium-hub    | 	at org.openqa.selenium.grid.node.remote.RemoteNode.getStatus(RemoteNode.java:177)
selenium-hub    | 	at org.openqa.selenium.grid.distributor.local.LocalDistributor.add(LocalDistributor.java:289)
selenium-hub    | 	at org.openqa.selenium.grid.distributor.local.LocalDistributor.register(LocalDistributor.java:276)
selenium-hub    | 	at org.openqa.selenium.events.EventListener.accept(EventListener.java:43)
selenium-hub    | 	at org.openqa.selenium.events.EventListener.accept(EventListener.java:25)
selenium-hub    | 	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.lambda$notifyListeners$10(UnboundZmqEventBus.java:252)
selenium-hub    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
selenium-hub    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
selenium-hub    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
selenium-hub    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
selenium-hub    | 	at java.lang.Thread.run(Thread.java:748)
selenium-hub    | Caused by: java.net.ConnectException: Connection refused: /172.18.0.7:5555
selenium-hub    | 	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
selenium-hub    | 	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
selenium-hub    | 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
selenium-hub    | 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
selenium-hub    | 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
selenium-hub    | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
selenium-hub    | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
selenium-hub    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
selenium-hub    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    | 	... 1 more
selenium-hub    | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.18.0.7:5555
selenium-hub    | Caused by: java.net.ConnectException: Connection refused
selenium-hub    | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
selenium-hub    | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
selenium-hub    | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
selenium-hub    | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
selenium-hub    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
selenium-hub    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    | 	at java.lang.Thread.run(Thread.java:748)
```

## Expected behavior

the chrome node should communicate the ip given in SE_NODE_HOST to selenium-hub. 
Currently it is the local docker ip that is communicated

```
INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.7:5555
```

## Test script reproducing this issue (when applicable)

- start selenium_hub on machine 1
- start node-chrome on machine 2

## Environment

OS: Ubuntu 18.04.3 LTS
Docker-Selenium image version: selenium/hub:4.0.0-beta-1-20210215
Docker version: 19.03.5, build 633a0ea838
Docker-Compose version (if applicable): 3

**Comment by stawr93** [comment]
seems like the bug is in https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/generate_config - it does not write `[server]` to _config.toml_ if only SE_NODE_HOST set.

workaround is to set both SE_NODE_HOST and SE_NODE_PORT

**Comment by diemol** [comment]
Yes, this was just fixed in https://github.com/SeleniumHQ/docker-selenium/commit/b3e57343237c2b6e23cd36efa6c228934d6b52fa, a release will be done in 1-2 days.

**Comment by idexlab** [comment]
it's good for me, thank you

**Comment by timrajan** [comment]
Well @idexlab  - I struggled with this issue for the past one week. So, how I solved it, I just removed the depends-on in docker compose and started the selenium-hub at last after starting every other nodes. This made sure, all the nodes are connected to the hub.

**Comment by timrajan** [comment]
is there a way to do a hard wait in the selenium hub node or in docker-compose.yml to start the selenium-hub after say 2 mins of all the selenium ( chrome + ff + edge ) running ??
