### ISSUE TITLE
Request timeout to selenium-session-queuer

### ISSUE THREAD

**Issue by zzvara** [SeleniumHQ/docker-selenium#1221]
## 🐛 Bug Report

```
2021-03-01 18:06:00,356 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-router.conf" during parsing
2021-03-01 18:06:00,358 INFO supervisord started with pid 7
2021-03-01 18:06:01,360 INFO spawned: 'selenium-grid-router' with pid 9
Starting Selenium Grid Router...
2021-03-01 18:06:01,367 INFO success: selenium-grid-router entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --max-threads 20
18:06:01.708 INFO [LogManager$RootLogger.log] - Using the system default encoding
18:06:01.710 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
18:06:02.584 INFO [RouterServer.execute] - Started Selenium router 4.0.0-beta-1 (revision 02d5e641d5): http://10.233.85.108:4444
18:06:18.235 ERROR [HashedWheelTimer.reportTooManyInstances] - You are creating too many HashedWheelTimer instances. HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.
18:07:40.361 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: NettyHttpHandler request execution error
java.lang.RuntimeException: NettyHttpHandler request execution error
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:75)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:90)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:137)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:90)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
	at org.openqa.selenium.grid.web.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:29)
	at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer/10.233.14.236:5559 after 60000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 32 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer/10.233.14.236:5559 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
18:07:40.362 WARN [LoggingOptions$1.lambda$export$1] - {"traceId": "b2589257a1b6ae90b3161ccea54877d4","spanId": "2f3d0dd4d73c7253","spanKind": "INTERNAL","eventTime": 1614622060360479895,"eventName": "exception","attributes": {"http.target": "\u002fsession","exception.type": "java.lang.RuntimeException","http.flavor": 1,"http.user_agent": "selenium\u002f4.0.0-alpha.4 (js windows)","exception.message": "Unable to execute request: NettyHttpHandler request execution error","http.handler_class": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer","exception.stacktrace": "java.lang.RuntimeException: NettyHttpHandler request execution error\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:75)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:90)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:137)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:90)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.web.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:29)\n\tat org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.grid.web.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer\u002f10.233.14.236:5559 after 60000 ms\n\tat java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)\n\t... 32 more\nCaused by: java.util.concurrent.TimeoutException: Request timeout to selenium-session-queuer\u002f10.233.14.236:5559 after 60000 ms\n\tat org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)\n\tat org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)\n\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\n","http.method": "POST","http.host": "10.233.52.235:4444","http.request_content_length": "104","http.scheme": "HTTP"}}
```

The above router is deployed using HelmRelease as follows:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selenium-grid-advanced
  namespace: experimental
spec:
  releaseName: selenium-grid-advanced
  chart:
    # https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart/chart/selenium-grid
    repository: https://#redacted#/artifactory/releases
    name: selenium-grid
    version: 0.1.0
  values:
    isolateComponents: true
    chromeNode:
      replicas: 30
    firefoxNode:
      replicas: 1
    operaNode:
      replicas: 1
    components:
      router:
        resources:
          requests:
            memory: "32Gi"
          limits:
            memory: "32Gi"
      extraEnvironmentVariables:
        - name: JAVA_OPTS
          # @note "POOL_MAX" not confirmed that it is working.
          value: "-Xmx20g -Xms2g -XX:+UseG1GC -DPOOL_MAX=512"
        - name: SE_OPTS
          value: "--max-threads 20"
        - name: SE_SESSION_REQUEST_TIMEOUT
          value: "15"
```

Executing into the Pod, connection can be made through `wget`:

![image](https://user-images.githubusercontent.com/8371789/109553944-eabee800-7ad3-11eb-8826-45034961a1d7.png)

## To Reproduce

Reproduce with the above HelmRelease.

## Expected behavior

Any `selenium-side-runner` connecting to the `route` not to get timed out in 60 seconds.

## Test script reproducing this issue (when applicable)

Deploy HelmRelease to Kubernetes and attempt to run any test suite.

## Environment

OS: Flatcar Container Linux by Kinvolk stable (2605.12.0)
Docker-Selenium image version: 4.0.0-beta-1-20210215
Docker version: Docker version 19.03.14, build f8db474
Kubernetes: v1.18.10

**Comment by diemol** [comment]
Please alter the values in the chart and use the most recent tag https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-1-20210215

This bug has already been fixed.

I can see that the most recent tag is not being used because the commit being referenced during the startup
>Started Selenium router 4.0.0-beta-1 (revision 02d5e641d5)

belongs to a pre-release and not the `beta-1` release .

**Comment by zzvara** [comment]
@diemol I can not say I did not check that before posting, but it seems reading among numbers 20210102210 is harder for me than it seems. Thanks!

After updating the image, the issue is gone!
