### ISSUE TITLE
Router after a few successful tests: Unable to execute request: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by zzvara** [SeleniumHQ/docker-selenium#1222]
## 🐛 Bug Report

Running Selenium tests timeout as follows:

```
15:49:07.004 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.util.concurrent.TimeoutException
Build info: version: '4.0.0-beta-1', revision: 'Unknown'
System info: host: 'selenium-router-54996d9d47-gb9bs', ip: '10.233.89.115', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.92-flatcar', java.version: '1.8.0_282'
Driver info: driver.version: unknown
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.0.0-beta-1', revision: 'Unknown'
System info: host: 'selenium-router-54996d9d47-gb9bs', ip: '10.233.89.115', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.92-flatcar', java.version: '1.8.0_282'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:93)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:56)
	at org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:89)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:138)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:92)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
	... 33 more
15:49:07.005 WARN [OpenTelemetryTracer$1.lambda$export$0] - {"traceId": "88a56ca8adfa5ff0cae5c00ec32d3354","spanId": "649741b2431b1219","spanKind": "INTERNAL","eventTime": 1614700147004070726,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-beta-1', revision: 'Unknown'\nSystem info: host: 'selenium-router-54996d9d47-gb9bs', ip: '10.233.89.115', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.92-flatcar', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.0.0-beta-1', revision: 'Unknown'\nSystem info: host: 'selenium-router-54996d9d47-gb9bs', ip: '10.233.89.115', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.92-flatcar', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:93)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:56)\n\tat org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer.addToQueue(RemoteNewSessionQueuer.java:89)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueuer.execute(NewSessionQueuer.java:138)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:92)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)\n\t... 33 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueuer","http.host": "selenium-router.experimental.svc.sigma:4444","http.method": "POST","http.request_content_length": "487","http.scheme": "HTTP","http.target": "\u002fsession","http.user_agent": "selenium\u002f4.0.0-beta-1 (java unix)"}}
```

Deploy with:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selenium-grid-advanced
  namespace: experimental
spec:
  releaseName: selenium-grid-advanced
  chart:
    # https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart/chart/selenium-grid
    repository: https://#redacted#/artifactory/releases
    name: selenium-grid
    version: 0.1.0
  values:
    isolateComponents: true
    chromeNode:
      replicas: 30
      imageTag: "4.0.0-beta-1-20210215"
    firefoxNode:
      replicas: 1
      imageTag: "4.0.0-beta-1-20210215"
    operaNode:
      replicas: 1
      imageTag: "4.0.0-beta-1-20210215"
    components:
      distributor:
        imageTag: "4.0.0-beta-1-20210215"
      eventBus:
        imageTag: "4.0.0-beta-1-20210215"
      sessionMap:
        imageTag: "4.0.0-beta-1-20210215"
      sessionQueuer:
        imageTag: "4.0.0-beta-1-20210215"
      router:
        imageTag: "4.0.0-beta-1-20210215"
        resources:
          requests:
            memory: "32Gi"
          limits:
            memory: "32Gi"
      extraEnvironmentVariables:
        - name: JAVA_OPTS
          # @note "POOL_MAX" not confirmed that it is working.
          value: "-Xmx20g -Xms2g -XX:+UseG1GC -DPOOL_MAX=512"
        - name: SE_OPTS
          value: "--max-threads 20"
        - name: SE_SESSION_REQUEST_TIMEOUT
          value: "15"
```

Run a few tests successfully after you deployed with the above `HelmRelease`, wait few hours while the grid is stand-by (no jobs are submitted).

## Environment

OS: Flatcar Container Linux by Kinvolk stable (2605.12.0)
Docker-Selenium image version: **4.0.0-beta-1-20210215**
Docker version: Docker version 19.03.14, build f8db474
Kubernetes: v1.18.10

**Comment by diemol** [comment]
How could we reproduce this?

**Comment by zzvara** [comment]
@diemol I think it would be easier to use the HelmRelease. I patched the YAML for you to be able to deploy without building the Chart TAR.

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selenium-grid
  namespace: default
spec:
  releaseName: selenium-grid
  chart:
    git: https://github.com/pedrodotmc/docker-selenium
    path: chart/selenium-grid
    ref: selenium-grid-helm-chart
  values:
    isolateComponents: true
    chromeNode:
      replicas: 2
      imageTag: "4.0.0-beta-1-20210215"
    firefoxNode:
      replicas: 1
      imageTag: "4.0.0-beta-1-20210215"
    operaNode:
      replicas: 1
      imageTag: "4.0.0-beta-1-20210215"
    components:
      distributor:
        imageTag: "4.0.0-beta-1-20210215"
      eventBus:
        imageTag: "4.0.0-beta-1-20210215"
      sessionMap:
        imageTag: "4.0.0-beta-1-20210215"
      sessionQueuer:
        imageTag: "4.0.0-beta-1-20210215"
      router:
        imageTag: "4.0.0-beta-1-20210215"
        resources:
          requests:
            memory: "20Gi"
          limits:
            memory: "20Gi"
      extraEnvironmentVariables:
        - name: JAVA_OPTS
          value: "-Xmx20g -Xms2g -XX:+UseG1GC -DPOOL_MAX=512"
        - name: SE_OPTS
          value: "--max-threads 20"
        - name: SE_SESSION_REQUEST_TIMEOUT
          value: "15"
```

Please note I only changed this part:

```
    git: https://github.com/pedrodotmc/docker-selenium
    path: chart/selenium-grid
    ref: selenium-grid-helm-chart
```

You may use the Flux Helm Operator with the `HelmRelease` [1].

[1] https://github.com/fluxcd/helm-operator

After `apply`ing the above `HelmRelease`, you will have the same Selenium Grid 4 on K8S.

Then run any tests that would exhaust sessions so that all slots get busy (logs of queuer):

```
08:35:44.351 INFO [LocalNewSessionQueue.retryRequest] - Adding request back to the queue. All slots are busy. Request: bebbfa85-68fd-49af-999a-8f7cab5c4d1f
08:35:49.351 INFO [LocalNewSessionQueue.retryRequest] - Adding request back to the queue. All slots are busy. Request: 02b0248a-c813-4a0d-ab57-5d7cf419e42b
08:35:50.352 INFO [LocalNewSessionQueue.retryRequest] - Adding request back to the queue. All slots are busy. Request: bebbfa85-68fd-49af-999a-8f7cab5c4d1f
08:35:56.353 INFO [LocalNewSessionQueue.retryRequest] - Adding request back to the queue. All slots are busy. Request: bebbfa85-68fd-49af-999a-8f7cab5c4d1f
```

Then, wait for slots to free up, few hours if you will. After this, no more tests can be run on the grid.

Restarting the `router` or `session-queuer` does not help. It looks like "after a while it is broken". If I can provide more information or help in any way please instruct me.

Thanks!

**Comment by diemol** [comment]
I am referrring to the tests you are using to bump into that error.

**Comment by zzvara** [comment]
Unfortunately, I'm not sure I can transfer that code/use-case, but I'd be glad to receive instructions from you on:
- how to modify logging so that more information is printed,
- what components could be involved in the problem itself (for example where to look and where not to look),
- what to check specifically.

And in general, how would you approach debugging the problem.

**Comment by zzvara** [comment]
@diemol we attempted to debug it by setting the log level to FINEST, but could not identify the problem. However, deploying to Kubernetes with non-isolated components seems to fix the problem. We are further testing the deployment.

Note: this is still a problem with `4.0.0-beta-2-prerelease-20210310`.

**Comment by diemol** [comment]
I can see you have 30 replicas for Chrome, and 1 replica for Opera and Firefox. If you have many tests for Opera or Firefox they will be queued, and eventually timeout if there are not enough Nodes available. I can also see that the `SE_SESSION_REQUEST_TIMEOUT` is set to 15 seconds. 

What happens when you add more Firefox or Opera replicas or extend the timeout?

**Comment by zzvara** [comment]
@diemol

Using the Helm chart from #1184 in a **non-isolated** way fixes the problem with the same Firefox, Opera replica number, and the same timeout setting (15 seconds). In our tests, only Chrome nodes are used anyway.

However, increasing Firefox, Opera replicas, or increasing the timeout to 300 seconds does not help in **isolated** deployment mode (where all components are running in a separate Pod under a separate Service).

**Comment by diemol** [comment]
Ok, so that is an issue with the helm chart, which we are not yet supporting because we haven't had the time to add it. We will do at some point in the near future. Perhaps you can collaborate with @pedrodotmc and see what is going on?

**Comment by zzvara** [comment]
@diemol sure!

We debugged that the Pods/Services are connected properly and DNS/network works even though the deployment is in isolated mode. I doubt that it is related to the Helm chart itself.
