### ISSUE TITLE
Dynamic Grid standalone-docker image throws error on startup

### ISSUE THREAD

**Issue by iceinvein** [SeleniumHQ/docker-selenium#1236]
## 🐛 Bug Report

Dynamic Grid does not start up successfully.

## To Reproduce

Run the following
```
docker run --rm -ti --name selenium-docker -p 4444:4444 \
-v ${PWD}/config.toml:/opt/bin/config.toml \
-v ${PWD}/assets:/opt/selenium/assets \
selenium/standalone-docker:4.0.0-beta-2-prerelease-20210315
```

## Expected behavior

Server to start up successfully

## Failure Output
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
        ... 14 more
Caused by: java.io.FileNotFoundException
        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:122)
        at io.netty.channel.unix.Socket.connect(Socket.java:239)
        at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:736)
        at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:721)
        at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:563)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
        at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
        at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
        at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
        at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
        at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

## Environment

OS: Windows 10
Docker-Selenium image version: 4.0.0-beta-2-prerelease-20210315
Docker version: 20.10.5, build 55c4c88

**Comment by diemol** [comment]
The exception says that the file was not found. Are you sure the file is there? Have you tried the full path?

**Comment by iceinvein** [comment]
Yea the `config.toml` file is present and can verify that the file is mapped in `/opt/bin/config.toml` using docker exec into the container

If I change image back to `4.0.0-beta-1-20210215` it works

**Comment by diemol** [comment]
Can you please share your `config.yml`?

**Comment by iceinvein** [comment]
config.toml
```
[docker]
configs = [
    "selenium/standalone-chrome:4.0.0-beta-2-prerelease-20210315", "{\"browserName\": \"chrome\"}"
]

host = "tcp://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
assets-path = "C:\\docker\\assets"
container-assets-path = "/opt/selenium/assets"

#[server]
#hostname = <ip-from-node-machine>
#port = <port-from-node-machine>
```
I can verify the file is being picked as if I put garbage in this file it'll complain about parsing it

**Comment by josesa-xx** [comment]
You need to shared a folder in windows flesystem like "C:\\" in Docker Settings so you can mount those paths inside the container.

In my case I created a test folder in "c:\tmp\selenium" and setup local mounts as follows:

```shell
mkdir -p /c/tmp/selenium/assets
cd /c/tmp/selenium

cat <<_EOF_ >config.toml
[docker]
configs = [
    "selenium/standalone-firefox:4.0.0-beta-2-prerelease-20210315", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0-beta-2-prerelease-20210315", "{\"browserName\": \"chrome\"}"
 ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
_EOF_
```
Then I executed the same command you have in the description and it worked
```
$ docker run --rm -ti --name selenium-docker -p 4444:4444 -v ${PWD}/config.toml:/opt/bin/config.toml -v ${PWD}/assets:/opt/selenium/assets selenium/standalone-docker:4.0.0-beta-2-prerelease-20210315
2021-03-16 09:31:56,511 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-03-16 09:31:56,518 INFO supervisord started with pid 9
2021-03-16 09:31:57,520 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
Starting Selenium Grid Standalone Docker...
2021-03-16 09:31:57,524 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
...
```

However, if I use in config.toml `host = "tcp://host.docker.internal:2375"` it fails with the same error in description

**Comment by iceinvein** [comment]
> You need to shared a folder in windows flesystem like "C:\" in Docker Settings so you can mount those paths inside the container.
> 
> In my case I created a test folder in "c:\tmp\selenium" and setup local mounts as follows:
> 
> ```shell
> mkdir -p /c/tmp/selenium/assets
> cd /c/tmp/selenium
> 
> cat <<_EOF_ >config.toml
> [docker]
> configs = [
>     "selenium/standalone-firefox:4.0.0-beta-2-prerelease-20210315", "{\"browserName\": \"firefox\"}",
>     "selenium/standalone-chrome:4.0.0-beta-2-prerelease-20210315", "{\"browserName\": \"chrome\"}"
>  ]
> url = "http://host.docker.internal:2375"
> video-image = "selenium/video:ffmpeg-4.3.1-20210315"
> _EOF_
> ```
> 
> Then I executed the same command you have in the description and it worked
> 
> ```
> $ docker run --rm -ti --name selenium-docker -p 4444:4444 -v ${PWD}/config.toml:/opt/bin/config.toml -v ${PWD}/assets:/opt/selenium/assets selenium/standalone-docker:4.0.0-beta-2-prerelease-20210315
> 2021-03-16 09:31:56,511 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
> 2021-03-16 09:31:56,518 INFO supervisord started with pid 9
> 2021-03-16 09:31:57,520 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
> Starting Selenium Grid Standalone Docker...
> 2021-03-16 09:31:57,524 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> ...
> ```
> 
> However, if I use in config.toml `host = "tcp://host.docker.internal:2375"` it fails with the same error in description

Yea not sure what's the reasoning behind having config for assets on host in config.toml as docker volume mount was taking care of it. If we have to go inside the container and mount it manually then it sorta feel counter-intuitive

**Comment by diemol** [comment]
@iceinvein please check the most recent example [here](https://github.com/SeleniumHQ/docker-selenium#configuration-example).
There is no need to specify 
```
assets-path = "C:\\docker\\assets"
container-assets-path = "/opt/selenium/assets"
```
anymore (which is causing this error).
