### ISSUE TITLE
chrome not reachable exception after script execution

### ISSUE THREAD

**Issue by gilo** [SeleniumHQ/docker-selenium#126]
I am using docker-compose to run a grid on Azure, when I am running a js script I get an exception from chrome. see details below 

7:44:03.840 INFO - Executing: [execute script: return window.getTestimStatus && window.getTestimStatus(), []])
07:44:04.164 WARN - Exception thrown
org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=46.0.2490.71)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-68-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '6703fd2b721e', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-68-generic', java.version: '1.8.0_45-internal'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.LYk6Is}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=46.0.2490.71, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f6d54cd33ec2992f78303d7d12f2c9cd
    at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:556)
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
    at com.sun.proxy.$Proxy1.executeScript(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:216)
    at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:56)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
07:44:04.165 WARN - Exception: chrome not reachable
  (Session info: chrome=46.0.2490.71)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-68-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds

docker-compose.yml
hub:
  image: selenium/hub
  restart: always
  environment:
    - JAVA_OPTS=-Xmx3g
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  privileged: true
  restart: always
  links:
    - hub

**Comment by rubytester** [comment]
The Chrome may have crashed. Try using the /dev/shm mount solution to the issue.  https://github.com/SeleniumHQ/docker-selenium#running-the-images

**Comment by gilo** [comment]
Thanks, I found the link u sent after writing. It did solved the problem. Though it feels like the chrome in docker is less stable (than without). Do u know a good way to track chrome crashes in containers ?

**Comment by elgalu** [comment]
Is not about feelings :P, so docker starts containers by default with a small shm size and that was the reason why it worked different that real or virtual machines. Many people are using selenium in docker which makes finding issues and solving them quicker ;)

**Comment by pauldraper** [comment]
I see similar symptoms, though I am not using Docker.

> The Chrome may have crashed.

How can I verify/debug this?

**Comment by diemol** [comment]
@gilo that is the nature of Chrome in docker, you need to share that to get Chrome to work properly in docker-selenium.

As the issue seems to be solved, could you please close it?

Thanks!
