### ISSUE TITLE
"Pull appears to have succeeded, but image not present locally" using Artifactory proxy

### ISSUE THREAD

**Issue by josesa-xx** [SeleniumHQ/docker-selenium#1264]
## 🐛 Bug Report

In standalone docker when using image proxied from artifactory fails to start with error:
org.openqa.selenium.docker.DockerException: Pull appears to have succeeded, but image not present locally

## To Reproduce

Using the below code as starting point (tested to work connected to Internet)
https://github.com/josesa-xx/selenium-tests/tree/master/standalone-docker

Changed the file config.toml with following (server name redacted)
```
[docker]
configs = [
    "registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-prerelease-20210402", "{\"browserName\": \"firefox\"}",
    "registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402", "{\"browserName\": \"chrome\"}"
 ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
```
In this case:
- "repo.artifactory.fqdn.com" is the Artifactory server name
- "registry1-docker-io" is the repository in Artifactory to proxy from internet on docker hub
- "selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402" is the image name as we get from Internet on docker hub 

## Expected behavior

Since "docker pull" is able to work with given image name it should not fail to load

## Output 

The following output is produced after doing "docker-compose up"

```
2021-04-17 14:11:04,239 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-04-17 14:11:04,242 INFO supervisord started with pid 8
2021-04-17 14:11:05,244 INFO spawned: 'selenium-grid-standalone-docker' with pid 10
Starting Selenium Grid Standalone Docker...
2021-04-17 14:11:05,249 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
14:11:05.602 INFO [LogManager$RootLogger.log] - Using the system default encoding
14:11:05.606 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:11:06.238 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors
14:11:07.045 INFO [V140Docker.isContainerPresent] - Checking if container is present: 5afeeff7f7b8
14:11:07.094 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
14:11:07.094 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-prerelease-20210402
14:11:07.107 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:07.107 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:07.222 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:07.222 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:07.227 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:07.228 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:08.936 INFO [PullImage.apply] - Have response from server
14:11:08.936 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:11:08.968 INFO [PullImage.apply] - Have response from server
14:11:08.968 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
        ... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Pull appears to have succeeded, but image not present locally: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
        at org.openqa.selenium.docker.v1_40.V140Docker.getImage(V140Docker.java:87)
        at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
        at org.openqa.selenium.grid.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:222)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
14:11:09.043 INFO [LocalDistributor.callExecutorShutdown] - Shutting down Distributor executor service
14:11:09.043 INFO [LocalNewSessionQueue.callExecutorShutdown] - Shutting down session queue executor service
2021-04-17 14:11:09,099 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)
Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2021-04-17 14:11:36,130 WARN received SIGTERM indicating exit request
Shutdown complete
2021-04-17 14:21:27,075 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-04-17 14:21:27,079 INFO supervisord started with pid 9
2021-04-17 14:21:28,081 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
Starting Selenium Grid Standalone Docker...
2021-04-17 14:21:28,086 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
14:21:28.504 INFO [LogManager$RootLogger.log] - Using the system default encoding
14:21:28.509 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:21:29.180 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors
14:21:29.929 INFO [V140Docker.isContainerPresent] - Checking if container is present: 5afeeff7f7b8
14:21:29.968 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-prerelease-20210402
14:21:29.968 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
14:21:29.974 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:29.974 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:30.064 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:30.064 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:30.077 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:30.078 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:31.873 INFO [PullImage.apply] - Have response from server
14:21:31.874 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
14:21:31.953 INFO [PullImage.apply] - Have response from server
14:21:31.953 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-prerelease-20210402', digest='null'}
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
        ... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Pull appears to have succeeded, but image not present locally: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
        at org.openqa.selenium.docker.v1_40.V140Docker.getImage(V140Docker.java:87)
        at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
        at java.util.Optional.map(Optional.java:215)
        at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
        at org.openqa.selenium.grid.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:222)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-04-17 14:21:32,020 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)
```

## Environment

OS: Windows 10
Docker Desktop: 3.3.1
WSL: Ubuntu-20.04 (wsl v1)
Docker-Selenium image version: 4.0.0-beta-3-prerelease-20210402

**Comment by diemol** [comment]
I am not able to reproduce it using an image tagged locally with the full name you suggest. I am using https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-3-20210426, please try with that tag.

If the issue is still happening, please let me know how I can pull that image so I can reproduce the issue.

**Comment by josesa-xx** [comment]
I've updated all image tags to use "4.0.0-beta-3-20210426" and repeated the test.

This time I deleted all "standalone" images I had locally before running and I noticed the following:

```
$ docker-compose up selenium-hub
Creating network "gui-selenium-standalone-docker_default" with the default driver
Pulling selenium-hub (registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-docker:4.0.0-beta-3-20210426)...
4.0.0-beta-3-20210426: Pulling from selenium/standalone-docker
a70d879fa598: Already exists
c4394a92d1f8: Already exists
10e6159c56c0: Already exists
ca42c4e8bef8: Already exists
836691c8e243: Already exists
16de38122648: Already exists
60d4552a0c13: Already exists
c5640070e490: Already exists
3feaf4c3f848: Already exists
70df8b93686b: Already exists
5faae73ee746: Pull complete
cd6242452eb1: Pull complete
Digest: sha256:b856e1e9e027021a0370f04296446d924784a48dc9c682a714ffa6b1508f0eaa
Status: Downloaded newer image for registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-docker:4.0.0-beta-3-20210426
Creating selenium-hub ... done
Attaching to selenium-hub
selenium-hub    | 2021-05-24 16:09:50,710 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
selenium-hub    | 2021-05-24 16:09:50,714 INFO supervisord started with pid 8
selenium-hub    | 2021-05-24 16:09:51,717 INFO spawned: 'selenium-grid-standalone-docker' with pid 10
selenium-hub    | Starting Selenium Grid Standalone Docker...
selenium-hub    | 2021-05-24 16:09:51,722 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 16:09:52.401 INFO [LogManager$RootLogger.log] - Using the system default encoding
selenium-hub    | 16:09:52.407 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 16:09:53.050 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors
selenium-hub    | 16:09:53.737 INFO [V140Docker.isContainerPresent] - Checking if container is present: 94af825248d7
selenium-hub    | 16:09:53.765 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
selenium-hub    | 16:09:53.765 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
selenium-hub    | 16:09:53.769 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:53.769 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:53.822 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:53.823 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:53.827 INFO [V140Docker.getImage] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:53.827 INFO [PullImage.apply] - Pulling Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:58.842 INFO [PullImage.apply] - Have response from server
selenium-hub    | 16:09:58.842 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:09:59.142 INFO [PullImage.apply] - Have response from server
selenium-hub    | 16:09:59.143 INFO [V140Docker.getImage] - Pull completed. Listing local images again: Reference{domain='registry1-docker-io.repo.artifactory.fqdn.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | java.lang.reflect.InvocationTargetException
selenium-hub    |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
selenium-hub    |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
selenium-hub    |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
selenium-hub    |       at java.lang.reflect.Method.invoke(Method.java:498)
selenium-hub    |       at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
selenium-hub    |       at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
selenium-hub    | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
selenium-hub    |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
selenium-hub    |       at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
selenium-hub    |       at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:195)
selenium-hub    |       at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
selenium-hub    |       at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:206)
selenium-hub    |       at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
selenium-hub    |       at org.openqa.selenium.grid.Main.launch(Main.java:83)
selenium-hub    |       at org.openqa.selenium.grid.Main.go(Main.java:57)
selenium-hub    |       at org.openqa.selenium.grid.Main.main(Main.java:42)
selenium-hub    |       ... 6 more
selenium-hub    | Caused by: java.lang.reflect.InvocationTargetException
selenium-hub    |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
selenium-hub    |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
selenium-hub    |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
selenium-hub    |       at java.lang.reflect.Method.invoke(Method.java:498)
selenium-hub    |       at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
selenium-hub    |       at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
selenium-hub    |       at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
selenium-hub    |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
selenium-hub    |       ... 14 more
selenium-hub    | Caused by: org.openqa.selenium.docker.DockerException: Pull appears to have succeeded, but image not present locally: registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
selenium-hub    |       at org.openqa.selenium.docker.v1_40.V140Docker.getImage(V140Docker.java:87)
selenium-hub    |       at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
selenium-hub    |       at java.util.Optional.map(Optional.java:215)
selenium-hub    |       at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
selenium-hub    |       at org.openqa.selenium.grid.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:222)
selenium-hub    |       at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
selenium-hub    |       at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
selenium-hub    |       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
selenium-hub    |       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
selenium-hub    |       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
selenium-hub    |       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
selenium-hub    | 2021-05-24 16:09:59,211 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)
```

After aborting this execution I could see that it had the following images listed:
```
$ docker images | grep standalone
registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-docker   4.0.0-beta-3-20210426                                   8223f30c60b5   4 weeks ago     296MB
selenium/standalone-firefox                                                     4.0.0-beta-3-20210426                                   339c78064b6e   4 weeks ago     999MB
selenium/standalone-chrome                                                      4.0.0-beta-3-20210426                                   b9bdec5fc292   4 weeks ago     1.08GB
```

**So it ignored the full name for the firefox and chrome images defined in config.toml and just downloaded the ones from internet (docker hub).**

After forcing manually a download on the images I declared in config.toml
```
$ docker pull registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
4.0.0-beta-3-20210426: Pulling from selenium/standalone-firefox
Digest: sha256:aac9d6c7ab9db5b277aabd01274127a8506883693cd571a91cae4e0f5824456c
Status: Downloaded newer image for registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-firefox:4.0.0-beta-3-20210426

$ docker pull registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
4.0.0-beta-3-20210426: Pulling from selenium/standalone-chrome
Digest: sha256:1532a6d76064edc555045aa790918fbbca972426099e0559ee4eef138dd0db62
Status: Downloaded newer image for registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
registry1-docker-io.repo.artifactory.fqdn.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
```

Then the standone-docker started normally:
```
$ docker-compose up selenium-hub
Creating network "gui-selenium-standalone-docker_default" with the default driver
Creating selenium-hub ... done
Attaching to selenium-hub
selenium-hub    | 2021-05-24 16:19:40,576 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
selenium-hub    | 2021-05-24 16:19:40,578 INFO supervisord started with pid 9
selenium-hub    | 2021-05-24 16:19:41,581 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
selenium-hub    | Starting Selenium Grid Standalone Docker...
selenium-hub    | 2021-05-24 16:19:41,590 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 16:19:41.990 INFO [LogManager$RootLogger.log] - Using the system default encoding
selenium-hub    | 16:19:41.993 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 16:19:42.660 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors
selenium-hub    | 16:19:43.322 INFO [V140Docker.isContainerPresent] - Checking if container is present: 28923a956b04
selenium-hub    | 16:19:43.352 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
selenium-hub    | 16:19:43.352 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
selenium-hub    | 16:19:43.358 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.lab.pl.alcatel-lucent.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:19:43.358 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.lab.pl.alcatel-lucent.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:19:43.421 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20210315
selenium-hub    | 16:19:43.421 INFO [V140Docker.getImage] - Listing local images: Reference{domain='docker.io', repository='selenium', name='video', tag='ffmpeg-4.3.1-20210315', digest='null'}
selenium-hub    | 16:19:43.466 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20210315
selenium-hub    | 16:19:43.466 INFO [V140Docker.getImage] - Listing local images: Reference{domain='docker.io', repository='selenium', name='video', tag='ffmpeg-4.3.1-20210315', digest='null'}
selenium-hub    | 16:19:43.498 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-firefox:4.0.0-beta-3-20210426
selenium-hub    | 16:19:43.498 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.lab.pl.alcatel-lucent.com', repository='selenium', name='standalone-firefox', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:19:43.537 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: firefox} to docker image registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-firefox:4.0.0-beta-3-20210426 6 times
selenium-hub    | 16:19:43.537 INFO [Docker.getImage] - Obtaining image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-chrome:4.0.0-beta-3-20210426
selenium-hub    | 16:19:43.537 INFO [V140Docker.getImage] - Listing local images: Reference{domain='registry1-docker-io.repo.lab.pl.alcatel-lucent.com', repository='selenium', name='standalone-chrome', tag='4.0.0-beta-3-20210426', digest='null'}
selenium-hub    | 16:19:43.565 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: chrome} to docker image registry1-docker-io.repo.lab.pl.alcatel-lucent.com/selenium/standalone-chrome:4.0.0-beta-3-20210426 6 times
selenium-hub    | 16:19:43.581 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
selenium-hub    | 16:19:43.600 INFO [LocalDistributor.add] - Added node bcf2fbe4-76b5-4bdd-8872-8add89e3143d at http://172.21.0.2:4444.
selenium-hub    | 16:19:43.606 INFO [GridModel.setAvailability] - Switching node bcf2fbe4-76b5-4bdd-8872-8add89e3143d (uri: http://172.21.0.2:4444) from DOWN to UP
selenium-hub    | 16:19:43.635 INFO [Standalone.execute] - Started Selenium Standalone 4.0.0-beta-3 (revision 5d108f9a67): http://172.21.0.2:4444
```

**Comment by diemol** [comment]
How can I pull that image? Is it a private registry?

**Comment by josesa-xx** [comment]
You can think as private registry (to proxy from internet), you can simulate this with:

```
# docker private registry
docker run -d -p 5000:5000 --restart=always --name registry registry:2

# proxy images into private registry
for node in docker chrome firefox; do
  image="selenium/standalone-${node}:4.0.0-beta-3-20210426"
  docker pull ${image}
  docker tag ${image} localhost:5000/${image}
  docker push localhost:5000/${image}
  docker rmi ${image}
  docker rmi localhost:5000/${image}
done
```

I've updated then my config.toml to use:
```
[docker]
configs = [
    "localhost:5000/selenium/standalone-firefox:4.0.0-beta-3-20210426", "{\"browserName\": \"firefox\"}",
    "localhost:5000/selenium/standalone-chrome:4.0.0-beta-3-20210426", "{\"browserName\": \"chrome\"}"
 ]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210315"
```

then when running the docker 
```
docker run --rm -it \
  -v $PWD/config_private.toml:/opt/bin/config.toml \
  -p 4444:4444 \
  localhost:5000/selenium/standalone-docker:4.0.0-beta-3-20210426
```

we can see the error 
```
Caused by: org.openqa.selenium.docker.DockerException: Pull appears to have succeeded, but image not present locally: localhost:5000/selenium/standalone-firefox:4.0.0-beta-3-20210426
```

**Comment by diemol** [comment]
Thank you, now I clearly understood. I was able to reproduce it and will fix it soon in the Selenium repo. Will do a prerelease soon after that.
