### ISSUE TITLE
Unable to launch dynamic grid using README.md resources on Linux

### ISSUE THREAD

**Issue by iandeveseleer** [SeleniumHQ/docker-selenium#1266]
## 🐛 Bug Report

I'm unable to get the Dynamic Grid given in README.md to work.

I have just edit config.toml URL to 172.17.0.1 like it's said in code comment but I'm facing this stacktrace in the node-docker logs : 

```
15:42:03.023 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:125)
at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:181)
at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:227)
at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
at org.openqa.selenium.grid.Main.launch(Main.java:83)
at org.openqa.selenium.grid.Main.go(Main.java:57)
at org.openqa.selenium.grid.Main.main(Main.java:42)
... 6 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://172.17.0.1:2375
at org.openqa.selenium.grid.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:124)
at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:76)
... 22 more
```

## To Reproduce

Steps to reproduce :

- Execute the **docker-compose -f docker-compose-dynamic-grid.yml** command
- The given error stacktrace will be displayed in node-docker container logs.

## Expected behavior

A grid should start, and the selenium/node-docker should be able to interact with the host Docker Daemon.

## Environment

OS: Ubuntu 20.04
Docker-Selenium image version: 4.0.0-beta-3-prerelease-20210422
Docker version: 20.10.6
Docker-Compose version: 1.26.2

Files to use to reproduce bug :

[docker-compose-dynamic-grid.yml.txt](https://github.com/SeleniumHQ/docker-selenium/files/6359499/docker-compose-dynamic-grid.txt)

Used config.toml file : [config.toml.txt](https://github.com/SeleniumHQ/docker-selenium/files/6359536/config.toml.txt)

**Comment by diemol** [comment]
Please check the Docker daemon is reachable at that url...
```
Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://172.17.0.1:2375
```

**Comment by diemol** [comment]
Maybe your docker daemon is listening to other port?

**Comment by iandeveseleer** [comment]
Hello, thanks, indeed under Ubuntu the Docker Daemon does not expose anything by default... 

Actions taken : https://gist.github.com/styblope/dc55e0ad2a9848f2cc3307d4819d819f

I close this issue.
