### ISSUE TITLE
Dynamic grid is not able to parse docker images other than from the default registry

### ISSUE THREAD

**Issue by iandeveseleer** [SeleniumHQ/docker-selenium#1275]
## 🐛 Bug Report

Dynamic grid is not able to parse docker images other than from the default registry

Node-docker console logs :

```
15:09:41.097 INFO [Docker.getImage] - Obtaining image: eu.gcr.io/XXX/standalone-firefox:4.0.0-latest
15:09:41.097 INFO [Docker.getImage] - Obtaining image: eu.gcr.io/XXX/standalone-chrome:4.0.0-latest
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:93)
at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:125)
at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:181)
at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:227)
at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
at org.openqa.selenium.grid.Main.launch(Main.java:83)
at org.openqa.selenium.grid.Main.go(Main.java:57)
at org.openqa.selenium.grid.Main.main(Main.java:42)
... 6 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:47)
at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Unable to parse: eu.gcr.io/XXX/standalone-firefox:4.0.0-latest
at org.openqa.selenium.docker.internal.Reference.parse(Reference.java:135)
at org.openqa.selenium.docker.v1_40.V140Docker.getImage(V140Docker.java:70)
at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
at java.util.Optional.map(Optional.java:215)
at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
at org.openqa.selenium.grid.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:222)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-05 15:09:41,479 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
```

## To Reproduce

Steps to reproduce the behavior (including the command to start the containers)

Use standalone-chrome and standalone-firefox images from another registry in config.yaml file:

```
[docker]
configs = [
"eu.gcr.io/XXX/standalone-firefox:4.0.0-latest", "{"browserName": "firefox"}",
"eu.gcr.io/XXX/standalone-chrome:4.0.0-latest", "{"browserName": "chrome"}"
]
```
Start the Dynamic grid : https://github.com/SeleniumHQ/docker-selenium/#execution-with-hub--node-roles

## Expected behavior

The hub and node containers should be running, and node container should download given images.

## Environment

OS: Ubuntu 20.04
Docker-Selenium image version: 4.0.0-beta-3-20210426
Docker version: 20.10.6, build 370c289
Docker-Compose version (if applicable): N/A
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): https://github.com/SeleniumHQ/docker-selenium/#execution-with-hub--node-roles

**Comment by diemol** [comment]
Please use https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-beta-3-20210426
(changed repo to lowercase `XXX -> xxx`)

```
docker run --rm --name selenium-docker -p 4444:4444 \                                                                                                                                              SIGINT(2) ↵  14:05:04
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v /Users/diegomolina/Projects/github.com/seleniumhq/assets:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-3-20210426
2021-05-11 12:05:08,928 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-05-11 12:05:08,930 INFO supervisord started with pid 9
2021-05-11 12:05:09,934 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
Starting Selenium Grid Standalone Docker...
2021-05-11 12:05:09,943 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
12:05:10.253 INFO [LogManager$RootLogger.log] - Using the system default encoding
12:05:10.256 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
12:05:10.743 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
12:05:11.206 INFO [V140Docker.isContainerPresent] - Checking if container is present: 1a812bdcb9c4
12:05:11.241 INFO [Docker.getImage] - Obtaining image: eu.gcr.io/xxx/standalone-firefox:4.0.0-latest
12:05:11.245 INFO [V140Docker.getImage] - Listing local images: Reference{domain='eu.gcr.io', repository='xxx', name='standalone-firefox', tag='4.0.0-latest', digest='null'}
12:05:11.304 INFO [V140Docker.getImage] - Pulling Reference{domain='eu.gcr.io', repository='xxx', name='standalone-firefox', tag='4.0.0-latest', digest='null'}
12:05:11.304 INFO [PullImage.apply] - Pulling Reference{domain='eu.gcr.io', repository='xxx', name='standalone-firefox', tag='4.0.0-latest', digest='null'}
```

**Comment by iandeveseleer** [comment]
Hello @diemol,

I had over-anonymised the name of the image, in reality it's something like: **eu.gcr.io/xxx/xxx/xxx/standalone-firefox:4.0.0-latest**

I'm on version **4.0.0-beta-3-20210426** and I have the same problem as the one I had initially

```
Caused by: org.openqa.selenium.docker.DockerException: Unable to parse: eu.gcr.io/xxx/xxx/xxx/standalone-firefox:4.0.0-latest
at org.openqa.selenium.docker.internal.Reference.parse(Reference.java:135)
at org.openqa.selenium.docker.v1_40.V140Docker.getImage(V140Docker.java:70)
at org.openqa.selenium.docker.Docker.lambda$getImage$0(Docker.java:51)
at java.util.Optional.map(Optional.java:215)
at org.openqa.selenium.docker.Docker.getImage(Docker.java:51)
at org.openqa.selenium.grid.docker.DockerOptions.lambda$loadImages$4(DockerOptions.java:222)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-11 15:18:22,464 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
```

**Comment by diemol** [comment]
Is that a valid docker image name?

**Comment by iandeveseleer** [comment]
Yes, it's the structure of the images directories within an GCP enterprise registry. With the spotify docker-client library for example we never encountered this kind of problem

**Comment by josesa-xx** [comment]
This seems like the same issue I reported in https://github.com/SeleniumHQ/docker-selenium/issues/1264

**Comment by diemol** [comment]
I think they are different issues, this one is about parsing the image name, the other one was missing the domain part of the image when creating it locally.

**Comment by diemol** [comment]
@iandeveseleer, thanks for the information, I was able to reproduce it. I will fix it in the Selenium repo and will do a prerelease soon after that.
