### ISSUE TITLE
Fail to start the node container in Dynamic Grid 4

### ISSUE THREAD

**Issue by amartanwar42** [SeleniumHQ/docker-selenium#1284]
## 🐛 Bug Report

I am trying Dynamic grid 4 and When I am following steps mentioned in the Readme I am getting the below error:

```
2021-05-12 14:22:57,152 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: io.ous.jtoml.ParseException: Unexpected token ] at 7:4
	at io.ous.jtoml.impl.Parser.error(Parser.java:250)
	at io.ous.jtoml.impl.Parser.readValue(Parser.java:149)
	at io.ous.jtoml.impl.Parser.readArray(Parser.java:97)
	at io.ous.jtoml.impl.Parser.readValue(Parser.java:144)
	at io.ous.jtoml.impl.Parser.onAssignment(Parser.java:78)
	at io.ous.jtoml.impl.Parser.parse(Parser.java:48)
	at io.ous.jtoml.JToml.parse(JToml.java:35)
	at org.openqa.selenium.grid.config.TomlConfig.<init>(TomlConfig.java:45)
	at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:55)
	at org.openqa.selenium.grid.config.Configs.from(Configs.java:40)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:72)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:105)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
```

## Note:
I have tried both the approach to start the container. By command and using a docker-compose file. But getting a similar error in both the case.

Node container is showing up even though the above error has occured. And in the grid UI shows
![image](https://user-images.githubusercontent.com/40663687/117994695-01d64d80-b341-11eb-93ae-83acc60f1a5b.png)
 

## Steps to reproduce:

- https://github.com/amartanwar42/wdio-zelenium-dockerize
- run command ~ ` docker-compose -f docker-compose-v3-dynamic-grid.yml up`

## Environment

- OS: mac
- selenium image: Same as mentioned in the readme.
- Docker version: 20.10.5
- Docker-Compose version (if applicable):  1.29.0,

**Comment by diemol** [comment]
The `config.toml` file you are using is malformatted. 
Please check the stacktrace -> `Caused by: io.ous.jtoml.ParseException: Unexpected token ] at 7:4`

```
configs = [
    "selenium/standalone-firefox:4.0.0-beta-3-20210426", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0-beta-3-20210426", "{\"browserName\": \"chrome\"}",
    ]
```

There is a comma (`,`) at the end of the Chrome config. You need to remove it.
