### ISSUE TITLE
Dynamicgrid standalone startup FileNotFoundException

### ISSUE THREAD

**Issue by MartykQ** [SeleniumHQ/docker-selenium#1314]
## 🐛 Bug Report

When executing:

```
docker run --rm --privileged --name selenium-docker -p 4444:4444 \
    -v /root/Selenium/dynamic/config.toml:/opt/bin/config.toml \
    -v /root/Selenium:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-20210608

```
with config.toml

```
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-beta-4-20210608", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "unix:///var/run/docker.sock"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210608"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>i

```

I am getting:

```
2021-06-10 11:26:29,030 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-06-10 11:26:29,032 INFO supervisord started with pid 9
2021-06-10 11:26:30,035 INFO spawned: 'selenium-grid-standalone-docker' with pid 11
Starting Selenium Grid Standalone Docker...
2021-06-10 11:26:30,045 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
11:26:30.532 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:26:30.537 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:26:31.445 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:96)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:191)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:202)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: java.io.FileNotFoundException
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:153)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.connect(Socket.java:270)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
	at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-10 11:26:32,104 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)


```

## To Reproduce

Commands above ^ 

## Expected behavior

Successful startup.

I doubled checked config.toml being properly copied to the container, and it works. Throws parsing exception when invalid toml is provided

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Docker-Selenium image version: 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
This command is mounting the same directory on both volumes:
```
docker run --rm --privileged --name selenium-docker -p 4444:4444 \
    -v /root/Selenium/dynamic/config.toml:/opt/bin/config.toml \
    -v /root/Selenium:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-20210608
```

So this means that the `config.file` will be gone or overwritten because `/opt/selenium/assets` probably won't contain it.

Try to mount different directories for each volume, e.g.:

```
docker run --rm --privileged --name selenium-docker -p 4444:4444 \
    -v /root/Selenium/dynamic/config.toml:/opt/bin/config.toml \
    -v /root/Selenium/assets:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-20210608
```

**Comment by MartykQ** [comment]
Still with:
```
docker run --rm --privileged --name selenium-docker -p 4444:4444 \
    -v /root/Selenium/dynamic/config.toml:/opt/bin/config.toml \
    -v /root/Selenium/assets:/opt/selenium/assets \
    selenium/standalone-docker:4.0.0-beta-4-20210608
```
result:

```
2021-06-11 06:45:05,665 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-standalone-docker.conf" during parsing
2021-06-11 06:45:05,668 INFO supervisord started with pid 10
2021-06-11 06:45:06,671 INFO spawned: 'selenium-grid-standalone-docker' with pid 12
Starting Selenium Grid Standalone Docker...
2021-06-11 06:45:06,685 INFO success: selenium-grid-standalone-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
06:45:07.275 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
06:45:07.284 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
06:45:08.443 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:96)
	at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:191)
	at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
	at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:202)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: java.io.FileNotFoundException
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:153)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.connect(Socket.java:270)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
	at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-11 06:45:09,166 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)

```


also tried with: `selenium/standalone-docker:4.0.0-beta-3-20210426` but the result is the same

**Comment by MartykQ** [comment]
@diemol Can you have a look?

**Comment by diemol** [comment]
After checking again, the issue happens because:
```
url = "unix:///var/run/docker.sock"
```

We do not communicate with the Docker API through the socket, we use the REST endpoint. That is what the stacktrace mentions when the file cannot be found.

Please follow the comments in the example:
```
# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
```
