### ISSUE TITLE
Unable to remote upload files

### ISSUE THREAD

**Issue by iceinvein** [SeleniumHQ/docker-selenium#1324]
## 🐛 Bug Report
Trying to upload file to a file input is failing while running test via hub-dynamic nodes or dynamic standalone docker containers

## To Reproduce
- Launch dynamic grid standalone using docker-compose
- Run test that tries to upload the file to a file input

## Expected behavior
File uploaded to the input

## Test script reproducing this issue (when applicable)
```
File file = new File("c:\\files\\resources.xml");

ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.addArguments("--disable-dev-shm-usage");
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), chromeOptions);
driver.setFileDetector(new LocalFileDetector());
driver.get("https://ps.uci.edu/~franklin/doc/file_upload.html");
driver.findElement(By.name("userfile")).sendKeys(file.getAbsolutePath());
driver.quit();
```

## Error
```
org.openqa.selenium.InvalidArgumentException: 
invalid argument: File not found : /tmp/session115118697587297940072d02f409e1b952cd54a6fdc3ac9451a7/upload17190313395070520511file/resources.xml
  (Session info: chrome=91.0.4472.114)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.114, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: /tmp/.com.google.Chrome.jXFf0R}, goog:chromeOptions: {args: [--disable-dev-shm-usage], extensions: []}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.29.0.2:4444/sessio..., se:cdpVersion: 91.0.4472.114, se:vnc: ws://172.29.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://localhost:7900/websockify, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 2d02f409e1b952cd54a6fdc3ac9451a7
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at ava.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
```

## Environment
OS: Windows 10
Docker-Selenium image version: 4.0.0-rc-1-prerelease-20210618
Docker version: 20.10.6
Docker-Compose version: 1.29.1
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker-compose up -d

docker-compose.yaml
```
version: '2.4'
services:
  selenium-docker:
    image: selenium/standalone-docker:4.0.0-rc-1-prerelease-20210618
    hostname: selenium-docker
    container_name: selenium-docker
    ports:
      - 4444:4444
    volumes:
      - ./config.toml:/opt/bin/config.toml
      - ./assets:/opt/selenium/assets
    networks:
      - selenium-network
networks:
  selenium-network:
    name: grid
    driver: bridge
```
config.toml
```
[docker]
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
]
url = "http://host.docker.internal:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20210618"
```

**Comment by RomanPszonka** [comment]
your file needs to be in the container, not on your machine

try adding this mapping in docker-compose.yaml
```
    volumes:
      - /local-directory:/remote-directory
```
keep the file on your machine in c:\local-directory\ 
(I'm not exactly sure about the paths, but just connect to the container and check if your file is accessible in /remote-directory

and then in the script use /remote-directory/resources.xml

**Comment by iceinvein** [comment]
The issue isn't with mounting folder to containers as they're running remotely away from where script is ran. The dynamic node docker is failing to remote upload file with `driver.setFileDetector(new LocalFileDetector());`

If I setup hub and standalone node
```
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.0.0-rc-1-prerelease-20210618
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -v /dev/shm:/dev/shm \
    selenium/node-chrome:4.0.0-rc-1-prerelease-20210618
```
The script manages to upload file remotely.

But with hub and dynamic node docker
```
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.0.0-rc-1-prerelease-20210618
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -v ${PWD}/config.toml:/opt/bin/config.toml selenium/node-docker:4.0.0-rc-1-prerelease-20210618
```

I end up with the error `File not found`

**Comment by namilkimfree** [comment]
Hi
@diemol , @RomanPszonka 

i have same issue .

1. have test.png  in   (- ./seleniumFile:/file/images)   
2. SendKeys(/file/images/test.png)
3. throw file not found exception

```
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
      - ./seleniumFile:/file/images
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - LANGUAGE=ko



  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
#    volumes:
#      - ./seleniumHub:/file/seleniumHub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

```
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210618"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>

```
How do I mount a directory on this?

 "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"

**Comment by namilkimfree** [comment]
i connect bash in Dynamic-Standalone docker, but the file was not found.

**Comment by diemol** [comment]
Thank you for reporting this, @iceinvein!

This was a bug which has been fixed in the linked commit. We will do a new prerelease next week and this will be available there.
