### ISSUE TITLE
Can not create new session (timeout) between hub and nodes

### ISSUE THREAD

**Issue by VejaL** [SeleniumHQ/docker-selenium#1358]
## Last working version

Worked up to version: node-chrome3.141.59-20200515

Stopped working in version:node-chrome3.141.59-2020525
## To Reproduce

1. Make sure that nodes connected with hub.
    Node's Log:
    `DEBUG [SelfRegisteringRemote.registerToHub] - Updated node configuration:`
    Hub's Log:
    `DEBUG [RegistrationServlet.lambda$process$0] - proxy added http://10.2.105.80:5555 INFO [DefaultGridRegistry.add] - Registered a node http://10.2.105.80:5555`
2. Run test script like 
    `driver = webdriver.Remote(
            command_executor=os.environ['SERVER_HUB_URL'],
            desired_capabilities=capabilities)`
3. Then test script would fail here. At the same time, the Node's Log was stopped as below:
```
11:52:51.845 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@218e91e84 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 263}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
11:52:51.844 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@2f497a715 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_292}{Host: localhost:20430}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
e7895134-refs/branch-heads/4515@{#1634}) on port 20430
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Starting ChromeDriver 92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cb11:52:51.835 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:20430/status
11:52:51.822 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:20430/status
11:52:51.821 DEBUG [UrlChecker.waitUntilAvailable] - Waiting for [http://localhost:20430/status]
```
On the other hand, the Hub's Log was like:
```
11:50:26.532 INFO [RequestHandler.process] - Error forwarding the new session Error forwarding the request timeout
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request timeout
at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
at okio.Okio$4.newTimeoutException(Okio.java:232)
at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
... 35 more
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.read(SocketInputStream.java:204)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
... 61 more
```
## Expected behavior

Session started successfully.

## Test script reproducing this issue (when applicable)

No dependency I assume.

## Environment

OS: Linux based AWS ECS Fargate 1.4.0
Docker-Selenium image version: 
```
Hub:latest DIGEST:sha256:faf6f192792e26bd23ba2507934fe52c70f623eec0921a955bbd3758f780544d
Node(worked):3.141.59-20200515
Node(not worked but tried):3.141.59-20200525, 3.141.59-20200719, latest DIGEST:sha256:02906c6f1b2c9520d2d4405dee65b84251fd11d0b6cec18546a0078e07a7efba
```
Docker version: not sure
Docker-Compose version (if applicable):
```
Enviroment variables were set:
HUB_HOST, HUB_PORT,NODE_MAX_INSTANCES,NODE_MAX_SESSION,JAVA_OPTS(-Xmx4000m),
SE_OPTS(-debug),TZ
```

I am sorry the information seems like not enough, but I'd really appreciate some good idea to investigate this issue furthermore.
Thank you!

**Comment by Nagam-Naidu** [comment]
@diemol, Facing the same issue with Chrome version >92. This issue seems to be coming from the latest node-chrome image published last week .

`Error forwarding the new session Error forwarding the request timeout
org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request timeout
at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)`

**Comment by diemol** [comment]
There is an issue with Chrome 92, please check https://github.com/SeleniumHQ/docker-selenium/issues/1346

@VejaL I am confused on which version works and which one does not, I assume you tried the latest release and bumped into the issue. If not, please create a new issue and fill out the whole template.

**Comment by VejaL** [comment]
@diemol 
I filled out the whole template as much as I can. If necessarily I would like copy paste to create a new issue.
```
Worked up to version: node-chrome3.141.59-20200515
Stopped working in version:node-chrome3.141.59-2020525
```

```
Docker-Selenium image version: 
Hub:latest DIGEST:sha256:faf6f192792e26bd23ba2507934fe52c70f623eec0921a955bbd3758f780544d
Node(worked):3.141.59-20200515
Node(not worked but tried):3.141.59-20200525, 3.141.59-20200719, latest DIGEST:sha256:02906c6f1b2c9520d2d4405dee65b84251fd11d0b6cec18546a0078e07a7efba
```

**Comment by diemol** [comment]
`3.141.59-2020525` is a very old release which is not supported anymore. Most likely something needs to be adapted in the test code. You can also join us in the Slack/IRC channel, links at https://www.selenium.dev/support/
