### ISSUE TITLE
Selenium dynamic f config.toml ,I used a separate vm ip and port, but Not running chrome node dynamically in NodeDocker. An error occurs.

### ISSUE THREAD

**Issue by namilkimfree** [SeleniumHQ/docker-selenium#1359]
## To Reproduce

I used a separate vm ip and port, but
Not running chrome node dynamically in NodeDocker. An error occurs.

but  docker -H 172.30.1.31:2375 images command success .

my config.toml file
```
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210713", "{\"browserName\": \"chrome\"}"
    ]
video-image = "selenium/video:ffmpeg-4.3.1-20210713"
[server]
host = 172.30.1.31    
port = 2375
```

my code

   ```
  var options = new ChromeOptions() { AcceptInsecureCertificates = true };
            options.PageLoadStrategy = OpenQA.Selenium.PageLoadStrategy.Normal;
            options.AddArgument("--lang=ko");
            options.AddArgument("--start-maximized");
            options.AddAdditionalOption("intl.accept_languages", "ko");
            options.AddAdditionalOption("se:recordVideo", true);
            options.AddAdditionalOption("se:timeZone", "Asia/Seoul");
            options.AddAdditionalOption("se:screenResolution", "1920x1080");
            var driver = new RemoteWebDriver(new Uri("http://localhost:4444"),options);
            driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(30);
            driver.Navigate().GoToUrl("www.google.com");
```

node docker log 
```

2021-08-04 10:51:49,198 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-node-docker.conf" during parsing
2021-08-04 10:51:49,200 INFO supervisord started with pid 8
2021-08-04 10:51:50,202 INFO spawned: 'selenium-grid-node-docker' with pid 10
Starting Selenium Grid Node Docker...
2021-08-04 10:51:50,207 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
10:51:50.554 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
10:51:50.558 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:51:50.640 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
10:51:50.687 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:51:51.690 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:51:51.802 INFO [NodeServer.createHandlers] - Reporting self as: http://172.30.1.31:2375
10:51:51.818 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:100)
	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:124)
	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:180)
	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:226)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
	... 14 more
Caused by: java.io.FileNotFoundException
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:153)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.connect(Socket.java:270)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
	at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
	at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-08-04 10:51:52,364 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2021-08-04 10:57:08,736 WARN received SIGTERM indicating exit request
Shutdown complete
2021-08-04 10:57:09,655 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-node-docker.conf" during parsing
2021-08-04 10:57:09,657 INFO supervisord started with pid 8
2021-08-04 10:57:10,659 INFO spawned: 'selenium-grid-node-docker' with pid 10
Starting Selenium Grid Node Docker...
2021-08-04 10:57:10,665 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: io.ous.jtoml.ParseException: Newline expected after assignment at 13:13
	at io.ous.jtoml.impl.Parser.error(Parser.java:250)
	at io.ous.jtoml.impl.Parser.parse(Parser.java:51)
	at io.ous.jtoml.JToml.parse(JToml.java:35)
	at org.openqa.selenium.grid.config.TomlConfig.<init>(TomlConfig.java:45)
	at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:55)
	at org.openqa.selenium.grid.config.Configs.from(Configs.java:40)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:72)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:105)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
2021-08-04 10:57:10,984 INFO exited: selenium-grid-node-docker (exit status 1; not expected)

```

## Expected behavior

run dynamic video and chrome node

## Environment

OS: Windows 10  (selenium hub and node docker),   
OS: Ubuntu 20 (docker deamon )

Docker-Selenium image version: prerelease-20210713

-->
Docker version: 
Docker-Compose version (if applicable): 20.10.7
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):

**Comment by diemol** [comment]
What is the command used to start the containers?

**Comment by namilkimfree** [comment]
@diemol  

my local machine:   docker-compose -f .\docker-compose-v3-dynamic-grid.yml up -d


```
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0-rc-1-prerelease-20210618
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


```

and config.toml
```

[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]


video-image = "selenium/video:ffmpeg-4.3.1-20210618"


[server]
host = "172.30.1.31"
port = "2375"

```
Same with changing version to 0618

It was the same even if I removed the quota on the server and port.

**Comment by diemol** [comment]
The error is `Caused by: java.io.FileNotFoundException`, so it seems the `config.toml` cannot be found. Please check that the paths are correct.

**Comment by namilkimfree** [comment]
@diemol 

![image](https://user-images.githubusercontent.com/44854923/128175988-41a55166-148e-45e5-af3c-1f080d65a956.png)

this is  NodeDocker  cli 

have a config.toml file  in /opt/bin/config.toml path

**Comment by diemol** [comment]
A few things:

- There seem to be some special characters in the configuration before and after `browserName`. That seems to be affecting the parsing.
- The `server` section has the docker port, which is wrong. That section needs to have the host machine IP and port in case you are running the Node in a separate VM.
- Please use the latest prerelease https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713

**Comment by namilkimfree** [comment]
@diemol 
how to valid server write?
my ubunt server(virtual box) ip: 172.30.1.31
port(docker daemon): 2375

can i have [server] example?


browserName is valid: https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeDocker/config.toml
same issue 20210713 version

**Comment by diemol** [comment]
It all seems like a configuration issue, I would advise to start first with the Standalone option and when that is working, move from there
https://github.com/SeleniumHQ/docker-selenium#execution-with-standalone-roles

**Comment by namilkimfree** [comment]
@diemol 
 
Standardalone and dockercompose

If i use locally, it's success   in config.toml 
url = "http://host.docker.internal:2375"

but throw error, I use to [server] section

**Comment by namilkimfree** [comment]
@diemol 

It works fine when I use it
url = "http://host.docker.internal:2375"

If a remote VM is used, it will not work properly.

[server]
host:  "myubuntserverip (172.30.1.31)"
port: "2375"


hot to fix? 

[server] section


```
java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)

at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)

Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException

at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)

at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:100)

at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:202)

at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)

at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:213)

at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)


at org.openqa.selenium.grid.Main.launch(Main.java:83)

at org.openqa.selenium.grid.Main.go(Main.java:57)

at org.openqa.selenium.grid.Main.main(Main.java:42)

... 6 more

Caused by: java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)

at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)

at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)

at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)

... 14 more


Caused by: java.io.FileNotFoundException

at io.netty.channel.unix.Errors.newConnectException0(Errors.java:153)

at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)

at io.netty.channel.unix.Socket.connect(Socket.java:270)

at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)

at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)

at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)

at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)

at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)

at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)

at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)

at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)

at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)

at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)

at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)

at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)

at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)

at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)

at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)


at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.base/java.lang.Thread.run(Thread.java:829)


2021-08-04 16:01:32,656 INFO exited: selenium-grid-standalone-docker (exit status 1; not expected)
```

**Comment by namilkimfree** [comment]
```
#Uncomment the following section if you are running the node on a separate VM <-- i want remote server
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```
Previously, all were only used locally, so there was no problem.

**Comment by namilkimfree** [comment]
@diemol 
i found soluation

remote vm server : 
host: tcp://node-ip 
port: daemon port (2375 non tls, 2376 tls and other port maaped)


1. move the remote server (linux)
2. docker download
3. sudo vi /lib/systemd/system/docker.service
4. chnaged ExecStart value ->   /usr/bin/dockerd -H unix:///var/run/docker.sock -H 0.0.0.0:2375
5. sudo systemctl daemon-reload 
6. sudo systemctl restart docker.service

```
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618", "{\"browserName\": \"chrome\"}"
    ]


video-image = "selenium/video:ffmpeg-4.3.1-20210618"


#[server]
host = "tcp://172.30.1.31"
port = "2375"


```
