### ISSUE TITLE
[🐛 Bug]: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by mrkgoh** [SeleniumHQ/docker-selenium#1448]
### What happened?

I have a StockBuyingBot that I dubbed Kenbot which I have running for a year now trying to iron out some bugs along the way.

Kenbot runs via my Synology NAS on a docker image (selenium/standalone-chrome:latest) every morning before the market opens it will place orders for few stocks.

Now when the code gets to driver.get it throws the following traceback:

### Command used to start Selenium Grid with Docker

```shell
#%%
@contextlib.contextmanager
def docker_selenium():
    try:
        client = docker.from_env()

#         #Check if there are Selenium containers
#         if client.containers.list(filters={'ancestor':'selenium/standalone-chrome'})==[]:

        # Then run a selenium container
        container = client.containers.run('selenium/standalone-chrome',
                                          user = 'root',
                                          detach=True,
                                          auto_remove=True,
                                          environment = ["TZ=Asia/Kuala_Lumpur"],
                                          ports={'4444/tcp':('127.0.0.1',4444)},
                                          extra_hosts={
                                              'www.kentrade.com.my': '211.24.18.135', #  source:https://stackoverflow.com/a/69732302/15339732
                                              'www.kentrade.com.my': '211.24.18.7'
                                          	},
                                          volumes = {'/dev/shm':{'bind':'/dev/shm','mode':'rw'},
                                                    '/volume1/docker/chrome/downloads/':{'bind':'/home/seluser/downloads/', 'mode':'rw'}},
                                         privileged = True)
        
        print('{:<47s} : {}'.format('Container' ,'Starting'))
        logger.info('{} : {}'.format('Container' ,'Starting'))

        # check for 20 seconds if the connection to http://127.0.0.1:4444/ is established 
        # and selenium chrome browser is ready
        for _ in range(40):
            try:
                if requests.get('http://127.0.0.1:4444/').status_code==200:
                    print('{:<47s} : {}'.format('Selenium chrome '+ container.name ,'Running'))
                    logger.info('{} : {}'.format('Selenium chrome '+ container.name ,'Running'))
                    break
            except:
                time.sleep(0.5)
        else:
            print('{:<47s} : {}'.format('Container' ,'Failed to start'))
            logger.info('{} : {}'.format('Container' ,'Failed to start'))
        
        yield
        
    finally:

        # Stop all running Selenium containers
        for i in client.containers.list(filters={'ancestor':'selenium/standalone-chrome'}):
            i.stop()
            print('{:<47s} : {}'.format('Container '+ i.name ,'Stopped'))
            logger.info('{} : {}'.format('Container '+ i.name ,'Stopped'))
            
        client.containers.prune()
        print('{:<47s} : {}'.format('Container status','All stopped'))
        logger.info('{} : {}'.format('Container status','All stopped'))
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/volume1/homes/admin/Drive/stock/bursa/bursaqr_announcer.py", line 385, in <module>
    main()
  File "/volume1/homes/admin/Drive/stock/bursa/bursaqr_announcer.py", line 379, in main
    BursaQR().application(sc, px, eg)
  File "/volume1/homes/admin/Drive/stock/bursa/bursaqr_announcer.py", line 338, in application
    sc.producer()
  File "/volume1/homes/admin/Drive/stock/bursa/bursaqr_announcer.py", line 73, in producer
    df = screener(
  File "/volume1/homes/admin/Drive/stock/filehandler/file_handler2.py", line 121, in wrapper
    df = func(*args, **kwargs)
  File "/volume1/homes/admin/Drive/stock/filter/screener.py", line 23, in screener
    acc, pri = getet()
  File "/volume1/homes/admin/Drive/stock/filter/get_ETfilter.py", line 45, in get_ETfilter
    driver.get("https://trade.stockbroking.com.my/stockbroking/research/researchvalidate.aspx?StkCode")
  File "/volume1/homes/admin/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/volume1/homes/admin/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/volume1/homes/admin/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Unable to execute request for an existing session: java.util.concurrent.TimeoutException
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: '7a534966c65d', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.59+', java.version: '11.0.11'
Driver info: driver.version: unknown
```

### Operating System

Linux

### Docker Selenium version (tag)

Selenium Standalone 4.0.0 (revision 3a21814679)

**Comment by diemol** [comment]
Can you share the complete script so we can reproduce this?

**Comment by diemol** [comment]
It does not need to be the exact same one you use, just anything we can run ourselves to replicate the issue.

**Comment by mghantous** [comment]
Have you tried adding the `--disable-gpu` Chrome option? I did not seem to need it before v4, but now seems necessary to avoid this and other similar session timeout exceptions.

**Comment by diemol** [comment]
So this is most likely the same as https://github.com/SeleniumHQ/selenium/issues/9528, so I will close this one.
