### ISSUE TITLE
[🐛 Bug]: Can't get started Selenium Dynamic Grid just from scratch in Ubuntu (getting error)

### ISSUE THREAD

**Issue by ssfxate** [SeleniumHQ/docker-selenium#1465]
### What happened?

I'm getting `Failure due to server error` from node-docker on startup.

Docker version 20.10.2, build 2291f61
docker-compose version 1.25.0, build unknown

### Command used to start Selenium Grid with Docker

```shell
// docker-dynamic-grid.yml
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.1.0-20211209
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.1.0-20211209
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

// config.toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.1.0-20211209", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.1.0-20211209", "{\"browserName\": \"chrome\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20211209"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
[server]
# host = <ip-from-node-machine>
# port = <port-from-node-machine>
```

### Relevant log output

```shell
~/Documents/wdio-setup-docker$ docker-compose -f docker-dynamic-grid.yml up
Starting selenium-hub ... done
Starting wdio-setup-docker_node-docker_1 ... done
Attaching to selenium-hub, wdio-setup-docker_node-docker_1
selenium-hub    | 2021-12-13 05:40:57,538 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub    | 2021-12-13 05:40:57,541 INFO supervisord started with pid 8
node-docker_1   | 2021-12-13 05:40:57,958 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-node-docker.conf" during parsing
node-docker_1   | 2021-12-13 05:40:57,960 INFO supervisord started with pid 8
selenium-hub    | 2021-12-13 05:40:58,543 INFO spawned: 'selenium-grid-hub' with pid 10
node-docker_1   | 2021-12-13 05:40:58,963 INFO spawned: 'selenium-grid-node-docker' with pid 10
node-docker_1   | Starting Selenium Grid Node Docker...
node-docker_1   | 2021-12-13 05:40:58,970 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 05:40:59.065 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub    | 2021-12-13 05:40:59,068 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 05:40:59.071 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 05:40:59.199 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.22.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.22.0.2:4443]
selenium-hub    | 05:40:59.286 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.22.0.2:4442 and tcp://172.22.0.2:4443
selenium-hub    | 05:40:59.318 INFO [UnboundZmqEventBus.<init>] - Sockets created
node-docker_1   | 05:40:59.531 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
node-docker_1   | 05:40:59.537 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
node-docker_1   | 05:40:59.671 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
node-docker_1   | 05:40:59.732 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub    | 05:41:00.320 INFO [UnboundZmqEventBus.<init>] - Event bus ready
node-docker_1   | 05:41:00.734 INFO [UnboundZmqEventBus.<init>] - Event bus ready
node-docker_1   | 05:41:00.944 INFO [NodeServer.createHandlers] - Reporting self as: http://172.22.0.3:5555
node-docker_1   | 05:41:00.976 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
selenium-hub    | 05:41:01.292 INFO [Hub.execute] - Started Selenium Hub 4.1.0 (revision 87802e897b): http://172.22.0.2:4444
node-docker_1   | 05:41:02.568 WARN [RetryRequest.lambda$static$5] - Failure due to server error #1. Retrying.
node-docker_1   | 05:41:04.517 WARN [RetryRequest.lambda$static$5] - Failure due to server error #2. Retrying.
node-docker_1   | java.lang.reflect.InvocationTargetException
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   | 	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
node-docker_1   | 	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
node-docker_1   | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
node-docker_1   | 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
node-docker_1   | 	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:148)
node-docker_1   | 	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:127)
node-docker_1   | 	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:183)
node-docker_1   | 	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
node-docker_1   | 	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
node-docker_1   | 	at org.openqa.selenium.grid.Main.launch(Main.java:83)
node-docker_1   | 	at org.openqa.selenium.grid.Main.go(Main.java:57)
node-docker_1   | 	at org.openqa.selenium.grid.Main.main(Main.java:42)
node-docker_1   | 	... 6 more
node-docker_1   | Caused by: java.lang.reflect.InvocationTargetException
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   | 	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
node-docker_1   | 	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
node-docker_1   | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
node-docker_1   | 	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
node-docker_1   | 	... 14 more
node-docker_1   | Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://host.docker.internal:2375
node-docker_1   | 	at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:125)
node-docker_1   | 	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
node-docker_1   | 	... 22 more
node-docker_1   | Exception in thread "Thread-0" java.lang.NullPointerException
node-docker_1   | 	at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:79)
node-docker_1   | 	at java.base/java.lang.Thread.run(Thread.java:829)
node-docker_1   | 2021-12-13 05:41:04,856 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
```

### Operating System

Ubuntu 21.04

### Docker Selenium version (tag)

4.1.0-20211209

**Comment by ssfxate** [comment]
I've got, that on Linux I can't use `http://host.docker.internal:2375`, but still have no idea about Linux address for Docker Daemon to put in the toml file.

**Comment by ssfxate** [comment]
And the solution is
1. Navigate to `/lib/systemd/system` in your terminal and open `docker.service` file
`nano /lib/systemd/system/docker.service`
2. Find the line which starts with ExecStart and adds `-H=tcp://0.0.0.0:2375` to make it look like
`ExecStart=/usr/bin/dockerd -H=fd:// -H=tcp://0.0.0.0:2375`
Save the Modified File
3. Reload the docker daemon
`systemctl daemon-reload`
4. Restart the container
`sudo service docker restart`
