### ISSUE TITLE
[🐛 Bug]: After upgrade to 4.1.1 images, sessions are not properly terminated

### ISSUE THREAD

**Issue by fkrivsky** [SeleniumHQ/docker-selenium#1471]
### What happened?

**EDIT: The downgrade or hub restart works temporarily. However, overnight the issue comes back.**
The grid seems to work fine during the day under load - multiple tests running, multiple threads each.
However, after some scheduled tests and over the night, the problem comes back. It's difficult to find the exact start because the Hub logs are full of unsuccessful retries - see logs below.

Original report kept:
_After we upgraded from images :4.1.0-20211209 to :4.1.1-20211217 we start seeing issue that browser sessions are not terminated after run is finished. Instead, they are kept open indefinitely, effectively blocking the grid._

_Downgrading back to :4.1.0-20211209 seems to fix the issue._

![image](https://user-images.githubusercontent.com/68921465/146937281-8c6eb3f3-5bae-448c-89c3-76b7bf0b8e5c.png)

### Command used to start Selenium Grid with Docker
We use both Docker Swarm and Kubernetes setup, issue repro in both. Posting Docker Swarm compose file due to brevity:
```shell
version: '3.7'
services:
  selenium-hub:
    image: selenium/hub:4
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      TZ: "America/New_York"
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    deploy:
      labels:
        - "diun.enable=true"
      placement:
        constraints:
          - node.labels.grid == true

  chrome:
    image: selenium/node-chrome:4
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - TZ=America/New_York
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=[REDACTED]:4444
      - SCREEN_HEIGHT=1080
      - SCREEN_WIDTH=1920
      - SCREEN_DEPTH=24
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - VNC_NO_PASSWORD=1
    deploy:
      labels:
        - "diun.enable=true"
      replicas: 40
      placement:
        constraints:
          - node.labels.grid == true
      resources:
        limits:
          cpus: '1.0'
          memory: 800M
        reservations:
          # cpus: '0.25'
          memory: 100M
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
```

### Relevant log output
Hub log:
```shell
06:29:45.256 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
 [Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: chrome, goog:chromeOptions: {args: [--proxy-bypass-list=<-loopb..., --disable-dev-shm-usage, --no-sandbox], excludeSwitches: [enable-automation, load-extension], extensions: [], prefs: {credentials_enable_service: false, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, safebrowsing.enabled: true}}, handlesAlerts: true, javascriptEnabled: true, pageLoadStrategy: normal, takesScreenshot: true}, Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--proxy-bypass-list=<-loopb..., --disable-dev-shm-usage, --no-sandbox], excludeSwitches: [enable-automation, load-extension], extensions: [], prefs: {credentials_enable_service: false, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, safebrowsing.enabled: true}}, pageLoadStrategy: normal}]
06:29:46.043 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 1ecf145433f3fa4c09d0020fac9b1e79, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 96.0.4664.110, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: /tmp/.com.google.Chrome.LLSaqp}, goog:chromeOptions: {debuggerAddress: localhost:38832}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://mgs-qa-harbor201.be.mo..., se:cdpVersion: 96.0.4664.110, se:vnc: ws://mgs-qa-harbor201.be.mo..., se:vncEnabled: true, se:vncLocalAddress: ws://10.0.21.28:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
06:32:29.441 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
java.io.IOException: Invalid Status code=400 text=Bad Request
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
06:34:15.354 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
java.io.IOException: Invalid Status code=400 text=Bad Request
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
06:35:15.517 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
java.io.IOException: Invalid Status code=400 text=Bad Request
	at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
	at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:118)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Node log:
```shell
2021-12-30 05:28:31,419 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-12-30 05:28:31,421 INFO supervisord started with pid 9
2021-12-30 05:28:32,424 INFO spawned: 'xvfb' with pid 11
2021-12-30 05:28:32,425 INFO spawned: 'vnc' with pid 12
2021-12-30 05:28:32,427 INFO spawned: 'novnc' with pid 13
2021-12-30 05:28:32,429 INFO spawned: 'selenium-node' with pid 14
2021-12-30 05:28:32,906 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-12-30 05:28:32,906 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-12-30 05:28:32,906 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-12-30 05:28:32,907 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --host 646a3dad9c82
Generating Selenium Config
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Selenium Grid Node configuration: 
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
grid-url = "http://mgs-qa-harbor201.be.monster.com:4444"
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "96.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Node...
05:28:34.690 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
05:28:34.718 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
05:28:34.935 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
05:28:35.133 INFO [UnboundZmqEventBus.<init>] - Sockets created
05:28:36.139 INFO [UnboundZmqEventBus.<init>] - Event bus ready
05:28:36.347 INFO [NodeServer.createHandlers] - Reporting self as: http://646a3dad9c82:5555
05:28:36.429 INFO [NodeOptions.getSessionFactories] - Detected 1 available processors
05:28:36.531 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "96.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times
05:28:36.542 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
05:28:37.035 INFO [NodeServer$1.start] - Starting registration process for node id ba559d08-6f8e-4ba3-9621-29a004ed6bf7
05:28:37.037 INFO [NodeServer.execute] - Started Selenium node 4.1.1 (revision e8fcc2cecf): http://646a3dad9c82:5555
05:28:37.052 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
05:28:38.065 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 49256
On[l1640860125.226][SEVERE]: bind() failed: Cannoyt  laoscsailg nconnect iroenqsu easrtee da laldodwreeds.s
Please  s(e9e9 )h
ttps://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
05:28:46.376 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
06:16:45.661 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=b541cf15-8a79-4dfe-b0d0-c07650e0e043, type=selenium-rejected-event, data={"data": "ea���+�NfJ��@\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000:\u0000��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007�\u0011�\u0016\u0000\u0018�\b�\u0012\u0000\u0016\u0000\u0013�\u0017\u0000\u001b\u00005\u0000�\u0000\u002f\u0000�\u0000A\u0000\u0007\u0000\u0005\u0000\u0004\u0000\n\u0000�\u0001\u0000\u0000S\u0000\u0000\u0000+\u0000)\u0000\u0000\u0026mgs-qa-harbor-worker201.be.monster.com\u0000\u000b\u0000\u0004\u0003\u0000\u0001\u0002\u0000\n\u0000\f\u0000\n\u0000\u001d\u0000\u0017\u0000\u001e\u0000\u0019\u0000\u0018\u0000#","name": "%��"}] -> ea���+�NfJ��@  R�
� 9 8 � �� : ��	� 3 2 � � E D� 4 � F��� ��  �  5 � / � A    
 �  S   + )  &<HOSTNAME_REDACTED>    
  
      
      #
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 47476
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[164086ChromeDriver was started suc3c7e8s5s.f2u7l9l]y[.S
EVERE]: bind() failed: Cannot assign requested address (99)
06:29:46.034 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
06:32:29.439 INFO [ProxyNodeWebsockets.apply] - Not owner of 1ecf145433f3fa4c09d0020fac9b1e79
06:34:15.353 INFO [ProxyNodeWebsockets.apply] - Not owner of 1ecf145433f3fa4c09d0020fac9b1e79
06:35:15.515 INFO [ProxyNodeWebsockets.apply] - Not owner of 1ecf145433f3fa4c09d0020fac9b1e79
```

### Operating System

CentOS 7, latest Docker with Swarm

### Docker Selenium version (tag)
4.0.0
4.1.0
4.1.1-20211217

**Comment by fkrivsky** [comment]
Could this be related to #1469 ? AFAIK our company also uses Nessus security scanning software.

**Comment by fkrivsky** [comment]
Confirmed the sec scan hypothesis - this is indeed duplicate issue of #1469. After excluding the grid machines from the vulnerability scanner the issue is not happening again.
