### ISSUE TITLE
[🐛 Bug]: when I connect node docker on vm2 to node hub on vm1 there is an error

### ISSUE THREAD

**Issue by ibodog** [SeleniumHQ/docker-selenium#1487]
### What happened?

Following [latest docs](https://github.com/SeleniumHQ/docker-selenium/issues/1403#issuecomment-959134307), but using docker-compose on Ubuntu 20.04 instead of docker commands shown in docs.  When vm2 is started up there is an error.  Maybe it is a problem with my translation of the doc's docker command to docker-compose?  vm1 has hub and local node running and working as expected.  vm2 has the error on the node-docker.

Could not bind to address or port is already in use. Host 10.10.0.213, Port 5555

vm1 10.10.0.215

vm2 10.10.0.213 docker-compose.yaml

> version: '3.7'
>
> 
> services:
> 
>   node-docker:
>     image: selenium/node-docker:latest
>     container_name: node-docker
>     shm_size: "2gb"
>     volumes:
>       - ./assets:/opt/selenium/assets
>       - ./config.toml:/opt/bin/config.toml
>     environment:
>       - SE_EVENT_BUS_HOST=10.10.0.215
>       - SE_EVENT_BUS_PUBLISH_PORT=4442
>       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
>       - SE_NODE_MAX_SESSIONS=6
>       - SE_NODE_OVERRIDE_MAX_SESSIONS=true
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
>     ports:
>       - "5555:5555"

vm2 10.10.0.213 config.toml

> [docker]
> configs = [
>     "selenium/standalone-firefox:latest", "{\"browserName\": \"firefox\"}",
>     "selenium/standalone-chrome:latest", "{\"browserName\": \"chrome\"}",
>     "selenium/standalone-edge:latest", "{\"browserName\": \"MicrosoftEdge\"}"
>     ]
> 
> url = "http://host.docker.internal:2375"
> 
> video-image = "selenium/video:latest"
> 
> [server]
> host = "10.10.0.213"
> port = "5555"

### Command used to start Selenium Grid with Docker

```shell
version: '3.7'

services:

  node-docker:
    image: selenium/node-docker:latest
    container_name: node-docker
    shm_size: "2gb"
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
03:45:31.936 INFO [Docker.getImage] - Obtaining image: selenium/standalone-edge:latest
03:45:31.937 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-edge', tag='latest', digest='null'}
03:45:31.944 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: MicrosoftEdge} to docker image selenium/standalone-edge:latest 6 times
03:45:31.944 INFO [Docker.getImage] - Obtaining image: selenium/standalone-firefox:latest
03:45:31.944 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-firefox', tag='latest', digest='null'}
03:45:31.949 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: firefox} to docker image selenium/standalone-firefox:latest 6 times
03:45:31.969 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: java.io.UncheckedIOException: java.io.IOException: Could not bind to address or port is already in use. Host 10.10.0.213, Port 5555
        at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:169)
        at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:191)
        at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:188)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:57)
        at org.openqa.selenium.grid.Main.main(Main.java:42)
        ... 6 more
Caused by: java.io.IOException: Could not bind to address or port is already in use. Host 10.10.0.213, Port 5555
        ... 14 more
Caused by: java.net.BindException: Cannot assign requested address
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-30 03:45:32,374 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
```

### Operating System

Ubuntu 20.04 for both hub and node

### Docker Selenium version (tag)

4.1.1-20220121

**Comment by diemol** [comment]
Thank you for reporting this. 

This was a solved issue but for some reason I forgot to apply the fix in the Node Docker as well. This will be part of the next release.

**Comment by ibodog** [comment]
Pulled new image 4.1.2-20220131.  The port or address in use problem is gone.  But still not able to connect and register in the same config documented above.  VM2 node repeats "Sending registration event..." message about every 10 seconds.

The VM1 hub responds incorrectly when queried for status:

curl http://vm1.server.net:4444/status
{
  "value": {
    "ready": false,
    "message": "Unable to read distributor status."
  }

Prior to trying to connect the VM2 the VM1 was responding correctly to the same status request.

**Comment by diemol** [comment]
For Dynamic Grid in different VMs, check https://github.com/SeleniumHQ/docker-selenium#using-dynamic-grid-in-different-machinesvms

**Comment by ibodog** [comment]
Thanks, diemol.  I found the problem was a typo in the config.toml so the IP address of the node was incorrect.  I turned on log level TRACE and http logging on the hub and discovered that the wrong IP address that was accepted by the hub causes the hub to fail when it tries to reach out to "<bad.ip.add.ress>:5555".  But I think this is a different bug.
