### ISSUE TITLE
[🐛 Bug]: can't get selenium-docker image to find ca/cert/key to enable TLS communication with dockerd

### ISSUE THREAD

**Issue by ibodog** [SeleniumHQ/docker-selenium#1496]
### What happened?

Ubuntu 20.04 & Docker 20.10.12.  Selenium-docker can't reach the Docker daemon
Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at https://172.17.0.1:2376

Why would I try this:
Systemd won't start docker daemon at startup if trying to bind to a tcp port w/o TLS enabled.  This binding is needed for selenium-docker container to start the browser containers.  So on a linux system reboot the docker daemon fails to start and thus my grid has to be manually restarted (involves mucking around with the docker.service - won't go into detail on that).

What I tried:
Following directions on Docker web site https://docs.docker.com/engine/security/protect-access/ I am able to configure the local daemon with TLS on port 2376 with -H tcp://0.0.0.0:2376.  A local docker client command can correctly reach the docker daemon through the tcp binding with command:

docker --tlsverify --tlscacert=certs/ca-cert.pem --tlscert=certs/client-cert.pem --tlskey=certs/client-key.pem -H=grid4.server.net:2376 version

Now I need to get the selenium-docker container to access the ca/cert/key for the client. So following the instructions from the above Docker docs, I mounted a local docker folder with the 3 ca/cert/key files and changed the ownership of the files and directory to 1200:1201 to match the container seluser.  This directory is then mounted in the container at /home/seluser/.docker.  There are also 2 env vars set in the docker-compose file for the container per the Docker docs: DOCKER_HOST=tcp://172.17.0.1:2376 and DOCKER_TLS_VERIFY=1

config.toml has url = https://172.17.0.1:2376

I am able to validate that the selenium-docker container sees the .Docker file in /home/seluser/.docker and that directory and file permissions are correct for seluser and seluser can cat out all 3 files.  But still the selenium process cannot find the Docker daemon.  I also executed a shell in the selenium-docker container and I can reach the docker daemon at the address and port specified in the config and read the remote cert:
openssl s_client -connect 172.17.0.1:2376

I suspect that somehow the ca/cert/grid files need to be exposed to the java process when the selenium process starts?  Does this require a change to the docker image?  Would be nice if this could be fixed/documented because I think maybe lots of people will eventually run into this docker/tls issue as Docker tightens security.

config.toml:
[docker]
configs = [
    "selenium/standalone-firefox:latest", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:latest", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:latest", "{\"browserName\": \"MicrosoftEdge\"}"
    ]
url = "https://172.17.0.1:2376"
video-image = "selenium/video:latest"

### Command used to start Selenium Grid with Docker

```shell
version: '3.7'

services:

  node-docker:
    image: selenium/node-docker:latest
    shm_size: "2gb"
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - ./docker:/home/seluser/.docker
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - DOCKER_HOST=tcp://172.17.0.1:2376
      - DOCKER_TLS_VERIFY=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
$ docker-compose up
Starting grid4_selenium-hub_1 ... done
Starting grid4_http_1         ... done
Starting grid4_node-docker_1  ... done
Attaching to grid4_http_1, grid4_selenium-hub_1, grid4_node-docker_1
http_1          | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
selenium-hub_1  | 2022-02-01 19:36:51,254 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
http_1          | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
selenium-hub_1  | 2022-02-01 19:36:51,256 INFO supervisord started with pid 8
http_1          | [Tue Feb 01 19:36:51.072720 2022] [mpm_event:notice] [pid 1:tid 139652510731080] AH00489: Apache/2.4.52 (Unix) configured -- resuming normal operations
http_1          | [Tue Feb 01 19:36:51.072744 2022] [core:notice] [pid 1:tid 139652510731080] AH00094: Command line: 'httpd -D FOREGROUND'
node-docker_1   | 2022-02-01 19:36:51,490 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-node-docker.conf" during parsing
node-docker_1   | 2022-02-01 19:36:51,492 INFO supervisord started with pid 8
selenium-hub_1  | 2022-02-01 19:36:52,258 INFO spawned: 'selenium-grid-hub' with pid 10
node-docker_1   | 2022-02-01 19:36:52,494 INFO spawned: 'selenium-grid-node-docker' with pid 10
selenium-hub_1  | 19:36:52.496 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub_1  | 2022-02-01 19:36:52,498 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
node-docker_1   | Starting Selenium Grid Node Docker...
node-docker_1   | 2022-02-01 19:36:52,501 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub_1  | 19:36:52.500 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub_1  | 19:36:52.574 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.18.0.3:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.18.0.3:4443]
selenium-hub_1  | 19:36:52.618 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.18.0.3:4442 and tcp://172.18.0.3:4443
selenium-hub_1  | 19:36:52.631 INFO [UnboundZmqEventBus.<init>] - Sockets created
node-docker_1   | 19:36:52.771 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
node-docker_1   | 19:36:52.774 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
node-docker_1   | 19:36:52.849 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
node-docker_1   | 19:36:52.892 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub_1  | 19:36:53.632 INFO [UnboundZmqEventBus.<init>] - Event bus ready
node-docker_1   | 19:36:53.893 INFO [UnboundZmqEventBus.<init>] - Event bus ready
node-docker_1   | 19:36:53.995 INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.4:5555
node-docker_1   | 19:36:54.024 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
selenium-hub_1  | 19:36:54.103 INFO [Hub.execute] - Started Selenium Hub 4.1.2 (revision 9a5a329c5a): http://172.18.0.3:4444
node-docker_1   | java.lang.reflect.InvocationTargetException
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   |       at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
node-docker_1   |       at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
node-docker_1   | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
node-docker_1   |       at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:148)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:127)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:183)
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
node-docker_1   |       at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
node-docker_1   |       at org.openqa.selenium.grid.Main.launch(Main.java:83)
node-docker_1   |       at org.openqa.selenium.grid.Main.go(Main.java:57)
node-docker_1   |       at org.openqa.selenium.grid.Main.main(Main.java:42)
node-docker_1   |       ... 6 more
node-docker_1   | Caused by: java.lang.reflect.InvocationTargetException
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
node-docker_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
node-docker_1   |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
node-docker_1   |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
node-docker_1   |       at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
node-docker_1   |       at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
node-docker_1   |       at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
node-docker_1   |       ... 14 more
node-docker_1   | Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at https://host.docker.internal:2376
node-docker_1   |       at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:125)
node-docker_1   |       at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
node-docker_1   |       ... 22 more
node-docker_1   | Exception in thread "Thread-0" java.lang.NullPointerException
node-docker_1   |       at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:79)
node-docker_1   |       at java.base/java.lang.Thread.run(Thread.java:829)
node-docker_1   | 2022-02-01 19:38:26,767 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
```

### Operating System

Ubuntu 20.04

### Docker Selenium version (tag)

4.1.2-20220131

**Comment by diemol** [comment]
There are a few things here:

1. It is not straightforward to have to talk via TCP in some cases, like this in Ubuntu. For that, at some point, we will offer the alternative to mount the `docker.sock`, follow #1430 for updates.
2. If you mount a certificate, you need to tell the store to accept it so Java can use it: https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image
3. Not sure why you need a certificate if everything is local, these instructions should be enough https://github.com/SeleniumHQ/docker-selenium/issues/1465#issuecomment-992310199

**Comment by ibodog** [comment]
The certificate requirement is from docker.  It won't start at boot time in systemd if there is a tcp connection defined without tls enabled.

**Comment by diemol** [comment]
It is a recommendation from docker, not a must. In anycase, we need to offer the `docker.sock` option as well.

I believe this issue can be closed and it will serve as good knowledge base for other users.
