### ISSUE TITLE
[🐛 Bug]: Hub/Node stops responding when scanned by vulnerability scanning software

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/docker-selenium#1497]
### What happened?

After a Nessus Scan(vulnerability scanning software) the Website only show the Text "Loading" and cant be reached. This should be related to #1469 which was fixed in the last release. 

Timestamps are the same, i just forgot to set the timezone on the hub. 
Log Node:
```
08:32:02.883 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: UUID string too large

java.lang.IllegalArgumentException: UUID string too large

        at java.base/java.util.UUID.fromString(UUID.java:199)

        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:829)

08:32:02.938 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=220621d5-58f4-4b5d-b20b-e50a10af1bfd, type=selenium-rejected-event, data={"data": "��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007�\u0011�\u0016\u0000\u0018�\b�\u0012\u0000\u0016\u0000\u0013�\u0017\u0000\u001b\u00005\u0000�\u0000\u002f\u0000�\u0000A\u0000\u0007","name": "�ot�1��G\u0004��#KX�\u0006ON\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000"}] -> ��   �32��ED�4�F������/�A
```

Log Hub:
```
07:32:02.882 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: UUID string too large

java.lang.IllegalArgumentException: UUID string too large

        at java.base/java.util.UUID.fromString(UUID.java:199)

        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:829)

07:32:02.935 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=68e768fc-24ec-40ab-a1d7-3815aee77113, type=selenium-rejected-event, data={"data": "��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007�\u0011�\u0016\u0000\u0018�\b�\u0012\u0000\u0016\u0000\u0013�\u0017\u0000\u001b\u00005\u0000�\u0000\u002f\u0000�\u0000A\u0000\u0007","name": "�ot�1��G\u0004��#KX�\u0006ON\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000"}] -> ��   �32��ED�4�F������/�A

07:32:52.624 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "5ff8e20c8f4de395d834dd60b0eb28b8","eventTime": 1643787172623046714,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: \nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: \nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:147)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "*I deleted servername*","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002f","http.user_agent": "Mozilla\u002f4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident\u002f4.0)","session.id": ""}}

 

07:34:19.464 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "f5958b75bec27911c754b65750f65e23","eventTime": 1643787259463365237,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: login.php\nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: login.php\nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:147)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "*i deleted servername*","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002flogin.php","http.user_agent": "Mozilla\u002f4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident\u002f4.0)","session.id": "login.php"}}
```

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4442-4444:4442-4444 \
--name selenium-hub selenium/hub:latest
```

### Relevant log output

```shell
08:32:02.883 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: UUID string too large

java.lang.IllegalArgumentException: UUID string too large

        at java.base/java.util.UUID.fromString(UUID.java:199)

        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:829)

08:32:02.938 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=220621d5-58f4-4b5d-b20b-e50a10af1bfd, type=selenium-rejected-event, data={"data": "��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007�\u0011�\u0016\u0000\u0018�\b�\u0012\u0000\u0016\u0000\u0013�\u0017\u0000\u001b\u00005\u0000�\u0000\u002f\u0000�\u0000A\u0000\u0007","name": "�ot�1��G\u0004��#KX�\u0006ON\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000"}] -> ��   �32��ED�4�F������/�A



07:32:02.882 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: UUID string too large

java.lang.IllegalArgumentException: UUID string too large

        at java.base/java.util.UUID.fromString(UUID.java:199)

        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

        at java.base/java.lang.Thread.run(Thread.java:829)

07:32:02.935 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=68e768fc-24ec-40ab-a1d7-3815aee77113, type=selenium-rejected-event, data={"data": "��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007�\u0011�\u0016\u0000\u0018�\b�\u0012\u0000\u0016\u0000\u0013�\u0017\u0000\u001b\u00005\u0000�\u0000\u002f\u0000�\u0000A\u0000\u0007","name": "�ot�1��G\u0004��#KX�\u0006ON\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000"}] -> ��   �32��ED�4�F������/�A

07:32:52.624 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "5ff8e20c8f4de395d834dd60b0eb28b8","eventTime": 1643787172623046714,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: \nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: \nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:147)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "*I deleted servername*","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002f","http.user_agent": "Mozilla\u002f4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident\u002f4.0)","session.id": ""}}

 

07:34:19.464 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "f5958b75bec27911c754b65750f65e23","eventTime": 1643787259463365237,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: login.php\nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: login.php\nBuild info: version: '4.1.2', revision: '9a5a329c5a'\nSystem info: host: '96e1264419bb', ip: '10.88.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-348.7.1.el8_5.x86_64', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:129)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$3(HandleSession.java:147)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:219)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "*i deleted servername*","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002flogin.php","http.user_agent": "Mozilla\u002f4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident\u002f4.0)","session.id": "login.php"}}
```

### Operating System

Linux RHEL8

### Docker Selenium version (tag)

4.1.2

**Comment by diemol** [comment]
Can you please share the request being sent so I can reproduce and fix this?
(I thought it got fixed :/)

**Comment by erik-rnbt** [comment]
Sorry i dont know how to get a specifix request that causes the crash. The people who run these scans in our company just told me that is scans every port of the server ...
I just can provide you another Log from the Hub with the Log-Level Debug:
```
21:41:14.698 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=2cb5717e-672b-4f1b-a831-a0626c85fcd3, type=selenium-rejected-event, data={"data": "���j�\u00108���\u002f4Ҳ�\u0026�O\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000:\u0000��\t�\u0013\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018","name": "��sE�W�m�\u0012\u001f�q\u000f�\u0007�\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000:\u0000��\t"}] -> ���j�8���/4Ҳ�&�OR�

�98���:��       �32��ED�
```

Hope this is enough information for you. 

Maybe the free version of Nessus from tenable can reproduce this error or grossga from the last issue sees this an can give additional information, if he has the issue too.

**Comment by abaldwin-op** [comment]
_Something_ is sending requests and crashing our 4.1.2 hub/nodes (running on Kubernetes 1.18.20). Our hub deployment _is_ exposed, so it's hard to say if internal or external. But adding my snippet in case it helps the investigation/fix... Let me know what other info. may help.

```
02:49:35.033 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=5f9566ac-431f-4f61-8b2b-fe8815b91402, type=selenium-rejected-event, data={"data": "@\u0000f\u0000j\u0000�\u0000�\u0001\u0000\u0000Q\u0000\u0000\u0000\u0018\u0000\u0016\u0000\u0000\u0013x.x.x.x:4443\u0000\u0005\u0000\u0005\u0001\u0000\u0000\u0000\u0000\u0000\n\u0000\b\u0000","name": "�0��m��J�\u0010\u001a\u0026�b�\u0017�\u0002\u0000\u0000h�\u0014�\u0013�\u002f�+�0�,�\u0011�\u0007�'�#�\u0013�\t�(�$�\u0014�\n�\u0015\u0000�\u0000�\u0000g\u0000k\u00003\u00009\u0000�\u0000�\u0000\u0005\u0000\u0004\u0000\u003c\u0000=\u0000\u002f\u00005�\u0012\u0000\u0016\u0000\n\u0000\u0003\u0000\b\u0000\u0006\u0000\u0014\u0000\u0011\u0000\u0019\u0000\u0017\u00002�\b\u0000\u0012\u0000\u0013\u0000\u0015\u0000"}] -> @ f j � �  Q      x.x.x.x:4443
```

We've reverted to 3.141.59 and are simply building our own node-chrome images for now.

**Comment by meemic-man** [comment]
We are seeing something similar as well.

`16:02:07.011 ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. Event[id=bcab9c7c-afff-479b-ab38-2d9c0f7f7b38, type=selenium-rejected-event, data={"data": "node-heartbeat","name": "\u0000\u0000\u0000\u0000\u0000\u0001\u0000\b\u0000\u0000\u0000\u0000\u0000"}] -> node-heartbeat`

We also have security scans, possibly from Nessus and others.

We are running 4.1.2. We had seen more failures in previous weeks, which appear to have been resolved since migrating.

**Comment by zafor99** [comment]
I am seeing the similar issue on my grid. Once I get the error " Received message without a valid secret. Rejecting.", the hub stops deleting session from session map. The session does not get deleted.  On the hub log, I only notice log for "Session created by the distributor" but nothing for "Deleted session from local session map".

**Comment by diemol** [comment]
@abaldwin-op @meemic-man @zafor99 
can you please share your full stacktrace and/or log message?

**Comment by diemol** [comment]
I implemented a fix based on the information I got from this issue, ideally those scanning software tools should not affect more but if there is another problem, please create a new issue.

This will be released either in 4.1.3 oe 4.2.0

**Comment by kartick-s** [comment]
@diemol 
We are also facing the same error while scanning server where grid is running.
Observed that after we have received the below error, Grid UI is not showing any nodes but status API call(https://seleniumgrid/status/) is still returning 200(OK) response which is not correct.

Hope this issue will also be addressed in next version i.e. 4.1.3 oe 4.2.0

Error:

ERROR [UnboundZmqEventBus$PollingRunnable.rejectEvent] - Received message without a valid secret. Rejecting. 
Event[id=347c50c3-850d-4856-b727-19117eec483b, type=selenium-rejected-event, data={"data": "\u0000p�{���\u001c`�e�8�da",
"name": "?�\u0006Q�r��X\u0001�3A\u0014�%:�\u0000\u0000R�\n�\u0014\u00009\u00008\u0000�\u0000��\u0019\u0000:\u0000��\t�\u0013
\u00003\u00002\u0000�\u0000�\u0000E\u0000D�\u0018\u00004\u0000�\u0000F�\u0007"}] -> ^@p�{���^\`�e�8�da

Grid UI:

![image](https://user-images.githubusercontent.com/95689276/155376514-c7f3b08d-aa9a-4f5f-82da-578f179c4de3.png)

Grid Status:

![image](https://user-images.githubusercontent.com/95689276/155376771-6e15a7d6-0058-4959-be62-7386b4355b23.png)

**Comment by cgossett** [comment]
FWIW, I was able to recreate the issue using a Nessus Essentials/Home version and performing a "Basic Network Scan" against a "standalone" grid instance. As I think others have noted, while the /status REST calls still seem to be functional, calls to the /graphql endpoint fail, which seems to result in the UI's infinite "Loading" status.

I'll try and post more details/information later on especially if I can identify which part of the Nessus scan is triggering the failure in the Grid.

**Comment by cedricroijakkers** [comment]
> FWIW, I was able to recreate the issue using a Nessus Essentials/Home version and performing a "Basic Network Scan" against a "standalone" grid instance. As I think others have noted, while the /status REST calls still seem to be functional, calls to the /graphql endpoint fail, which seems to result in the UI's infinite "Loading" status.

We are having the exact same problem in our production cluster, but in this case it seems to be triggered by a Qualys Cloud Agent network scan.

However, I've noticed that the `/graphql` endpoint does not become fully unresponsive. We have some monitoring on the endpoint to retrieve the `sessionCount` and `maxSession`, and check if the slots are not full for too long. During the moment of the hub outage, the monitoring managed to query the `sessionCount` just fine, meaning that the `/graphql` endpoint is reachable, at least for this part.

It seems as though the grid is accepting new Selenium tests to be executed, but it not managing to start them and therefore the test gets a timeout since it does not want to run on a node. I'm not entirely sure if this is because the node has died or the hub has died. They are both running on VMs in the same network that are being scanned by Qualys at the same time.

The annoying part is, that there seems to be no way to detect that the hub and/or node is down, because the `/status` endpoint is responding that everything is just fine (we have a Docker healthcheck on this, so if this fails Docker will restart the container) and the `/graphql` is responding that the session slots are not full, so from a distance it seems as if everything is just fine. However tests are not running.

I'm trying to find out what exactly in the Qualys scan suite is causing this, but since the scan is literally doing thousands of funky requests, it's very hard to find the one(s) that is (are) causing the breakage. Not having access to the Qualys security scan application is not helping.
