### ISSUE TITLE
[🐛 Bug]: scalable grid: hub stops processing if remote node reports incorrect address

### ISSUE THREAD

**Issue by ibodog** [SeleniumHQ/docker-selenium#1499]
### What happened?

On a remote selenium-docker node there was a typo in the node server's IP address in the config.toml file.  The ip address in the toml file was not reachable on the network.  When the remote node is started it does not report success in connecting to the hub.  The request to connect that includes the wrong ip address causes the selenium hub process to stop most processing - no more browser sessions will run on any previously attached node.  To recover the hub has to be restarted.

From the server TRACE log (VM1)
```
02:47:43.337 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x52653e75] with a retry value of false
02:47:43.338 DEBUG [NettyConnectListener.onFailure] - Failed to recover from connect exception: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.213:5555 with channel [id: 0x52653e75]
02:47:43.338 DEBUG [AsyncCompletionHandler.onThrowable] - No route to host: /10.10.0.213:5555
java.net.ConnectException: No route to host: /10.10.0.213:5555
```

part of config.toml on the remote node (VM2)
```toml
[server]
host = "10.10.0.212"  <--there is the wrong host ip address
port = "5555"
```

When I corrected the IP address in config.toml the node connects correctly.  But probably there is missing error handling in the hub process that should handle the error more gracefully.

### Command used to start Selenium Grid with Docker

```shell
version: '3.7'

services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_OPTS=--http-logs true --log-level FINE
```

### Relevant log output

```shell
02:47:43.337 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x52653e75] with a retry value of false
02:47:43.338 DEBUG [NettyConnectListener.onFailure] - Failed to recover from connect exception: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.213:5555 with channel [id: 0x52653e75]
02:47:43.338 DEBUG [AsyncCompletionHandler.onThrowable] - No route to host: /10.10.0.213:5555
java.net.ConnectException: No route to host: /10.10.0.213:5555
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.10.0.213:5555
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
02:47:43.596 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:44.339 DEBUG [RetryRequest.lambda$static$5] - Failure due to server error #1. Retrying.
02:47:44.695 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:45.795 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:46.895 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:47.401 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x05e49b6f] with a retry value of true
02:47:47.402 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:47.995 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:48.360 DEBUG [LoggingHandler.channelRead] - [id: 0x972b434b, L:/0.0.0.0:4444] READ: [id: 0x51230b9d, L:/172.19.0.2:4444 - R:/10.10.0.103:54880]
02:47:48.361 DEBUG [LoggingHandler.channelReadComplete] - [id: 0x972b434b, L:/0.0.0.0:4444] READ COMPLETE
02:47:48.370 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET /status HTTP/1.1
Host: se-hub.server.net:4444
User-Agent: curl/7.64.1
Accept: */*
02:47:48.370 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET /status HTTP/1.1
Host: se-hub.server.net:4444
User-Agent: curl/7.64.1
Accept: */*
02:47:48.370 DEBUG [RequestConverter.channelRead0] - Incoming message: EmptyLastHttpContent
02:47:48.370 DEBUG [RequestConverter.channelRead0] - Closing input pipe.
02:47:49.096 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:50.195 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:50.372 DEBUG [SeleniumSpanExporter$1.lambda$export$1] - SpanData{spanContext=ImmutableSpanContext{traceId=ce6cefbf49aeafcac4730cb8016c01fa, spanId=66aacf344496c880, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.8.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.10.1"}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=default, version=null, schemaUrl=null}, name=grid.status, kind=INTERNAL, startEpochNanos=1643770068371000000, endEpochNanos=1643770070372299074, attributes=AttributesMap{data={http.method=GET, error=true, http.target=/status, http.status_code=200}, capacity=128, totalAddedValues=4}, totalAttributeCount=4, events=[ImmutableEventData{name=exception, attributes={exception.message="Error or timeout while getting Distributor status: null", exception.stacktrace="java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at org.openqa.selenium.grid.router.GridStatusHandler.execute(GridStatusHandler.java:85)
        at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
        at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
", exception.type="java.util.concurrent.TimeoutException", http.flavor=1, http.host="se-hub.server.net:4444", http.method="GET", http.scheme="HTTP", http.status_code=200, http.target="/status", http.user_agent="curl/7.64.1", logger="org.openqa.selenium.grid.router.GridStatusHandler"}, epochNanos=1643770070372287655, totalAttributeCount=11}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=OK, description=Kind: OK Description:}, hasEnded=true}
02:47:50.373 DEBUG [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "ce6cefbf49aeafcac4730cb8016c01fa","eventTime": 1643770070372287655,"eventName": "exception","attributes": {"exception.message": "Error or timeout while getting Distributor status: null","exception.stacktrace": "java.util.concurrent.TimeoutException\n\tat java.base\u002fjava.util.concurrent.FutureTask.get(FutureTask.java:204)\n\tat org.openqa.selenium.grid.router.GridStatusHandler.execute(GridStatusHandler.java:85)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "java.util.concurrent.TimeoutException","http.flavor": 1,"http.host": "se-hub.server.net:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 200,"http.target": "\u002fstatus","http.user_agent": "curl\u002f7.64.1","logger": "org.openqa.selenium.grid.router.GridStatusHandler"}}

02:47:50.473 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x9fc142e8] with a retry value of true
02:47:50.473 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:51.295 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:52.395 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:53.495 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:53.545 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x0f0c7d75] with a retry value of true
02:47:53.546 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:54.596 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.expiredChannels] - Adding Candidate expired Channel [id: 0xd8202c3c, L:/172.19.0.2:39982 - R:/172.19.0.4:5555] isIdleTimeoutExpired=true isRemotelyClosed=false isTtlExpired=false
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.closeChannels] - Closing Idle Channel [id: 0xd8202c3c, L:/172.19.0.2:39982 - R:/172.19.0.4:5555]
02:47:55.696 DEBUG [AsyncHttpClientHandler.channelInactive] - Channel Closed: [id: 0xd8202c3c, L:/172.19.0.2:39982 ! R:/172.19.0.4:5555] with attribute DISCARD
02:47:55.697 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Closed 1 connections out of 1 in 2 ms
02:47:56.617 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0xe139ff17] with a retry value of true
02:47:56.617 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*
il.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "java.util.concurrent.TimeoutException","http.flavor": 1,"http.host": "se-hub.server.net:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 200,"http.target": "\u002fstatus","http.user_agent": "curl\u002f7.64.1","logger": "org.openqa.selenium.grid.router.GridStatusHandler"}}

02:47:50.473 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x9fc142e8] with a retry value of true
02:47:50.473 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:51.295 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:52.395 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:53.495 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:53.545 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x0f0c7d75] with a retry value of true
02:47:53.546 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:54.596 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Entry count for : http://172.19.0.4:5555 : 1
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.expiredChannels] - Adding Candidate expired Channel [id: 0xd8202c3c, L:/172.19.0.2:39982 - R:/172.19.0.4:5555] isIdleTimeoutExpired=true isRemotelyClosed=false isTtlExpired=false
02:47:55.695 DEBUG [DefaultChannelPool$IdleChannelDetector.closeChannels] - Closing Idle Channel [id: 0xd8202c3c, L:/172.19.0.2:39982 - R:/172.19.0.4:5555]
02:47:55.696 DEBUG [AsyncHttpClientHandler.channelInactive] - Channel Closed: [id: 0xd8202c3c, L:/172.19.0.2:39982 ! R:/172.19.0.4:5555] with attribute DISCARD
02:47:55.697 DEBUG [DefaultChannelPool$IdleChannelDetector.run] - Closed 1 connections out of 1 in 2 ms
02:47:56.617 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0xe139ff17] with a retry value of true
02:47:56.617 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*

02:47:59.689 DEBUG [NettyConnectListener.onFailure] - Trying to recover from failing to connect channel [id: 0x00538b6c] with a retry value of true
02:47:59.689 DEBUG [NettyRequestSender.retry] - Trying to recover request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /status HTTP/1.1
User-Agent: selenium/4.1.2 (java unix)
traceparent: 00-ab5c7e6813483d54f2f0707058b5e8d6-73917fbadc9e9561-01
host: 10.10.0.213:5555
accept: */*
```

### Operating System

ubuntu 20.04

### Docker Selenium version (tag)

4.1.2-20220131

**Comment by ibodog** [comment]
This could be related to #1497

**Comment by diemol** [comment]
> This could be related to #1497

Why do you think so?

**Comment by ibodog** [comment]
Web application scans often happen in the context of commercial security scanners.  This bug is about putting some incorrect info into a field being submitted which results in an almost immediate loss of function.  In this bug there is a specific instance to look at.  The other bug doesn't have the specifics. But you could imagine the scanner hitting the same endpoint with some security attack in the same field it would result in a similar result.

**Comment by diemol** [comment]
I was able to replicate this, thank you for the report. Working on a fix.
