### ISSUE TITLE
[🐛 Bug]: Remote WebDriver session creation times out when START_XVFB=false is set (selenium/standalone-chrome)

### ISSUE THREAD

**Issue by yugokato** [SeleniumHQ/docker-selenium#1500]
### What happened?

The issue is seen with `selenium/standalone-chrome` image version `4.1.1-20220121` or later. When a container starts with `START_XVFB=false` env var, a new session creation always times out. 
Note: It does not occur with `selenium/standalone-firefox` and `selenium/standalone-edge`

Steps to reproduce:
1. Start a container with `-e START_XVFB=false`
```
$ docker run -p 4444:4444 -e START_XVFB=false --shm-size="2g" selenium/standalone-chrome:4.1.1-20220121
```
2. Create a remove driver
```
>>> from selenium import webdriver
>>> from selenium.webdriver import ChromeOptions
>>> options= ChromeOptions()
>>> options.headless=True
>>> driver = webdriver.Remote(command_executor="http://127.0.0.1:4444", options=options)
```

After waiting for about 3 minutes, the following exception is raised.
`selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Error while creating session with the driver service. Stopping driver service: java.util.concurrent.TimeoutException`

### Command used to start Selenium Grid with Docker

```shell
docker run -p 4444:4444 -e START_XVFB=false --shm-size="2g" selenium/standalone-chrome:4.1.1-20220121
```

### Relevant log output

```shell
$ docker run  -p 4444:4444 -e START_XVFB=false --shm-size="2g" selenium/standalone-chrome:4.1.1-20220121
2022-02-02 20:30:38,289 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2022-02-02 20:30:38,291 INFO supervisord started with pid 8
2022-02-02 20:30:39,296 INFO spawned: 'xvfb' with pid 10
2022-02-02 20:30:39,299 INFO spawned: 'vnc' with pid 11
2022-02-02 20:30:39,301 INFO spawned: 'novnc' with pid 12
2022-02-02 20:30:39,303 INFO spawned: 'selenium-standalone' with pid 13
2022-02-02 20:30:39,304 INFO exited: xvfb (exit status 0; expected)
2022-02-02 20:30:39,306 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-02 20:30:39,306 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-02 20:30:39,306 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-02 20:30:39,306 INFO exited: vnc (exit status 0; expected)
2022-02-02 20:30:39,309 INFO exited: novnc (exit status 0; expected)
Setting up SE_NODE_GRID_URL...
Selenium Grid Standalone configuration: 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "97.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Standalone...
20:30:39.977 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
20:30:39.983 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
20:30:40.882 INFO [NodeOptions.getSessionFactories] - Detected 6 available processors
20:30:40.965 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "97.0","platformName": "Linux"} 1 times
20:30:40.989 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
20:30:41.023 INFO [LocalDistributor.add] - Added node 0289e6bd-b9c1-4035-ad45-9b47220b8d50 at http://172.17.0.2:4444. Health check every 120s
20:30:41.026 INFO [GridModel.setAvailability] - Switching node 0289e6bd-b9c1-4035-ad45-9b47220b8d50 (uri: http://172.17.0.2:4444) from DOWN to UP
20:30:41.255 INFO [Standalone.execute] - Started Selenium Standalone 4.1.1 (revision e8fcc2cecf): http://172.17.0.2:4444
20:31:10.352 INFO [LocalDistributor.newSession] - Session request received by the distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless], extensions: []}, pageLoadStrategy: normal}]
Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 44884
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1643833870.407][SEVERE]: bind() failed: Cannot assign requested address (99)


20:34:18.569 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
	at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
	at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
	at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:152)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:281)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:183)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:513)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:440)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:648)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:612)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
20:34:18.570 ERROR [OsProcess.destroy] - Unable to kill process Process[pid=71, exitValue=143]
20:34:18.577 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "59f59356df19dd696e9cfe07f94ac0ae","eventTime": 1643834050752004700,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:44884","exception.message": "Error while creating session with the driver service. Stopping driver service: java.util.concurrent.TimeoutException\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'e979068f2b73', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.47-linuxkit', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'e979068f2b73', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.47-linuxkit', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)\n\tat org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:83)\n\tat net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.Execution.executeSync(Execution.java:128)\n\tat net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)\n\tat net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)\n\tat org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:83)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)\n\tat org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:83)\n\tat net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)\n\tat net.jodah.failsafe.Execution.executeSync(Execution.java:128)\n\tat net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)\n\tat net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)\n\tat org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:83)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:110)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:131)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:513)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:440)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:648)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:612)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)\n\tat java.base\u002fjava.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)\n\t... 39 more\n","exception.type": "org.openqa.selenium.TimeoutException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"chrome\",\"goog:chromeOptions\": {\"extensions\": [  ],  \"args\": [    \"--headless\"    ]    },    \"pageLoadStrategy\": \"normal\"    }\n"}}

20:34:18.591 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "59f59356df19dd696e9cfe07f94ac0ae","eventTime": 1643834058796299300,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:4444","http.method": "POST","http.request_content_length": "322","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.1.0 (python mac)"}}
```

### Operating System

macOS

### Docker Selenium version (tag)

4.1.1-20220121 or later

**Comment by diemol** [comment]
I cannot reproduce, what else is needed to bump into this?

```
docker run -p 4444:4444 -e START_XVFB=false --shm-size="2g" selenium/standalone-chrome:4.1.2-20220131                                                                                                      125 ↵  12:20:18
Unable to find image 'selenium/standalone-chrome:4.1.2-20220131' locally
4.1.2-20220131: Pulling from selenium/standalone-chrome
ea362f368469: Pull complete
3be79de7f138: Pull complete
e3263d7617fd: Pull complete
27fbc127335c: Pull complete
263d11ddb148: Pull complete
258163ba8d4b: Pull complete
252eb16342f7: Pull complete
93db28d7468a: Pull complete
b43d6898a8f0: Pull complete
5f7e91acd3b4: Pull complete
c5f42fec9ab7: Pull complete
fcd179705d63: Pull complete
234b76578584: Pull complete
d8ad25432a2c: Pull complete
25e6936005bf: Pull complete
178e78eeb592: Pull complete
0ec8d305e3c5: Pull complete
807f151877d9: Pull complete
752093aba24b: Pull complete
869330117880: Pull complete
b8e9dc1df30b: Pull complete
fa311e5be39f: Pull complete
67518cfb2209: Pull complete
506d4605c2b2: Pull complete
2f5388cba7dc: Pull complete
68020352349a: Pull complete
5b5b70f0dc4c: Pull complete
78aff889bc82: Pull complete
4de306e22427: Pull complete
b3f18cbbc7bc: Pull complete
Digest: sha256:6a611690c0a48c02e96e8ae4ca70d4c2a59037fcab34591d946cadb0b6ad20f5
Status: Downloaded newer image for selenium/standalone-chrome:4.1.2-20220131
2022-02-04 11:22:32,216 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2022-02-04 11:22:32,219 INFO supervisord started with pid 9
2022-02-04 11:22:33,222 INFO spawned: 'xvfb' with pid 11
2022-02-04 11:22:33,226 INFO spawned: 'vnc' with pid 12
2022-02-04 11:22:33,230 INFO spawned: 'novnc' with pid 13
2022-02-04 11:22:33,233 INFO spawned: 'selenium-standalone' with pid 14
2022-02-04 11:22:33,235 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-04 11:22:33,236 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-04 11:22:33,237 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-04 11:22:33,237 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-02-04 11:22:33,238 INFO exited: xvfb (exit status 0; expected)
2022-02-04 11:22:33,239 INFO exited: vnc (exit status 0; expected)
2022-02-04 11:22:33,245 INFO exited: novnc (exit status 0; expected)
Setting up SE_NODE_GRID_URL...
Selenium Grid Standalone configuration:
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "97.0", "platformName": "Linux"}'
max-sessions = 1

Starting Selenium Grid Standalone...
11:22:33.900 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:22:33.907 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:22:34.651 INFO [NodeOptions.getSessionFactories] - Detected 5 available processors
11:22:34.704 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "97.0","platformName": "Linux"} 1 times
11:22:34.722 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
11:22:34.764 INFO [LocalDistributor.add] - Added node 4dc4122b-937c-4f34-9e1e-aa428b29b84c at http://172.17.0.2:4444. Health check every 120s
11:22:34.791 INFO [GridModel.setAvailability] - Switching node 4dc4122b-937c-4f34-9e1e-aa428b29b84c (uri: http://172.17.0.2:4444) from DOWN to UP
11:22:34.951 INFO [Standalone.execute] - Started Selenium Standalone 4.1.2 (revision 9a5a329c5a): http://172.17.0.2:4444
11:27:11.651 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless], extensions: []}}]
Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 51343
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started s[uccessfully.
1643974031.724][SEVERE]: bind() failed: Cannot assign requested address (99)
11:27:12.375 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
11:27:12.396 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 955bcf9de01ca986922396da17b31f4f, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.99, chrome: {chromedriverVersion: 97.0.4692.71 (adefa7837d02a..., userDataDir: /tmp/.com.google.Chrome.g84PJx}, goog:chromeOptions: {debuggerAddress: localhost:36353}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 97.0.4692.99, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
11:27:13.958 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: 955bcf9de01ca986922396da17b31f4f
```

This is the code I used https://github.com/diemol/selenium-issues/tree/master/docker-selenium/issue-1500

**Comment by yugokato** [comment]
Thanks for checking. I could reproduce this with your Java code too. But, after upgrading docker engine version of my laptop to the latest, I can no longer reproduce it. I'm not sure what it was, but I think we can close this ticket.
