### ISSUE TITLE
[🐛 Bug]: noVNC in Node does not react: Error proxying websocket command

### ISSUE THREAD

**Issue by Fatihh68** [SeleniumHQ/docker-selenium#1515]
### What happened?

I have full selenium grid on a kubernetes cluster, when i run testcases the noVNC window/password prompts only appears sometimes.
The hub crashes after that after some time and i get a unexpected token error as seen on the picture below. A refresh solves this. [Blacked out areas are just the selenium-hub.com url from an ingress]
<img width="692" alt="hub exception" src="https://user-images.githubusercontent.com/73878684/155560545-0f7549ab-41b1-4a44-bda2-3f4b43d2f5d3.png">
![novnc](https://user-images.githubusercontent.com/73878684/155549958-7885a9d9-86dc-4921-acf8-31593b272409.png)

### Command used to start Selenium Grid with Docker

```shell
# To execute this yml file use this command in your local kubernetes environment `kubectl apply -f k8s-deployment-full-grid.yaml`
#***************************************
#SELENIUM EVENT BUS
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-event-bus
  labels:
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-event-bus
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-event-bus-deployment
  labels:
    app: selenium-event-bus
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-event-bus
  template:
    metadata:
      labels:
        app: selenium-event-bus
        name: selenium-event-bus
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-event-bus
          image: selenium/event-bus:4.1.2
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 5557
              protocol: TCP
---
#***************************************
#SELENIUM SESSIONS MAP
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-sessions
  labels:
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-sessions
  ports:
    - name: port1
      protocol: TCP
      port: 5556
      targetPort: 5556

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-sessions-deployment
  labels:
    app: selenium-sessions
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-sessions
  template:
    metadata:
      labels:
        app: selenium-sessions
        name: selenium-sessions
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-sessions
          image: selenium/sessions:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 5556
              protocol: TCP
---
#***************************************
#SELENIUM SESSION QUEUE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-session-queue
  labels:
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-session-queue
  ports:
    - name: port1
      protocol: TCP
      port: 5559
      targetPort: 5559
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-session-queue-deployment
  labels:
    app: selenium-session-queue
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queue
  template:
    metadata:
      labels:
        app: selenium-session-queue
        name: selenium-session-queue
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-session-queue
          image: selenium/session-queue:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 5556
              protocol: TCP
---
#***************************************
#SELENIUM DISTRIBUTOR
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-distributor
  labels:
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-distributor
  ports:
    - name: port1
      protocol: TCP
      port: 5553
      targetPort: 5553

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-distributor-deployment
  labels:
    app: selenium-distributor
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-distributor
  template:
    metadata:
      labels:
        app: selenium-distributor
        name: selenium-distributor
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-distributor
          image: /selenium/distributor:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 5553
              protocol: TCP
---
#***************************************
#SELENIUM ROUTER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-router-deployment
  labels:
    app: selenium-router
    name: selenium-router
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-router
  template:
    metadata:
      labels:
        app: selenium-router
        name: selenium-router
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-router
          image: selenium/router:4.1.2
          env:
            - name: SE_DISTRIBUTOR_HOST
              value: "selenium-distributor"
            - name: SE_DISTRIBUTOR_PORT
              value: "5553"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          resources:
            limits:
              cpu: "4"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          ports:
            - containerPort: 4444
              protocol: TCP
---
#***************************************
#SELENIUM CHROME NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-chrome-node
          image: selenium/node-chrome:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
---
#***************************************
#SELENIUM EDGE NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-edge-node
  labels:
    name: selenium-edge-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-edge-node
  ports:
    - name: port1
      protocol: TCP
      port: 6901
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-edge-node-deployment
  labels:
    app: selenium-edge-node
    name: selenium-edge-node
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-edge-node
  template:
    metadata:
      labels:
        app: selenium-edge-node
        name: selenium-edge-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-edge-node
          image: selenium/node-edge:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_GRID_URL
              value: http://selenium-hub.ta.test.com:4444
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
---
#***************************************
#SELENIUM FIREFOX NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-ff-node
  labels:
    name: selenium-ff-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-ff-node
  ports:
    - name: port1
      protocol: TCP
      port: 6902
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-ff-node-deployment
  labels:
    app: selenium-ff-node
    name: selenium-ff-node
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-ff-node
  template:
    metadata:
      labels:
        app: selenium-ff-node
        name: selenium-ff-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-ff-node
          image: selenium/node-firefox:4.1.2
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
```

### Relevant log output

```shell
This is from Edge-Node:

Starting MSEdgeDriver 98.0.1108.56 (9a336a18eae89157b3c7ea0568a9cbced8ebc3f7) on port 48724
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
[1645707345.275][SEVERE]: bind() failed: Cannot assign requested address (99)
12:55:46.681 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:55:56.521 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://10.233.80.140:7900
12:56:10.278 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://10.233.80.140:7900
12:57:10.301 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://10.233.80.140:7900
12:58:56.589 WARN [NettyWebSocket.lambda$new$0] - Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
12:58:56.590 WARN [ProxyNodeWebsockets$ForwardingListener.onError] - Error proxying websocket command
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
12:58:56.599 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://10.233.80.140:7900
12:59:10.288 WARN [NettyWebSocket.lambda$new$0] - Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
12:59:10.289 WARN [ProxyNodeWebsockets$ForwardingListener.onError] - Error proxying websocket command
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:7900 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
12:59:10.300 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://10.233.80.140:7900

and this is from router deployment:

12:58:56.550 WARN [NettyWebSocket.lambda$new$0] - Request timeout to 10.233.80.140/10.233.80.140:5555 after 180000 ms
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:5555 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
12:58:56.552 WARN [ProxyWebsocketsIntoGrid$ForwardingListener.onError] - Error proxying websocket command
java.util.concurrent.TimeoutException: Request timeout to 10.233.80.140/10.233.80.140:5555 after 180000 ms
    at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
    at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
    at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

centOS

### Docker Selenium version (tag)

4.1.2

**Comment by diemol** [comment]
What is using this IP `10.233.80.140`? Is it the pod? Then maybe you need to expose that port (7900) as well.

**Comment by Fatihh68** [comment]
> 

Yes the ip is from the edge-node-pod. I added the port 7900+7901+6900+6901 also in the loadbalancer but it did not help. I want to note that the noVnc-passwort prompt in the hub appears like every 2nd testrun/testsession (no changes by adding the ports).

**Comment by Fatihh68** [comment]
The Grid is working in a isolated environment with no internet access. My guess would be that one of these Selenium-Grid deployments needs to load some kind of Library/image/url from the internet in order to work properly. Could that be the case ?

**Comment by diemol** [comment]
In theory, it does not need any external resources for that. Could you please try with the helm chart we provide now and see if something changes?

**Comment by diemol** [comment]
Closing as we did not get more information.
