### ISSUE TITLE
[🐛 Bug]: Selenium 4 hangs with parallel tests

### ISSUE THREAD

**Issue by cocorossello** [SeleniumHQ/docker-selenium#1525]
### What happened?

If I use some parallel tests with selenium 4 standalone image the execution. This did not happen in selenium 3.

I made a very simple reproducer in https://github.com/cocorossello/selenium4-slow-driver-creation/ (I reused the project name).

These are 2 very simple tests opening 30 chromes in parallel and opening a website 10 times. Selenium3 works fine but selenium4 never ends.

I can see some error logs in the docker container, but I think they are not relevant.I have also tried with 4.1.1, it didn't work.

In the selenium4 web interface I can see there is 1 session running (stucked) but when I click sessions it says "There are no running or queued sessions at the moment."

Please let me know if I can provide something else

### Command used to start Selenium Grid with Docker

```shell
See docker-compose.yml in the reproducer project
```

### Relevant log output

```shell
No relevant logs really, I can see these errors in the selenium4 container.

21:06:30.709 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:152)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:281)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:183)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:581)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:508)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:718)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:679)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.1.2-20220217

**Comment by diemol** [comment]
What do you mean by "not handle well parallel tests"? Could you give some more context? What hardware are you using for this scenario?

**Comment by cocorossello** [comment]
You can try the reproducer project, is not specially demanding, the selenium 3 can run in any decent hardware. My laptop is ryzen 5800HX but i'm sure it can run fine in most computers. 

The selenium 4 test never finishes, but I don't think it's because system load

**Comment by akaczinski** [comment]
Also seeing this in my tests.
Tests will freeze randomly on a step, node receives commands like normal if I use Postman to send in requests manually.

Not sure what to try here, have been pulling out my hair trying to figure this out.
Let me know if I can contribute at all.

**Comment by grossga** [comment]
I am also seeing this as well.  When running with only a docker browsers, it only affects Chrome docker containers.  When running against Firefox docker containers, my test suite runs to completion.  

Looking at my logs with FINE logging shows the Chrome containers look to finish everything with a `"eventName": "HTTP request execution complete"` DEBUG message and there isn't anything obvious in the logs that denote a problem.

As noted in the original description, when this occurs there isn't anything showing as running on the hub's `Sessions` tab.

I am also willing to provide any information needed to get this resolved.


One other thing to note, when I run my tests 5 wide everything works as expected.  When I bump the number of browser instances run in parallel to anything higher than 5 is when I run into this issue.

**Comment by michaelsatish** [comment]
I am too running into this issue. The tests run on an AWS ECS Task and use the Grid deployed in an AWS EKS Cluster.
 
If I run more than five tests in parallel, the tests never get to the completion state. I was trying to figure out the issue for the last couple of days and ran into this GitHub issue.

I can confirm the Selenium Grid 3 findings. After deploying Grid 3 to the same AWS EKS Cluster and pointing the tests to that Grid, I can run more than five tests in parallel, and each time the tests run to completion.

**Comment by cocorossello** [comment]
I can't see this issue with 4.1.4 anymore. 

Now we are hit by #1507 , I can't provide a reproducer, I will try to provide more information. I think this issue should be closed

**Comment by diemol** [comment]
Thanks for letting us know, I will look again into the other issue, which has been hard to track since there is no way to reproduce it.

**Comment by valsky4** [comment]
Any updates on this matter ?
