### ISSUE TITLE
[🐛 Bug]: Selenium Grid fails to connect

### ISSUE THREAD

**Issue by buggtb** [SeleniumHQ/docker-selenium#1528]
### What happened?

I wanted to try out the latest helm goodness, so I launched it using the defaults

(I also tried this with a LoadBalancer which is why the settings are set)

I then have a very simple bit of launch code:

```
String loc = (String) pluginConfig.getOrDefault("chrome.dns", "http://<hostname>:31439");
final ChromeOptions chromeOptions = new ChromeOptions();
driver = new RemoteWebDriver(new URL(loc), chromeOptions);
```

When the driver spins up it tries to connect, the Selenium Grid session starts, so its not a connectivity issue entirely, but then it fails to return from the spin up and dies.

Driver and Grid versions match, there's nothing obvious to me in the logs and as the sessions get started I'm unsure as to where to look next to debug, but as this helm stuff is new, if its not user error I figure the docs could probably do with a pointer to whatever the resolution is to this problem. The Firefox output is also the same, so i guess this is a grid config issue that I'm not understanding.

### Command used to start Selenium Grid with Docker

```shell
helm --kubeconfig /mnt/c/Users/barber/Downloads/kubeconfig-k8s-crawlcentral-main1.yaml upgrade selenium-grid docker-selenium/chart/selenium-grid/. --set hub.serviceType=NodePort --set chromeNode.service.type=ClusterIP --set firefoxNode.service.type=ClusterIP
```

### Relevant log output

```shell
=== Driver Logs ===
Mar 23, 2022 9:43:10 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
Mar 23, 2022 9:46:12 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #1. Retrying.
Mar 23, 2022 9:46:14 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #2. Retrying.
Mar 23, 2022 9:46:15 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #1. Retrying.
Mar 23, 2022 9:46:16 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #1. Retrying.
Mar 23, 2022 9:46:18 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #2. Retrying.
Mar 23, 2022 9:46:20 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #2. Retrying.
Mar 23, 2022 9:46:21 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #1. Retrying.
Mar 23, 2022 9:46:23 PM org.openqa.selenium.remote.http.RetryRequest lambda$static$5
INFO: Failure due to server error #2. Retrying.
Mar 23, 2022 9:46:23 PM uk.co.spicule.crawler.ChromeFetcher startDriver
INFO: Intercepted the following error when attempting to start the web driver
Mar 23, 2022 9:46:23 PM uk.co.spicule.crawler.ChromeFetcher startDriver
WARNING: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'spiculedata-sparklerredu-9l2jzqnzpo6', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.16.14-051614-generic', java.version: '11.0.13'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]
Capabilities {}
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'spiculedata-sparklerredu-9l2jzqnzpo6', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.16.14-051614-generic', java.version: '11.0.13'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]
Capabilities {}
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at uk.co.spicule.crawler.ChromeFetcher.startDriver(ChromeFetcher.java:206)
	at uk.co.spicule.crawler.ChromeFetcher.startDriver(ChromeFetcher.java:226)
	at uk.co.spicule.crawler.ChromeFetcher.fetch(ChromeFetcher.java:250)
	at uk.co.spicule.crawler.APICrawlFn.processElement(APICrawlFn.java:19)
	at uk.co.spicule.crawler.APICrawlFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228)
	at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187)
	at org.apache.beam.repackaged.direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:79)
	at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:244)
	at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:54)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:165)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.UncheckedIOException: java.io.IOException: Stream closed
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:80)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:80)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:80)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:80)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:110)
	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
	... 21 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:220)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:136)
	at io.netty.handler.stream.ChunkedStream.isEndOfInput(ChunkedStream.java:83)
	at io.netty.handler.stream.ChunkedStream.readChunk(ChunkedStream.java:106)
	at io.netty.handler.stream.ChunkedStream.readChunk(ChunkedStream.java:36)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:230)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:132)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at org.asynchttpclient.netty.request.body.NettyInputStreamBody.write(NettyInputStreamBody.java:77)
	at org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:433)
	at org.asynchttpclient.netty.channel.NettyConnectListener.writeRequest(NettyConnectListener.java:80)
	at org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:156)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onSuccess(NettyChannelConnector.java:92)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:26)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

Mar 23, 2022 9:46:23 PM uk.co.spicule.crawler.ChromeFetcher startDriver


=== Chrome Pod Logs ===

21:05:24.519 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://100.64.0.202:7900
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 37958
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
21:10:46.009 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 44580
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
21:27:11.881 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
21:27:17.549 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://100.64.0.202:7900
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 41407
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
21:37:35.598 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 48817
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
21:42:46.508 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C

=== Hub Pod Logs ===

21:37:34.110 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]
21:37:35.677 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: f649f5185b5413358e086f31c7300d9a, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.74, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.dpxBzl}, goog:chromeOptions: {debuggerAddress: localhost:42429}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://100.64.0.202:4444/sess..., se:cdpVersion: 99.0.4844.74, se:vnc: ws://100.64.0.202:4444/sess..., se:vncEnabled: true, se:vncLocalAddress: ws://100.64.0.202:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
21:42:44.819 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: f649f5185b5413358e086f31c7300d9a
21:42:44.828 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]
21:42:46.525 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 8724400f06b16b92db282e6defe0238e, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.74, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.anULJo}, goog:chromeOptions: {debuggerAddress: localhost:37297}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://100.64.0.202:4444/sess..., se:cdpVersion: 99.0.4844.74, se:vnc: ws://100.64.0.202:4444/sess..., se:vncEnabled: true, se:vncLocalAddress: ws://100.64.0.202:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

### Operating System

Docker

### Docker Selenium version (tag)

4.1.2

**Comment by buggtb** [comment]
I assume from a service perspective, as the sessions do get created, the client talks to the remote websdriver via the router url and nothing else needs publicly exposing?

Guess it might be related to https://github.com/SeleniumHQ/selenium/issues/9528 but I'm not sure, cause I'm not trying to do anything other than just create a driver object. Tried updating the chrome pod to use 3GB of RAM, same error.

When the sessions that don't work start, I can VNC into the node and see the browser up and running.

**Comment by buggtb** [comment]
Guess it might be related to https://github.com/SeleniumHQ/selenium/issues/9528 but I'm not sure, cause I'm not trying to do anything other than just create a driver object. Tried updating the chrome pod to use 3GB of RAM, same error.

**Comment by buggtb** [comment]
Okay, figured it out.

There was a 

```
java.util.concurrent.ExecutionException: java.lang.ClassNotFoundException: io.netty.handler.codec.compression.Brotli
```

Which was occurring before the stream closed issue, this never appeared in my log output then it would retry and then fail and print the stream closed error, but the real error was the missing class.

```
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-remote-driver</artifactId>
      <version>4.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-chrome-driver</artifactId>
      <version>4.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-firefox-driver</artifactId>
      <version>4.1.2</version>
    </dependency>
```
I had those in my pom.xml but none brought in the class it seems so I added:

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
      <version>4.1.69.Final</version>
    </dependency>
```
