### ISSUE TITLE
[🐛 Bug]: cannot run most simple example from official Selenium website using sendKeys method

### ISSUE THREAD

**Issue by olifur** [SeleniumHQ/docker-selenium#1532]
### What happened?

when running the most simple example from the official Selenium Node code example from [https://www.selenium.dev/selenium/docs/api/javascript/](here) I get the following error.
```
FAIL __tests__/wikipedia.spec.ts (5.891 s)
telegram-bot-tests_1    |   Selenium wiki page
telegram-bot-tests_1    |     ✕ it performs a validation of title of the google homepage (1709 ms)
telegram-bot-tests_1    | 
telegram-bot-tests_1    |   ● Selenium wiki page › it performs a validation of title of the google homepage
telegram-bot-tests_1    | 
telegram-bot-tests_1    |     ElementNotInteractableError: Element <input class="gLFyf gsfi" name="q" type="text"> is not reachable by keyboard
telegram-bot-tests_1    | 
telegram-bot-tests_1    |       at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
telegram-bot-tests_1    |       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:548:13)
telegram-bot-tests_1    |       at Executor.execute (node_modules/selenium-webdriver/lib/http.js:474:28)
telegram-bot-tests_1    |       at Object.execute (node_modules/selenium-webdriver/lib/webdriver.js:735:17)
```

### Command used to start Selenium Grid with Docker

```shell

// docker-compose

selenium-firefox:
    image: selenium/standalone-firefox:4.1.3-20220327
    shm_size: '2gb'
    restart: ""
    ports:
      - "4444:4444"
    networks:
     - nginx-proxy


//   node.js code
// __tests__/wikipedia.spec.ts

import { afterAll, beforeAll, describe, expect, test } from "@jest/globals";
import {Builder, By, Key, until} from 'selenium-webdriver'; 

let driver = null;
beforeAll(async () => {
  driver = await new Builder().forBrowser('firefox')
    .usingServer('http://selenium-firefox:4444/wd/hub')
    .build();

});

afterAll(async () => {
  await driver.quit();
});

describe("Selenium wiki page", () => {

  test('it performs a validation of title of the google homepage', async () => {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);

    driver.getTitle().then(function (title) {
      expect(title).toBe('Google')
    });
  })
});
```

### Relevant log output

```shell
elenium-firefox_1      | 18:00:25.579 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "3bf9886d032f6d94b0b790bcc7b36b74","eventTime": 1648576825578836249,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium-firefox:4444","http.method": "POST","http.request_content_length": "75","http.scheme": "HTTP","http.status_code": 400,"http.target": "\u002fsession\u002fca5f6ca3-ce34-442d-8564-938c431b3957\u002felement\u002f88f0302c-84fa-4e37-b279-42e72ec9d34f\u002fvalue","http.user_agent": "selenium\u002f4.1.1 (js linux)"}}
selenium-firefox_1      | 
selenium-firefox_1      | 1648576825603 Marionette      INFO    Stopped listening on port 40531
selenium-firefox_1      | 
selenium-firefox_1      | ###!!! [Parent][PImageBridgeParent] Error: RunMessage(msgname=PImageBridge::Msg_WillClose) Channel closing: too late to send/recv, messages will be lost
selenium-firefox_1      | 
selenium-firefox_1      | 18:00:26.151 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: ca5f6ca3-ce34-442d-8564-938c431b3957
telegram-bot-tests_1    | FAIL __tests__/wikipedia.spec.ts (5.891 s)
telegram-bot-tests_1    |   Selenium wiki page
telegram-bot-tests_1    |     ✕ it performs a validation of title of the google homepage (1709 ms)
telegram-bot-tests_1    | 
telegram-bot-tests_1    |   ● Selenium wiki page › it performs a validation of title of the google homepage
telegram-bot-tests_1    | 
telegram-bot-tests_1    |     ElementNotInteractableError: Element <input class="gLFyf gsfi" name="q" type="text"> is not reachable by keyboard
telegram-bot-tests_1    | 
telegram-bot-tests_1    |       at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
telegram-bot-tests_1    |       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:548:13)
telegram-bot-tests_1    |       at Executor.execute (node_modules/selenium-webdriver/lib/http.js:474:28)
telegram-bot-tests_1    |       at Object.execute (node_modules/selenium-webdriver/lib/webdriver.js:735:17)
telegram-bot-tests_1    | 
telegram-bot-tests_1    | Test Suites: 1 failed, 1 total
telegram-bot-tests_1    | Tests:       1 failed, 1 total
telegram-bot-tests_1    | Snapshots:   0 total
telegram-bot-tests_1    | Time:        5.908 s
telegram-bot-tests_1    | Ran all test suites.
telegram-bot-tests_1    |
```

### Operating System

Fedora 33

### Docker Selenium version (tag)

4.1.3-20220327

**Comment by diemol** [comment]
Please run the example we have at our main docs site https://www.selenium.dev/documentation/

The one you are using comes from the JavaScript docs, which is out of date because we are having some issues there (being tracked in another GitHub issue).
