### ISSUE TITLE
[🐛 Bug]: WDIO Test fails in gitlab CI/CD with the new release as session could not get started for the tests

### ISSUE THREAD

**Issue by AndunRanmal** [SeleniumHQ/docker-selenium#1560]
### What happened?

Following error received when trying to create a session with selenium standalone server firefox

``` 2022-04-28T03:33:06.775Z WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
[0-0] Build info: version: '4.1.4', revision: '535d840ee2'
[0-0] System info: host: 'd1fe4018505a', ip: '0.0.0.0', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-0] Driver info: driver.version: unknown

### Command used to start Selenium Grid with Docker

```shell
`wdio run wdio.conf.js --hostname=selenium__standalone-firefox`
```

### Relevant log output

```shell
2022-04-28T03:33:07.853Z INFO webdriver: [POST] http://selenium__standalone-firefox:4444/wd/hub/session
[0-3] 2022-04-28T03:33:07.853Z INFO webdriver: DATA {
[0-3]   capabilities: {
[0-3]     alwaysMatch: { browserName: 'firefox', 'moz:firefoxOptions': [Object] },
[0-3]     firstMatch: [ {} ]
[0-3]   },
[0-3]   desiredCapabilities: { browserName: 'firefox', 'moz:firefoxOptions': { args: [Array] } }
[0-3] }
[0-1] 2022-04-28T03:33:07.955Z DEBUG webdriver: request failed due to response error: session not created
[0-1] 2022-04-28T03:33:07.955Z INFO webdriver: Retrying 2/3
[0-1] 2022-04-28T03:33:07.956Z INFO webdriver: [POST] http://selenium__standalone-firefox:4444/wd/hub/session
[0-1] 2022-04-28T03:33:07.956Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: { browserName: 'firefox', 'moz:firefoxOptions': [Object] },
[0-1]     firstMatch: [ {} ]
[0-1]   },
[0-1]   desiredCapabilities: { browserName: 'firefox', 'moz:firefoxOptions': { args: [Array] } }
[0-1] }
[0-1] 2022-04-28T03:33:07.955Z WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
[0-1] Build info: version: '4.1.4', revision: '535d840ee2'
[0-1] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-1] Driver info: driver.version: unknown
[0-1] Build info: version: '4.1.4', revision: '535d840ee2'
[0-1] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-1] Driver info: driver.version: unknown
[0-3] 2022-04-28T03:33:08.038Z DEBUG webdriver: request failed due to response error: session not created
[0-3] 2022-04-28T03:33:08.038Z ERROR webdriver: Request failed with status 500 due to session not created: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
[0-3] Build info: version: '4.1.4', revision: '535d840ee2'
[0-3] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-3] Driver info: driver.version: unknown
[0-3] Build info: version: '4.1.4', revision: '535d840ee2'
[0-3] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-3] Driver info: driver.version: unknown
[0-3] 2022-04-28T03:33:08.038Z ERROR webdriver: [
[0-3]   {
[0-3]     fileName: 'DriverServiceSessionFactory.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'apply',
[0-3]     className: 'org.openqa.selenium.grid.node.config.DriverServiceSessionFactory',
[0-3]     lineNumber: 194,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'DriverServiceSessionFactory.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'apply',
[0-3]     className: 'org.openqa.selenium.grid.node.config.DriverServiceSessionFactory',
[0-3]     lineNumber: 67,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'SessionSlot.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'apply',
[0-3]     className: 'org.openqa.selenium.grid.node.local.SessionSlot',
[0-3]     lineNumber: 145,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'LocalNode.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'newSession',
[0-3]     className: 'org.openqa.selenium.grid.node.local.LocalNode',
[0-3]     lineNumber: 349,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'LocalDistributor.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'startSession',
[0-3]     className: 'org.openqa.selenium.grid.distributor.local.LocalDistributor',
[0-3]     lineNumber: 609,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'LocalDistributor.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'newSession',
[0-3]     className: 'org.openqa.selenium.grid.distributor.local.LocalDistributor',
[0-3]     lineNumber: 535,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'LocalDistributor.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'handleNewSessionRequest',
[0-3]     className: 'org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable',
[0-3]     lineNumber: 746,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'LocalDistributor.java',
[0-3]     moduleVersion: null,
[0-3]     moduleName: null,
[0-3]     nativeMethod: false,
[0-3]     methodName: 'lambda$run$1',
[0-3]     className: 'org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable',
[0-3]     lineNumber: 707,
[0-3]     classLoaderName: 'app'
[0-3]   },
[0-3]   {
[0-3]     fileName: 'ThreadPoolExecutor.java',
[0-3]     moduleVersion: '11.0.15',
[0-3]     moduleName: 'java.base',
[0-3]     nativeMethod: false,
[0-3]     methodName: 'runWorker',
[0-3]     className: 'java.util.concurrent.ThreadPoolExecutor',
[0-3]     lineNumber: 1128,
[0-3]     classLoaderName: null
[0-3]   },
[0-3]   {
[0-3]     fileName: 'ThreadPoolExecutor.java',
[0-3]     moduleVersion: '11.0.15',
[0-3]     moduleName: 'java.base',
[0-3]     nativeMethod: false,
[0-3]     methodName: 'run',
[0-3]     className: 'java.util.concurrent.ThreadPoolExecutor$Worker',
[0-3]     lineNumber: 628,
[0-3]     classLoaderName: null
[0-3]   },
[0-3]   {
[0-3]     fileName: 'Thread.java',
[0-3]     moduleVersion: '11.0.15',
[0-3]     moduleName: 'java.base',
[0-3]     nativeMethod: false,
[0-3]     methodName: 'run',
[0-3]     className: 'java.lang.Thread',
[0-3]     lineNumber: 829,
[0-3]     classLoaderName: null
[0-3]   }
[0-3] ]
[0-3] 2022-04-28T03:33:08.042Z ERROR @wdio/runner: Error: Failed to create session.
[0-3] Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
[0-3] Build info: version: '4.1.4', revision: '535d840ee2'
[0-3] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-3] Driver info: driver.version: unknown
[0-3] Build info: version: '4.1.4', revision: '535d840ee2'
[0-3] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-3] Driver info: driver.version: unknown
[0-3]     at startWebDriverSession (/builds/qa/chope-wdio-auto-tests/node_modules/webdriver/build/utils.js:72:15)
[0-3]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-3]     at Function.newSession (/builds/qa/chope-wdio-auto-tests/node_modules/webdriver/build/index.js:42:45)
[0-3]     at remote (/builds/qa/chope-wdio-auto-tests/node_modules/webdriverio/build/index.js:73:22)
[0-3]     at Runner._startSession (/builds/qa/chope-wdio-auto-tests/node_modules/@wdio/runner/build/index.js:223:56)
[0-3]     at Runner._initSession (/builds/qa/chope-wdio-auto-tests/node_modules/@wdio/runner/build/index.js:176:25)
[0-3]     at Runner.run (/builds/qa/chope-wdio-auto-tests/node_modules/@wdio/runner/build/index.js:88:19)
[0-2] 2022-04-28T03:33:08.142Z DEBUG webdriver: request failed due to response error: session not created
[0-2] 2022-04-28T03:33:08.143Z WARN webdriver: Request failed with status 500 due to Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: Argument --remote-debugging-port can't be set via capabilities
[0-2] Build info: version: '4.1.4', revision: '535d840ee2'
[0-2] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-2] Driver info: driver.version: unknown
[0-2] Build info: version: '4.1.4', revision: '535d840ee2'
[0-2] System info: host: 'd1fe4018505a', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.193-149.317.amzn2.x86_64', java.version: '11.0.15'
[0-2] Driver info: driver.version: unknown
```

### Operating System

Linux

### Docker Selenium version (tag)

latest

**Comment by diemol** [comment]
Can you share a test or a GitHub repository with instructions showing how I can reproduce the issue?

**Comment by ancajuravle** [comment]
I've run into the exact issue since the "latest" image (4.1.4-20220427), my tests won't run anymore in Firefox.

**Comment by diemol** [comment]
> I've run into the exact issue since the "latest" image (4.1.4-20220427), my tests won't run anymore in Firefox.

@ancajuravle 
>Can you share a test or a GitHub repository with instructions showing how I can reproduce the issue?

**Comment by ancajuravle** [comment]
@diemol I am afraid I don't have a public repository, but I would say my setup is very similar with the tag "latest" to [docker-compose-v2.yml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v2.yml) with Jenkins, and just spinning up my WebDriver tests. That all went fine with 4.1.3-20220405 (Firefox: 99.0 GeckoDriver: 0.30.0) and also with 4.1.3-20220427. But not anymore with 4.1.4-20220427. So I am suspecting the bump of the GeckoDriver or the Grid (or maybe the combination) gives some incompatibility?

**Comment by diemol** [comment]
We have passing tests on both this and the main Selenium repo, which is why I would need any test that can be used to reproduce the issue. We might be overseeing something. Thank you!

**Comment by ancajuravle** [comment]
I see, I might have found the culprit on my side. I have updated my wdio/webdriverio dependencies from 7.16 to 7.19 and the tests pass again. Thanks, that helped!

**Comment by diemol** [comment]
Great news! Thank you for letting us know.

**Comment by jkostrhun** [comment]
I had same issue and I can confirm that updating WDIO dependencies to 7.19 solve this issue.

**Comment by andreeapan** [comment]
Same here! Thanks so much. Was looking for the solution for hours!
