### ISSUE TITLE
Unable to capture Chrome DevTools logging[🐛 Bug]: 

### ISSUE THREAD

**Issue by msscribner** [SeleniumHQ/docker-selenium#1572]
### What happened?

Upgraded 
from: 
selenium/hub:4.1.1-20220121, selenium/node-chrome:4.1.1-20220121  
to:
selenium/hub:4.1.4-20220427, to selenium/node-chrome:4.1.4-20220427

Now when I attempt to derive the Remote WebDriver's Session, I'm getting a [System.NullReferenceException: Object reference not set to an instance of an object.] exception:

                // Cast the RemoteWebDriver to a IDevTools
                IDevTools iDevTools = remoteWebDriver as IDevTools;

                // Derive the Session, SessionId and Domain
                DevToolsSession devToolSession = iDevTools.GetDevToolsSession();   ==> exception occurs on this line.

### Command used to start Selenium Grid with Docker

```shell
version: '3'

services:
  chrome:
#   image: selenium/node-chrome:4.1.1-20220121
    image: selenium/node-chrome:4.1.4-20220427
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=500
      - SE_NODE_GRID_URL=http://172.16.50.67:4444
      - TZ=America/New_York      
    deploy:
      replicas: 0
      placement:
       constraints: 
        - node.role == worker
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
#   image: selenium/hub:4.1.1-20220121
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 2gb
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    deploy:
      replicas: 1
      placement:
       constraints: 
        - node.role == manager
```

### Relevant log output

```shell
The stack trace error looks like this:

2022-05-13 11:30:06,565 ERROR DevTools -  Message=[Unexpected error creating WebSocket DevTools session.]
2022-05-13 11:30:06,597 ERROR DevTools -  InnerException=[System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session, Int32 versionRange)
   at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session)
   at OpenQA.Selenium.DevTools.DevToolsSession.<StartSession>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)]
2022-05-13 11:30:06,599 ERROR DevTools -  StackTrace=[   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession()
   at Automation.Common.DevTools.StartDevToolsConsoleLogging(RemoteWebDriver remoteWebDriver) in C:\CTS\Azure\ProjectOverwatch-Enterprise\Automation.Common\DevTools.cs:line 53]
```

### Operating System

Ubuntu - Ubuntu 20.04.3

### Docker Selenium version (tag)

4.1.4-20220427

**Comment by diemol** [comment]
I'm not able to reproduce it, can you share a GitHub repo with the complete setup and also using the latest version of the C# bindings?

**Comment by msscribner** [comment]
I've created a GitHub repo with an example solution.   https://github.com/msscribner/DevToolsTest

An exception is encountered on line 84 of Driver::StartDevToolsConsoleLogging()

**Comment by msscribner** [comment]
I've been able to resolve the issue...and it's is a coding issue.

**Comment by msscribner** [comment]
Instead of using:
using DevToolsSessionDomains = OpenQA.Selenium.DevTools.V96.DevToolsSessionDomains;
var domains = devToolSession.GetVersionSpecificDomains<DevToolsSessionDomains>();       //THIS LINE THROWS EXCEPTION


Should use:
using DevToolsVersion = OpenQA.Selenium.DevTools.**V101**;
var domains = devToolSession.GetVersionSpecificDomains<DevToolsVersion.DevToolsSessionDomains>();


Complete solution:

using DevToolsVersion = OpenQA.Selenium.DevTools.V101;
. . . 

// Cast the RemoteWebDriver to a IDevTools
IDevTools iDevTools = remoteWebDriver as IDevTools;

// Derive the Session, SessionId and Domain
DevToolsSession devToolSession = iDevTools.GetDevToolsSession();
var sessionId = devToolSession.EndpointAddress.Split('/')[4];
var domains = devToolSession.GetVersionSpecificDomains<DevToolsVersion.DevToolsSessionDomains>();

// Associate the Console with the Event Handler
domains.Console.Enable();
domains.Console.ClearMessages();
domains.Console.MessageAdded += DevToolsConsoleMessageAdded;


. . . 

private static readonly EventHandler<DevToolsVersion.Console.MessageAddedEventArgs> DevToolsConsoleMessageAdded = (sender, e) =>
{
	// Filter the console message based upon the DevToolsConsoleMessageLevel;
	var messageLevel = e.Message.Level.ToString();

       . . . 

};/*DevToolsConsoleMessageAdded*/
