### ISSUE TITLE
[🐛 Bug]: Random "connection refused errors" using selenium/standalone-chrome:4.1.0

### ISSUE THREAD

**Issue by lvonk** [SeleniumHQ/docker-selenium#1581]
### What happened?

We have upgraded to `selenium/standalone-chrome:4.1.0` recently and are experiencing the following failures while running our specs (I pasted the entire stacktrace to relevant log output):

```
     1.1) Failure/Error: find_field(locator).send_keys [:command, 'a'], :backspace
          
          Selenium::WebDriver::Error::ScriptTimeoutError:
            Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost/127.0.0.1:59957
          # java.lang.RuntimeException: Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost/127.0.0.1:59957
          # 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)
```

These errors are rather random because they don't occur for the same specs and only every now and then, today for instance during 2 builds.

We run on circleci using ruby-3.1 and use Capybara with the `selenium-webdriver` gem version `4.1.0`.

One of the questions I have is what is the port `59957`? Since this is not the port our application under test is running at during this test.

Any help or pointers where to look is appreciated.

### Command used to start Selenium Grid with Docker

```shell
circleci/config.yml


- image: selenium/standalone-chrome:4.1.0-20211209
  environment:
    SE_NODE_MAX_SESSIONS: 8
    SE_NODE_OVERRIDE_MAX_SESSIONS: true
```

### Relevant log output

```shell
Log output from our tests:

     1.1) Failure/Error: find_field(locator).send_keys [:command, 'a'], :backspace
          
          Selenium::WebDriver::Error::ScriptTimeoutError:
            Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost/127.0.0.1:59957
          # java.lang.RuntimeException: Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost/127.0.0.1:59957
          # 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)
          # 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
          # 	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
          # 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
          # 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
          # 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
          # 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
          # 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
          # 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
          # 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
          # 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
          # 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
          # 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
          # 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
          # 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
          # 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
          # 	at java.base/java.lang.Thread.run(Thread.java:829)
          # Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:59957
          # 	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
          # 	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
          # 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
          # 	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
          # 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
          # 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
          # 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
          # 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
          # 	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
          # 	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
          # 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
          # 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
          # 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
          # 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
          # 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
          # 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
          # 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
          # 	... 1 more
          # Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:59957
          # Caused by: java.net.ConnectException: Connection refused
          # 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
          # 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
          # 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
          # 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
          # 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
          # 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
          # 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
          # 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
          # 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
          # 	at java.base/java.lang.Thread.run(Thread.java:829)
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:35:in `initialize'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:109:in `request'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:416:in `send_keys_to_element'
          # ./vendor/bundle/ruby/3.1.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/element.rb:208:in `send_keys'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/node.rb:157:in `send_keys'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/nodes/chrome_node.rb:89:in `block in send_keys'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/nodes/chrome_node.rb:78:in `<<'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/nodes/chrome_node.rb:78:in `each'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/nodes/chrome_node.rb:78:in `each'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/selenium/nodes/chrome_node.rb:78:in `send_keys'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/node/element.rb:275:in `block in send_keys'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/node/base.rb:83:in `synchronize'
          # ./vendor/bundle/ruby/3.1.0/gems/capybara-3.36.0/lib/capybara/node/element.rb:275:in `send_keys'

Log output from selenium webdriver:

2022-05-24 15:43:28 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"5067"}
2022-05-24 15:43:28 INFO Selenium <- {"value":true}
2022-05-24 15:43:28 INFO Selenium -> POST session/cc7d0ad67e26214ea69f99f4badb8d4b/execute/sync
2022-05-24 15:43:28 INFO Selenium    >>> http://localhost:4444/wd/hub/session/cc7d0ad67e26214ea69f99f4badb8d4b/execute/sync | {"script":"return arguments[0].matches(':disabled, select:disabled *')","args":[{"element-6066-11e4-a52e-4f735466cecf":"bc9b2e77-f8bc-46d6-8f05-0b747b449038"}]}
2022-05-24 15:43:28 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"160"}
2022-05-24 15:43:28 INFO Selenium <- {"value":false}
2022-05-24 15:43:28 INFO Selenium -> POST session/cc7d0ad67e26214ea69f99f4badb8d4b/element/bc9b2e77-f8bc-46d6-8f05-0b747b449038/value
2022-05-24 15:43:28 INFO Selenium    >>> http://localhost:4444/wd/hub/session/cc7d0ad67e26214ea69f99f4badb8d4b/element/bc9b2e77-f8bc-46d6-8f05-0b747b449038/value | {"value":["","a","",""],"text":"a"}
2022-05-24 15:43:28 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby linux)", "Content-Length"=>"53"}
2022-05-24 15:43:38 INFO Selenium <- {
  "value": {
    "error": "script timeout",
    "message": "Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost\u002f127.0.0.1:59957",
    "stacktrace": "java.lang.RuntimeException: Unable to execute request for an existing session: java.net.ConnectException: Connection refused: localhost\u002f127.0.0.1:59957\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.net.ConnectException: Connection refused: localhost\u002f127.0.0.1:59957\n\tat org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)\n\tat org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)\n\tat org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)\n\tat org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)\n\tat io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)\n\tat io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)\n\tat io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost\u002f127.0.0.1:59957\nCaused by: java.net.ConnectException: Connection refused\n\tat java.base\u002fsun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat java.base\u002fsun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n"
  }
}
```

### Operating System

Linux

### Docker Selenium version (tag)

4.1.0-20211209

**Comment by diemol** [comment]
How can I reproduce the issue?

**Comment by lvonk** [comment]
Hi @diemol ,

Sorry for my late reply but was enjoying a long weekend :-). It turned out that the culprit was that we executed this command  from Capybara to ensure an input field was cleared before filling some value:

```ruby
find_field(locator).send_keys [:command, 'a'], :backspace
```

This, seen from the logs, was translated into the following selenium command:

```
2022-05-24 15:43:28 INFO Selenium -> POST session/cc7d0ad67e26214ea69f99f4badb8d4b/element/bc9b2e77-f8bc-46d6-8f05-0b747b449038/value
2022-05-24 15:43:28 INFO Selenium    >>> http://localhost:4444/wd/hub/session/cc7d0ad67e26214ea69f99f4badb8d4b/element/bc9b2e77-f8bc-46d6-8f05-0b747b449038/value | {"value":["","a","",""],"text":"a"}
```

When I changed the code on how to clear an input field in Capybara to their "new way" the timeout error went away and the test are no longer flaky. Their "new way" of clearing translated to the following selenium command:

```
2022-05-30 11:25:45 INFO Selenium -> POST session/57261cfa6b810d892667881871b1e3ed/execute/sync
2022-05-30 11:25:45 INFO Selenium    >>> http://localhost:4444/wd/hub/session/57261cfa6b810d892667881871b1e3ed/execute/sync | {"script":"arguments[0].select()","args":[{"element-6066-11e4-a52e-4f735466cecf":"f3495d6f-86d0-45ab-b4d3-6d87b2d87c94"}]}
2022-05-30 11:25:45 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.1.0 (ruby macosx)", "Content-Length"=>"122"}
2022-05-30 11:25:45 INFO Selenium <- {"value":null}
```

Still wonder why this resulted in a timeout though and what the port referred to that I mentioned...
