### ISSUE TITLE
[🐛 Bug]:  CHROME Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500

### ISSUE THREAD

**Issue by bhashagemini** [SeleniumHQ/docker-selenium#1628]
### What happened?

1. Apply k8s deployment file to create kubecluster - I'm using kind locally
2. Connect to grid after it is available, i.e. via `self.driver = webdriver.Remote(command_executor="http://localhost:4444", options=options)`
3. Errors received. [1] is from running locally.  [2] is from selenium-chrome-node server

### Command used to start Selenium Grid with Docker

```shell
kubectl apply -f k8s-deployment-full-grid.yaml

# To execute this yml file use this command in your local kubernetes environment `kubectl apply -f k8s-deployment-full-grid.yaml`
#***************************************
#SELENIUM EVENT BUS
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-event-bus
  labels:
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-event-bus
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-event-bus-deployment
  labels:
    app: selenium-event-bus
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-event-bus
  template:
    metadata:
      labels:
        app: selenium-event-bus
        name: selenium-event-bus
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-event-bus
          image: selenium/event-bus:4.1.1-20211217
          ports:
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 5557
              protocol: TCP
---
#***************************************
#SELENIUM SESSIONS MAP
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-sessions
  labels:
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-sessions
  ports:
    - name: port1
      protocol: TCP
      port: 5556
      targetPort: 5556

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-sessions-deployment
  labels:
    app: selenium-sessions
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-sessions
  template:
    metadata:
      labels:
        app: selenium-sessions
        name: selenium-sessions
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-sessions
          image: selenium/sessions:4.1.1-20211217
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5556
              protocol: TCP
---
#***************************************
#SELENIUM SESSION QUEUE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-session-queue
  labels:
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-session-queue
  ports:
    - name: port1
      protocol: TCP
      port: 5559
      targetPort: 5559
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-session-queue-deployment
  labels:
    app: selenium-session-queue
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queue
  template:
    metadata:
      labels:
        app: selenium-session-queue
        name: selenium-session-queue
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-session-queue
          image: selenium/session-queue:4.1.1-20211217
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5556
              protocol: TCP
---
#***************************************
#SELENIUM DISTRIBUTOR
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-distributor
  labels:
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-distributor
  ports:
    - name: port1
      protocol: TCP
      port: 5553
      targetPort: 5553

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-distributor-deployment
  labels:
    app: selenium-distributor
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-distributor
  template:
    metadata:
      labels:
        app: selenium-distributor
        name: selenium-distributor
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-distributor
          image: selenium/distributor:4.1.1-20211217
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          ports:
            - containerPort: 5553
              protocol: TCP
---
#***************************************
#SELENIUM ROUTER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-router-deployment
  labels:
    app: selenium-router
    name: selenium-router
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-router
  template:
    metadata:
      labels:
        app: selenium-router
        name: selenium-router
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-router
          image: selenium/router:4.1.1-20211217
          env:
            - name: SE_DISTRIBUTOR_HOST
              value: "selenium-distributor"
            - name: SE_DISTRIBUTOR_PORT
              value: "5553"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
          ports:
            - containerPort: 4444
              protocol: TCP
---
#***************************************
#SELENIUM CHROME NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-chrome-node
          image: selenium/node-chrome:4.1.1-20211217
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: START_XVFB
              value: "true"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
```

### Relevant log output

```shell
Error[1]

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x122877280>
response = {'status': 500, 'value': '{\n  "value": {\n    "error": "session not created",\n    "message": "Could not start a new ..."className": "java.lang.Thread",\n        "lineNumber": 829,\n        "classLoaderName": null\n      }\n    ]\n  }\n}'}

    def check_response(self, response: Dict[str, Any]) -> None:
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if not status or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen: str = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, str):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if not status:
                        status = value.get("status", ErrorCode.UNKNOWN_ERROR)
                        message = value.get("value") or value.get("message")
                        if not isinstance(message, str):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class: Type[WebDriverException]
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:
            exception_class = NoSuchShadowRootException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if not value:
            value = response['value']
        if isinstance(value, str):
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None  # type: ignore[assignment]
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        st_value = value.get('stackTrace') or value.get('stacktrace')
        if st_value:
            if isinstance(st_value, str):
                stacktrace = st_value.split('\n')
            else:
                stacktrace = []
                try:
                    for frame in st_value:
                        line = self._value_or_default(frame, 'lineNumber', '')
                        file = self._value_or_default(frame, 'fileName', '<anonymous>')
                        if line:
                            file = "%s:%s" % (file, line)
                        meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                        if 'className' in frame:
                            meth = "%s.%s" % (frame['className'], meth)
                        msg = "    at %s (%s)"
                        msg = msg % (meth, file)
                        stacktrace.append(msg)
                except TypeError:
                    pass
        if exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
E         (chrome not reachable)
E         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
E       Build info: version: '4.1.1', revision: 'e8fcc2cecf'
E       System info: host: 'selenium-chrome-node-deployment-5c97fbc757-fc2cr', ip: '10.244.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.13'
E       Driver info: driver.version: unknown
E       Build info: version: '4.1.1', revision: 'e8fcc2cecf'
E       System info: host: 'selenium-chrome-node-deployment-5c97fbc757-fc2cr', ip: '10.244.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.13'
E       Driver info: driver.version: unknown
E       Build info: version: '4.1.1', revision: 'e8fcc2cecf'
E       System info: host: 'selenium-session-queue-deployment-8548f45966-tpwfz', ip: '10.244.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.13'
E       Driver info: driver.version: unknown
E       Stacktrace:
E           at org.openqa.selenium.grid.sessionqueue.SessionNotCreated.execute (SessionNotCreated.java:55)
E           at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
E           at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
E           at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0 (RequiresSecretFilter.java:64)
E           at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
E           at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
E           at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
E           at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:120)
E           at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
E           at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
E           at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
E           at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
E           at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
E           at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
E           at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
E           at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
E           at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
E           at java.util.concurrent.FutureTask.run (FutureTask.java:264)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
E           at java.lang.Thread.run (Thread.java:829)

../venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:247: SessionNotCreatedException

Error[2]
[selenium-chrome-node-deployment-5c97fbc757-fc2cr] Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 49768
[selenium-chrome-node-deployment-5c97fbc757-fc2cr] Only local connections are allowed.
[selenium-chrome-node-deployment-5c97fbc757-fc2cr] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[selenium-chrome-node-deployment-5c97fbc757-fc2cr] ChromeDriver was started successfully.
[selenium-chrome-node-deployment-5c97fbc757-fc2cr] 17:41:24.671 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "8db6df1a2b4a2f31aa7a2dc8cceaa34f","eventTime": 1657474884499717672,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:49768","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'selenium-chrome-node-deployment-5c97fbc757-fc2cr', ip: '10.244.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.13'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.1.1', revision: 'e8fcc2cecf'\nSystem info: host: 'selenium-chrome-node-deployment-5c97fbc757-fc2cr', ip: '10.244.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '11.0.13'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:131)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"goog:chromeOptions\": {\"prefs\": {\"download.default_directory\": \"\\u002fvar\\u002ffolders\\u002fnr\\u002f863xl1j51mxg6y0gdz1p4tnw0000gn\\u002fT\",\"download.prompt_for_download\": false,\"download.directory_upgrade\": true,\"profile.default_content_settings.popups\": false},\"extensions\": [  ],  \"args\": [    ]    },    \"browserName\": \"chrome\",    \"pageLoadStrategy\": \"normal\",    \"se:vncEnabled\": true    }\n"}}
```

### Operating System

macOS Montery 12.4

### Docker Selenium version (tag)

4.1.1-20211217

**Comment by bhashagemini** [comment]
I have tried:
- Upgrading to latest chrome image
- Verifying chrome version and chrome driver version are matching
- Re-installing my kube cluster with both latest and older version of kind.
- Tried with minikube instead of kind
- Running with no chrome options
- Running with only chrome options `--sandbox` and `----disable-dev-shm-usage`
- Running with `--headless`
- Running with increased resource allocation 1Gi -> 2Gi

**Comment by diemol** [comment]
That error is most of the time related to the environment, probably resources.

Have you tried in a different machine? Also, please note that we only provide the Helm chart, not manifests anymore.

**Comment by jinjin123** [comment]
hitting the same issue on another server, same img on local is fine without arguments, but it works for me, on selenium/standalone-chrome:latest, may be change the solution let it works first? 
```
chromeOptions.add_argument('--disable-dev-shm-usage')
chromeOptions.add_argument('--no-sandbox')
chromeOptions.add_argument('--headless')
```
```
Starting ChromeDriver 103.0.5060.53 (a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}) on port 40864
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started succes[sful1l6y5.8
060174.418][SEVERE]: bind() failed: Cannot assign requested address (99)
12:16:14.659 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'selenium-standalone-chrome', ip: '172.17.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-39-generic', java.version: '11.0.15'
Driver info: driver.version: unknown
12:16:14.659 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'selenium-standalone-chrome', ip: '172.17.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-39-generic', java.version: '11.0.15'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:141)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:67)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:145)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:362)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:624)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:550)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:797)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:758)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

12:16:14.661 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "cb514b65f4dae494f2b2246de473cf64","eventTime": 1658060174620043832,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:40864","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.3.0', revision: 'a4995e2c09*'\nSystem info: host: 'selenium-standalone-chrome', ip: '172.17.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-39-generic', java.version: '11.0.15'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.3.0', revision: 'a4995e2c09*'\nSystem info: host: 'selenium-standalone-chrome', ip: '172.17.0.8', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-39-generic', java.version: '11.0.15'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:141)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:67)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:145)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:362)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:624)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:550)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:797)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:758)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"goog:chromeOptions\": {\"extensions\": [  ],  \"args\": [    \"--user-data-dir=\\u002fhome\\u002fseluser\\u002fdata\",    \"--disable-dev-shm-usage\"    ]    },    \"se:noVncPort\": 7900,    \"browserName\": \"chrome\",    \"pageLoadStrategy\": \"normal\",    \"se:vncEnabled\": true    }\n"}}

12:16:14.675 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "cb514b65f4dae494f2b2246de473cf64","eventTime": 1658060174674888812,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "192.168.1.110:9515","http.method": "POST","http.request_content_length": "424","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.1.3 (python linux)"}}

```

**Comment by bhashagemini** [comment]
@diemol Yes it seems so.  I setup everything in our kubernetes cluster in AWS rather than locally and it is working now.  Though my PC has plenty of resources (32 GB RAM Mac).  Locally, Firefox worked fine with the exact same resource allocation.

**Comment by maurozaccariotto** [comment]
Hi, having same issue on OSX host with selenium/standalone-chrome:latest running tests from another container with Laravel dusk, the issue started only after upgrading from Big Sur to Monterey (Apple chip)

**Comment by maurozaccariotto** [comment]
is there any temporary workaround to run locally in your opinion? thanks

**Comment by diemol** [comment]
Thanks for replying @bhashagemini. Closing this issue then.

@maurozaccariotto, these images do not work on ARM. Check the ARM images https://github.com/SeleniumHQ/docker-selenium#experimental-mult-arch-aarch64armhfamd64-images
