### ISSUE TITLE
[🐛 Bug]: Selenium HasAuthentication is not working with docker selenium grid

### ISSUE THREAD

**Issue by chetakkochrekar** [SeleniumHQ/docker-selenium#1673]
### What happened?

When I run below code on docker selenium grid set up then error is thrown. When I run same code in local selenium grid in my machine then its working fine. It looks like selenium's HasAuthentication is not compatible with current docker selenium grid. When i comment out HasAuthentication, then it works fine in selenium docker grid.

Can you please help to resolve this?

**Code:**
```
public static void main(String[] args) {
		// TODO Auto-generated method stub
		ChromeOptions chromeOptions = new ChromeOptions();
		WebDriver driver=null;
		try {
			driver = new RemoteWebDriver(new URL("http://localhost:4444"),chromeOptions);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Augmenter augmenter = new Augmenter();
		driver = augmenter.augment(driver);
		DevTools devTools = ((HasDevTools) driver).getDevTools();
		devTools.createSession();
		driver = augmenter.addDriverAugmentation("chrome", HasAuthentication.class, (caps, exec) ->
		(whenThisMatches, useTheseCredentials) -> {
			devTools.getDomains().network().addAuthHandler(whenThisMatches, useTheseCredentials);
		}).augment(driver);
		((HasAuthentication) driver).register(UsernameAndPassword.of("foo", "bar"));
		driver.get("http://httpbin.org/basic-auth/foo/bar");
		System.out.println(driver.findElement(By.tagName("pre")).getText());
		driver.quit();

	}	
```

**Java Version -**  "18.0.1.1"
**Host Operating System** - "mac OS Monterey version 12.4"
**Docker yml file used**  -  https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml
**Selenium maven dependency**
<dependency>
       <groupId>org.seleniumhq.selenium</groupId>
       <artifactId>selenium-java</artifactId>
       <version>4.4.0</version>
</dependency>

### Command used to start Selenium Grid with Docker

```shell
docker compose -f docker-compose.yml up
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.21.0.4:4444/session/7a14cbb2f48de3ff5477f413979fe37d/se/cdp
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'FIN0052ochrekar.fritz.box', ip: '2001:9e8:214:2400:e91a:96ed:e2f4:5299%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.4', java.version: '17.0.3'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:104)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:137)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:127)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:48)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:186)
	at OTPAuthentication.docketTest.main(docketTest.java:37)
```

### Operating System

mac OS Monterey version 12.4

### Docker Selenium version (tag)

4.4.0-20220831

**Comment by chetakkochrekar** [comment]
Docker Chrome Node Logs-

```
Starting ChromeDriver 105.0.5195.19 (b9c217c128c16f53d12f9a02933fcfdec1bf49af-refs/branch-heads/5195@{#176}) on port 52414
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1663151093.917][SEVERE]: bind() failed: Cannot assign requested address (99)
ChromeDriver was started successfully.
10:24:54.566 INFO [ProtocolHandshake.createSession] - Detected upstream dialect: W3C
10:24:54.572 INFO [LocalNode.newSession] - Session created by the Node. Id: 5bb1547d20fc40937823957e5155ec82, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.52, chrome: {chromedriverVersion: 105.0.5195.19 (b9c217c128c1..., userDataDir: /tmp/.com.google.Chrome.K0g0cP}, goog:chromeOptions: {debuggerAddress: localhost:39065}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:39065, se:cdpVersion: 105.0.5195.52, se:vncEnabled: true, se:vncLocalAddress: ws://172.21.0.4:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

**Comment by chetakkochrekar** [comment]
@diemol: Hi Diemol, Could you please look into this issue? Many thanks in advance

**Comment by jamesmortensen** [comment]
Hi @chetakkochrekar It looks like HasAuthentication is using CDP, which relies on a websocket connection to Chrome.  I think it is trying to connect via port 39065.  

Here are my initial thoughts: I'm wondering if it is possible to specify a specific CDP port to use and then tell docker to also bind that same port to the running standalone-chrome container, just like we do with port 4444.

**Comment by chetakkochrekar** [comment]
@jamesmortensen :Thanks for your response. This issue got resolved when i added "SE_NODE_GRID_URL=https://localhost:4444" in the docker file for all the nodes.
