### ISSUE TITLE
[🐛 Bug]: Running on Mac M1 laptop raising DevToolsActivePort 

### ISSUE THREAD

**Issue by omerls-pw** [SeleniumHQ/docker-selenium#1676]
### What happened?

When running on `Mac M1` laptop it raises

```bash
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
``` 
exception 

it's resolved when using `seleniarm/standalone-chromium` image.

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 4444:4444 --name chrome --platform linux/amd64 -v /dev/shm:/dev/shm selenium/standalone-chrome
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/omerlivne/workspace/tc365/tc365/main.py", line 137, in <module>
    main()
  File "/Users/omerlivne/workspace/tc365/tc365/main.py", line 114, in main
    driver = create_webdriver()
  File "/Users/omerlivne/workspace/tc365/tc365/main.py", line 100, in create_webdriver
    driver = webdriver.Remote(browser_host , options=options)
  File "/Users/omerlivne/Library/Caches/pypoetry/virtualenvs/tc365-Wgk8G4ng-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/omerlivne/Library/Caches/pypoetry/virtualenvs/tc365-Wgk8G4ng-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/omerlivne/Library/Caches/pypoetry/virtualenvs/tc365-Wgk8G4ng-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/Users/omerlivne/Library/Caches/pypoetry/virtualenvs/tc365-Wgk8G4ng-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'f264f4e0fc59', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.124-linuxkit', java.version: '11.0.16'
Driver info: driver.version: unknown
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'f264f4e0fc59', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.124-linuxkit', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:200)
    at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply (DriverServiceSessionFactory.java:68)
    at org.openqa.selenium.grid.node.local.SessionSlot.apply (SessionSlot.java:145)
    at org.openqa.selenium.grid.node.local.LocalNode.newSession (LocalNode.java:362)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession (LocalDistributor.java:639)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession (LocalDistributor.java:558)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest (LocalDistributor.java:812)
    at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1 (LocalDistributor.java:773)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
```

### Operating System

macOS 12.5.1

### Docker Selenium version (tag)

4.4.0-20220831

**Comment by omerls-pw** [comment]
closing

**Comment by caseyprovost** [comment]
Question on this! We use chromium and selenium as part of a pre-existing docker image like so:

```
RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) ARCH='x64';; \
    ppc64el) ARCH='ppc64le';; \
    s390x) ARCH='s390x';; \
    arm64) ARCH='arm64';; \
    armhf) ARCH='armv7l';; \
    i386) ARCH='x86';; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac \
```

later on in that file
```
apt-get install chromium-driver chromium
```

Everything works just fine on Intel mac, but not the M1. How do we use this solution in our context?
