### ISSUE TITLE
[🐛 Bug]: Opening session with firefox docker image always times out (ruby)

### ISSUE THREAD

**Issue by danielittlewood0** [SeleniumHQ/docker-selenium#1682]
### What happened?

I am trying to use the selenium/standalone-firefox docker image as a remote browser to run some ruby tests in a separate container. The remote browser opens fine, and I can visit localhost:4444 and localhost:7900 in a browser. I can also make curl requests to the browser from inside my testing container, so it doesn't seem to be a networking issue.

When the tests try to open a session with the browser, however, it always times out. I have tried messing with the version number of selenium-webdriver, and the docker image (none have worked for me).

### Command used to start Selenium Grid with Docker

```shell
docker-compose run test

Full repo at https://gitlab.com/danielittlewood0/selenium-test
```

### Relevant log output

```shell
/usr/local/lib/ruby/3.0.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
        from /usr/local/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
        from /usr/local/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
        from /usr/local/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
        from /usr/local/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
        from /usr/local/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
        from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
        from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
        from /usr/local/lib/ruby/3.0.0/net/http.rb:1521:in `request'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/http/default.rb:118:in `response_for'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/bridge.rb:625:in `execute'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:323:in `block in create_bridge'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/remote/driver.rb:43:in `initialize'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:57:in `new'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver/common/driver.rb:57:in `for'
        from /usr/local/bundle/gems/selenium-webdriver-4.4.0/lib/selenium/webdriver.rb:89:in `for'
        from test.rb:5:in `<main>'
ERROR: 1
```

### Operating System

Gentoo Linux

### Docker Selenium version (tag)

selenium/standalone-firefox:4.4.0-20220831

**Comment by jamesmortensen** [comment]
Hi @danielittlewood0 when you make those curl requests from inside your test container, are they to localhost:4444 or firefox:4444?

Are you able to obtain any logs from the selenium/standalone-firefox container?

**Comment by danielittlewood0** [comment]
Hi @jamesmortensen, thanks for the reply - I made the curls to firefox:4444. I don't think localhost:4444 would work (but I can check).

I can attach to the firefox container; I think I only saw lines when the timeout completed saying that the request execution had completed. I'll do a test and get the actual lines.

**Comment by danielittlewood0** [comment]
Note that I ran docker compose down before both tests to make sure the environment was clear.

## Test 1 (curls)

```
# in terminal 1
docker compose run test bash
# in terminal 2
docker attach 2b144aaadcdb | tee test_1.log
# in terminal 1
root@fd93e23d4dd3:/code# curl localhost:4444
curl: (7) Failed to connect to localhost port 4444: Connection refused
root@fd93e23d4dd3:/code# curl firefox:4444
root@fd93e23d4dd3:/code# curl firefox:4444/status
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "97e893d0-e21b-475d-9c82-4e9aa7686795",
        "uri": "http:\u002f\u002f172.28.0.2:4444",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "5.10.61-gentoo-x86_64"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.4.0 (revision e5c75ed026a)",
        "slots": [
          {
            "id": {
              "hostId": "97e893d0-e21b-475d-9c82-4e9aa7686795",
              "id": "4390d6aa-880b-4283-8bc9-77fd81e4c3bb"
            },
            "lastStarted": "1970-01-01T00:00:00Z",
            "session": null,
            "stereotype": {
              "browserName": "firefox",
              "browserVersion": "104.0",
              "platformName": "LINUX",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      }
    ]
  }
}
exit
docker compose down
```

test_1.log didn't capture anything until I quit docker.

## Test 2 (firefox logs)

```
docker compose up | tee test_2.log
```

test_2.log is here: https://gist.github.com/danielittlewood0/b7f73ee4ccd37e613c8ec481d29c0e42

**Comment by jamesmortensen** [comment]
Hi @danielittlewood0 not 100% sure on this:  what do you think of setting env variable SE_NODE_GRID_URL=http://localhost:4444 on the Firefox container?  I've seen this solve the problem on a few similar issues before...

**Comment by danielittlewood0** [comment]
@jamesmortensen I added the following to docker-compose.yml (linked repo updated to match)

```diff
+    environment:
+      - SE_NODE_GRID_URL=http://localhost:4444
```

I didn't see anything different unfortunately.

**Comment by jamesmortensen** [comment]
So you were able to curl the node and confirm you can reach it. Any way to see what endpoint it is trying to reach when it is failing?  Is there a way to increase the log level?

**Comment by pgiblock** [comment]
I also have this problem. Doesn't matter if it is firefox or chrome standalone containers. The SE_NODE_GRID_URL workaround had no apparent affect. To eliminate a possible issue with curl vs ruby networking, I used HTTParty to fetch the status from the rspec container, which works fine:
```ruby
puts HTTParty.get('http://selenium:4444/status').body
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
    ...
```

**Comment by pgiblock** [comment]
I threw `tcpdump` on the selenium container and traced. I then recreated the issue with curl, and here's what we get:
```console
% time curl -v \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"capabilities":{"alwaysMatch":{}}}' \
  'http://selenium:4444/session'
*   Trying 172.28.0.3:4444...
* Connected to selenium (172.28.0.3) port 4444 (#0)
> POST /session HTTP/1.1
> Host: selenium:4444
> User-Agent: curl/7.74.0
> Accept: application/json
> Content-Type: application/json
> Content-Length: 35
>
* upload completely sent off: 35 out of 35 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 9426
< Cache-Control: no-cache
< Content-Type: application/json; charset=utf-8
<
{
  "value": {
    "error": "session not created",
    "message": "Could not start a new session. New session request timed out\nBuild info: version: '4.4.0', revision: 'e5c75ed026a'\nSystem info: host: '3290f345d772', ip: '172.28.0.3', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.15.32-0-virt', java.version: '11.0.16'\nDriver info: driver.version: unknown",
    "stacktrace": [
      {
        "fileName": "LocalNewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "addToQueue",
        "className": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue",
        "lineNumber": 179,
        "classLoaderName": "app"
      },
      {
        "fileName": "NewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$new$0",
        "className": "org.openqa.selenium.grid.sessionqueue.NewSessionQueue",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$TemplatizedRoute",
        "lineNumber": 192,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 336,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "NewSessionQueue.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.grid.sessionqueue.NewSessionQueue",
        "lineNumber": 120,
        "classLoaderName": "app"
      },
      {
        "fileName": "SpanWrappedHttpHandler.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler",
        "lineNumber": 86,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 64,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 336,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "Router.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.grid.router.Router",
        "lineNumber": 91,
        "classLoaderName": "app"
      },
      {
        "fileName": "EnsureSpecCompliantResponseHeaders.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders",
        "lineNumber": 34,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 64,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 336,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "handle",
        "className": "org.openqa.selenium.remote.http.Route$CombinedRoute",
        "lineNumber": 336,
        "classLoaderName": "app"
      },
      {
        "fileName": "Route.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Route",
        "lineNumber": 68,
        "classLoaderName": "app"
      },
      {
        "fileName": "AddWebDriverSpecHeaders.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.AddWebDriverSpecHeaders",
        "lineNumber": 35,
        "classLoaderName": "app"
      },
      {
        "fileName": "ErrorFilter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.ErrorFilter",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 64,
        "classLoaderName": "app"
      },
      {
        "fileName": "ErrorFilter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$apply$0",
        "className": "org.openqa.selenium.remote.ErrorFilter",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": "Filter.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "execute",
        "className": "org.openqa.selenium.remote.http.Filter$1",
        "lineNumber": 64,
        "classLoaderName": "app"
      },
      {
        "fileName": "SeleniumHandler.java",
        "moduleVersion": null,
        "moduleName": null,
        "nativeMethod": false,
        "methodName": "lambda$channelRead0$0",
        "className": "org.openqa.selenium.netty.server.SeleniumHandler",
        "lineNumber": 44,
        "classLoaderName": "app"
      },
      {
        "fileName": "Executors.java",
        "moduleVersion": "11.0.16",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "call",
        "className": "java.util.concurrent.Executors$RunnableAdapter",
        "lineNumber": 515,
        "classLoaderName": null
      },
      {
        "fileName": "FutureTask.java",
        "moduleVersion": "11.0.16",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.util.concurrent.FutureTask",
        "lineNumber": 264,
        "classLoaderName": null
      },
      {
        "fileName": "ThreadPoolExecutor.java",
        "moduleVersion": "11.0.16",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "runWorker",
        "className": "java.util.concurrent.ThreadPoolExecutor",
        "lineNumber": 1128,
        "classLoaderName": null
      },
      {
        "fileName": "ThreadPoolExecutor.java",
        "moduleVersion": "11.0.16",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.util.concurrent.ThreadPoolExecutor$Worker",
        "lineNumber": 628,
        "classLoaderName": null
      },
      {
        "fileName": "Thread.java",
        "moduleVersion": "11.0.16",
        "moduleName": "java.base",
        "nativeMethod": false,
        "methodName": "run",
        "className": "java.lang.Thread",
        "lineNumber": 829,
        "classLoaderName": null
      }
    ]
  }
}
real    5m0.036s
user    0m0.035s
sys     0m0.012s
```
The response takes just over 5 minutes. The selenium server logs this message:
`
19:51:02.642 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "03d2cd4be5b322be5a6e85da907e756f","eventTime": 1664394662641349976,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "selenium:4444","http.method": "POST","http.request_content_length": "35","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "curl\u002f7.74.0"}}
`

**Comment by jamesmortensen** [comment]
@pgiblock I noticed in your log that your architecture is aarch64.  Are you trying to run the Selenium containers on an ARM machine?  If so, then that may be why you're facing issues.  We have a forked repo which builds ARM-compatible Selenium container images:  https://github.com/seleniumhq-community/docker-seleniarm/releases/tag/seleniarm-v4.5.0-20221001

**Comment by pgiblock** [comment]
Yes @jamesmortensen - my apologies as I didn't realize where that project is maintained on Github, however, that (seleniarm) is the the image I was running originally. I just retested with `seleniarm/standalone-firefox:105.0-20221001` and encounter the same problem.

Furthermore, I tried `selenium/standalone-firefox:105.0-20221004` (amd64 running via emulation) and still have the exact same problem:
```
{
  "value": {
    "error": "session not created",
    "message": "Could not start a new session. New session request timed out \nHost info: host: 'de05ed822a4f', ip: '172.28.0.2'\nBuild info: version: '4.5.0', revision: 'fe167b119a'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.32-0-virt', java.version: '11.0.16'\nDriver info: driver.version:
 unknown",
    "stacktrace": [
```
Just to show that I didn't confuse platforms:
```console
seluser@de05ed822a4f:/$ uname -a
Linux de05ed822a4f 5.15.32-0-virt #1-Alpine SMP Mon, 28 Mar 2022 13:09:00 +0000 x86_64 x86_64 x86_64 GNU/Linux
```

Considering this fails on both selenium and seleniarm images, both with firefox and chrome drivers, I wonder if there is something wrong with the client's request. Is anyone able to look at the [curl request in my comment above](https://github.com/SeleniumHQ/docker-selenium/issues/1682#issuecomment-1261400525) and let me know if that is a valid request?

**Comment by jamesmortensen** [comment]
I tried to replicate this without docker-compose, to simplify things.  I ran the tests in a Gitpod host and ran the standalone-firefox:latest with docker run so there's just that one container.  

When I try to run the sample with Ruby, I see the timeouts, but if I use JavaScript and WebdriverIO, I can pass tests.  This leads me to believe it might be something to do with the Ruby language bindings, but I'm not 100% sure since I'm not a Ruby dev.  It might be interesting to also try with Selenium JS and Python as well.

I also noticed in the docs that they are calling for adding desired_capabilities.  Ruby doesn't seem to accept this as a valid argument though when I tried it:  https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/

To help debug this further, would you be able to try the same setup with Selenium Python or JavaScript instead of Ruby?  Otherwise, I may be able to dig into this more over the weekend.

Also, just an FYI, I'm on an M1 so am running aarch64 hardware.  To explore the AMD64 Intel containers, you can use Gitpod so you don't have to deal with emulation. Emulated amd64 sometimes creates issues due to the slowness and sometimes because the hardware kernel isn't perfectly emulated properly for running the browsers.

`https://gitpod.io/#https://github.com/<YOUR_GITHUB_USERNAME_HERE>/docker-selenium`

**Comment by jamesmortensen** [comment]
Just wanted to add another thought on this.  We were able to replicate the issue with a standalone-firefox container.  If you run Selenium locally, without Docker, and run the Ruby script, do you still see the same behavior?  This would help determine whether the issue is docker-related or something to do with the Ruby bindings specifically.

**Comment by diemol** [comment]
The issue is that you are not passing the capabilities to the request, therefore Grid receives a blank for the browser and the Firefox container cannot match. Sending `capabilities: :firefox` makes it work.

```ruby
require 'selenium-webdriver'

# this is a hack to ensure firefox is started before the test runs
sleep 10

driver = Selenium::WebDriver.for :remote, url: "http://firefox:4444", capabilities: :firefox
driver.get "http://www.google.com"
driver.quit  
```

**Comment by jogaco** [comment]
hey I am facing a similar issue.
This is what I see from docker container logs:
```
``8:20:30.599 INFO [LocalNode.newSession] - Session created by the Node. Id: eefd149f-32f5-4fb5-b8ee-220eb0fe9e05, Caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 116.0, moz:accessibilityChecks: false, moz:buildID: 20230727152340, moz:debuggerAddress: 127.0.0.1:10778, moz:firefoxOptions: {binary: /opt/firefox-latest/firefox}, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 5.4.0-113-generic, moz:processID: 795, moz:profile: /tmp/rust_mozprofilekuMFU0, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore}
18:20:30.602 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: eefd149f-32f5-4fb5-b8ee-220eb0fe9e05 
 Caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 116.0, moz:accessibilityChecks: false, moz:buildID: 20230727152340, moz:debuggerAddress: 127.0.0.1:10778, moz:firefoxOptions: {binary: /opt/firefox-latest/firefox}, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 5.4.0-113-generic, moz:processID: 795, moz:profile: /tmp/rust_mozprofilekuMFU0, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore}
18:21:07.406 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "3499f019327004bd3dba4347b55222aa","eventTime": 1694024467405542986,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:4444","http.method": "POST","http.request_content_length": "171","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.9.0 (ruby linux) watir\u002f7.1.0"}}
``
Any clue?

**Comment by jogaco** [comment]
This seems to work ok:

`Selenium::WebDriver.for :remote, url: "http://127.0.0.1:4444", capabilities: :chrome`

Initially I was trying w this:

`Watir::Browser.new :firefox, url: "http://127.0.0.1:4444/wd/hub"``

**Comment by jogaco** [comment]
Ups. No. Same error.
Just worked once, but no more :(

These are some logs I see:

``````19:15:04.368 WARN [SeleniumManager.lambda$runCommand$1] - Exception managing chrome: Unable to discover proper chromedriver version in offline mode
19:15:04.825 INFO [LocalNode.newSession] - Session created by the Node. Id: 714011ca3736f2b8eb28d514978433eb, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 116.0.5845.140, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:39615}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 116.0.5845.140, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
19:15:04.828 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 714011ca3736f2b8eb28d514978433eb 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 116.0.5845.140, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:39615}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 116.0.5845.140, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
19:16:51.607 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "408899cfc39c3c7627029df284a0aa6d","eventTime": 1694027811606327773,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:4444","http.method": "POST","http.request_content_length": "81","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.9.0 (ruby linux)"}}
