### ISSUE TITLE
[🐛 Bug]: all attempts to connect to * failed

### ISSUE THREAD

**Issue by ArtsiomAntropau** [SeleniumHQ/docker-selenium#1702]
### What happened?

I'm using Kubernetes and I see the next error
`all attempts to connect to 100.98.133.209:4444 failed`
So I have two services, first for selenium-hub and second for scalable selenium-chrome-nodes
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/82237255/197426117-9ac783a9-63ab-46c5-bf7b-f1708b63cecd.png">
I'm trying to connect to the 
`http://selenium-hub:4444` and connect is ok, but when I'm trying to run any CDP command it fails because it is trying to connect to the selenium chrome node directly, not via selenium-hub because the IP `100.98.133.209` relates to chrome node
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/82237255/197426252-4fe2dc15-d557-4554-a7d6-2b30aba7ba1c.png">
but as we know chrome node doesn't have a 4444 port (selenium trying `100.98.133.209:4444`), only 5555
<img width="338" alt="image" src="https://user-images.githubusercontent.com/82237255/197426287-2d67d2ba-da40-4ade-ac63-83b105e13292.png">

(no errors in the selenium-hub container found)

### Command used to start Selenium Grid with Docker

```shell
chart: selenium-grid
version: ~0.12
values:
  chromeNode:
    enabled: true
    replicas: 2
  firefoxNode:
    enabled: false
  edgeNode:
    enabled: false
```

### Relevant log output

```shell
exceptiongroup.ExceptionGroup: all attempts to connect to 100.98.133.209:4444 failed (1 sub-exception)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/artsiom_antropau/app/myapp/src/dash_app/pptx.py", line 112, in ppt_link_controller
    data = get_presentation(
  File "/Users/artsiom_antropau/app/myapp/src/pptx_export.py", line 175, in get_presentation
    with generate_image_for_report(url_path,
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/artsiom_antropau/app/myapp/src/domains/screenshot_generator/screenshot_generator.py", line 180, in generate_image_for_report
    execute_cdp_cmd(driver, devtools.network.enable())
  File "/Users/artsiom_antropau/app/myapp/src/domains/screenshot_generator/screenshot_generator.py", line 156, in execute_cdp_cmd
    return trio.run(async_execute_cdp_cmd, *args)
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/Users/artsiom_antropau/app/myapp/src/domains/screenshot_generator/screenshot_generator.py", line 150, in async_execute_cdp_cmd
    async with driver.bidi_connection() as session:
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/selenium/webdriver/remote/webdriver.py", line 1182, in bidi_connection
    async with cdp.open_cdp(ws_url) as conn:
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/selenium/webdriver/common/bidi/cdp.py", line 476, in open_cdp
    conn = await connect_cdp(nursery, url)
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/selenium/webdriver/common/bidi/cdp.py", line 497, in connect_cdp
    ws = await connect_websocket_url(nursery, url,
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/trio_websocket/_impl.py", line 262, in connect_websocket_url
    return await connect_websocket(nursery, host, port, resource,
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/trio_websocket/_impl.py", line 171, in connect_websocket
    stream = await trio.open_tcp_stream(host, port)
  File "/Users/artsiom_antropau/app/myapp/__pypackages__/3.10/lib/trio/_highlevel_open_tcp_stream.py", line 375, in open_tcp_stream
    raise OSError(msg) from ExceptionGroup(msg, oserrors)
OSError: all attempts to connect to 100.98.133.209:4444 failed
```

### Operating System

k8s v1.22.10, linux

### Docker Selenium version (tag)

4.5.0

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

**Comment by ArtsiomAntropau** [comment]
@diemol so and what, how it may help me? `SE_NODE_GRID_URL` should be specified for inside nodes?

**Comment by diemol** [comment]
Yes, `SE_NODE_GRID_URL` needs to have the public url of the Grid.

**Comment by ArtsiomAntropau** [comment]
Got it, so my finalization:

for my case this construction fixed the issue:
```
chromeNode:
  enabled: true
  replicas: 2
  extraEnvironmentVariables:
    - name: SE_NODE_GRID_URL
      value: http://selenium-hub:4444
```

todo: add any info about this here https://www.selenium.dev/documentation/webdriver/bidirectional/
