### ISSUE TITLE
[🐛 Bug]: Selenium-hub ignoring parameter SE_NODE_SESSION_TIMEOUT

### ISSUE THREAD

**Issue by Schtil** [SeleniumHQ/docker-selenium#1725]
### What happened?

I apologize for the duplicate issues.
The last one was closed and I can't reopen it.
First part - #1724 

I also tried `SE_NODE_SESSION_TIMEOUT`
Which is listed in the documentation

> Containers can be further configured through environment variables, such as SE_NODE_SESSION_TIMEOUT and SE_OPTS.
> When a child container is created, all environment variables prefixed with SE_ will be forwared and set in the container. 
> You can set the desired environment variables in the standalone-docker or node-docker containers. 
> The following example sets the session timeout to 700 seconds for all sessions:

Nothing changed

Hub continues to ignore it and does not kill sessions by timeout

### Command used to start Selenium Grid with Docker

```shell
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=30
  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=5
      - SE_NODE_SESSION_TIMEOUT=30
```

### Relevant log output

```shell
-
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

4.3.0-20220726

**Comment by diemol** [comment]
`SE_NODE_SESSION_TIMEOUT` should be used at the Node or Standalone only. 

>Hub continues to ignore it and does not kill sessions by timeout

The Hub does not kill the session, the Node does. The value you are setting is 30 seconds, can you share the log from the Node showing that the session is not killed when the `SE_NODE_SESSION_TIMEOUT` is set to 30 seconds?

**Comment by Schtil** [comment]
```
ubuntu@host:~$ docker logs ubuntu_chrome_1 
2022-11-12 17:24:30,248 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2022-11-12 17:24:30,253 INFO RPC interface 'supervisor' initialized
2022-11-12 17:24:30,253 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-11-12 17:24:30,253 INFO supervisord started with pid 8
2022-11-12 17:24:31,257 INFO spawned: 'xvfb' with pid 10
2022-11-12 17:24:31,259 INFO spawned: 'vnc' with pid 11
2022-11-12 17:24:31,262 INFO spawned: 'novnc' with pid 12
2022-11-12 17:24:31,264 INFO spawned: 'selenium-node' with pid 15
2022-11-12 17:24:31,286 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Generating Selenium Config
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Tracing is disabled
Selenium Grid Node configuration: 
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
grid-url = "http://{IP_ADDRESS}:4444"
session-timeout = "30"
override-max-sessions = false
detect-drivers = false
drain-after-session-count = 0
max-sessions = 5

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "107.0", "platformName": "Linux"}'
max-sessions = 5

Starting Selenium Grid Node...
17:24:32.096 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
17:24:32.102 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
17:24:32.244 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
2022-11-12 17:24:32,291 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-12 17:24:32,291 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-12 17:24:32,291 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
17:24:32.321 INFO [UnboundZmqEventBus.<init>] - Sockets created
17:24:33.323 INFO [UnboundZmqEventBus.<init>] - Event bus ready
17:24:33.466 INFO [NodeServer.createHandlers] - Reporting self as: http://172.17.0.3:5555
17:24:33.489 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
17:24:33.547 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "107.0","se:noVncPort": 7900,"browserName": "chrome","platformName": "LINUX","se:vncEnabled": true} 5 times
17:24:33.574 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
17:24:33.817 INFO [NodeServer$1.start] - Starting registration process for Node http://172.17.0.3:5555
17:24:33.819 INFO [NodeServer.execute] - Started Selenium node 4.6.0 (revision 79f1c02ae20): http://172.17.0.3:5555
17:24:33.835 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
17:24:34.477 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 4497
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1668273887.5Ch9r8o]m[eSDErViEvReEr] :w absi nsdt(a)r tfeadi lseudc:c eCsasnfnuoltl ya.s
sign requested address (99)
17:24:48.346 INFO [LocalNode.newSession] - Session created by the Node. Id: 13fae28cb3aa90f7a750190668264831, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.X1rax6}, goog:chromeOptions: {debuggerAddress: localhost:34369}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:34369, se:cdpVersion: 107.0.5304.87, se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
17:25:18.471 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:282)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:460)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
        ... 26 more
17:25:18.472 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
17:25:18.473 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:282)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:460)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
        ... 26 more

17:25:18.474 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "1ef1244a9b9a22886f12c54a29c4cf38","eventTime": 1668273918470852046,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.6.0', revision: '79f1c02ae20'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.6.0', revision: '79f1c02ae20'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:282)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)\n\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:460)\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.net.http.HttpTimeoutException: request timed out\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)\n\t... 26 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "{IP_ADDRESS}:4444","http.method": "POST","http.request_content_length": "24","http.scheme": "HTTP","http.target": "\u002fsession\u002f13fae28cb3aa90f7a750190668264831\u002furl","http.user_agent": "selenium\u002f4.6.0 (python mac)"}}

17:25:33.625 INFO [LocalNode.lambda$new$3] - Session id 13fae28cb3aa90f7a750190668264831 timed out, stopping...
17:26:03.636 WARN [LocalCache.processPendingNotifications] - Exception thrown by removal listener
org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:282)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)
        at org.openqa.selenium.grid.node.local.LocalNode.lambda$new$3(LocalNode.java:193)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1814)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3467)
        at com.google.common.cache.LocalCache$Segment.cleanUp(LocalCache.java:3449)
        at com.google.common.cache.LocalCache.cleanUp(LocalCache.java:3905)
        at com.google.common.cache.LocalCache$LocalManualCache.cleanUp(LocalCache.java:4926)
        at org.openqa.selenium.concurrent.GuardedRunnable.lambda$guard$0(GuardedRunnable.java:36)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
        ... 17 more
```

**Comment by Schtil** [comment]
reproduced also on chrome node version 107.0

```
18:32:27.887 INFO [LocalNode.lambda$new$3] - Session id 33592b42c97d321c99cf17b30f6df944 timed out, stopping...
18:32:57.902 WARN [LocalCache.processPendingNotifications] - Exception thrown by removal listener
org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:282)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)
        at org.openqa.selenium.grid.node.local.LocalNode.lambda$new$3(LocalNode.java:193)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1814)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3467)
        at com.google.common.cache.LocalCache$Segment.cleanUp(LocalCache.java:3449)
        at com.google.common.cache.LocalCache.cleanUp(LocalCache.java:3905)
        at com.google.common.cache.LocalCache$LocalManualCache.cleanUp(LocalCache.java:4926)
        at org.openqa.selenium.concurrent.GuardedRunnable.lambda$guard$0(GuardedRunnable.java:36)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
        ... 17 more
```

**Comment by diemol** [comment]
There are two things here. First, you have a command that is timing out after 30 seconds (which is the `SE_NODE_SESSION_TIMEOUT` value). Second, the execution order to time out a session needs to first cancel the current command (if there is one running), and then stop the session. 

In this case, the command timeout happens first, and a some seconds later the session is stopped. Please note that timing out a session while a command is running will always take a bit longer as the two steps I mentioned above are needed. Also, because the timeout is checked every 30 seconds. 

Having said that, the functionality is working as expected.
