### ISSUE TITLE
[🐛 Bug]: Unexpected error creating WebSocket DevTools session

### ISSUE THREAD

**Issue by vipuldeshpande** [SeleniumHQ/docker-selenium#1728]
### What happened?

We are trying to access the Chrome Dev Tools while running our tests on an AWS server which has the Selenium Dynamic grid on it. 

The error is encountered on the below line:
DevToolsSession sessions = devTools.GetDevToolsSession();

Reference to solution tried-
https://github.com/SeleniumHQ/selenium/issues/11131

We tried to add the localhost URL, the actual IP address of the host in the SE_NODE_GRID_URL of the YAML, but it didn't seem to work. 

### Command used to start Selenium Grid with Docker

```shell
docker compose -f docker-compose-v3-dynamic-grid.yml up

docker-compose-v3-dynamic-grid.yml file:
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:  node-docker:    image: selenium/node-docker:4.5.3-20221024    volumes:      - ./assets:/opt/selenium/assets      - ./NodeDocker/config.toml:/opt/bin/config.toml      - /var/run/docker.sock:/var/run/docker.sock    depends_on:      - selenium-hub    environment:      - SE_EVENT_BUS_HOST=selenium-hub      - SE_EVENT_BUS_PUBLISH_PORT=4442      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      - SE_NODE_GRID_URL=http://localhost:4444/

  selenium-hub:    image: selenium/hub:4.5.3-20221024    container_name: selenium-hub    ports:      - "4442:4442"      - "4443:4443"      - "4444:4444"

config.toml file:
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [    "selenium/standalone-firefox:4.5.3-20221024", "{\"browserName\": \"firefox\"}",    "selenium/standalone-chrome:4.5.3-20221024", "{\"browserName\": \"chrome\"}",    "selenium/standalone-edge:4.5.3-20221024", "{\"browserName\": \"MicrosoftEdge\"}"    ]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted
# If var/run/docker.sock is not mounted:
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://localhost:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20221104"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=Unexpected error creating WebSocket DevTools session.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetDevToolsSession()
   at Dynamics365Base.UI.Methods.Impersonate.ChangeUser(ISeleniumTestObject testObject) in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Base\UI\Methods\Impersonate.cs:line 64
   at Dynamics365Base.UI.Methods.UIBase.ChangeUser(ISeleniumTestObject testObject) in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Base\UI\Methods\UIBase.cs:line 58
   at Dynamics365Base.UI.Methods.UIBase..ctor(ISeleniumTestObject testObject, Boolean openurl) in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Base\UI\Methods\UIBase.cs:line 35
   at Dynamics365Base.UI.PageModels.NavigationPageModel..ctor(ISeleniumTestObject testObject, Boolean openurl) in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Base\UI\PageModels\NavigationPageModel.cs:line 40
   at Dynamics365Base.UI.PageModels.MSFTLoginPageModel..ctor(ISeleniumTestObject testObject, Boolean openurl) in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Base\UI\PageModels\MSFTLoginPageModel.cs:line 23
   at Dynamics365Tests.UI.Account.BBLA.TestInitialize() in C:\Users\vdeshpan\source\repos\Dynamics365\Dynamics365Tests\UI\Account\BBLA.cs:line 37

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebSocketException: Unable to connect to the remote server

Inner Exception 2:
HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (172.28.0.3:4444)

Inner Exception 3:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

### Operating System

CentOS AWS EC2 

### Docker Selenium version (tag)

4.5.3-20221024

**Comment by diemol** [comment]
You need to add here `SE_NODE_GRID_URL=http://localhost:4444/` the public IP or domain name of the Grid. What you are entering on the `RemoteWebDriver`to create the connection.

**Comment by vipuldeshpande** [comment]
Thanks, we were able to make it work after using the domain name in the URL.

**Comment by campbellja** [comment]
Thank you @diemol you are a lifesaver!
