### ISSUE TITLE
[🐛 Bug]: Connection refusal in router and hence getting timeout exception straight from Chrome node

### ISSUE THREAD

**Issue by suadhika** [SeleniumHQ/docker-selenium#1736]
### What happened?

I have installed selenium 4.6.0 in my local machine which works fine, within company VPN.

Then when I deployed it in our orgs kubernetes cluster (isolateComponents: true) I am getting HTTP 504 for my test cases.

No issues in the chrome node logs

```
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 16517
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1670230314.770][SEVERE]: bind() failed: Cannot assign requested address (99)
08:51:54.972 INFO [LocalNode.newSession] - Session created by the Node. Id: 28c938ed7495ed7987bd6f37987e6f96, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.QNhMmk}, goog:chromeOptions: {debuggerAddress: localhost:43699}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:43699, se:cdpVersion: 107.0.5304.87, se:vncEnabled: true, se:vncLocalAddress: ws://192.168.161.159:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
08:52:02.203 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://192.168.161.159:7900
```
But the router node I can see the below issue:

```
❯ kubectl logs selenium-router-7458b5ccbd-nb48c
2022-12-05 08:45:30,097 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-router.conf" during parsing
2022-12-05 08:45:30,100 INFO RPC interface 'supervisor' initialized
2022-12-05 08:45:30,100 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:45:30,100 INFO supervisord started with pid 7
2022-12-05 08:45:31,103 INFO spawned: 'selenium-grid-router' with pid 9
Starting Selenium Grid Router...
2022-12-05 08:45:31,106 INFO success: selenium-grid-router entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:45:31.432 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:45:31.437 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
08:45:32.323 INFO [RouterServer.execute] - Started Selenium Router 4.6.0 (revision 79f1c02ae20): http://192.168.175.198:4444
08:49:55.051 WARN [SimpleDataFetcherExceptionHandler.logException] - Exception while fetching data (/sessionsInfo) : java.net.ConnectException: Connection refused
java.io.UncheckedIOException: java.net.ConnectException: Connection refused
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:284)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
```
I have created the chrome node and router image with the following command for secure ssl connection to my website.

```
FROM selenium/node-chrome:107.0-chromedriver-107.0
USER root
ADD ssl.crt /usr/local/share/ca-certificates/ssl.crt
RUN update-ca-certificates
USER seluser
```
```
FROM FROM selenium/router:4.6.0
USER root
ADD ssl.crt /usr/local/share/ca-certificates/ssl.crt
RUN update-ca-certificates
USER seluser
```
Not able to understand the issue for the connection refusal, do I need to add proxy details? If so where can I add the same?

### Command used to start Selenium Grid with Docker

```shell
# Clone the project
git clone https://github.com/pedrodotmc/docker-selenium.git

# Install basic grid
helm install selenium-grid docker-selenium/chart/selenium-grid/.

# Or install full grid (Router, Distributor, EventBus, SessionMap and SessionQueuer components separated)
helm install selenium-grid --set isolateComponents=true docker-selenium/chart/selenium-grid/.
```

### Relevant log output

```shell
❯ kubectl logs selenium-router-7458b5ccbd-nb48c
2022-12-05 08:45:30,097 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-router.conf" during parsing
2022-12-05 08:45:30,100 INFO RPC interface 'supervisor' initialized
2022-12-05 08:45:30,100 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:45:30,100 INFO supervisord started with pid 7
2022-12-05 08:45:31,103 INFO spawned: 'selenium-grid-router' with pid 9
Starting Selenium Grid Router...
2022-12-05 08:45:31,106 INFO success: selenium-grid-router entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:45:31.432 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:45:31.437 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
08:45:32.323 INFO [RouterServer.execute] - Started Selenium Router 4.6.0 (revision 79f1c02ae20): http://192.168.175.198:4444
08:49:55.051 WARN [SimpleDataFetcherExceptionHandler.logException] - Exception while fetching data (/sessionsInfo) : java.net.ConnectException: Connection refused
java.io.UncheckedIOException: java.net.ConnectException: Connection refused
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:284)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
```
```


### Operating System

macOs

### Docker Selenium version (tag)

4.6.0

**Comment by diemol** [comment]
Are all components up and able to talk to each other? Check logs for each component.

**Comment by suadhika** [comment]
**distributor log:**


```
10:16:00.702 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: ee4aae8083549875d08d46bef2c1a8c3 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.LIaWXF}, goog:chromeOptions: {debuggerAddress: localhost:40051}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://192.168.161.159:4444/s..., se:cdpVersion: 107.0.5304.87, se:vnc: ws://192.168.161.159:4444/s..., se:vncEnabled: true, se:vncLocalAddress: ws://192.168.161.159:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
10:18:14.640 INFO [GridModel.release] - Releasing slot for session id ee4aae8083549875d08d46bef2c1a8c3
10:18:14.888 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}]
10:18:15.206 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: d7e01bf1f5ed8ca5070c8aa53e05703b 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.5vHrei}, goog:chromeOptions: {debuggerAddress: localhost:33483}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://192.168.161.159:4444/s..., se:cdpVersion: 107.0.5304.87, se:vnc: ws://192.168.161.159:4444/s..., se:vncEnabled: true, se:vncLocalAddress: ws://192.168.161.159:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
10:20:26.879 INFO [GridModel.release] - Releasing slot for session id d7e01bf1f5ed8ca5070c8aa53e05703b
```

**Chrome Node Log:**

```
10:18:46.844 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://192.168.161.159:7900
10:20:25.599 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "e684a377c71fe3620dd16d6b10ba59cf","eventTime": 1670235625598480977,"eventName": "HTTP request execution complete","attributes": {"http.client_ip": "192.168.5.0","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.168.161.159:5555","http.method": "GET","http.request_content_length": "0","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002fd7e01bf1f5ed8ca5070c8aa53e05703b\u002falert\u002ftext","http.user_agent": "selenium\u002f4.6.0 (java mac)"}}

10:20:26.879 INFO [SessionSlot.stop] - Stopping session d7e01bf1f5ed8ca5070c8aa53e05703b
```

**Session Queue Log**:

```
❯ kubectl logs selenium-session-queue-6776f58566-2q46f
2022-12-05 08:50:26,618 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-session-queue.conf" during parsing
2022-12-05 08:50:26,620 INFO RPC interface 'supervisor' initialized
2022-12-05 08:50:26,620 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:50:26,620 INFO supervisord started with pid 7
2022-12-05 08:50:27,623 INFO spawned: 'selenium-grid-session-queue' with pid 9
Starting Selenium Grid SessionQueue...
2022-12-05 08:50:27,634 INFO success: selenium-grid-session-queue entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:50:27.914 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:50:27.994 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
```

**Event Bus Log:**

```
2022-12-05 08:49:58,536 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-eventbus.conf" during parsing
2022-12-05 08:49:58,538 INFO RPC interface 'supervisor' initialized
2022-12-05 08:49:58,538 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:49:58,538 INFO supervisord started with pid 7
2022-12-05 08:49:59,540 INFO spawned: 'selenium-grid-eventbus' with pid 9
Starting Selenium Grid EventBus...
2022-12-05 08:49:59,546 INFO success: selenium-grid-eventbus entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:49:59.901 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:49:59.932 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.175.235:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://192.168.175.235:4443]
08:50:00.003 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.175.235:4442 and tcp://192.168.175.235:4443
08:50:00.032 INFO [UnboundZmqEventBus.<init>] - Sockets created
08:50:01.059 INFO [UnboundZmqEventBus.<init>] - Event bus ready
08:50:01.327 INFO [EventBusCommand.execute] - Started Selenium EventBus 4.6.0 (revision 79f1c02ae20): http://192.168.175.235:5557
```

**Session Map Logs:**

```
2022-12-05 08:50:15,763 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-sessions.conf" during parsing
2022-12-05 08:50:15,765 INFO RPC interface 'supervisor' initialized
2022-12-05 08:50:15,766 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:50:15,766 INFO supervisord started with pid 7
2022-12-05 08:50:16,769 INFO spawned: 'selenium-grid-sessions' with pid 9
Starting Selenium Grid Sessions...
2022-12-05 08:50:16,778 INFO success: selenium-grid-sessions entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:50:17.165 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:50:17.172 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
08:50:17.278 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-event-bus:4442 and tcp://selenium-event-bus:4443
08:50:17.338 INFO [UnboundZmqEventBus.<init>] - Sockets created
08:50:18.343 INFO [UnboundZmqEventBus.<init>] - Event bus ready
08:50:18.541 INFO [SessionMapServer.execute] - Started Selenium SessionMap 4.6.0 (revision 79f1c02ae20): http://192.168.128.126:5556
08:51:54.547 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 51906d5fa3f6061e4b6ef768a6f21671
08:54:07.781 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 28c938ed7495ed7987bd6f37987e6f96
10:18:14.643 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: ee4aae8083549875d08d46bef2c1a8c3
10:20:26.881 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: d7e01bf1f5ed8ca5070c8aa53e05703b
```                                                                                                                 
**Only router log is giving me error:** and all the pods are running fine/no restarts
```
2022-12-05 08:45:30,097 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-router.conf" during parsing
2022-12-05 08:45:30,100 INFO RPC interface 'supervisor' initialized
2022-12-05 08:45:30,100 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-05 08:45:30,100 INFO supervisord started with pid 7
2022-12-05 08:45:31,103 INFO spawned: 'selenium-grid-router' with pid 9
Starting Selenium Grid Router...
2022-12-05 08:45:31,106 INFO success: selenium-grid-router entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Tracing is disabled
08:45:31.432 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
08:45:31.437 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
08:45:32.323 INFO [RouterServer.execute] - Started Selenium Router 4.6.0 (revision 79f1c02ae20): http://192.168.175.198:4444
08:49:55.051 WARN [SimpleDataFetcherExceptionHandler.logException] - Exception while fetching data (/sessionsInfo) : java.net.ConnectException: Connection refused
java.io.UncheckedIOException: java.net.ConnectException: Connection refused
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:284)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.distributor.remote.RemoteDistributor.getStatus(RemoteDistributor.java:113)
        at org.openqa.selenium.grid.graphql.Grid.<init>(Grid.java:64)
        at org.openqa.selenium.grid.graphql.GridData.get(GridData.java:47)
        at org.openqa.selenium.grid.graphql.GridData.get(GridData.java:28)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:282)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59)
```


**One more observation:**
 In the session UI(selenium grid) I can see it loading the URL but then after sometime it timeout before entering the login credentials and I get the HTTP504 for the test.

**Comment by diemol** [comment]
`/sessionsInfo` failing means that the GraphQL endpoints cannot be accessed by the Router, which might be because the Router cannot reach the Distributor.

Aside of that, it seems the session is timing out, per the Node logs. I cannot say more because that is an extract from the logs.

**Comment by suadhika** [comment]
The node is hitting the application under test, the login page is opening ( extreamly  slow) and then it is getting timed out waiting for the client call.
So obviously the router is talking to the distributor and creating a session (**d7e01bf1f5ed8ca5070c8aa53e05703b**) which is getting stored in the session map as well. ( I get the delete message in log not the created msg).

Chrome node also says that the connection is trying to established eventually a HTTP 404, then it is stopping.
```
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 5467
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1670235494.913][SEVERE]: bind() failed: Cannot assign requested address (99)
10:18:15.199 INFO [LocalNode.newSession] - Session created by the Node. Id: d7e01bf1f5ed8ca5070c8aa53e05703b, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.5vHrei}, goog:chromeOptions: {debuggerAddress: localhost:33483}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:33483, se:cdpVersion: 107.0.5304.87, se:vncEnabled: true, se:vncLocalAddress: ws://192.168.161.159:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
10:18:46.844 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://192.168.161.159:7900
10:20:25.599 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "e684a377c71fe3620dd16d6b10ba59cf","eventTime": 1670235625598480977,"eventName": "HTTP request execution complete","attributes": {"http.client_ip": "192.168.5.0","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.168.161.159:5555","http.method": "GET","http.request_content_length": "0","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002fd7e01bf1f5ed8ca5070c8aa53e05703b\u002falert\u002ftext","http.user_agent": "selenium\u002f4.6.0 (java mac)"}}

10:20:26.879 INFO [SessionSlot.stop] - Stopping session d7e01bf1f5ed8ca5070c8aa53e05703b
```
finally from the session map also it is getting deleted.
```
10:20:26.881 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: d7e01bf1f5ed8ca5070c8aa53e05703b
```
The Event bus don't capture any logs which is strange, neither do the session queue(though the distributor log confirms that it is creating a session ).

Again since it is working on my local machine ( VPN network), I am pretty sure it is related to the network, but not sure how to resolve/debug the issue.

On Zalenium we used to add zalenium_http/zalenium_https and no_proxy details for Hub. Other than that I don't see any config change.

**Comment by diemol** [comment]
The Router does not talk to the Distributor directly for session creation. It talks to the SessionQueue and the Distributor queries the SessionQueue.

In any case
>The node is hitting the application under test, the login page is opening ( extreamly slow) and then it is getting timed out waiting for the client call.

That is where the issue starts, check the network settings between your cluster and the application under test.

**Comment by diemol** [comment]
Because the rest of the Grid is behaving fine, as per the logs show.

**Comment by suadhika** [comment]
Tried curl command from the chrome node to the application endpoint with  auth details and it worked absolutely fine without a delay. 
So networking is not the issue.
The router creates the session request in session queue, distributor pulls the info and create a session , stores sessionid:node info in session map. All of these are working fine. The browser opens and then the test terminates waiting for much longer time.
The client code is the same that used to run in zalenium. 

Can I start the selenium hub with my org proxy setting? I am using serenity and adding

serenity.proxy.http=
serenity.proxy.sslProxy=
serenity.proxy.noProxy=

properties add no value as seen below.

`{
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
      {
        "id": "beed7307-0b0e-4074-91bf-5867a68d48cf",
        "uri": "http:\u002f\u002f192.168.253.29:5555",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "4.15.0-42-generic"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.6.0 (revision 79f1c02ae20)",
        "slots": [
          {
            "id": {
              "hostId": "beed7307-0b0e-4074-91bf-5867a68d48cf",
              "id": "7e6e18a7-4042-448b-831a-c21b9646c15c"
            },
            "lastStarted": "2022-12-08T12:30:35.519159Z",
            "session": {
              "capabilities": {
                "acceptInsecureCerts": false,
                "browserName": "chrome",
                "browserVersion": "107.0.5304.87",
                "chrome": {
                  "chromedriverVersion": "107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs\u002fbranch-heads\u002f5304@{#942})",
                  "userDataDir": "\u002ftmp\u002f.com.google.Chrome.vO11am"
                },
                "goog:chromeOptions": {
                  "debuggerAddress": "localhost:42235"
                },
                "networkConnectionEnabled": false,
                "pageLoadStrategy": "normal",
                "platformName": "LINUX",
                "proxy": {
                },
                "se:bidiEnabled": false,
                "se:cdp": "ws:\u002f\u002f192.168.253.29:4444\u002fsession\u002fb522b7f41e8d1bf9b226589a80e68702\u002fse\u002fcdp",
                "se:cdpVersion": "107.0.5304.87",
                "se:vnc": "ws:\u002f\u002f192.168.253.29:4444\u002fsession\u002fb522b7f41e8d1bf9b226589a80e68702\u002fse\u002fvnc",
                "se:vncEnabled": true,
                "se:vncLocalAddress": "ws:\u002f\u002f192.168.253.29:7900",
                "setWindowRect": true,
                "strictFileInteractability": false,
                "timeouts": {
                  "implicit": 0,
                  "pageLoad": 300000,
                  "script": 30000
                },
                "unhandledPromptBehavior": "dismiss and notify",
                "webauthn:extension:credBlob": true,
                "webauthn:extension:largeBlob": true,
                "webauthn:virtualAuthenticators": true
              },
              "sessionId": "b522b7f41e8d1bf9b226589a80e68702",
              "start": "2022-12-08T12:30:35.519159Z",
              "stereotype": {
                "browserName": "chrome",
                "browserVersion": "107.0",
                "platformName": "LINUX",
                "se:noVncPort": 7900,
                "se:vncEnabled": true
              },
              "uri": "http:\u002f\u002f192.168.253.29:5555"
            },
            "stereotype": {
              "browserName": "chrome",
              "browserVersion": "107.0",
              "platformName": "LINUX",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      }
    ]
  }
}`

**Comment by suadhika** [comment]
I finally figured out on how to ADD PROXY DETAILS from client code ( using serenity : custom web driver extension). Now it is able to talk properly.
