### ISSUE TITLE
[🐛 Bug]:  Firefox does not seem to respect custom stereotype

### ISSUE THREAD

**Issue by indrekj** [SeleniumHQ/docker-selenium#1737]
### What happened?

I'm using `SE_NODE_STEREOTYPE` to set custom stereotypes. Examples:
* `{"browserName":"chrome","browserVersion":"latest"}`
* `{"browserName":"chrome","browserVersion":"beta"}`
* `{"browserName":"firefox","browserVersion":"latest"}`

Both chrome latest and beta work fine. But Firefox does not.

In the node-firefox logs I can see:
```
[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName":"firefox","browserVersion":"latest"}'
max-sessions = 1
```

That means that `stereotype` config is set.

If I remove the version matcher: `options.add_option(:browser_version, 'latest')` then it works fine. It also works fine if I don't change the stereotype and use the actual firefox version.

### Command used to start Selenium Grid with Docker

```shell
# We're building the whole thing dynamically so it's not easy to paste it here.
# But basically browsers are linked to hub and have arguments:
# --link=selenium-hub:hub
# --shm-size=1g
# 'SE_EVENT_BUS_HOST=hub'
# 'SE_EVENT_BUS_PUBLISH_PORT=4442'
# 'SE_EVENT_BUS_SUBSCRIBE_PORT=4443'
# "SE_NODE_STEREOTYPE=#{stereotype}"
```

### Relevant log output

```shell
2022-12-07 10:46:46,004 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2022-12-07 10:46:46,006 INFO RPC interface 'supervisor' initialized
2022-12-07 10:46:46,006 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-12-07 10:46:46,006 INFO supervisord started with pid 8
2022-12-07 10:46:47,008 INFO spawned: 'xvfb' with pid 10
2022-12-07 10:46:47,009 INFO spawned: 'vnc' with pid 11
2022-12-07 10:46:47,009 INFO spawned: 'novnc' with pid 12
2022-12-07 10:46:47,010 INFO spawned: 'selenium-node' with pid 13
2022-12-07 10:46:47,018 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Generating Selenium Config
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Setting up SE_NODE_GRID_URL...
Tracing is disabled
Selenium Grid Node configuration: 
[events]
publish = "tcp://hub:4442"
subscribe = "tcp://hub:4443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
drain-after-session-count = 0
max-sessions = 1

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName":"firefox","browserVersion":"latest"}'
max-sessions = 1

Starting Selenium Grid Node...
10:46:47.629 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
10:46:47.632 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:46:47.709 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://hub:4442 and tcp://hub:4443
10:46:47.738 INFO [UnboundZmqEventBus.<init>] - Sockets created
2022-12-07 10:46:48,021 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-07 10:46:48,021 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-12-07 10:46:48,021 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
10:46:48.740 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:46:48.807 INFO [NodeServer.createHandlers] - Reporting self as: http://172.17.0.6:5555
10:46:48.817 INFO [NodeOptions.getSessionFactories] - Detected 24 available processors
10:46:48.843 INFO [NodeOptions.report] - Adding firefox for {"browserVersion": "latest","se:noVncPort": 7900,"browserName": "firefox","platformName": "LINUX","se:vncEnabled": true} 1 times
10:46:48.850 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
10:46:48.967 INFO [NodeServer$1.start] - Starting registration process for Node http://172.17.0.6:5555
10:46:48.967 INFO [NodeServer.execute] - Started Selenium node 4.7.0 (revision 52e3a49ea2): http://172.17.0.6:5555
10:46:48.974 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:46:49.068 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
1670410012089	geckodriver	INFO	Listening on 127.0.0.1:5883
10:46:52.289 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities 
Host info: host: 'e04d3568cff7', ip: '172.17.0.6'
Build info: version: '4.7.0', revision: '52e3a49ea2'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '11.0.17'
Driver info: driver.version: unknown
10:46:52.341 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities 
Host info: host: 'e04d3568cff7', ip: '172.17.0.6'
Build info: version: '4.7.0', revision: '52e3a49ea2'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '11.0.17'
Driver info: driver.version: unknown
10:46:52.341 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities 
Host info: host: 'e04d3568cff7', ip: '172.17.0.6'
Build info: version: '4.7.0', revision: '52e3a49ea2'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:146)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:379)
	at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

10:46:52.342 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21723c271ee2f9ba8ddfa2fddc344f37","eventTime": 1670410012289887010,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:5883","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities \nHost info: host: 'e04d3568cff7', ip: '172.17.0.6'\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '11.0.17'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Unable to find a matching set of capabilities \nHost info: host: 'e04d3568cff7', ip: '172.17.0.6'\nBuild info: version: '4.7.0', revision: '52e3a49ea2'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-56-generic', java.version: '11.0.17'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:148)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:146)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:379)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"acceptInsecureCerts\": true,\"browserVersion\": \"latest\",\"se:noVncPort\": 7900,\"browserName\": \"firefox\",\"moz:firefoxOptions\": {\"args\": [  \"-headless\"  ],  \"profile\": \"UEsDBBQAAAAIANllh1XaKbKgLAEAAIsCAAAHAAAAdXNlci5qc4WSwWrDMAyG73uKkdMGi9O0tJTtNNixMBgbOwbFllsRxzaWk3RvPxXWS5etFyOJ75fk3x4YUxMT2ruiTWGSTHmcMrQR9qjQQ+vQFA+3Fhzj\\u002fdPN8JvnDCkPUR1CjyeV0AW0YciPrQPfFfMqKZlX\\u002f0neSF4vFPmcwsfb7n+1xzyF1CkNMdOIZQwpgysFGElf2ZdRD4nyl9Icf8h5sEdDoDyMtIcckoqYemKm4JUhPk\\u002fIabii45wQelYWOpwVnL04oJMZzzGymD9KxJ1iGPE9vBB3J0eoF2Or6PfSBo+50sx\\u002f+Cp2ehfAKBucwbQjztJgeQU2lE5jqtzHypIw4ViOxCTXKE1dr1ZrbRd2s62h3i5bA3rZwgo3di1Hc+5yudLlx2gmdFriZkhu5pm\\u002fAVBLAQI0AxQAAAAIANllh1XaKbKgLAEAAIsCAAAHAAAAAAAAAAEAAAC0gQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAFEBAAAAAA==\"  },  \"se:vncEnabled\": true  }\n"}}

10:46:52.343 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21723c271ee2f9ba8ddfa2fddc344f37","eventTime": 1670410012342346446,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: latest, moz:firefoxOptions: {args: [-headless], profile: UEsDBBQAAAAIANllh1XaKbKgLAE...}}","session.request.downstreamdialect": "[W3C]"}}
```

### Operating System

Ubuntu

### Docker Selenium version (tag)

node-firefox:latest (107.0.1), node-hub:latest (4.7.0)

**Comment by indrekj** [comment]
Also, I don't think this is a new issue. We tried to implement this some time ago with older versions and had the same problem. Again, only with firefox.

**Comment by cezzarez** [comment]
Looks like issue is still not solved.
@indrekj Did you maybe found out how to do that? Or this is just a bug for firefox?

In my case I am using different browser versions - customized. Whenever I add string type of browser version it just not work.
@diemol any news about that?

**Comment by diemol** [comment]
How can we reproduce that?

**Comment by cezzarez** [comment]
Hello!
Easy. Just set up environment variable to:
`SE_NODE_STEREOTYPE={"browserName":"firefox","browserVersion":"latest"}`
It will be registered as @indrekj mentioned.

Then you can just use curl to create a session:
`curl -m 60 -s -X POST \
     -H "Content-Type: application/json" \
     -d '{"desiredCapabilities":{"browserName":"firefox","browserVersion":'latest'}}' \
     ${HUB_URL}/wd/hub/session | jq -r ".sessionId"`
     
It will not set up a session.
But if you set up the version to for example 115.0 or just not set up the version it is going to work.

**Comment by diemol** [comment]
Can you share the whole command? I guess that's easy for you.

**Comment by diemol** [comment]
Also, that payload is wrong. Not W3C WebDriver compatible.

**Comment by cezzarez** [comment]
I've got a bit different setup, because I am using KEDA with Selenium Grid on k8s.
So in the deployment.yaml env variables I am setting up the SE_NODE_STEREOTYPE with a similar value I sent to you.

In my case then there is a hub and nodes scaled on demand.

Also I found out one more thing. For versions 111.0 the curl works, but for newer (I am using 115) it does not. I mean something happen, but capabilities are empty on the Selenium Hub (in the queue).

I cannot pass the java code to run those commands unfortunately.
Will try to prepare something tomorrow.

Anyway, I tested once again, and looks like whenever I change the browserVersion in the stereotype (even to just a different number - like instead of 111.0 to 112.0, there is no possibility to run the node.

So I assume that we just cannot change the browserVersion in stereotype, because it is just not working after that.

**Comment by cezzarez** [comment]
So to summarize and be clear.
You can set up the `SE_NODE_STEREOTYPE` with `browserVersion` parameter. But this parameter cannot be different than the actual version of the firefox.
So if the firefox version is `116.0` you can't change that to the different value, because it will just not work.

**Comment by diemol** [comment]
Hard to assume something when there is not a way to reproduce the issue. Would be easier if you share a way to reproduce that using the docker images.

**Comment by cezzarez** [comment]
> Hard to assume something when there is not a way to reproduce the issue. Would be easier if you share a way to reproduce that using the docker images.

Will prepare tomorrow. Thanks!

**Comment by cezzarez** [comment]
@diemol 
Ok, as I promised there is a full simple setup which can show you chrome with changes SE_NODE_STEREOTYPE value works, but firefox does not.

1. First create a Selenium Grid setup (Hub + Chrome with changed SE_NODE_STEREOTYPE + Original Firefox + Firefox with changed SE_NODE_STEREOTYPE)
```
#!/bin/bash

# Create a grid network
docker network create grid

# Setup selenium hub
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.8.3-20230404

# Setup original firefox (no changes for SE_NODE_STEREOTYPE)
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
       --shm-size="2g" \
       -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
       -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
       selenium/node-firefox:4.8.3-20230404

# Setup changes firefox (changes for SE_NODE_STEREOTYPE)
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
       --shm-size="2g" \
       -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
       -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
       -e SE_NODE_STEREOTYPE="{\"browserName\":\"firefox\",\"browserVersion\":\"latest1\",\"platformName\": \"Linux\"}" \
       selenium/node-firefox:4.8.3-20230404

# Setup changes chrome (changes for SE_NODE_STEREOTYPE)
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
       --shm-size="2g" \
       -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
       -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
       -e SE_NODE_STEREOTYPE="{\"browserName\":\"chrome\",\"browserVersion\":\"latest1\",\"platformName\": \"Linux\"}" \
       selenium/node-chrome:4.8.3-20230404
```

2. Now on localhost:4444 you can see there are 3 nodes, and you can even see the versions of them.

3. Run test for chrome with provided browserVersion:
```
#!/bin/bash

###################################################
# Test for chrome with changes SE_NODE_STEREOTYPE
###################################################

HUB_URL="http://localhost:4444"

set -xo pipefail
shopt -s lastpipe

SESSION_ID=$(curl -m 60 -s -X POST \
     -H "Content-Type: application/json" \
     -d '{"desiredCapabilities":{"browserName":"chrome","browserVersion":"latest1"}}' \
     ${HUB_URL}/wd/hub/session | jq -r ".sessionId")

if (( $? != 0 )) || [[ ! "$SESSION_ID" =~ [a-z0-9]{5,50} ]]; then
  echo error on creating session, exiting abnormally
  exit 1
fi

echo $SESSION_ID

sleep 20

curl -s -X DELETE ${HUB_URL}/wd/hub/session/${SESSION_ID}
```

4. Do the same for firefox with browserVersion provided:
```
#!/bin/bash

####################################################
# Test for firefox with changes SE_NODE_STEREOTYPE
####################################################

HUB_URL="http://localhost:4444/"

set -xo pipefail
shopt -s lastpipe

SESSION_ID=$(curl -m 60 -s -X POST \
     -H "Content-Type: application/json" \
     -d '{"desiredCapabilities":{"browserName":"firefox","browserVersion":"latest1"}}' \
     ${HUB_URL}/wd/hub/session | jq -r ".sessionId")

if (( $? != 0 )) || [[ ! "$SESSION_ID" =~ [a-z0-9]{5,50} ]]; then
  echo error on creating session, exiting abnormally
  exit 1
fi

echo $SESSION_ID

sleep 20

curl -s -X DELETE ${HUB_URL}/wd/hub/session/${SESSION_ID}
```

5. You can see if you change the browserVersion to the original value it is going to work, to do that:
```
#!/bin/bash

#######################################################
# Test for firefox without changed SE_NODE_STEREOTYPE
#######################################################

HUB_URL="http://localhost:4444"

set -xo pipefail
shopt -s lastpipe

SESSION_ID=$(curl -m 60 -s -X POST \
     -H "Content-Type: application/json" \
     -d '{"desiredCapabilities":{"browserName":"firefox","browserVersion":"111.0"}}' \
     ${HUB_URL}/wd/hub/session | jq -r ".sessionId")

if (( $? != 0 )) || [[ ! "$SESSION_ID" =~ [a-z0-9]{5,50} ]]; then
  echo error on creating session, exiting abnormally
  exit 1
fi

echo $SESSION_ID

sleep 20

curl -s -X DELETE ${HUB_URL}/wd/hub/session/${SESSION_ID}
```


I was using version 4.8.3 because with this version curl works fine.
But on the k8s with KEDA the problem is the same for newer versions.

**Comment by diemol** [comment]
We cannot fix things in such an old image. What happens when you use the latest images?

**Comment by cezzarez** [comment]
The same. This is just a showcase for the version which works with curl.
Newer version as I mention has the same problem.

**Comment by cezzarez** [comment]
Basically if you know how to construct the curl for newer versions you can use the same scripts. Just change the curl command and docker images version.

**Comment by cezzarez** [comment]
@diemol Did you maybe have a moment to take a look?

**Comment by diemol** [comment]
Yes. It works. I tried it with Firefox Standalone:

```
docker run -p 4444:4444 --shm-size="2g" \
  -e SE_NODE_STEREOTYPE="{\"browserName\":\"firefox\",\"browserVersion\":\"latest1\",\"platformName\": \"Linux\"}" \
  selenium/standalone-firefox:4.15.0-20231129
```

Then, I used this payload:
```
curl -XPOST --header "Content-Type: application/json; charset=utf-8" http://localhost:4444/session -d '{"capabilities": {"alwaysMatch": {"browserName": "firefox1", "browserVersion": "latest1"}}}'
```

Notice that the payload you are using is not W3C WebDriver compliant, which means the Grid does not recognize it.
