### ISSUE TITLE
[🐛 Bug]: Dynamic grid failing to run tests

### ISSUE THREAD

**Issue by lharriespipe** [SeleniumHQ/docker-selenium#1741]
### What happened?

I've using the code from https://github.com/SeleniumHQ/docker-selenium#execution-with-docker-compose and can see it works with 4.5.0-20221004 but not 4.6.0-20221104 or 4.7.1-20221208 

The error I get when requesting a new browser is a new container is created but is left in a warning state with no log output.

The logs from the dynamic node show it as unable to create the session

### Command used to start Selenium Grid with Docker

```shell
https://github.com/SeleniumHQ/docker-selenium#execution-with-docker-compose
```

### Relevant log output

```shell
2022-12-09 16:43:09 16:43:09.924 INFO [Container.<init>] - Created container b2cccb01f845b0f75c41b38918819d396c6ceb7e46b80ec11642347e5751514f
2022-12-09 16:43:09 16:43:09.925 INFO [Container.start] - Starting container b2cccb01f845b0f75c41b38918819d396c6ceb7e46b80ec11642347e5751514f
2022-12-09 16:43:09 16:43:09.927 WARN [SessionSlot.apply] - Unable to create session
2022-12-09 16:43:09 java.lang.IllegalArgumentException: non-positive contentLength: 0
2022-12-09 16:43:09     at java.net.http/java.net.http.HttpRequest$BodyPublishers.fromPublisher(HttpRequest.java:539)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.notChunkingBodyPublisher(JdkHttpMessages.java:124)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.createRequest(JdkHttpMessages.java:76)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:280)
2022-12-09 16:43:09     at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
2022-12-09 16:43:09     at org.openqa.selenium.docker.v1_41.StartContainer.apply(StartContainer.java:40)
2022-12-09 16:43:09     at org.openqa.selenium.docker.v1_41.V141Docker.startContainer(V141Docker.java:115)
2022-12-09 16:43:09     at org.openqa.selenium.docker.Container.start(Container.java:47)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:155)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.docker.DockerSessionFactory.apply(DockerSessionFactory.java:90)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:372)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
2022-12-09 16:43:09     at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
2022-12-09 16:43:09     at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
2022-12-09 16:43:09     at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
2022-12-09 16:43:09     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
2022-12-09 16:43:09     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
2022-12-09 16:43:09     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2022-12-09 16:43:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
2022-12-09 16:43:09     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
2022-12-09 16:43:09     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-12-09 16:43:09     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-12-09 16:43:09     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-12-09 16:43:09     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-12-09 16:43:09     at java.base/java.lang.Thread.run(Thread.java:829)
2022-12-09 16:43:09 16:43:09.929 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "c224e714a4becafdabb98654782050c6","eventTime": 1670604189928545663,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {browserName: chrome, goog:chromeOptions: {}}","session.request.downstreamdialect": "[W3C]"}}
2022-12-09 16:43:09
```

### Operating System

Windows 10

### Docker Selenium version (tag)

4.7.1-20221208

**Comment by diemol** [comment]
This is fixed by https://github.com/SeleniumHQ/selenium/pull/11417. We will do a release early next week.
