### ISSUE TITLE
[🐛 Bug]: Selenium tests in queue are failing when a node in docker selenium grid is not available to execute the script.

### ISSUE THREAD

**Issue by chandupranayp** [SeleniumHQ/docker-selenium#1769]
### What happened?

When I up when 1 docker chrome/edge node and execute two parallel selenium tests. The first test which picked the node in selenium grid will run without any sessions. The second test will go into queue and waits for 60 seconds after which the test will fail with the WebDriverTimeout execution.

Exception: OpenQA.Selenium.WebDriverTimeoutException: java.net.http.HttpTimeoutException: request timed out Build info: version: '4.7.2', revision: '4d4020c3b7' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17' Driver info: driver.version: unknown at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout) 

I updated RemoteWebDriver by overriding the default wait which is 60 seconds to 3600 seconds and noticed that now the scripts are failing exactly after 300 seconds. I need to keep the test in queue until the node becomes free to execute the next test.
driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), options.ToCapabilities(),TimeSpan.FromSeconds(3600)); 
I also updated the docker-compose.yml file by overriding the below environment variables
      - SE_SESSION_REQUEST_TIMEOUT=3600 
      - SE_NODE_SESSION_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=2

### Command used to start Selenium Grid with Docker

```shell
Below is my complete docker-compose file for reference
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-full-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-full-grid.yml down`
version: "3"
services:
  selenium-event-bus:
    #image: selenium/event-bus:4.2.1-20220531
    image: selenium/event-bus
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"
    environment:
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000
      - SE_SESSION_REQUEST_TIMEOUT=3600      

  selenium-sessions:
    #image: selenium/sessions:4.2.1-20220531
    image: selenium/sessions
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-session-queue:
    #image: selenium/session-queue:4.2.1-20220531
    image: selenium/session-queue
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_REQUEST_TIMEOUT=3600 #Bhanu added
      - SE_SESSION_RETRY_INTERVAL=2

  selenium-distributor:
    #image: selenium/distributor:4.2.1-20220531
    image: selenium/distributor
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  selenium-router:
    #image: selenium/router:4.2.1-20220531
    image: selenium/router
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  chrome:
    #image: selenium/node-chrome:4.2.1-20220531
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SESSION_REQUEST_TIMEOUT=3600 #Bhanu added
      - SE_NODE_SESSION_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=2

  chrome_video:
    #image: selenium/video:ffmpeg-4.3.1-20220609
    image: selenium/video:ffmpeg-4.3.1-20220609
    volumes:
      #- /tmp/videos:/videos
      - C:/Users/EX_BMiryala/temp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4    

  edge:
    #image: selenium/node-edge:4.2.1-20220531
    image: selenium/node-edge
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SESSION_REQUEST_TIMEOUT=3600 #Bhanu added
      - SE_NODE_SESSION_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=2

  firefox:
    #image: selenium/node-firefox:4.2.1-20220531
    image: selenium/node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SESSION_REQUEST_TIMEOUT=3600 #Bhanu added
      - SE_NODE_SESSION_TIMEOUT=3600
      - SE_SESSION_RETRY_INTERVAL=2
```

### Relevant log output

```shell
Exception: OpenQA.Selenium.WebDriverTimeoutException: java.net.http.HttpTimeoutException: request timed out Build info: version: '4.7.2', revision: '4d4020c3b7' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17' Driver info: driver.version: unknown at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
```

### Operating System

OS Arch: amd64  OS Name: Linux  OS Version: 5.10.16.3-microsoft-standard-WSL2

### Docker Selenium version (tag)

Grid version: 4.7.2

**Comment by diemol** [comment]
I do not understand what the issue is. Could you please clarify after describing your scenario? Please also provide a way to reproduce the issue (with test scrips, avoiding narratives). Note that the docker-compose file you provide has environment variables in the wrong places or that are not valid for the images. Check the example we provide https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-full-grid.yml

**Comment by chandupranayp** [comment]
Step 1) I have created one chrome node with the docker compose file provided https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-full-grid.yml 
Step 2) Created two tests as below 

```
        [TestMethod]
        public void TestCase1() { 
            LoginPage login = new LoginPage();
            login.validategit();
        }

        [TestMethod]
        public void TestCase2() { 
            LoginPage login = new LoginPage();
            login. validategit();
        }

public void validategit()
        {
            try
            {
                
                ChromeOptions options = new ChromeOptions();
driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), options.ToCapabilities(), TimeSpan.FromSeconds(3600));
                Thread.Sleep(5000);
                driver.Manage().Window.Maximize();
                driver.Navigate().GoToUrl("https://github.com/");
                Thread.Sleep(5000);

                for (int i=0;i<=10000;i++)
                {
                    try
                    {
                        if (driver.FindElement(By.XPath("//a[contains(text(),'Pull')]")).Displayed)
                        {
                            Thread.Sleep(90000);
                        }
                    }
                    catch (NoSuchElementException ex)
                    {
    
                    }
                }           

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                throw e;
            }
        }
```

Step 3)  Triggered both the tests in parallel and each of these tests are expected to run more than 5 minutes 
Step 4) Since we only have 1 chrome node available in grid. TestCase1() will start the execution in available chrome node and TestCase2() will wait in queue.


**Expected behavior:** TestCase2() should wait in queue and continue the execution after TestCase1() is completed.
**Actual behavior:** TestCase2() waits only for 5 mins and then fails with the below exception:

```
  Message: 
    Test method TestProject.TestCase.TestCase1 threw exception: 
    OpenQA.Selenium.WebDriverTimeoutException: java.net.http.HttpTimeoutException: request timed out
    Build info: version: '4.7.2', revision: '4d4020c3b7'
    System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
    Driver info: driver.version: unknown
```

Standard Output: 

```
OpenQA.Selenium.WebDriverTimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
Driver info: driver.version: unknown
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at ProjectInfrastructure.LoginPage.Login1() in C:\NBFC\DCTestFrameworkSelenium - Copy\ProjectInfrastructure\LoginPage.cs:line 67
```

Docker Console log:

```
dockerconfig-chrome-1   | Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 12576
dockerconfig-chrome-1   | Only local connections are allowed.
dockerconfig-chrome-1   | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keepin[1673482613.463][SEVERE]: bind() failed: Cannot assign requested address (99)
dockerconfig-chrome-1   | g ChromeDriver safe.
dockerconfig-chrome-1   | ChromeDriver was started successfully.
dockerconfig-chrome-1   | 00:16:55.474 INFO [LocalNode.newSession] - Session created by the Node. Id: 206201d9332617834e8339c5d3be530e, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.124, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.JqSDK2}, goog:chromeOptions: {debuggerAddress: localhost:43541}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:43541, se:cdpVersion: 108.0.5359.124, se:vncEnabled: true, se:vncLocalAddress: ws://172.21.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
selenium-distributor    | 00:16:56.062 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 206201d9332617834e8339c5d3be530e
selenium-distributor    |  Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.124, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.JqSDK2}, goog:chromeOptions: {debuggerAddress: localhost:43541}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.21.0.5:4444/sessio..., se:cdpVersion: 108.0.5359.124, se:vnc: ws://172.21.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.21.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
selenium-router         | 00:21:53.233 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
selenium-router         | Build info: version: '4.7.2', revision: '4d4020c3b7'
selenium-router         | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-router         | Driver info: driver.version: unknown
selenium-router         | org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
selenium-router         | Build info: version: '4.7.2', revision: '4d4020c3b7'
selenium-router         | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-router         | Driver info: driver.version: unknown
selenium-router         |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:294)
selenium-router         |       at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
selenium-router         |       at org.openqa.selenium.grid.security.AddSecretFilter.lambda$apply$0(AddSecretFilter.java:40)
selenium-router         |       at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueue.addToQueue(RemoteNewSessionQueue.java:99)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0(NewSessionQueue.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute(NewSessionQueue.java:122)
selenium-router         |       at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
selenium-router         |       at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
selenium-router         |       at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium-router         |       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
selenium-router         |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
selenium-router         |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-router         |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-router         |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-router         | Caused by: java.net.http.HttpTimeoutException: request timed out
selenium-router         |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
selenium-router         |       at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
selenium-router         |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:292)
selenium-router         |       ... 36 more
selenium-router         | 00:21:53.236 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
selenium-router         | Build info: version: '4.7.2', revision: '4d4020c3b7'
selenium-router         | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-router         | Driver info: driver.version: unknown
selenium-router         | 00:21:53.237 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
selenium-router         | Build info: version: '4.7.2', revision: '4d4020c3b7'
selenium-router         | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'
selenium-router         | Driver info: driver.version: unknown
selenium-router         |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:294)
selenium-router         |       at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
selenium-router         |       at org.openqa.selenium.grid.security.AddSecretFilter.lambda$apply$0(AddSecretFilter.java:40)
selenium-router         |       at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueue.addToQueue(RemoteNewSessionQueue.java:99)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0(NewSessionQueue.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute(NewSessionQueue.java:122)
selenium-router         |       at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
selenium-router         |       at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-router         |       at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
selenium-router         |       at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium-router         |       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
selenium-router         |       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
selenium-router         |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-router         |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-router         |       at java.base/java.lang.Thread.run(Thread.java:829)
selenium-router         | Caused by: java.net.http.HttpTimeoutException: request timed out
selenium-router         |       at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)
selenium-router         |       at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
selenium-router         |       at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:292)
selenium-router         |       ... 36 more
selenium-router         |
selenium-router         | 00:21:53.238 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "554283b0eefd309d8e3d1c49a8cee2f4","eventTime": 1673482913231871800,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.7.2', revision: '4d4020c3b7'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.7.2', revision: '4d4020c3b7'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.17'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:294)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.security.AddSecretFilter.lambda$apply$0(AddSecretFilter.java:40)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueue.addToQueue(RemoteNewSessionQueue.java:99)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0(NewSessionQueue.java:68)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute(NewSessionQueue.java:122)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: java.net.http.HttpTimeoutException: request timed out\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:559)\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:292)\n\t... 36 more\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "82","http.scheme": "HTTP","http.target": "\u002fsession","http.user_agent": "selenium\u002f4.0.0 (.net windows)"}}
selenium-router         |
dockerconfig-chrome-1   | 00:25:48.851 INFO [LocalNode.stopTimedOutSession] - Session id 206201d9332617834e8339c5d3be530e timed out, stopping...
dockerconfig-chrome-1   | 00:25:48.984 INFO [SessionSlot.stop] - Stopping session 206201d9332617834e8339c5d3be530e
selenium-distributor    | 00:25:48.986 INFO [GridModel.release] - Releasing slot for session id 206201d9332617834e8339c5d3be530e
selenium-sessions       | 00:25:48.989 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 206201d9332617834e8339c5d3be530e
```

**Comment by diemol** [comment]
Waiting for 5 minutes in the queue and then timing out is the expected behavior. Please check https://github.com/SeleniumHQ/docker-selenium#session-request-timeout
