### ISSUE TITLE
[🐛 Bug]: Long running POST-request throws UnreachableBrowserException after 50 seconds using Chrome on Selenium-Grid running on Kubernetes

### ISSUE THREAD

**Issue by thomas-wasilewski** [SeleniumHQ/docker-selenium#1793]
### What happened?

I'm using Selenium-Grid Helm-Chart Version 0.14.3 (https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid) on Kubernetes with default configuration values.

I have a test case, where I execute a long-running POST-request (it generates a report and offers it for download) using Chrome.
When the post-request is running longer than 50 seconds, I get the following exception after (nearly exactly) 50 seconds (difference between the first two timestamps in the following exception log) everytime (!):
```
2023-02-17 17:37:16,429 DEBUG d.h.s.b.h.CommandExecutor:160  -   [webElement.click()]
2023-02-17 17:38:06,579 ERROR d.h.s.b.h.ScreenshotOnExceptionHandler:26   - Exception occured!
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [b61e3834694e3d48657515076739817a, clickElement {id=8dc03979-8107-43e3-bd82-d50ab5e0d0a8}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.124, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.ntVrkO}, goog:chromeOptions: {debuggerAddress: localhost:33185}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://10.42.20.43:4444/sessi..., se:cdpVersion: 108.0.5359.124, se:vnc: ws://10.42.20.43:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://10.42.20.43:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 600000, pageLoad: 600000, script: 600000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[RemoteWebDriver: chrome on LINUX (b61e3834694e3d48657515076739817a)] -> id: FORM_REPORT:BUTTON_REPORT]
Session ID: b61e3834694e3d48657515076739817a
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:78) ~[selenium-remote-driver-4.7.2.jar:?]
	at d.h.s.b.h.CommandExecutor.click(CommandExecutor.java:161) ~[SeleniumHelper-2.1.108-tests.jar:?]
	at d.h.s.b.h.CommandExecutor.click(CommandExecutor.java:128) ~[SeleniumHelper-2.1.108-tests.jar:?]
	at d.h.m.s.p.ReportingPage.click(ReportingPage.java:54) ~[test-classes/:?]
	at d.h.m.s.t.s.ReportsIT.testReport(ReportsIT.java:59) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628) ~[junit-platform-commons-1.4.2.jar:1.4.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68) ~[junit-jupiter-engine-5.4.2.jar:5.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229) ~[junit-platform-launcher-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197) ~[junit-platform-launcher-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211) [junit-platform-launcher-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191) [junit-platform-launcher-1.4.2.jar:1.4.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) [junit-platform-launcher-1.4.2.jar:1.4.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57) [junit5-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) [junit-rt.jar:?]
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42) ~[selenium-http-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.7.2.jar:?]
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:181) ~[selenium-remote-driver-4.7.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535) ~[selenium-remote-driver-4.7.2.jar:?]
	... 59 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
	at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source) ~[async-http-client-2.12.3.jar:?]
```

When I run the test on a local Chrome browser, everything works as desired:
```
2023-02-17 18:03:34,504 DEBUG d.h.s.b.h.CommandExecutor:160  -   [webElement.click()]
2023-02-17 18:04:52,627 DEBUG d.h.s.b.h.CommandExecutor:486  -   [webElement.click() finished] 
[...]
```

I have tried to set several timeout-switches to a higher value (> 50 seconds), but it had no effect:
```
driver.manage().timeouts().implicitlyWait(Duration.ofMinutes(10));
driver.manage().timeouts().pageLoadTimeout(Duration.ofMinutes(10));
driver.manage().timeouts().scriptTimeout(Duration.ofMinutes(10));
```

Only setting the `pageLoadTimeout` to a value < 50 seconds produced another Exception (as expected using 49 seconds):
```
2023-02-16 19:24:25 DEBUG d.h.s.b.h.CommandExecutor:160  -   [webElement.click()]
2023-02-16 19:25:14 ERROR d.h.s.b.h.ScreenshotOnExceptionHandler:26   - Exception occured!
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 49.000
  (Session info: chrome=108.0.5359.124)
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [23e0d4136b19d507d84f7f7387ca0957, clickElement {id=261a47a6-1641-4d60-a93b-28875371a08b}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.124, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.COgKKx}, goog:chromeOptions: {debuggerAddress: localhost:45901}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://10.42.5.6:4444/session..., se:cdpVersion: 108.0.5359.124, se:vnc: ws://10.42.5.6:4444/session..., se:vncEnabled: true, se:vncLocalAddress: ws://10.42.5.6:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 600000, pageLoad: 600000, script: 600000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

The logs on the Kubernetes-Cluster on the Chrome-node show the following output when I use a ``pageLoadTimeout`` of more than 50 seconds (51 seconds in the following example):
```
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 5709
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1676571997.608][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
ChromeDriver was started successfully.
[1676571997.994][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
19:26:38.185 INFO [LocalNode.newSession] - Session created by the Node. Id: b2f56d46f9fce8aa2bb355d17d4a8c6e, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.124, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: /tmp/.com.google.Chrome.nExOyb}, goog:chromeOptions: {debuggerAddress: localhost:42591}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:42591, se:cdpVersion: 108.0.5359.124, se:vncEnabled: true, se:vncLocalAddress: ws://10.42.14.97:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 181000, pageLoad: 182000, script: 180000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
[1676572059.230][SEVERE]: Timed out receiving message from renderer: 51.000
[1676572059.236][SEVERE]: Timed out receiving message from renderer: 51.000
19:27:39.240 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "b4ff29a298728aef47912819d410442b","eventTime": 1676572059240441745,"eventName": "HTTP request execution complete","attributes": {"http.client_ip": "159.4.114.17","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "10.42.14.97:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fb2f56d46f9fce8aa2bb355d17d4a8c6e\u002felement\u002f88fcb116-440f-4537-a7a7-7331d0e84826\u002fclick","http.user_agent": "selenium\u002f4.7.2 (java windows)"}}
19:27:40.103 INFO [SessionSlot.stop] - Stopping session b2f56d46f9fce8aa2bb355d17d4a8c6e 
```

My conclusion:
Running the test locally generates no error, so I think the selenium-grid/chrome-driver are the problem?

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid current -n selenium-grid --debug
```

### Relevant log output

```shell
See section "what happened"
```

### Operating System

Ubuntu 20.04 (Rancher 2.6.8 on Kubernetes v1.21.12)

### Docker Selenium version (tag)

4.7.2-20221219

**Comment by jamesmortensen** [comment]
@TomekWa Thank you for reporting the issue.  I'm wondering what happens if you start selenium/standalone-chrome and then VNC into the container via http://localhost:7900 and then attempt to execute the POST request manually, independent of Selenium and Chromedriver.  Is the problem Selenium/Chromedriver or something else in the Linux environment?  

To clarify the environment you're running on, are you on a Windows host using Rancher Desktop to create the Kubernetes environment?  If we eliminate Kubernetes and just execute your test on standalone-chrome, do we still see this issue?  

I think you could start a standalone-chrome container with this, depending on how Rancher is configured:
```
$ docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome:latest
```

**Comment by thomas-wasilewski** [comment]
@jamesmortensen Thank you for your answer!

> @TomekWa Thank you for reporting the issue. I'm wondering what happens if you start selenium/standalone-chrome and then VNC into the container via http://localhost:7900 and then attempt to execute the POST request manually, independent of Selenium and Chromedriver. Is the problem Selenium/Chromedriver or something else in the Linux environment?
> 
> To clarify the environment you're running on, are you on a Windows host using Rancher Desktop to create the Kubernetes environment? If we eliminate Kubernetes and just execute your test on standalone-chrome, do we still see this issue?

We are running Rancher and Kubernetes on Ubuntu 20.04, I have added the information to the ticket.

> 
> I think you could start a standalone-chrome container with this, depending on how Rancher is configured:
> 
> ```
> $ docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome:latest
> ```

I started the container as described, VNC into the container via http://localhost:7900/ and executed the POST request in our application. The POST requested lasted longer than 50 seconds and was successful...

**Comment by thomas-wasilewski** [comment]
I started a local selenium-grid:
```
docker network create grid
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.7.2-20221219
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome:4.7.2-20221219
```

After that I ran the test case on the local grid and everything worked as expected!

Checking the logs on Rancher I noticed that the "Execute Shell" and "View Logs" tabs on Rancher change from "connected" to "disconnected" after 50 seconds, so this seems to be the cause of the problem.

I will dig further into that issue and keep you updated.

**Comment by diemol** [comment]
If it works with the setup @jamesmortensen suggested and not in Kubernetes then it implies something is wrong in that environment. Not much to do on the docker selenium side. Perhaps you can do the same with the container in Kubernetes?

We'll leave this issue open for a few days so you can leave more info but I guess we will end up closing it.

**Comment by diemol** [comment]
Closing since there was no more information.

**Comment by thomas-wasilewski** [comment]
fyi:

It was a problem with the nginx ingress-controller (I had to increase the value for `nginx.ingress.kubernetes.io/proxy-read-timeout`, the default is 60 seconds) and the haproxy (I had to increase the value for `timeout server`, the default ist 50 (!) seconds) we are using.

Thanks for the support and hints!

**Comment by diemol** [comment]
Thanks for sharing, @thomas-wasilewski!
