### ISSUE TITLE
[🐛 Bug]: Grid Queue size becomes double when nodes are busy

### ISSUE THREAD

**Issue by ShivaNaga4570** [SeleniumHQ/docker-selenium#1796]
### What happened?

We are running automation test cases in GRID, when all the nodes are busy, queue doubles and finally fails with 

Failed to invoke configuration method setupDriver:Could not start a new session. Unable to parse remote response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:130)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)

My Questions are as follows

1. How to disable the retry in Queue if a session is not found?
2. How to increase the Queue Wait time until the node is free

### Command used to start Selenium Grid with Docker

```shell
NA
```

### Relevant log output

```shell
NA
```

### Operating System

Linux

### Docker Selenium version (tag)

4.8.0-20230210

**Comment by ShivaNaga4570** [comment]
Here are my configurations. Do you think any thing that needs to be added here for more timeout in queue

<img width="546" alt="Screenshot 2023-02-21 at 3 51 26 PM" src="https://user-images.githubusercontent.com/125970302/220318439-55ebc244-9a97-4ca9-9bf1-709c58dc275c.png">
