### ISSUE TITLE
[🐛 Bug]: Can't run tests on dynamic selenium grid 4 using different VMs

### ISSUE THREAD

**Issue by PinhoL** [SeleniumHQ/docker-selenium#1826]
### What happened?

Hey,

Right now I've a distributed selenium grid on dfferent VMs working just fine. Now I'm trying to move to the dynamic grid, but I'm having problems when I run the tests against it.
I'm starting my hub like this:
```
docker run -p 4442-4444:4442-4444 selenium/hub:4.8.3-20230404
```
Log:
```
2023-04-13 15:54:50,008 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2023-04-13 15:54:50,012 INFO RPC interface 'supervisor' initialized
2023-04-13 15:54:50,013 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-04-13 15:54:50,013 INFO supervisord started with pid 8
2023-04-13 15:54:51,016 INFO spawned: 'selenium-grid-hub' with pid 10
Tracing is disabled
2023-04-13 15:54:51,025 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
15:54:51.529 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:54:51.535 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:54:51.673 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.17.0.3:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.17.0.3:4443]
15:54:51.759 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.17.0.3:4442 and tcp://172.17.0.3:4443
15:54:51.788 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:54:52.790 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:54:53.628 INFO [Hub.execute] - Started Selenium Hub 4.8.3 (revision b19b418e60): http://172.17.0.3:4444
```

Regarding my Node running in another VM:
```
docker run --net=host -p 5555:5555 \
    -e SE_EVENT_BUS_HOST=<IP-VM1> \
    -e SE_NODE_GRID_URL=http://<IP-VM1>:4444 \
    -e SE_NODE_HOST=<IP-VM2> \
    -e SE_NODE_PORT=5555 \
    -e START_XVFB=false \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v ${PWD}/assets:/opt/selenium/assets \
    -v /var/run/docker.sock:/var/run/docker.sock \
    selenium/node-docker:4.8.3-20230404
```
Which gets me to this point:
```
2023-04-13 16:00:23,247 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
2023-04-13 16:00:23,252 INFO RPC interface 'supervisor' initialized
2023-04-13 16:00:23,252 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-04-13 16:00:23,252 INFO supervisord started with pid 9
2023-04-13 16:00:24,255 INFO spawned: 'socat' with pid 11
2023-04-13 16:00:24,258 INFO spawned: 'selenium-grid-docker' with pid 12
2023-04-13 16:00:24,265 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-04-13 16:00:24,265 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Starting Selenium Grid Node Docker...
Appending Grid url: http://<IP-VM1>:4444
Tracing is disabled
16:00:24.788 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:00:24.794 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:00:24.956 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://<IP-VM1>:4442 and tcp://<IP-VM1>:4443
16:00:25.046 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:00:26.049 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:00:26.188 INFO [NodeServer.createHandlers] - Reporting self as: http://<IP-VM2>:4444
16:00:26.211 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
16:00:26.667 INFO [V141Docker.isContainerPresent] - Checking if container is present: <IP-VM2>
16:00:26.677 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.8.3-20230404
16:00:26.679 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.8.3-20230404', digest='null'}
16:00:26.712 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20230404
16:00:26.713 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='ffmpeg-4.3.1-20230404', digest='null'}
16:00:26.726 INFO [Docker.getImage] - Obtaining image: selenium/video:ffmpeg-4.3.1-20230404
16:00:26.727 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/video', tag='ffmpeg-4.3.1-20230404', digest='null'}
16:00:26.741 INFO [Docker.getImage] - Obtaining image: selenium/standalone-chrome:4.8.3-20230404
16:00:26.741 INFO [V141Docker.getImage] - Listing local images: Reference{domain='docker.io', name='selenium/standalone-chrome', tag='4.8.3-20230404', digest='null'}
16:00:26.757 INFO [DockerOptions.lambda$getDockerSessionFactories$1] - Mapping Capabilities {browserName: chrome} to docker image selenium/standalone-chrome:4.8.3-20230404 2 times
16:00:26.777 INFO [Node.<init>] - Binding additional locator mechanisms: relative
16:00:27.030 INFO [NodeServer$1.start] - Starting registration process for Node http://<IP-VM2>:4444
16:00:27.031 INFO [NodeServer.execute] - Started Selenium node 4.8.3 (revision b19b418e60): http://<IP-VM2>:4444
16:00:27.046 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
16:00:27.240 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
```

I can access to IP-VM1:444 and see that my node has been added successfully. Until this point, everything is the same as my previous setup (I start the chrome image directly instead of the node-docker on this dynamic case).

My `config.toml` file looks like this:
```
[docker]
 configs = [
     "selenium/standalone-chrome:4.8.3-20230404", '{"browserName": "chrome"}'
         ]
         url = "http://127.0.0.1:2375"
         video-image = "selenium/video:ffmpeg-4.3.1-20230404"
         assets-path= "/opt/selenium/assets" #if this is not here I've a "assets path is mandatory" error

         [server]
         host = "IP-VM2"
         port = "4444"
[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
max-sessions = 2
```

When I try to run the tests (I'm using webdriverIO, they run just fine on my other selenium grid setup) I've the following error:

`HUB:`
```
16:00:48.784 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-web-security, --auto-open-devtools-for-tabs], mobileEmulation: {deviceName: iPhone 6}}}]
16:00:53.904 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 96ebc87665f305c3b8d2b0c0b480c695
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.Jtc6Vn}, goog:chromeOptions: {debuggerAddress: localhost:46211}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://<IP-VM1>..., se:cdpVersion: 111.0.5563.146, se:forwardCdp: ws://172.17.0.2:12927/sessi..., se:vnc: ws://<IP-VM1>..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
16:00:54.443 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:131)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
16:00:55.198 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
```

`NODE:`
```
16:00:48.822 INFO [DockerSessionFactory.apply] - Starting session for Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-web-security, --auto-open-devtools-for-tabs], mobileEmulation: {deviceName: iPhone 6}}}
16:00:48.825 INFO [DockerSessionFactory.apply] - Creating container, mapping container port 4444 to 12927
16:00:48.892 INFO [Container.<init>] - Created container c420e10891655677ec86c28bb8f58e82651e2b92f6d769b24fb17704f66fafec
16:00:48.893 INFO [Container.start] - Starting container c420e10891655677ec86c28bb8f58e82651e2b92f6d769b24fb17704f66fafec
16:00:49.237 INFO [Container.inspect] - Inspecting container c420e10891655677ec86c28bb8f58e82651e2b92f6d769b24fb17704f66fafec
16:00:49.250 INFO [DockerSessionFactory.apply] - Waiting for server to start (container id: c420e10891655677ec86c28bb8f58e82651e2b92f6d769b24fb17704f66fafec, url http://127.0.0.1:12927/wd/hub)
16:00:52.498 INFO [DockerSessionFactory.apply] - Server is ready (container id: c420e10891655677ec86c28bb8f58e82651e2b92f6d769b24fb17704f66fafec)
16:00:53.881 INFO [LocalNode.newSession] - Session created by the Node. Id: 96ebc87665f305c3b8d2b0c0b480c695, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.Jtc6Vn}, goog:chromeOptions: {debuggerAddress: localhost:46211}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://<IP-VM1>..., se:cdpVersion: 111.0.5563.146, se:forwardCdp: ws://172.17.0.2:12927/sessi..., se:vnc: ws://<IP-VM1>..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
16:00:54.406 INFO [ProxyNodeWebsockets.apply] - Found endpoint where CDP connection needs to be forwarded
16:00:54.407 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://172.17.0.2:12927/session/96ebc87665f305c3b8d2b0c0b480c695/se/fwd
16:00:54.424 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:131)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
16:00:54.436 INFO [ProxyNodeWebsockets.apply] - Found endpoint where CDP connection needs to be forwarded
16:00:54.436 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://172.17.0.2:12927/session/96ebc87665f305c3b8d2b0c0b480c695/se/fwd
16:00:54.442 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:131)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I've tried a little bit of everything when it comes to flags (as it seems that it might be related to the way CDP is propagated from the node-docker to the child containers?) but with no luck, maybe this flag is indeed not being propagated?

### Command used to start Selenium Grid with Docker

```shell
docker run -p 4442-4444:4442-4444 selenium/hub:4.8.3-20230404

docker run --net=host -p 5555:5555 \
    -e SE_EVENT_BUS_HOST=<IP-VM1> \
    -e SE_NODE_GRID_URL=http://<IP-VM1>:4444 \
    -e SE_NODE_HOST=<IP-VM2> \
    -e SE_NODE_PORT=5555 \
    -e START_XVFB=false \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v ${PWD}/assets:/opt/selenium/assets \
    -v /var/run/docker.sock:/var/run/docker.sock \
    selenium/node-docker:4.8.3-20230404
```

### Relevant log output

```shell
NA
```

### Operating System

CentOS 7

### Docker Selenium version (tag)

4.8.3-20230404

**Comment by PinhoL** [comment]
Seems like a test runner (WDIO) issue when connecting to the websocket, closing this for now
