### ISSUE TITLE
[🐛 Bug]: Docker fails to kill containers under high load

### ISSUE THREAD

**Issue by DydyII** [SeleniumHQ/docker-selenium#1830]
### What happened?

Using version 4.8.3 of selenium/node-docker container and selenium grid, Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-146-generic x86_64)

With a high load (in our case, there are 100 parallel containers/sessions), after 10-15 minutes, the docker starts to get dumb and fall off according to the default timeout of 10 seconds when trying to kill containers:

Apr 19 11:59:43 srv06377 dockerd[33841]: time="2023-04-19T11:59:43.980407954Z" level=error msg="Container failed to exit within 10s of kill - trying direct SIGKILL" container=82e58732e70fa9dd242747967c88a384b6e241c9a8ff9a51f51726b13021f412 error="context deadline exceeded"

Apr 19 1159:38 srv06377 dockerd[33841]: time="2023-04-19T11:59:38.023229398Z" level=error msg="error killing container: context deadline exceeded" container=633fd2579e60039974f40d17664cf99e786d151871a23477ed513a2d224e3146 error="tried to kill container, but did not receive an exit event"

And container has only one process:
docker top 7204f5af2ec9
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
1200                2455652             2451068             0                   12:20               ?                   00:00:02            /usr/bin/fluxbox -display :99.0

What could be the problem? At the same time, the processor is enough (112 CPUs)

When running 40 parallel sessions, this problem was not observed.
Also in the tests there is a delay in waiting for the browser to close up to 2 minutes.

### Command used to start Selenium Grid with Docker

```shell
docker-compose.yml:

# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-full-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-full-grid.yml down`
version: "3"
networks:
  selenium-grid-net:
    driver: bridge
    ipam:
      config:
        - subnet: ***.***.***.***/**
services:
  selenium-event-bus:
    image: selenium/event-bus:4.8.3
    container_name: selenium-event-bus
    networks:
      - selenium-grid-net
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"

  selenium-sessions:
    image: selenium/sessions:4.8.3
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    networks:
      - selenium-grid-net
    environment:
      - SE_JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-session-queue:
    image: selenium/session-queue:4.8.3
    container_name: selenium-session-queue
    networks:
      - selenium-grid-net
    ports:
      - "5559:5559"

  selenium-distributor:
    image: selenium/distributor:4.8.3
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    networks:
      - selenium-grid-net
    environment:
      - SE_JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  selenium-router:
    image: selenium/router:4.8.3
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    networks:
      - selenium-grid-net
    environment:
      - SE_JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  node-docker:
    image: selenium/node-docker:4.8.3
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-event-bus
    networks:
      - selenium-grid-net
    environment:
      - SE_JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=****
      - SE_OPTS=--override-max-sessions true --max-sessions 54 --enable-managed-downloads true
      - SE_NODE_PORT=5555
      - SE_VNC_NO_PASSWORD=1
      - SE_SESSION_REQUEST_TIMEOUT=5400

  node-docker2:
    image: selenium/node-docker:4.8.3
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-event-bus
    networks:
      - selenium-grid-net
    environment:
      - SE_JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=****
      - SE_OPTS=--override-max-sessions true --max-sessions 54 --enable-managed-downloads true
      - SE_NODE_PORT=5555
      - SE_VNC_NO_PASSWORD=1
      - SE_SESSION_REQUEST_TIMEOUT=5400


config.toml:
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-chrome:4.8.3", "{\"browserName\": \"chrome\", \"se:downloadsEnabled\": \"true\"}"
    ]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted
# If var/run/docker.sock is not mounted:
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://127.0.0.1:2375"

# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20230210"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

### Relevant log output

```shell
08:39:52.317 WARN [Container.stop] - Unable to stop container: Unable to stop container: 2d13158bf2857fc02c5b2bbdc4fea60ce1074e80b28da2531dc716e2177477c0
cannot stop container: 2d13158bf2857fc02c5b2bbdc4fea60ce1074e80b28da2531dc716e2177477c0: tried to kill container, but did not receive an exit event
org.openqa.selenium.docker.DockerException: Unable to stop container: 2d13158bf2857fc02c5b2bbdc4fea60ce1074e80b28da2531dc716e2177477c0
cannot stop container: 2d13158bf2857fc02c5b2bbdc4fea60ce1074e80b28da2531dc716e2177477c0: tried to kill container, but did not receive an exit event
        at org.openqa.selenium.docker.v1_41.DockerMessages.throwIfNecessary(DockerMessages.java:59)
        at org.openqa.selenium.docker.v1_41.StopContainer.apply(StopContainer.java:49)
        at org.openqa.selenium.docker.v1_41.V141Docker.stopContainer(V141Docker.java:125)
        at org.openqa.selenium.docker.Container.stop(Container.java:57)
        at org.openqa.selenium.grid.node.docker.DockerSession.stop(DockerSession.java:70)
        at org.openqa.selenium.grid.node.local.SessionSlot.stop(SessionSlot.java:111)
        at org.openqa.selenium.grid.node.local.LocalNode.stopTimedOutSession(LocalNode.java:285)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1814)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3467)
        at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3443)
        at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:3077)
        at com.google.common.cache.LocalCache.remove(LocalCache.java:4251)
        at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4891)
        at org.openqa.selenium.grid.node.local.LocalNode.stop(LocalNode.java:706)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:585)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:255)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-146-generic x86_64)

### Docker Selenium version (tag)

4.8.3

**Comment by DydyII** [comment]
On version 4.9.0 is also reproduced

**Comment by diemol** [comment]
> On version 4.9.0 is also reproduced

Well, we did not make changes in this area of the code, so it makes sense the behavior is the same.

However, aside of wrapping the exception and trying again, and eventually throwing the exception again, there is not much we can do. The message in the log is a `WARN`, because the Selenium code tells the Docker daemon to stop the container, but probably because of the load, the daemon cannot stop it soon enough. 

Also, we recommend 1CPU and and 1GB RAM per browser container, and if you are recording video, add 1CPU more per container. Sometimes applications under test use more than 1CPU at a given time. 

What I recommend is to measure CPU/RAM/Disk on the host so you know what were the resources used when this `WARN` happens.

I'll leave this open for a while in case you have more comments, thanks!

**Comment by diemol** [comment]
Closing this as there is not much we can do when this warning shows up.
