### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Response code 500. Message: Could not start a new session. Unable to parse: {

### ISSUE THREAD

**Issue by ketanb02** [SeleniumHQ/docker-selenium#1844]
### What happened?

After upgrading docker node-chrome to v112 or v113 and running the test scripts,  we are getting error

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Unable to parse: {
  "metadata": {
  },
  "desiredCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--remote-allow-origins=*"
      ],
      "extensions": [
      ]
    }
  },
  "downstreamDialects": [
    "OSS",
    "W3C"
  ]
}

### Command used to start Selenium Grid with Docker

```shell
podman-compose -f chromenode.yml up -d
```

### Relevant log output

```shell
When checked the node-chrome logs seeing error - 

WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.json.JsonException: Unable to parse: {
  "metadata": {
  },
  "desiredCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--remote-allow-origins=*"
      ],
      "extensions": [
      ]
    }
  },
  "downstreamDialects": [
    "OSS",
    "W3C"
  ]
}
        at org.openqa.selenium.json.Json.toType(Json.java:57)
        at org.openqa.selenium.json.Json.toType(Json.java:50)
        at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:49)
        at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:255)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.grid.data.CreateSessionRequest
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.18'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:61)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
        at org.openqa.selenium.json.Json.toType(Json.java:71)
        at org.openqa.selenium.json.Json.toType(Json.java:55)
        ... 23 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:59)
        ... 27 more
Caused by: org.openqa.selenium.json.JsonException: Unable to find matching enum value for OSS in class org.openqa.selenium.remote.Dialect
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.18'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.EnumCoercer.lambda$apply$0(EnumCoercer.java:49)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
        at org.openqa.selenium.json.CollectionCoercer.lambda$apply$0(CollectionCoercer.java:64)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.openqa.selenium.json.CollectionCoercer.lambda$apply$1(CollectionCoercer.java:65)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
        at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
        at org.openqa.selenium.grid.data.CreateSessionRequest.fromJson(CreateSessionRequest.java:77)
        ... 32 more
```

### Operating System

Linux

### Docker Selenium version (tag)

4.9.1-20230508

**Comment by ketanb02** [comment]
The same automated scripts is working fine for node-chrome v111 and below

**Comment by diemol** [comment]
In [Selenium 4.9.0](https://www.selenium.dev/blog/2023/selenium-4-9-0-released/) we removed JWP support completely, it is something we have announced a [while ago](https://www.selenium.dev/blog/2022/legacy-protocol-support/). 

You need to send a W3C WebDriver payload to get it working.

**Comment by ketanb02** [comment]
I am using W3C payload only, i am not using desired capabilities

		 ChromeOptions chromeOptions = new ChromeOptions();
		 
		 chromeOptions.setPlatformName("LINUX");
		 chromeOptions.setBrowserVersion("113.0");
		 
		 driver = new RemoteWebDriver(new URL(gsg), chromeOptions);

Is the above one correct ?

Could you please reopen this ?

**Comment by diemol** [comment]
Are you using version 4.9.0 or higher on the code above?

**Comment by ketanb02** [comment]
Getting below error with 4.9.0 on code

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by diemol** [comment]
Make sure you are setting the shm memory. If you have more questions, I will leave some links below.

**Comment by ketanb02** [comment]
@diemol , i am setting shm memory to 2gb. If you referring below value in .yml, i am setting it to 2gb - still seeing the error

 shm_size: 2gb
 ports:
      - 5555:5555
    restart: always

**Comment by ketanb02** [comment]
@diemol , Any advise on this ?

**Comment by diemol** [comment]
Please create a new issue and share how to reproduce this.
