### ISSUE TITLE
[🐛 Bug]: After upgrade to 4.10.0 - Firefox is not working with platformName: Linux or any

### ISSUE THREAD

**Issue by ketanb02** [SeleniumHQ/docker-selenium#1873]
### What happened?

After upgrade to 4.10.0, when I run my test with firefox options and add platformName as Linux or ANY - it throws error. 
If I put platformName as Windows or "" - it works fine. 

This issue is only happening for Firefox. Chrome and Edge are working fine with all combination of platformName. 

This issue was not happening with Selenium Grid v4.5.0

Could you please check why this discrepancies ?

### Command used to start Selenium Grid with Docker

```shell
Firefox Not Working code -

FirefoxOptions options = new FirefoxOptions();
options.setPlatformName("LINUX");
driver = new RemoteWebDriver(new URL(hub), options);

FirefoxOptions options = new FirefoxOptions();
options.setPlatformName("ANY");
driver = new RemoteWebDriver(new URL(hub), options);

Firefox Working code -

FirefoxOptions options = new FirefoxOptions();
options.setPlatformName("WINDOWS");
driver = new RemoteWebDriver(new URL(hub), options);

FirefoxOptions options = new FirefoxOptions();
options.setPlatformName("");
driver = new RemoteWebDriver(new URL(hub), options);
```

### Relevant log output

```shell
Jun 21, 2023 10:52:44 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 

Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: LINUX}]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: LINUX}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
```

### Operating System

Linux

### Docker Selenium version (tag)

4.10.0-20230607

**Comment by diemol** [comment]
You either need to use the latest Selenium version on the client side or send the platform name as lower case.

**Comment by ketanb02** [comment]
Its the same with lower case and newer selenium version at client side

Jun 21, 2023 11:07:55 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 

Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: linux}]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: linux}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:134)

**Comment by ketanb02** [comment]
FirefoxOptions options = new FirefoxOptions();
options.setPlatformName("linux");

**Comment by ketanb02** [comment]
@diemol , i see you closed this - do i need to raise new one now or will this be picked up ?

**Comment by diemol** [comment]
Please share how the Grid is being started and the logs after it starts, also what you get from the `/status` endpoint.

**Comment by ketanb02** [comment]
Thank you for reopening!

**P.S. The issue is only in Firefox with platformName Linux or ANY. PlatformName Windows or "" is working fine for Firefox**

**Grid is started via the below compose -** 

**Hub.yml**

```
version: "3"
services:

 selenium-hub:
    environment:
      - SE_OPTS=--https-certificate /home/seluser/abc.pem --https-private-key /home/seluser/abc.key --registration-secret XXX
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    privileged: true
    extra_hosts:
      - "ServerName:ServerIP"
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    volumes:
      - /opt/certs:/home/seluser
    restart: always
```

**Node.yml**

```
version: "3"
services:

 ff_Container1:
    environment:
      - SE_EVENT_BUS_HOST=<HUBSERVER>
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - REMOTE_HOST=https://${HOSTNAME}:6161
      - SE_NODE_HOST=<NODESERVER>
      - SE_NODE_PORT=6161
      - SE_OPTS=--https-certificate /home/seluser/abc.pem --https-private-key /home/seluser/abc.key --registration-secret XXX
    image: selenium/node-firefox:114.0
    container_name: selenium-node
    shm_size: 2gb
    privileged: true
    ports:
      - 6161:6161
    restart: always
    volumes:
      - /opt/node/certs:/home/seluser
```

**Status endpoint** 

```
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
```

Let me know if you need more details.

**Comment by diemol** [comment]
What about the logs?

**Comment by ketanb02** [comment]
Hub log after running in firefox with linux

```
9:29:51.490 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: linux}]
09:29:51.716 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "aff371fc89175eb14bcca7862cfd591b","eventTime": 1687339791490077026,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: linux}]"}}

 

09:29:51.716 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1

 

Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
09:29:51.716 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1

 

Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '11.0.19'
Driver info: driver.version: unknown
        at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:151)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by diemol** [comment]
No, I need to see the log when the Hub starts and the Nodes get registered. Also the output from the `/session` endpoint when Hub and Nodes are up.

**Comment by ketanb02** [comment]
2023-06-21 10:50:47,631 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
10:50:48.281 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
10:50:48.286 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:50:48.388 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://<ip>:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://<ip>:4443]
10:50:48.451 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://<ip>:4442 and tcp://<ip>:4443
10:50:48.478 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:50:49.479 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:50:50.329 INFO [Hub.execute] - Started Selenium Hub 4.10.0 (revision c14d967899): https://<ip>:4444

10:51:27.009 INFO [Node.<init>] - Binding additional locator mechanisms: relative
10:51:27.056 INFO [GridModel.setAvailability] - Switching Node ea51cbf5-b566-4c34-aaa3-756a3b9a23e6 (uri: https://<server>:5151) from DOWN to UP
10:51:27.056 INFO [LocalDistributor.add] - Added node ea51cbf5-b566-4c34-aaa3-756a3b9a23e6 at https://<server>:5151. Health check every 120s
10:51:27.829 INFO [Node.<init>] - Binding additional locator mechanisms: relative


Is this okay ?

**Comment by diemol** [comment]
Missing the Nodes logs and the status endpoint

**Comment by ketanb02** [comment]
**Node logs**

```
11:39:47.631 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:39:47.731 INFO [NodeServer.createHandlers] - Reporting self as: https://<ip>:5151
11:39:47.747 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
11:39:47.748 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 16 concurrent sessions. Session stability and reliability might suffer!
11:39:47.748 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
11:39:47.748 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
11:39:47.748 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
11:39:47.792 INFO [NodeOptions.report] - Adding firefox for {"browserName": "firefox","browserVersion": "114","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times (Host)
11:39:47.808 INFO [Node.<init>] - Binding additional locator mechanisms: relative
11:39:48.188 INFO [NodeServer$1.start] - Starting registration process for Node https://<ip>:5151
11:39:48.189 INFO [NodeServer.execute] - Started Selenium node 4.10.0 (revision c14d967899): https://<ip>:5252
11:39:48.198 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:39:48.520 INFO [NodeServer.lambda$createHandlers$2] - Node has been added

```

**/status endpoint**

```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "<id>",
        "uri": "https:\u002f\u002f<ip>:5151",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "4.18.0-425.19.2.el8_7.x86_64"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.10.0 (revision c14d967899)",
        "slots": [
          {
            "id": {
              "hostId": "<id>",
              "id": "<id>"
            },
            "lastStarted": "1970-01-01T00:00:00Z",
            "session": null,
            "stereotype": {
              "browserName": "firefox",
              "browserVersion": "114",
              "platformName": "linux",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      },
```

**Comment by diemol** [comment]
I cannot reproduce this at all.

My status endpoint:
```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "3aae4fee-26a1-4ddd-a848-38053b41aa68",
        "uri": "http:\u002f\u002f172.19.0.3:5555",
        "maxSessions": 1,
        "osInfo": {
          "arch": "amd64",
          "name": "Linux",
          "version": "6.1.27-060127-generic"
        },
        "heartbeatPeriod": 60000,
        "availability": "UP",
        "version": "4.10.0 (revision c14d967899)",
        "slots": [
          {
            "id": {
              "hostId": "3aae4fee-26a1-4ddd-a848-38053b41aa68",
              "id": "69c09902-730d-4179-93df-b2125633c502"
            },
            "lastStarted": "2023-06-21T12:02:12.672755Z",
            "session": null,
            "stereotype": {
              "browserName": "firefox",
              "browserVersion": "114.0",
              "platformName": "linux",
              "se:noVncPort": 7900,
              "se:vncEnabled": true
            }
          }
        ]
      }
    ]
  }
}
```

![image](https://github.com/SeleniumHQ/docker-selenium/assets/5992658/50670f99-4f4e-43e6-8fd1-a8fd6f817cda)

Code in Java using 4.10.0

```java
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;

public class IssueDocker1873 {

  public static void main (String[] args) throws MalformedURLException {
    String url = "https://4444-seleniumhq-dockerseleni-2a6k3r2mxc0.ws-eu100.gitpod.io";
    FirefoxOptions options = new FirefoxOptions();
    options.setPlatformName("linux");

    RemoteWebDriver webDriver = new RemoteWebDriver(new URL(url), options);
    webDriver.get("https://selenium.dev");
    webDriver.quit();
  }

}
```

Full logs

```
gitpod /workspace/docker-selenium (diemol/bug-after-upgrade-to-firefox-1873) $ docker-compose -f docker-compose-v3.yml up
[+] Building 0.0s (0/0)                                                                                                                                                                       
WARN[0000] Found orphan containers ([docker-selenium-edge-1 docker-selenium-chrome-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 3/2
 ✔ Network docker-selenium_default      Created                                                                                                                                          0.1s 
 ✔ Container selenium-hub               Created                                                                                                                                          0.0s 
 ✔ Container docker-selenium-firefox-1  Created                                                                                                                                          0.0s 
Attaching to docker-selenium-firefox-1, selenium-hub
selenium-hub               | 2023-06-21 12:01:52,498 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub               | 2023-06-21 12:01:52,501 INFO RPC interface 'supervisor' initialized
selenium-hub               | 2023-06-21 12:01:52,501 CRIT Server 'unix_http_server' running without any HTTP authentication checking
selenium-hub               | 2023-06-21 12:01:52,501 INFO supervisord started with pid 116
docker-selenium-firefox-1  | 2023-06-21 12:01:53,039 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
docker-selenium-firefox-1  | 2023-06-21 12:01:53,042 INFO RPC interface 'supervisor' initialized
docker-selenium-firefox-1  | 2023-06-21 12:01:53,042 CRIT Server 'unix_http_server' running without any HTTP authentication checking
docker-selenium-firefox-1  | 2023-06-21 12:01:53,042 INFO supervisord started with pid 116
selenium-hub               | 2023-06-21 12:01:53,503 INFO spawned: 'selenium-grid-hub' with pid 118
selenium-hub               | Tracing is disabled
selenium-hub               | 2023-06-21 12:01:53,507 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub               | 12:01:54.022 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub               | 12:01:54.026 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
docker-selenium-firefox-1  | 2023-06-21 12:01:54,073 INFO spawned: 'xvfb' with pid 118
docker-selenium-firefox-1  | 2023-06-21 12:01:54,075 INFO spawned: 'vnc' with pid 119
docker-selenium-firefox-1  | 2023-06-21 12:01:54,076 INFO spawned: 'novnc' with pid 120
docker-selenium-firefox-1  | 2023-06-21 12:01:54,078 INFO spawned: 'selenium-node' with pid 121
docker-selenium-firefox-1  | 2023-06-21 12:01:54,089 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub               | 12:01:54.307 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.19.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.19.0.2:4443]
selenium-hub               | 12:01:54.482 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.19.0.2:4442 and tcp://172.19.0.2:4443
docker-selenium-firefox-1  | Generating Selenium Config
docker-selenium-firefox-1  | Configuring server...
docker-selenium-firefox-1  | Setting up SE_NODE_HOST...
docker-selenium-firefox-1  | Setting up SE_NODE_PORT...
docker-selenium-firefox-1  | Setting up SE_NODE_GRID_URL...
selenium-hub               | 12:01:54.574 INFO [UnboundZmqEventBus.<init>] - Sockets created
docker-selenium-firefox-1  | Tracing is disabled
docker-selenium-firefox-1  | Selenium Grid Node configuration: 
docker-selenium-firefox-1  | [events]
docker-selenium-firefox-1  | publish = "tcp://selenium-hub:4442"
docker-selenium-firefox-1  | subscribe = "tcp://selenium-hub:4443"
docker-selenium-firefox-1  | 
docker-selenium-firefox-1  | [node]
docker-selenium-firefox-1  | session-timeout = "300"
docker-selenium-firefox-1  | override-max-sessions = false
docker-selenium-firefox-1  | detect-drivers = false
docker-selenium-firefox-1  | drain-after-session-count = 0
docker-selenium-firefox-1  | max-sessions = 1
docker-selenium-firefox-1  | 
docker-selenium-firefox-1  | [[node.driver-configuration]]
docker-selenium-firefox-1  | display-name = "firefox"
docker-selenium-firefox-1  | stereotype = '{"browserName": "firefox", "browserVersion": "114.0", "platformName": "Linux"}'
docker-selenium-firefox-1  | max-sessions = 1
docker-selenium-firefox-1  | 
docker-selenium-firefox-1  | Starting Selenium Grid Node...
docker-selenium-firefox-1  | 2023-06-21 12:01:55,093 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
docker-selenium-firefox-1  | 2023-06-21 12:01:55,094 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
docker-selenium-firefox-1  | 2023-06-21 12:01:55,094 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
docker-selenium-firefox-1  | 12:01:55.225 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
docker-selenium-firefox-1  | 12:01:55.275 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
docker-selenium-firefox-1  | 12:01:55.420 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
docker-selenium-firefox-1  | 12:01:55.484 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub               | 12:01:55.575 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub               | 12:01:56.379 INFO [Hub.execute] - Started Selenium Hub 4.10.0 (revision c14d967899): http://172.19.0.2:4444
docker-selenium-firefox-1  | 12:01:56.486 INFO [UnboundZmqEventBus.<init>] - Event bus ready
docker-selenium-firefox-1  | 12:01:56.587 INFO [NodeServer.createHandlers] - Reporting self as: http://172.19.0.3:5555
docker-selenium-firefox-1  | 12:01:56.602 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
docker-selenium-firefox-1  | 12:01:56.638 INFO [NodeOptions.report] - Adding firefox for {"browserName": "firefox","browserVersion": "114.0","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times (Host)
docker-selenium-firefox-1  | 12:01:56.650 INFO [Node.<init>] - Binding additional locator mechanisms: relative
docker-selenium-firefox-1  | 12:01:56.842 INFO [NodeServer$1.start] - Starting registration process for Node http://172.19.0.3:5555
docker-selenium-firefox-1  | 12:01:56.843 INFO [NodeServer.execute] - Started Selenium node 4.10.0 (revision c14d967899): http://172.19.0.3:5555
docker-selenium-firefox-1  | 12:01:56.851 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
selenium-hub               | 12:01:56.883 INFO [Node.<init>] - Binding additional locator mechanisms: relative
selenium-hub               | 12:01:57.466 INFO [GridModel.setAvailability] - Switching Node 3aae4fee-26a1-4ddd-a848-38053b41aa68 (uri: http://172.19.0.3:5555) from DOWN to UP
selenium-hub               | 12:01:57.466 INFO [LocalDistributor.add] - Added node 3aae4fee-26a1-4ddd-a848-38053b41aa68 at http://172.19.0.3:5555. Health check every 120s
docker-selenium-firefox-1  | 12:01:57.473 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
selenium-hub               | 12:02:10.786 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
selenium-hub               |  [Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, platformName: linux}]
docker-selenium-firefox-1  | 12:02:10.839 INFO [DriverService$Builder.getLogOutput] - Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
docker-selenium-firefox-1  | 12:02:12.673 INFO [LocalNode.newSession] - Session created by the Node. Id: 127dfe50-c212-40ba-b20a-bef687d4c222, Caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 114.0, moz:accessibilityChecks: false, moz:buildID: 20230601151220, moz:debuggerAddress: 127.0.0.1:17698, moz:firefoxOptions: {}, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 6.1.27-060127-generic, moz:processID: 267, moz:profile: /tmp/rust_mozprofileztZMyB, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidi: ws://172.19.0.3:4444/sessio..., se:cdp: ws://172.19.0.3:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.19.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.19.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
selenium-hub               | 12:02:12.691 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 127dfe50-c212-40ba-b20a-bef687d4c222 
selenium-hub               |  Caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 114.0, moz:accessibilityChecks: false, moz:buildID: 20230601151220, moz:debuggerAddress: 127.0.0.1:17698, moz:firefoxOptions: {}, moz:geckodriverVersion: 0.33.0, moz:headless: false, moz:platformVersion: 6.1.27-060127-generic, moz:processID: 267, moz:profile: /tmp/rust_mozprofileztZMyB, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidi: ws://172.19.0.3:4444/sessio..., se:cdp: ws://172.19.0.3:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.19.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.19.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
docker-selenium-firefox-1  | 12:02:14.824 INFO [SessionSlot.stop] - Stopping session 127dfe50-c212-40ba-b20a-bef687d4c222
docker-selenium-firefox-1  | 12:02:14.825 WARN [LocalNode.lambda$new$5] - Removing Downloads folder associated with 127dfe50-c212-40ba-b20a-bef687d4c222
docker-selenium-firefox-1  | 12:02:14.826 WARN [LocalNode.lambda$new$6] - Removing Uploads folder associated with 127dfe50-c212-40ba-b20a-bef687d4c222
selenium-hub               | 12:02:14.827 INFO [GridModel.release] - Releasing slot for session id 127dfe50-c212-40ba-b20a-bef687d4c222
selenium-hub               | 12:02:14.828 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 127dfe50-c212-40ba-b20a-bef687d4c222
```

**Comment by diemol** [comment]
And this is the docker-compose file

```yml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  firefox:
    image: selenium/node-firefox:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Comment by ketanb02** [comment]
strange, can you please share the toml you are using for firefox? i will try the exact.. above details are exactly same for me as well..

**Comment by ketanb02** [comment]
i debugged it more and found that - if i use firefox node which is connected to hub with http protocol  -- it works...

But my firefox node is connected to hub with https - hence its not working. I have created the image based on your input - https://github.com/SeleniumHQ/docker-selenium/issues/1814

Do you have any idea, what can be the issue? I have updated the cacert inside the container with cert to support https between hub and node but thats breaking the firefox though the other browsers are working fine ?

**Comment by diemol** [comment]
I would need to see how the image is built. For example, a different OS is reported and the dates look strange on yours.

**Comment by ketanb02** [comment]
This is working now, able to fix in https as well. Thank you for your time!

**Comment by diemol** [comment]
What was the issue?

**Comment by ketanb02** [comment]
As per the https://github.com/SeleniumHQ/docker-selenium/issues/1814, to establish https connection between hub and node - I need to build image for node Firefox but seems this is breaking the firefox or its driver and hence session is not getting invoked.

But if i use vanilla node Firefox image and pass the cert details using SE_OPTS, its working fine and attaching to hub as https.

So, I am assuming that cacerts file changes while building image is somehow impacting Firefox driver to invoke the session causing error "Could not start a new session. Error while creating session with the driver service"
