### ISSUE TITLE
[🐛 Bug]: What happene   Why can't connect to devtools

### ISSUE THREAD

**Issue by bcvb2001** [SeleniumHQ/docker-selenium#1885]
### What happened?

I try to start this container, but it keeps prompting that I cannot connect to devtools. I can use it normally on my PC, but when I pull the image again and start the container on my linux, it prompts that it cannot be used. How can I solve it?

### Command used to start Selenium Grid with Docker

```shell
docker run -d -p 34444:4444 -p 37900:7900 -p 35900:5900 -e SE_NODE_GRID_URL="http://localhost:4444/" -e SE_NODE_MAX_SESSIONS=100 -e SE_NODE_SESSION_TIMEOUT=300 -e SE_NODE_OVERRIDE_MAX_SESSIONS=true  --name selenium --restart=always --shm-size="4g" selenium/standalone-chrome:latest
```

### Relevant log output

```shell
[momosa@MoMoSaTNAS ~]# docker logs -f 991324615a39c31b568a7e6b002c5353f890010d3f01580fd4f729760d0efdfb
2023-07-10 11:48:51,799 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2023-07-10 11:48:51,875 INFO RPC interface 'supervisor' initialized
2023-07-10 11:48:51,875 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-07-10 11:48:51,875 INFO supervisord started with pid 8
2023-07-10 11:48:52,878 INFO spawned: 'xvfb' with pid 10
2023-07-10 11:48:52,879 INFO spawned: 'vnc' with pid 11
2023-07-10 11:48:52,881 INFO spawned: 'novnc' with pid 12
2023-07-10 11:48:52,883 INFO spawned: 'selenium-standalone' with pid 13
2023-07-10 11:48:53,044 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-07-10 11:48:53,044 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-07-10 11:48:53,044 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-07-10 11:48:53,044 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Selenium Grid Standalone configuration:
[network]
relax-checks = true

[node]
grid-url = "http://localhost:4444/"
session-timeout = "300"
override-max-sessions = true
detect-drivers = false
drain-after-session-count = 0
max-sessions = 100

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "114.0", "platformName": "Linux"}'
max-sessions = 100

Starting Selenium Grid Standalone...
Tracing is disabled
11:48:57.888 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:48:57.920 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:48:58.517 WARN [HostIdentifier.resolveHostAddress] - Failed to resolve host address
java.net.UnknownHostException: 991324615a39: 991324615a39: Temporary failure in name resolution
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1670)
        at org.openqa.selenium.net.HostIdentifier.resolveHostAddress(HostIdentifier.java:104)
        at org.openqa.selenium.net.HostIdentifier.getHostAddress(HostIdentifier.java:123)
        at org.openqa.selenium.net.DefaultNetworkInterfaceProvider.<init>(DefaultNetworkInterfaceProvider.java:54)
        at org.openqa.selenium.net.NetworkUtils.<init>(NetworkUtils.java:48)
        at org.openqa.selenium.grid.server.BaseServerOptions.lambda$getExternalUri$0(BaseServerOptions.java:93)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at org.openqa.selenium.grid.server.BaseServerOptions.getExternalUri(BaseServerOptions.java:90)
        at org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:129)
        at org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:47)
        at org.openqa.selenium.grid.commands.Standalone.execute(Standalone.java:261)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: java.net.UnknownHostException: 991324615a39: Temporary failure in name resolution
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1665)
        ... 20 more
11:48:59.246 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
11:48:59.248 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 4 concurrent sessions. Session stability and reliability might suffer!
11:48:59.248 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
11:48:59.249 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
11:48:59.249 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
11:48:59.250 WARN [NodeOptions.getSessionFactories] - Max sessions set to 100
11:48:59.338 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "114.0","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 100 times (Host)
11:48:59.541 INFO [Node.<init>] - Binding additional locator mechanisms: relative
11:48:59.576 INFO [GridModel.setAvailability] - Switching Node 4b54f278-2684-451c-ba18-2f7e70e34c26 (uri: http://172.17.0.2:4444) from DOWN to UP
11:48:59.577 INFO [LocalDistributor.add] - Added node 4b54f278-2684-451c-ba18-2f7e70e34c26 at http://172.17.0.2:4444. Health check every 120s
11:48:59.832 INFO [Standalone.execute] - Started Selenium Standalone 4.10.0 (revision c14d967899): http://172.17.0.2:4444


11:49:32.645 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platformName: any}]
11:49:32.681 INFO [DriverService$Builder.getLogOutput] - Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
11:49:40.097 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.133)
Host info: host: '991324615a39', ip: 'Unknown'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
11:49:40.222 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.133)
Host info: host: '991324615a39', ip: 'Unknown'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
11:49:40.222 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.133)
Host info: host: '991324615a39', ip: 'Unknown'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:150)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

11:49:40.224 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "59bd624df575bc4130f4b338bc998009","eventTime": 1688960980096777887,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:10040","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=114.0.5735.133) \nHost info: host: '991324615a39', ip: 'Unknown'\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=114.0.5735.133) \nHost info: host: '991324615a39', ip: 'Unknown'\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:150)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"goog:chromeOptions\": {\"extensions\": [],\"args\": []},\"browserVersion\": \"114.0\",\"se:noVncPort\": 7900,\"browserName\": \"chrome\",\"se:vncEnabled\": true}\n"}}

11:49:40.226 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "59bd624df575bc4130f4b338bc998009","eventTime": 1688960980224479905,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platformName: any}","session.request.downstreamdialect": "[W3C]"}}

11:49:40.229 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "59bd624df575bc4130f4b338bc998009","eventTime": 1688960972643029476,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platformName: any}]"}}

11:49:40.229 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.133)
Host info: host: '991324615a39', ip: 'Unknown'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
11:49:40.229 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.133)
Host info: host: '991324615a39', ip: 'Unknown'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'
Driver info: driver.version: unknown
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:210)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

11:49:40.231 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "59bd624df575bc4130f4b338bc998009","eventTime": 1688960980227597367,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=114.0.5735.133) \nHost info: host: '991324615a39', ip: 'Unknown'\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=114.0.5735.133) \nHost info: host: '991324615a39', ip: 'Unknown'\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.59', java.version: '11.0.19'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:210)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, platformName: any}]"}}

11:49:40.240 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "59bd624df575bc4130f4b338bc998009","eventTime": 1688960980239164747,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:34444","http.method": "POST","http.request_content_length": "295","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f3.141.0 (python linux)"}}
```

### Operating System

 x86_64 GNU/Linux

### Docker Selenium version (tag)

4.10.0-20230709

**Comment by diemol** [comment]
Please fix your environment first, as you are getting 
>java.net.UnknownHostException: 991324615a39: 991324615a39: Temporary failure in name resolution

This is most likely affecting your setup. 

A quick search gave me these two links, maybe they can help
https://stackoverflow.com/questions/45868239/api-api-ai-temporary-failure-in-name-resolution
https://stackoverflow.com/questions/32537977/java-net-unknownhostexception-on-docker

If you are still facing the issue after fixing the environment, please comment and we can check again.

**Comment by bcvb2001** [comment]
> Please fix your environment first, as you are getting
> 
> > java.net.UnknownHostException: 991324615a39: 991324615a39: Temporary failure in name resolution
> 
> This is most likely affecting your setup.
> 
> A quick search gave me these two links, maybe they can help https://stackoverflow.com/questions/45868239/api-api-ai-temporary-failure-in-name-resolution https://stackoverflow.com/questions/32537977/java-net-unknownhostexception-on-docker
> 
> If you are still facing the issue after fixing the environment, please comment and we can check again.

At the beginning, I tried a lot of methods, modifying DNS, modifying the network, but found that it didn’t work at all, and then I found out that it might be my /etc/hosts file permission problem，The current permission is 600. After I changed it to 644, it started normally. Because my server is not user management, it is confusing and there is no root user. I don’t know if it is For this reason
