### ISSUE TITLE
[🐛 Bug]: Not able to execute automation scripts in Jenkins(linux server) using docker-compose

### ISSUE THREAD

**Issue by tbaruah58-elsv** [SeleniumHQ/docker-selenium#1920]
### What happened?

We are trying to execute our scripts in Jenkins server using docker-compose and scripts are failing with below exception-

webdriverio-test-chrome-2   | 15:13:35.027 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "866cdfeb7db376907d76de908ebe21d1","eventTime": 1692717215026209677,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.3:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002f2658763ae89bf4bbd7a6013d8e67dfbb\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-chrome-2   | 
webdriverio-test-chrome-2   | 
[0-0] 2023-08-22T15:13:35.051Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED
[0-0]   (Session info: chrome=110.0.5481.177)

### Command used to start Selenium Grid with Docker

```shell
npm install
docker-compose up
```

### Relevant log output

```shell
webdriverio-test-edge-1     | Microsoft Edge WebDriver was started successfully.
webdriverio-test-edge-1     | [1692717193.587][SEVERE]: bind() failed: Cannot assign requested address (99)
webdriverio-test-edge-1     | [1692717194.157][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
webdriverio-test-edge-1     | 15:13:14.520 INFO [LocalNode.newSession] - Session created by the Node. Id: c314723941e4a3751132928bdf9f9514, Caps: Capabilities {acceptInsecureCerts: true, browserName: msedge, browserVersion: 110.0.1587.63, ms:edgeOptions: {debuggerAddress: localhost:39241}, msedge: {msedgedriverVersion: 110.0.1587.63 (b26c9b8fc01e..., userDataDir: /tmp/.com.microsoft.Edge.qE...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:39241, se:cdpVersion: 110.0.1587.63, se:vncEnabled: true, se:vncLocalAddress: ws://172.22.0.4:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
selenium-hub                | 15:13:14.525 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: c314723941e4a3751132928bdf9f9514 
selenium-hub                |  Caps: Capabilities {acceptInsecureCerts: true, browserName: msedge, browserVersion: 110.0.1587.63, ms:edgeOptions: {debuggerAddress: localhost:39241}, msedge: {msedgedriverVersion: 110.0.1587.63 (b26c9b8fc01e..., userDataDir: /tmp/.com.microsoft.Edge.qE...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.22.0.4:4444/sessio..., se:cdpVersion: 110.0.1587.63, se:vnc: ws://172.22.0.4:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.22.0.4:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
webdriverio-test-chrome-2   | 15:13:35.027 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "866cdfeb7db376907d76de908ebe21d1","eventTime": 1692717215026209677,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.3:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002f2658763ae89bf4bbd7a6013d8e67dfbb\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-chrome-2   | 
webdriverio-test-chrome-2   | 
[0-0] 2023-08-22T15:13:35.051Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED
[0-0]   (Session info: chrome=110.0.5481.177)
[0-0] unknown error in "Elsevier - chrome.TC001_WSB-379_To Verify user able to create/delete section/subsection and Add/Remove Guidance/ QM in authoring screen"
unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=110.0.5481.177)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at LoginPage.openElsevierURL (/var/lib/jenkins/OS_Prod_HighCritical/web-app/client/application/tests/webdriverio-test/test/pageObjects/page.js:62:17)
    at Context.<anonymous> (/var/lib/jenkins/OS_Prod_HighCritical/web-app/client/application/tests/webdriverio-test/test/specs/OS_Prod_HighCritical/Elsevier/Authoring/TC001_WSB_379_ToVerifyUserableCreateDelSecOrSubSecAndAddRemoveGuidOrQMinAuthoringScreen.js:13:9)
webdriverio-test-chrome-2   | 15:13:35.348 INFO [SessionSlot.stop] - Stopping session 2658763ae89bf4bbd7a6013d8e67dfbb
selenium-hub                | 15:13:35.349 INFO [GridModel.release] - Releasing slot for session id 2658763ae89bf4bbd7a6013d8e67dfbb
selenium-hub                | 15:13:35.349 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 2658763ae89bf4bbd7a6013d8e67dfbb
[0-0] FAILED in chrome - /test/specs/OS_Prod_HighCritical/Elsevier/Authoring/TC001_WSB_379_ToVerifyUserableCreateDelSecOrSubSecAndAddRemoveGuidOrQMinAuthoringScreen.js
[0-1] RUNNING in chrome - /test/specs/OS_Prod_HighCritical/Elsevier/Authoring/TC002_WSB-1969_ToVerfiyUserableCreateDelPhaseinAuthoringScreen.js
selenium-hub                | 15:13:37.794 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
selenium-hub                |  [Capabilities {acceptInsecureCerts: true, browserName: chrome}]
webdriverio-test-chrome-2   | Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 27214
webdriverio-test-chrome-2   | Only local connections are allowed.
webdriverio-test-chrome-2   | Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
webdriverio-test-chrome-2   | ChromeDriver was started successfully.
webdriverio-test-chrome-2   | [1692717217.805][SEVERE]: bind() failed: Cannot assign requested address (99)
webdriverio-test-chrome-2   | [1692717218.273][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
webdriverio-test-chrome-2   | 15:13:38.448 INFO [LocalNode.newSession] - Session created by the Node. Id: 75fc61d82e1796a7986325eec573ddbc, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 110.0.5481.177, chrome: {chromedriverVersion: 110.0.5481.77 (65ed616c6e8e..., userDataDir: /tmp/.com.google.Chrome.MX0VyO}, goog:chromeOptions: {debuggerAddress: localhost:44499}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:44499, se:cdpVersion: 110.0.5481.177, se:vncEnabled: true, se:vncLocalAddress: ws://172.22.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
selenium-hub                | 15:13:38.454 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 75fc61d82e1796a7986325eec573ddbc 
selenium-hub                |  Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 110.0.5481.177, chrome: {chromedriverVersion: 110.0.5481.77 (65ed616c6e8e..., userDataDir: /tmp/.com.google.Chrome.MX0VyO}, goog:chromeOptions: {debuggerAddress: localhost:44499}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://172.22.0.3:4444/sessio..., se:cdpVersion: 110.0.5481.177, se:vnc: ws://172.22.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.22.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
webdriverio-test-edge-1     | 15:13:54.933 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "9025c413fc643d60968007d12415046f","eventTime": 1692717234933145246,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.4:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fc314723941e4a3751132928bdf9f9514\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-edge-1     | 
webdriverio-test-edge-1     | 
selenium-hub                | 15:14:22.973 INFO [GridModel.purgeDeadNodes] - Removing Node http://172.22.0.6:5555, DOWN for too long
webdriverio-test-edge-1     | 15:14:35.096 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "9f6145cf53e9e0bbe894370008aee84e","eventTime": 1692717275095528995,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.4:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fc314723941e4a3751132928bdf9f9514\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-edge-1     | 
webdriverio-test-edge-1     | 
webdriverio-test-chrome-2   | 15:14:38.846 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "741cfdcd21d4c0e927731239995ac74c","eventTime": 1692717278845495289,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.3:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002f75fc61d82e1796a7986325eec573ddbc\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-chrome-2   | 
webdriverio-test-chrome-2   | 
webdriverio-test-chrome-2   | 15:14:58.923 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "8a4ad4ea100729fce6967c7c0810e433","eventTime": 1692717298923452697,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.3:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002f75fc61d82e1796a7986325eec573ddbc\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-chrome-2   | 
webdriverio-test-chrome-2   | 
webdriverio-test-edge-1     | 15:15:15.276 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "b2765416a2e6079f0733296b9b2ecc1e","eventTime": 1692717315276012951,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.4:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fc314723941e4a3751132928bdf9f9514\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-edge-1     | 
webdriverio-test-edge-1     | 
webdriverio-test-edge-1     | 15:15:35.391 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "479b581adcffcd2bb11ea0b91fded211","eventTime": 1692717335390707294,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "172.22.0.4:5555","http.method": "POST","http.request_content_length": "50","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession\u002fc314723941e4a3751132928bdf9f9514\u002furl","http.user_agent": "webdriver\u002f7.31.1"}}
webdriverio-test-edge-1     | 
webdriverio-test-edge-1     | 
[2-2] 2023-08-22T15:15:35.406Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED
[2-2]   (Session info: MicrosoftEdge=110.0.1587.63)
[2-2] unknown error in "Elsevier - MicrosoftEdge.TC003_WSB_378_Verify Default Section In Authoring"
unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: MicrosoftEdge=110.0.1587.63)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at LoginPage.openElsevierURL (/var/lib/jenkins/OS_Prod_HighCritical/web-app/client/application/tests/webdriverio-test/test/pageObjects/page.js:62:17)
    at Context.<anonymous> (/var/lib/jenkins/OS_Prod_HighCritical/web-app/client/application/tests/webdriverio-
```

### Operating System

linux

### Docker Selenium version (tag)

docker-compose v2.2.3

**Comment by diemol** [comment]
>[0-0] 2023-08-22T15:13:35.051Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: net::ERR_NAME_NOT_RESOLVED

That means the docker container cannot resolve the URL you want to navigate to. Please check if you need to setup a proxy to reach the URL you want to. https://docs.docker.com/network/proxy/
