### ISSUE TITLE
[🐛 Bug]: Unable to obtain: Capabilities - Do not forget to update python lib while updating node and hub

### ISSUE THREAD

**Issue by eravion** [SeleniumHQ/docker-selenium#1939]
### What happened?

Hello,

My setup : docker on Linux to run GRID 4.x since month

While testing the upgrade of node from 4.10 to 4.11.x, open browser does not work for both Firefox and Chrome.
Same issue with 4.12.x

hub is running 4.12

file selenium-node_firefox.toml

[events]
publish = "tcp://hub_ip:4442"
subscribe = "tcp://hub_ip:4443"

[server]
host = "10.237.23.121"
port = 5555

[node]
session-timeout = 300
override-max-sessions = true
detect-drivers = false
max-sessions = 5

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "networkname:applicationName":"my_network_name", "nodename:applicationName":"robot_name" }'
max-sessions = 5

### Command used to start Selenium Grid with Docker

```shell
${profile} = BuiltIn . Evaluate sys.modules['selenium.webdriver'].FirefoxProfile(), sys
${profile} = <selenium.webdriver.firefox.firefox_profile.FirefoxProfile object at 0x7fe7f5037880>
 Call Method ${profile}, set_preference, intl.accept_languages, ${lang}

 ${capabilities} = BuiltIn . Create Dictionary platform=${platform}, browserName=firefox, networkname:applicationName=${networkname}
${capabilities} = {'platform': 'LINUX', 'browserName': 'firefox', 'networkname:applicationName': 'My-Network_name'}

Open Browser about:blank, remote_url=${remoteURL}, alias=${alias}, desired_capabilities=${capabilities}, ff_profile_dir=${profile}
```

### Relevant log output

```shell
12:48:04.530 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, nodename:applicationName: robot_name, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [/tmp/selenium-manager4281495091380269159752941351193773/selenium-manager, --browser, firefox, --output, json]
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'
Driver info: driver.version: unknown
12:48:04.537 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, nodename:applicationName: robot_name, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [/tmp/selenium-manager4281495091380269159752941351193773/selenium-manager, --browser, firefox, --output, json]
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'
Driver info: driver.version: unknown
12:48:04.538 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, nodename:applicationName: robot_name, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [/tmp/selenium-manager4281495091380269159752941351193773/selenium-manager, --browser, firefox, --output, json]
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:142)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:73)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)
	at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:50)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:193)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:62)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: Failed to run command: [/tmp/selenium-manager4281495091380269159752941351193773/selenium-manager, --browser, firefox, --output, json]
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'
Driver info: driver.version: unknown
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:124)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:273)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 27 more
Caused by: java.io.IOException: Cannot run program "/tmp/selenium-manager4281495091380269159752941351193773/selenium-manager": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:113)
	... 29 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 31 more

12:48:04.552 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ca82197bad169da98ef1f2e0d8fcffad","eventTime": 1694436484536684460,"eventName": "exception","attributes": {"exception.message": "Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, nodename:applicationName: robot_name, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [\u002ftmp\u002fselenium-manager4281495091380269159752941351193773\u002fselenium-manager, --browser, firefox, --output, json]\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, nodename:applicationName: robot_name, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [\u002ftmp\u002fselenium-manager4281495091380269159752941351193773\u002fselenium-manager, --browser, firefox, --output, json]\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:142)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:73)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:50)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:193)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:62)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:262)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: org.openqa.selenium.WebDriverException: Failed to run command: [\u002ftmp\u002fselenium-manager4281495091380269159752941351193773\u002fselenium-manager, --browser, firefox, --output, json]\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-11-amd64', java.version: '11.0.20'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:124)\n\tat org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:273)\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)\n\t... 27 more\nCaused by: java.io.IOException: Cannot run program \"\u002ftmp\u002fselenium-manager4281495091380269159752941351193773\u002fselenium-manager\": error=2, No such file or directory\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1128)\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1071)\n\tat org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:113)\n\t... 29 more\nCaused by: java.io.IOException: error=2, No such file or directory\n\tat java.base\u002fjava.lang.ProcessImpl.forkAndExec(Native Method)\n\tat java.base\u002fjava.lang.ProcessImpl.\u003cinit>(ProcessImpl.java:340)\n\tat java.base\u002fjava.lang.ProcessImpl.start(ProcessImpl.java:271)\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1107)\n\t... 31 more\n","exception.type": "org.openqa.selenium.remote.NoSuchDriverException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"nodename:applicationName\": \"robot_name\",\"networkname:applicationName\": \"my_network_name\",\"se:noVncPort\": 7900,\"browserName\": \"firefox\",\"moz:firefoxOptions\": {\"profile\": \"UEsDBBQAAAAIAJR1K1djabclngMAAP0MAAAHAAAAdXNlci5qc6VWy47bNhTd9ysCrxqgJjyTZtOuJpMpUCDoFDEGWRIUeSVxTJEseWmN\\u002f76XkpW4Hr2S7vQ4h\\u002fd9LlOEwH2A8udNEVxLb0y5hrXaKtcylRrPwIrCgNr88gZDgre\\u002f\\u002f5Rec4xACCHZC3ApTJxAW2hRFCwFQ7iNKFzC3woj7GEzh\\u002feignXnRxQBk2eZQcjdPKp2DZyRK3y5ZnF3pMi1AtZEdLY7RVfWBZg4gD6pR\\u002fulS3C82TFtMbinz5\\u002fmzeeiNOKFyzqQYR5l0B45ZZyjbrLRd7txwjpkAO8CcmEMf44cXiR41M7G0aI\\u002fi6Poj2Wuh7FYu\\u002fZPe0+PzsAoyQK2LhyYFEQ5wjbbE2ZLgKOWC3WNIFPQeGIyDu04AbwuTgtG5nwtttockwmldI5TLBzSQqECBRe4kDmDPFFtU0RQXELA8WxekGJM2eJXkqYPEEZZ1DXkV2+FPKkS+ZzP35ThyqkKLARhct8FAlkq2rljM\\u002fyeLLlme5d\\u002fXBGF9yx5RZPNREI3nvEL0KrRVDp6I06gHm52+78cUu2J8OsE2LXWOKGokS25Hro2+1KD3edqaVvN23p4+nR3Gey0fHXId+d8Lkmdtgfqe7A0JiR6fVPcLmFJwnpNnQa7siT8RGcPoABC5cwAgiRP\\u002f9Ah4h3lQk6M3VfZEiV0z5S1lSJ6yWiEaUVYK78ggqzPbbEENWVMPovBsA6mdBdizFKDpKyUhW5SStJCLoOI9YKVGoxhsgZ5+AilSAY\\u002f9H\\u002fmabRzIqOw7aO9Ny4uhHKBfqSKj4MpI6LX2pzVGoTBun9nq5Rwhp98HpWHH2QP1svcUJ\\u002fT97tvXFXlj7LfAd\\u002fhh3dGyxPLH\\u002fepaHRX5\\u002f\\u002fL\\u002f7v7ePdtoMeOgSM6ZyIjhXDh7PjsdSevSlKwDODdWCvaS7biOfPjNrJG2K5xOxH92JP3kthZrm92k\\u002fDCOHkwOuJ8R1wwuga\\u002fd40XqAtt8sK0uqrRnBapayT8NdySfpenp8lBurgozGV1uBr0Kr896+CWVjKmOH7yQKkR6ZpX61iftvm3px26NWArzJJw+\\u002f79f2nD0bS1qB7GuJYXJ656TRj1zZPEeIx5unnjFO3RdTeVUhugJ+aCprHgfY\\u002fmy9cCPmLQEvk1bcxUvmVaksIGmgLCvnudSFdu84NGdk7bsE7PrTwa+EBBMGQBw4n1qegiv13CzibpNTzAc7fORj158Zpkn6rFcsjUE6T+xPgn6TBl4RulrTWZyVM0wvgXUEsBAhQDFAAAAAgAlHUrV2NptyWeAwAA\\u002fQwAAAcAAAAAAAAAAAAAALSBAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAAwwMAAAAA\"},\"se:vncEnabled\": true}\n"}}

12:48:04.554 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ca82197bad169da98ef1f2e0d8fcffad","eventTime": 1694436484553913221,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {browserName: firefox, moz:firefoxOptions: {profile: UEsDBBQAAAAIAJR1K1djabclngM...}, networkname:applicationName: my_network_name, platformName: linux}","session.request.downstreamdialect": "[W3C]"}}
```

### Operating System

Docker fro Docker hub on Linux Debian

### Docker Selenium version (tag)

4.11, 4.12

**Comment by diemol** [comment]
Can you share the commands you use to start the Grid?

**Comment by eravion** [comment]
For the hub :  
docker run --restart=always -d -p 4442-4444:4442-4444 --name selenium-hub  DockerHub/selenium/hub:4.12

For the node :  
docker run --restart=always -d  -p 5555:5555 -p 5900:5900 --memory="3g"  --shm-size="2g" --hostname  robot_name -e SE_EVENT_BUS_HOST=hub_selenium_4_ip -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e SE_NODE_HOST=service_ip -v /opt/selenium/4/selenium-node_firefox.toml:/opt/selenium/config.toml -v /etc/nsswitch.conf:/etc/nsswitch.conf --name node-firefox --add-host=host.docker.internal:host-gateway DockerHub/selenium/node-firefox:4.11

**Comment by diemol** [comment]
Please avoid placeholders, I'd like to see the real command.

**Comment by eravion** [comment]
> Please avoid placeholders, I'd like to see the real command.

is it better now ?

**Comment by diemol** [comment]
Can you share the logs when using 4.12.1?

**Comment by eravion** [comment]
My mistake, I'm very sorry.

I forgot to update python lib
pip3 install robotframework-seleniumlibrary==6.1.2
pip3  install selenium==4.12.0

Now it is ok.

**Comment by eravion** [comment]
Closed
