### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException: Could not start a new session

### ISSUE THREAD

**Issue by mjbty** [SeleniumHQ/docker-selenium#1946]
### What happened?

When trying to execute tests on the grid deployed using the provided helm chart, I get the error : 
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

The grid is up and running and in the console, I can see the nodes are registered.
When I launch tests, the percentage in in the node is 100%, but the sessions count remains 0.
![2023-09-15_18-42-47](https://github.com/SeleniumHQ/docker-selenium/assets/145150583/921ce949-69c8-4971-94dd-eb4915d64bfb)
[](url)

### Command used to start Selenium Grid with Docker

```shell
helm install selenium-grid docker-selenium/selenium-grid --set 
ingress.hostname=http://selenium-hub.selenium.dev.com,chromeNode.replicas=3,firefoxNode.enabled=false,edgeNode.enabled=false
```

### Relevant log output

```shell
When launching just three tests in parallel, Inside the hub pod, I see an error about "No slot matched the requested capabilities" repeated too many times :

17:08:21.871 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: [UEsDBBQAAAAIAFlOHlc1u3yXWAE...]}}]
17:08:21.876 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21d21411470b5b457e221871b2e1555f","eventTime": 1694797701871083849,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: [UEsDBBQAAAAIAFlOHlc1u3yXWAE...]}}]"}}
17:08:21.876 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. No slot matched the requested capabilities.
Host info: host: 'selenium-chrome-node-6c859c94c9-zqxtm', ip: '10.10.12.126'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
17:08:21.876 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.RetrySessionRequestException: Could not start a new session. Could not start a new session. No slot matched the requested capabilities.
Host info: host: 'selenium-chrome-node-6c859c94c9-zqxtm', ip: '10.10.12.126'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:149)
at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:648)
at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:565)
at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:829)
at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:785)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
17:08:21.877 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21d21411470b5b457e221871b2e1555f","eventTime": 1694797701875895965,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Could not start a new session. No slot matched the requested capabilities. \nHost info: host: 'selenium-chrome-node-6c859c94c9-zqxtm', ip: '10.10.12.126'\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'\nDriver info: driver.version: unknown\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.RetrySessionRequestException: Could not start a new session. Could not start a new session. No slot matched the requested capabilities. \nH...

Then so many other errors about max sessions reached :
17:09:35.566 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: [UEsDBBQAAAAIAFlOHlc1u3yXWAE...]}}]
17:09:35.569 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21d21411470b5b457e221871b2e1555f","eventTime": 1694797775566070615,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: [UEsDBBQAAAAIAFlOHlc1u3yXWAE...]}}]"}}
17:09:35.570 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. Max session count reached.
Host info: host: 'selenium-chrome-node-6c859c94c9-6t9mr', ip: '10.10.11.47'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
17:09:35.570 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.RetrySessionRequestException: Could not start a new session. Could not start a new session. Max session count reached.
Host info: host: 'selenium-chrome-node-6c859c94c9-6t9mr', ip: '10.10.11.47'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'
Driver info: driver.version: unknown
at org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:149)
at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:648)
at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:565)
at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:829)
at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:785)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
17:09:35.570 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "21d21411470b5b457e221871b2e1555f","eventTime": 1694797775569386974,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Could not start a new session. Max session count reached. \nHost info: host: 'selenium-chrome-node-6c859c94c9-6t9mr', ip: '10.10.11.47'\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'\nDriver info: driver.version: unknown\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.72.1.el8_4.x86_64', java.version: '11.0.20'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.RetrySessionRequestException: Could not start a new session. Could not start a new session. Max session count reached. \nHost info: host: 'selenium-chrome-no...
```

### Operating System

rhel 8.8

### Docker Selenium version (tag)

4.11.0

**Comment by mjbty** [comment]
Hi @diemol, 
As specified in the question, I am not using any code, I am using the provided chart in the repo to deploy the grid on a Kubernetes cluster, the command used is : 
" helm install selenium-grid docker-selenium/selenium-grid --set 
ingress.hostname=http://selenium-hub.selenium.dev.com,chromeNode.replicas=3,firefoxNode.enabled=false,edgeNode.enabled=false "
If you need more logs or the output of any command executed on the pods, please let me know

Thanks for your help

**Comment by diemol** [comment]
>504 Gateway Time-out

This usually comes from whatever is on top of the Grid (ngnix, etc)

However, I need to know how to reproduce this issue.

**Comment by mjbty** [comment]
Thank you, the issue was resolved in the latest version of the chart
