### ISSUE TITLE
[🐛 Bug]:  selenium is taking too much cpu usage after upgrade to latest stable version 

### ISSUE THREAD

**Issue by sohaibMan** [SeleniumHQ/docker-selenium#1986]
### What happened?

Build info: version: '4.14.1', revision: '03f8ede370'

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'

Driver info: driver.version: unknown

14:37:43.035 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: d2deac84e0f7d9dcbf9aa5ffb511d22d

Build info: version: '4.14.1', revision: '03f8ede370'

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'

Driver info: driver.version: unknown

### Command used to start Selenium Grid with Docker

```shell
docker run --rm -it -p 4444:4444 --name chrome_browser --network scraping_network -d --shm-size="2g"selenium/standalone-chrome:4.14.1-20231025
```

### Relevant log output

```shell
2023-10-26 14:15:17,273 INFO RPC interface 'supervisor' initialized

2023-10-26 14:15:17,273 CRIT Server 'unix_http_server' running without any HTTP authentication checking

2023-10-26 14:15:17,273 INFO supervisord started with pid 8

2023-10-26 14:15:18,277 INFO spawned: 'xvfb' with pid 10

2023-10-26 14:15:18,280 INFO spawned: 'vnc' with pid 11

2023-10-26 14:15:18,283 INFO spawned: 'novnc' with pid 12

2023-10-26 14:15:18,286 INFO spawned: 'selenium-standalone' with pid 13

Setting up SE_NODE_GRID_URL...

2023-10-26 14:15:18,307 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2023-10-26 14:15:18,307 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2023-10-26 14:15:18,307 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2023-10-26 14:15:18,307 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Selenium Grid Standalone configuration: 

[network]

relax-checks = true



[node]

session-timeout = "300"

override-max-sessions = false

detect-drivers = false

drain-after-session-count = 0

max-sessions = 1



[[node.driver-configuration]]

display-name = "chrome"

stereotype = '{"browserName": "chrome", "browserVersion": "118.0", "platformName": "Linux"}'

max-sessions = 1



Starting Selenium Grid Standalone...

Tracing is disabled

Oct 26, 2023 2:15:18 PM org.openqa.selenium.grid.Bootstrap createExtendedClassLoader

WARNING: Extension file or directory does not exist: /opt/selenium/selenium-http-jdk-client.jar

14:15:19.029 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

14:15:19.041 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

14:15:19.725 INFO [NodeOptions.getSessionFactories] - Detected 56 available processors

14:15:19.768 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "118.0","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times

14:15:19.783 INFO [Node.<init>] - Binding additional locator mechanisms: relative

14:15:19.800 INFO [GridModel.setAvailability] - Switching Node a7a198f6-2775-462c-af6c-f678415626f6 (uri: http://172.18.0.5:4444) from DOWN to UP

14:15:19.800 INFO [LocalDistributor.add] - Added node a7a198f6-2775-462c-af6c-f678415626f6 at http://172.18.0.5:4444. Health check every 120s

14:15:19.971 INFO [Standalone.execute] - Started Selenium Standalone 4.14.1 (revision 03f8ede370): http://172.18.0.5:4444

14:33:49.185 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 

 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-ssl-errors=yes, --ignore-certificate-errors, --high-dpi-support=1, --device-scale-factor=1, --force-device-scale-factor=1, --user-agent=Mozilla/5.0 (W..., --headless], extensions: []}, pageLoadStrategy: normal, unhandledPromptBehavior: accept}]

14:33:49.392 WARN [SeleniumManager.lambda$runCommand$1] - Exception managing chrome: Unable to discover proper chromedriver version in offline mode

14:33:50.188 INFO [LocalNode.newSession] - Session created by the Node. Id: 7a56068a3f99d6732791cd036368c779, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.117, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:41140}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.18.0.5:4444/sessio..., se:cdpVersion: 118.0.5993.117, se:vnc: ws://172.18.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

14:33:50.197 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 7a56068a3f99d6732791cd036368c779 

 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.117, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:41140}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.18.0.5:4444/sessio..., se:cdpVersion: 118.0.5993.117, se:vnc: ws://172.18.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

14:34:16.379 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 7a56068a3f99d6732791cd036368c779

14:34:16.381 INFO [GridModel.release] - Releasing slot for session id 7a56068a3f99d6732791cd036368c779

14:34:16.382 INFO [SessionSlot.stop] - Stopping session 7a56068a3f99d6732791cd036368c779

14:37:43.034 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: d2deac84e0f7d9dcbf9aa5ffb511d22d

Build info: version: '4.14.1', revision: '03f8ede370'

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'

Driver info: driver.version: unknown

14:37:43.035 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: d2deac84e0f7d9dcbf9aa5ffb511d22d

Build info: version: '4.14.1', revision: '03f8ede370'

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'

Driver info: driver.version: unknown

	at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:132)

	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:168)

	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)

	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)

	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.grid.router.Router.execute(Router.java:87)

	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)

	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:271)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)

	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)

	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)

	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)

	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)

	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)

	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)

	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:829)



14:37:43.037 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "9cbd88c034b2f97580e35eae57f84212","eventTime": 1698331063028479793,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: d2deac84e0f7d9dcbf9aa5ffb511d22d\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: d2deac84e0f7d9dcbf9aa5ffb511d22d\nBuild info: version: '4.14.1', revision: '03f8ede370'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:132)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:168)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:87)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:271)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "81.17.22.82:4444","http.method": "DELETE","http.scheme": "HTTP","http.target": "\u002fsession\u002fd2deac84e0f7d9dcbf9aa5ffb511d22d","http.user_agent": "selenium\u002f4.11.2 (python linux)","session.id": "d2deac84e0f7d9dcbf9aa5ffb511d22d"}}



14:37:43.375 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 

 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless], extensions: []}, pageLoadStrategy: normal}]

14:37:43.501 WARN [SeleniumManager.lambda$runCommand$1] - Exception managing chrome: Unable to discover proper chromedriver version in offline mode

14:37:43.817 INFO [LocalNode.newSession] - Session created by the Node. Id: 1ebfc84ff261ceb4c385354b9d82673b, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.117, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:46327}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.18.0.5:4444/sessio..., se:cdpVersion: 118.0.5993.117, se:vnc: ws://172.18.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

14:37:43.822 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 1ebfc84ff261ceb4c385354b9d82673b 

 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.117, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:46327}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.18.0.5:4444/sessio..., se:cdpVersion: 118.0.5993.117, se:vnc: ws://172.18.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
```

### Operating System

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.95.1.el7.x86_64', java.version: '11.0.20.1'

### Docker Selenium version (tag)

4.14.1-20231025

**Comment by diemol** [comment]
And, what is using the CPU? Can you inspect the container and the processes running inside?

**Comment by sohaibMan** [comment]
> And, what is using the CPU? Can you inspect the container and the processes running inside?
![image](https://github.com/SeleniumHQ/docker-selenium/assets/96356071/eeda1966-5c7e-4f17-8006-d972a8d859d7)
![image](https://github.com/SeleniumHQ/docker-selenium/assets/96356071/386fb14e-02d7-4c0a-91e3-a650d6f43a94)
and here is my cpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

**Comment by diemol** [comment]
OK, so the issue is Chrome itself. Please report that to the Chrome team.

**Comment by diemol** [comment]
They always need a way to reproduce the issue, by the way.
