### ISSUE TITLE
[🐛 Bug]: Node wont connect to hub. Errors: Unable to reach the Docker daemon at http://127.0.0.1:2375 and no response - java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by mikejohnstonPremierinc** [SeleniumHQ/docker-selenium#2005]
### Description
I am starting a `selenium/hub` and `selenium/node-docker` on Linux Red Hat 9 Rhel 9. The Hub succeeds in starting, but the node-docker fails to be successful with multiple errors in the log. See errors below, `--log-level` was set to `FINE`. A couple things to note that may/may not be relevant:

1. I created the server 1 month ago. At this time, I moved the data storage location from it's default location of `/var/lib` to `/opt` by adding `"data-root": "/opt/docker"` to daemon.json
2. The docker compose to start hub and node were successful for 2 weeks and tests were executing without issue
3. I then got the error after 2 weeks.
4. I fixed it by doing the following: Removing all containers, images from the `/opt/docker` directory then executing the docker run command again. Since I removed images, it redownloads the selenium/node-docker image again. It then works again.
5. It stopped working again today, so the above workaround is only temporary
6. There was a server reboot yesterday but I do not believe that played a part
7. I have tried some of the proposed fixes that @diemol has listed here https://github.com/SeleniumHQ/selenium/issues/11935, but none have worked. Only my temporary workaround to delete then download a new image has worked

### Errors
**Exchange checkFor407: no response - java.net.ConnectException: Connection refused**

**MultiExchange ConnectException (async): retrying...java.net.ConnectException: Connection refused**

**[SocketTube$InternalReadPublisher$InternalReadSubscription.signalError] - [HttpClient-1-SelectorManager] [278ms] SocketTube(1) got read error: java.io.IOException: connection closed locally**

**[SocketTube$InternalReadPublisher$InternalReadSubscription.read] - [HttpClient-1-SelectorManager] [279ms] SocketTube(1) error raised before subscriber subscribed: java.io.IOException: connection closed locally**

**config-node-docker-1  | Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375**

### Versions
Docker engine version 24.0.7
docker-compose version 2.21.0

### Command used to start Selenium Grid with Docker

```shell
// compose_dynamic_hubandnode.yml
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.14.1
    volumes:
      - /share/pqafiles/assets:/opt/selenium/assets
      - /share/pqafiles/config/toml_server1.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub 
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
      - VNC_NO_PASSWORD=1  
      - SE_OPTS=--enable-managed-downloads true   

  selenium-hub:
    image: selenium/hub:4.14.1
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"    

// toml_server1.toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:117.0", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:117.0", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:117.0", "{\"browserName\": \"MicrosoftEdge\"}"
    ]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because interally the container uses socat when /var/run/docker.sock is mounted 
# If var/run/docker.sock is not mounted: 
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://127.0.0.1:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20231016"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
# [server]
# host = <ip-from-node-machine>
# port = <port-from-node-machine>
```

### Relevant log output

```shell
22:18:48.129 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [275ms] HttpClientImpl(1) next timeout: 9989
22:18:48.129 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [276ms] HttpClientImpl(1) next expired: 0
22:18:48.129 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [276ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.130 DEBUG [PlainHttpConnection$ConnectEvent.handle] - [HttpClient-1-SelectorManager] [276ms] PlainHttpConnection(SocketTube(1)) ConnectEvent: finishing connect
22:18:48.131 DEBUG [Exchange.checkFor407] - [pool-1-thread-1] [278ms] Exchange checkFor407: no response - java.net.ConnectException: Connection refused
22:18:48.131 DEBUG [PlainHttpConnection.close] - [HttpClient-1-SelectorManager] [278ms] PlainHttpConnection(SocketTube(1)) Closing channel: channel registered with selector, invalid key, sa.interestOps=8
22:18:48.132 DEBUG [MultiExchange.getExceptionalCF] - [pool-1-thread-1] [278ms] MultiExchange ConnectException (async): retrying...
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
22:18:48.132 DEBUG [SocketTube$InternalReadPublisher$InternalReadSubscription.signalError] - [HttpClient-1-SelectorManager] [278ms] SocketTube(1) got read error: java.io.IOException: connection closed locally
22:18:48.133 DEBUG [Exchange.establishExchange] - [pool-1-thread-1] [279ms] Exchange establishing exchange for http://127.0.0.1:2375/version GET,
         proxy=null
22:18:48.133 DEBUG [Http2ClientImpl.getConnectionFor] - [pool-1-thread-1] [279ms] Http2ClientImpl not found in connection pool
22:18:48.133 DEBUG [SocketTube$InternalReadPublisher$InternalReadSubscription.read] - [HttpClient-1-SelectorManager] [279ms] SocketTube(1) error raised before subscriber subscribed: java.io.IOException: connection closed locally
22:18:48.133 DEBUG [ExchangeImpl.get] - [pool-1-thread-1] [279ms] ExchangeImpl get: Trying to get HTTP/2 connection
22:18:48.133 DEBUG [ExchangeImpl.createExchangeImpl] - [pool-1-thread-1] [279ms] ExchangeImpl handling HTTP/2 connection creation result
22:18:48.133 DEBUG [ExchangeImpl.createExchangeImpl] - [pool-1-thread-1] [279ms] ExchangeImpl new Http1Exchange, try to upgrade
22:18:48.133 DEBUG [PlainHttpConnection.<init>] - [pool-1-thread-1] [279ms] PlainHttpConnection(?) Initial receive buffer size is: 65536
22:18:48.133 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [280ms] HttpClientImpl(1) next timeout: 180000
22:18:48.133 DEBUG [Exchange.checkFor407] - [pool-1-thread-1] [280ms] Exchange checkFor407: all clear
22:18:48.134 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [280ms] HttpClientImpl(1) next expired: 0
22:18:48.134 DEBUG [Http1Exchange.sendHeadersAsync] - [pool-1-thread-1] [280ms] Http1Exchange Sending headers only
22:18:48.134 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [280ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.134 DEBUG [Http1AsyncReceiver.subscribe] - [pool-1-thread-1] [280ms] Http1AsyncReceiver(SocketTube(2)) Subscribed pending jdk.internal.net.http.Http1Response$HeadersReader@225bb5d queue.isEmpty: true
22:18:48.134 DEBUG [Http1AsyncReceiver.handlePendingDelegate] - [pool-1-thread-1] [280ms] Http1AsyncReceiver(SocketTube(2)) delegate is now jdk.internal.net.http.Http1Response$HeadersReader@225bb5d, demand=1, canRequestMore=true, queue.isEmpty=true
22:18:48.134 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [280ms] HttpClientImpl(1) next timeout: 179999
22:18:48.134 DEBUG [Http1AsyncReceiver.hasDemand] - [pool-1-thread-1] [280ms] Http1AsyncReceiver(SocketTube(2)) downstream subscription demand is 1
22:18:48.134 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [280ms] HttpClientImpl(1) next expired: 0
22:18:48.134 DEBUG [Http1AsyncReceiver.checkRequestMore] - [pool-1-thread-1] [281ms] Http1AsyncReceiver(SocketTube(2)) checkRequestMore: canRequestMore=true, hasDemand=true
22:18:48.134 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [281ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.135 DEBUG [Http1AsyncReceiver.hasDemand] - [pool-1-thread-1] [281ms] Http1AsyncReceiver(SocketTube(2)) downstream subscription demand is 1
22:18:48.135 DEBUG [Http1AsyncReceiver.checkRequestMore] - [pool-1-thread-1] [281ms] Http1AsyncReceiver(SocketTube(2)) checkRequestMore: canRequestMore=true, hasDemand=true
22:18:48.135 DEBUG [Http1Exchange.sendHeadersAsync] - [pool-1-thread-1] [281ms] Http1Exchange response created in advance
22:18:48.135 DEBUG [Http1Exchange.sendHeadersAsync] - [pool-1-thread-1] [281ms] Http1Exchange initiating connect async
22:18:48.135 DEBUG [PlainHttpConnection.connectAsync] - [pool-1-thread-1] [281ms] PlainHttpConnection(SocketTube(2)) registering connect timer: ConnectTimerEvent, TimeoutEvent[id=4, duration=PT9.982752857S, deadline=2023-11-12T22:18:58.118158857Z]
22:18:48.135 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [281ms] HttpClientImpl(1) next timeout: 9983
22:18:48.135 DEBUG [PlainHttpConnection.connectAsync] - [pool-1-thread-1] [281ms] PlainHttpConnection(SocketTube(2)) registering connect event
22:18:48.135 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [281ms] HttpClientImpl(1) next expired: 0
22:18:48.135 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [282ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.136 DEBUG [HttpClientImpl$SelectorAttachment.register] - [HttpClient-1-SelectorManager] [282ms] SelectorAttachment Registering jdk.internal.net.http.PlainHttpConnection$ConnectEvent@56de79a8 for 8 (true)
22:18:48.136 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [282ms] HttpClientImpl(1) next timeout: 9982
22:18:48.136 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [282ms] HttpClientImpl(1) next expired: 0
22:18:48.136 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [282ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.136 DEBUG [PlainHttpConnection$ConnectEvent.handle] - [HttpClient-1-SelectorManager] [282ms] PlainHttpConnection(SocketTube(2)) ConnectEvent: finishing connect
22:18:48.137 DEBUG [Exchange.checkFor407] - [pool-1-thread-1] [283ms] Exchange checkFor407: no response - java.net.ConnectException: Connection refused
22:18:48.137 DEBUG [PlainHttpConnection.close] - [HttpClient-1-SelectorManager] [283ms] PlainHttpConnection(SocketTube(2)) Closing channel: channel registered with selector, invalid key, sa.interestOps=8
22:18:48.137 DEBUG [SocketTube$InternalReadPublisher$InternalReadSubscription.signalError] - [HttpClient-1-SelectorManager] [283ms] SocketTube(2) got read error: java.io.IOException: connection closed locally
22:18:48.137 DEBUG [MultiExchange.getExceptionalCF] - [pool-1-thread-1] [283ms] MultiExchange ConnectException (async): already retried once.
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
22:18:48.137 DEBUG [SocketTube$InternalReadPublisher$InternalReadSubscription.read] - [HttpClient-1-SelectorManager] [283ms] SocketTube(2) error raised before subscriber subscribed: java.io.IOException: connection closed locally
22:18:48.138 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [284ms] HttpClientImpl(1) next timeout: 0
22:18:48.138 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [284ms] HttpClientImpl(1) next expired: 0
22:18:48.138 DEBUG [HttpClientImpl$SelectorManager.run] - [HttpClient-1-SelectorManager] [284ms] HttpClientImpl(1) Next deadline is 3000
22:18:48.138 DEBUG [JdkHttpClient.execute0] - Ending request (GET) /version in 73ms
22:18:48.140 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=abcb7e2c630f9651ced06fa6cf9e24c0, spanId=a902fead04fa2cd3, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.28.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=httpclient.execute, kind=INTERNAL, startEpochNanos=1699827528054000000, endEpochNanos=1699827528138379578, attributes=AttributesMap{data={http.method=GET, span.kind=client, http.target=/version}, capacity=128, totalAddedValues=3}, totalAttributeCount=3, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375
        at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:124)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:92)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-11-12 22:18:48,466 INFO exited: selenium-grid-docker (exit status 1; not expected)
```

### Operating System

Linux Red Hat 9 Rhel 9

### Docker Selenium version (tag)

node-docker:4.14.1

**Comment by VietND96** [comment]
`Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2375/`
Based on this error, can you try to troubleshoot the Docker daemon following steps https://phoenixnap.com/kb/cannot-connect-to-the-docker-daemon-error

**Comment by diemol** [comment]
Thank you for troubleshooting, @vietnd96!

Yes, @mikejohnstonPremierinc, please configure and expose the Docker daemon properly. There is not much we can do on this.

**Comment by mikejohnstonPremierinc** [comment]
Hello @vietnd96 and @diemol, as noted in my OP, the issue is not occurring due to the Docker daemon not being exposed properly, as the issue is sporadic. It worked then did not work, then I redownloaded image, then it worked again, then again it did not work. Also in my OP on step #7, I noted that I DID follow steps to expose Docker daemon properly, even though that is not the cause of this.

**Comment by VietND96** [comment]
Yes, I understand your pain point with this unstable issue. However, when take a look at app logs, I am only able to configure out issue with Docker daemon, probably it was unreachable randomly and hub/node crashed.
I saw you are using docker compose file to deploy, I would like to suggest you add restart policy to both hub and node. something like
```yaml
version: "3"
services:
  node-docker:
    restart: always
    ...
  selenium-hub:
    restart: always
    ...
```
When the container fails unexpectedly, the Docker will try to restart the container to recover the application running inside. 
Refer to: https://www.baeldung.com/ops/docker-compose-restart-policies

**Comment by mikejohnstonPremierinc** [comment]
@vietnd96 There are other errors. See below. And these other errors show in the log BEFORE the Docker daemon error. Also, it was not unreachable "randomly". It is unreachable every single time until I remove the docker-node image then redownload the image.

### Other Errors
Exchange checkFor407: no response - java.net.ConnectException: Connection refused

MultiExchange ConnectException (async): retrying...java.net.ConnectException: Connection refused

[SocketTube$InternalReadPublisher$InternalReadSubscription.signalError] - [HttpClient-1-SelectorManager] [278ms] SocketTube(1) got read error: java.io.IOException: connection closed locally

[SocketTube$InternalReadPublisher$InternalReadSubscription.read] - [HttpClient-1-SelectorManager] [279ms] SocketTube(1) error raised before subscriber subscribed: java.io.IOException: connection closed locally
