### ISSUE TITLE
[🐛 Bug]: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.

### ISSUE THREAD

**Issue by ath0mas** [SeleniumHQ/docker-selenium#2023]
### What happened?

Start docker container and try to open session.
For basic testing I use [appium-inspector](https://github.com/appium/appium-inspector) and set 127.0.0.1, port 4444, and path /wd/hub. Then click "Start Session".

Error pops and prevent connection.
More error and trace are logged in `docker logs` for the selenium container.

Last working version: 4.10.0-20230614 (chrome 114.0). 🔙
Failing with `Chrome failed to start: exited normally` with current version 4.15.0-20231122 (chrome 119.0).
And failing in-between, from 4.11 to 4.14, with `Unable to obtain: Capabilities` (chrome 115.0 to 118.0).

### Command used to start Selenium Grid with Docker

```shell
docker run -d -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome:4.15.0-20231122
```

### Relevant log output

```shell
21:51:48.527 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {appium:connectHardwareKeyboard: true, appium:newCommandTimeout: 3600}]
21:51:48.910 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'cf00363c68c0', ip: '172.17.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
21:51:48.927 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'cf00363c68c0', ip: '172.17.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
21:51:48.928 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'cf00363c68c0', ip: '172.17.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:164)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

21:51:48.930 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "561fb92fa99032978ec2f5602cc4fb5f","eventTime": 1700689908910450097,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:30285","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: 'cf00363c68c0', ip: '172.17.0.2'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: 'cf00363c68c0', ip: '172.17.0.2'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:164)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"appium:connectHardwareKeyboard\": true,\"appium:newCommandTimeout\": 3600}\n"}}

21:51:48.931 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "561fb92fa99032978ec2f5602cc4fb5f","eventTime": 1700689908930478492,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {appium:connectHardwareKeyboard: true, appium:newCommandTimeout: 3600}","session.request.downstreamdialect": "[W3C]"}}

21:51:48.933 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "561fb92fa99032978ec2f5602cc4fb5f","eventTime": 1700689908526518499,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {appium:connectHardwareKeyboard: true, appium:newCommandTimeout: 3600}]"}}

21:51:48.934 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'cf00363c68c0', ip: '172.17.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
21:51:48.934 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: 'cf00363c68c0', ip: '172.17.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:225)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

21:51:48.936 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "561fb92fa99032978ec2f5602cc4fb5f","eventTime": 1700689908932822291,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: 'cf00363c68c0', ip: '172.17.0.2'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location \u002fopt\u002fgoogle\u002fchrome\u002fchrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) \nHost info: host: 'cf00363c68c0', ip: '172.17.0.2'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:225)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {appium:connectHardwareKeyboard: true, appium:newCommandTimeout: 3600}]"}}

21:51:48.943 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "561fb92fa99032978ec2f5602cc4fb5f","eventTime": 1700689908942851973,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "127.0.0.1:4444","http.method": "POST","http.request_content_length": "216","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "Mozilla\u002f5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\u002f537.36 (KHTML, like Gecko) appium-inspector\u002f2023.10.4 Chrome\u002f91.0.4472.164 Electron\u002f13.6.9 Safari\u002f537.36"}}
```

### Operating System

Windows 11, Ubuntu 22

### Docker Selenium version (tag)

4.15.0-20231122

**Comment by diemol** [comment]
These capabilities are not enough to create a browser session properly

```
 [Capabilities {appium:connectHardwareKeyboard: true, appium:newCommandTimeout: 3600}]
```

The big change in 4.10.0 was the complete removal of the old JWP protocol. You need to send W3C capabilities.

**Comment by ath0mas** [comment]
Thanks for your quick response, it helps me a lot and better not be a real issue.

Just for you to know, a similar "empty" _capabilities_ sent but to Appium is responding back with an Error response too, but something pretty explicit: `Failed to create session. 'automationName' can't be blank; 'platformName' can't be blank`.
Would it be possible for Selenium to have a similar explicit report with the minimal expected capabilities that are missing. I may create a dedicated issue to ask for this enhancement if you think it is fine.

Edit: indeed a minimal _capabilities_ with `"browserName":"chrome"` is doing it for 4.11+: session created and connection established 👍.

**Comment by diemol** [comment]
You could create it in the upstream Selenium repository.
