### ISSUE TITLE
[🐛 Bug]:   chrome extension start too slow and Concurrency control is very low

### ISSUE THREAD

**Issue by RickJou** [SeleniumHQ/docker-selenium#2079]
### What happened?

I use selenium grid mode to control 2000-5000 chrome nodes, they work well and the response rate is very fast!
Now I need to use chrome extension and then I have disaster!.
5 characters run on a 32cpu 128g ram server (why so much memory is needed, screenshot below)

<img width="898" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/22700839/20a7732b-6750-4462-8182-b40474be0963">

By comparing the difference between not using extensions and using extensions, it is mainly reflected in the huge difference in the time it takes to create WebDriver.
```java

            ChromeOptions options = new ChromeOptions();

            options.addExtensions(new File(crx));// The difference lies in this line

            ClientConfig config = ClientConfig
                        .defaultConfig()
                        .connectionTimeout(Duration.ofDays(2))
                        .readTimeout(Duration.ofDays(2));

                driver = RemoteWebDriver.builder()
                        .address(remoteWebDriverUrl)
                        .config(config)
                        .addAlternative(options)
                        .build();
                driver.manage().window().maximize();
```
It takes 5~6 seconds to start webdriver without extension, and more than 60 seconds with extension.

Without extension, more than 2000 threads can be opened to control 2000+ chrome nodes. If there are more than 50 threads after use, the program may overflow the heap memory and become stuck and unable to operate.

Now I can only make it run slowly by using 32 threads, which is causing me great trouble! 
It took me almost 2 hours to run more than 700 webdrivers. If extension is not needed, it only takes about 2 minutes.

<img width="1573" alt="image" src="https://github.com/SeleniumHQ/docker-selenium/assets/22700839/0392ffab-7f27-4a8b-ad55-3e76a3a1c5ce">

Because the chrome extension is customized and cannot be downloaded from the web store. Is there any way to solve this problem? For example, can the extension be preset in the container before chrome node is started? (I am not sure if this is the key to solving the problem)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
version: "3"
services:
  selenium-event-bus:
    #版本号一定要与maven中nseleium的一致!
    image: selenium/event-bus:4.16.1
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"
    environment:
      - SE_JAVA_OPTS=-Xmx4g -Xms4g -XX:+UseG1GC -DPOOL_MAX=3000

  selenium-sessions:
    image: selenium/sessions:4.16.1
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_JAVA_OPTS=-Xmx6g -Xms6g -XX:+UseG1GC -DPOOL_MAX=3000

  selenium-session-queue:
    image: selenium/session-queue:4.16.1
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    environment:
      - SE_JAVA_OPTS=-Xmx4g -Xms4g -XX:+UseG1GC -DPOOL_MAX=3000
      # 长时间多线程阶段性操作时,先完成任务的线程会进行等待,长时间无动作,导致session id 为null.
      - SE_SESSION_REQUEST_TIMEOUT=18000
      - SE_SESSION_RETRY_INTERVAL=2

  selenium-distributor:
    image: selenium/distributor:4.16.1
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
      - SE_JAVA_OPTS=-Xmx16g -Xms16g -XX:+UseG1GC -DPOOL_MAX=3000

  selenium-router:
    image: selenium/router:4.16.1
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
      - SE_JAVA_OPTS=-Xmx64g -Xms64g -XX:+UseG1GC -DPOOL_MAX=3000


docker run -d --shm-size="2g" -e SE_NODE_SESSION_TIMEOUT=18000 -e SE_EVENT_BUS_HOST=10.170.0.2 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 --net=host selenium/node-chrome:120.0.6099.109-chromedriver-120.0.6099.109-grid-4.16.1-20231219
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Unable to create instance of class org.openqa.selenium.grid.data.SessionRequest
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-26-cloud-amd64', java.version: '11.0.21'
Driver info: driver.version: unknown 
Host info: host: 'selenium-app', ip: '10.170.0.2'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-26-cloud-amd64', java.version: '21'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.getRemoteDriver(RemoteWebDriverBuilder.java:396)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:368)
	at org.selenium.app.ai.task.appWindowTask.run(appWindowTask.java:105)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Operating System

google cloud  debain11 

### Docker Selenium version (image tag)

selenium/node-chrome:120.0.6099.109-chromedriver-120.0.6099.109-grid-4.16.1-20231219

### Selenium Grid chart version (chart version)

selenium/event-bus:4.16.1

**Comment by diemol** [comment]
I think the problem revolves more around the extension's functionality than WebDriver's. It simply executes your commands, so you might want to debug locally to understand why the extension takes longer to load.
