### ISSUE TITLE
[🐛 Bug]: Getting org.openqa.selenium.json.JsonException: Unable to parse while running test on selenium GRID with chrome browser version (lower version)

### ISSUE THREAD

**Issue by naveenanimation20** [SeleniumHQ/docker-selenium#2085]
![Uploading Screenshot 2024-01-09 at 10.51.29 AM.png…]()
### What happened?

Hi Team,
I am getting Json excetpion while running tests on Selenium GRID.
Getting org.openqa.selenium.json.JsonException: Unable to parse while running test on selenium GRID with chrome browser version (lower versions like 90, 91, 79 etc..).

Issue is coming with the latest version of selenium 4.16.1 with chrome version 90.0 or some other lower version. This is just opening the browser but not entering the URL.
Issue is not coming with higher version of chrome like 111, 112, 119, 120 with selenium 4.16.1.

When I downgrade the selenium version to 4.6.0, then this issue is not reproducible and tests are running correctly. 

Platform: MacOS
Grid: Selenium grid / Selenoid both
Chrome version: 90
Selenium version: 4.16.1

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_79.0:
    image: "selenoid/vnc:chrome_79.0"
    container_name: chrome_79.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  chrome_90.0:
    image: "selenoid/vnc:chrome_90.0"
    container_name: chrome_90.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"

  chrome_113.0:
    image: "selenoid/vnc:chrome_113.0"
    container_name: chrome_113.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  chrome_111.0:
    image: "selenoid/vnc:chrome_111.0"
    container_name: chrome_111.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm" 
  chrome_119.0:
    image: "selenoid/vnc:chrome_119.0"
    container_name: chrome_119.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"            
  firefox_57.0:
    image: "selenoid/vnc:firefox_57.0"
    container_name: firefox_57.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  firefox_83.0:
    image: "selenoid/vnc:firefox_83.0"
    container_name: firefox_83.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm" 

                    
networks:
  selenoid:
    external:
      name: selenoid
```

### Relevant log output

```shell
org.openqa.selenium.json.JsonException: Unable to parse: 
	at org.openqa.selenium.json.Json.toType(Json.java:169)
	at org.openqa.selenium.json.Json.toType(Json.java:152)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)

Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '14.0.2'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:467)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:333)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:171)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
	at org.openqa.selenium.json.Json.toType(Json.java:206)
	at org.openqa.selenium.json.Json.toType(Json.java:167)
```

### Operating System

MAC OS

### Docker Selenium version (image tag)

4.16.1

### Selenium Grid chart version (chart version)

0.2.6.2

**Comment by diemol** [comment]
You are using Selenoid, please report this to the Selenoid project.
