### ISSUE TITLE
[🐛 Bug]: High CPU Usage

### ISSUE THREAD

**Issue by matheohan** [SeleniumHQ/docker-selenium#2102]
### What happened?

Selenium/standalone-chrome **takes too much cpu usage**. (running an i5-8500 and it takes about 60% of the cpu !)
(What I do with selenium is running a bot that could theoretically be disconected when the tasks are done and reconnected but either using : driver.close() or driver.quit does not exit gracefully so It break my while loop [python])

In order to solve this issue, I've tried many things, such as : 

- disable VNC with : SE_START_VNC=false (in my docker compose file)
- run headless chrome (with options.add_argument("--headless"))
- change to selenium/standalone-firefox image

none of these works.
The only things thats is working for now is to : 
1. Go to "Sessions" tab
2. Enter in the LiveView (VNC) of the session
3. Click in the bottom part of the window (see the photo below)
![clickhere](https://github.com/SeleniumHQ/docker-selenium/assets/66723357/394e0d76-78cd-4947-9ee9-c5d83320a7cb)
4. Then the VNC seems to be really turned off (I have now a black screen)
5. To note : that this trick only works without using headless and without SE_START_VNC=false
6. Another note : Sometime the VNC seems to restart again, so I have to do this trick again

Anyway, thank you for your amazing work !

**Information** : 
4.16.1 (revision 9b4c83354e)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    container_name: s-chrome
    restart: unless-stopped
    environment:
      - SE_NODE_SESSION_TIMEOUT=86400
      - SE_NODE_MAX_SESSIONS=1
    networks:
      selenium:
        ipv4_address: 172.26.0.3

networks:
  selenium:
    external: true
```

### Relevant log output

```shell
08:13:06.060 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: b1013b6040f305c65958c37800df5bd9
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-13-amd64', java.version: '11.0.21'
Driver info: driver.version: unknown
08:13:06.060 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: b1013b6040f305c65958c37800df5bd9
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-13-amd64', java.version: '11.0.21'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:132)
	at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)
	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
08:13:06.061 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "bed47bdc0460cb562ed9ae95661b2757","eventTime": 1705734786059422024,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: b1013b6040f305c65958c37800df5bd9\nBuild info: version: '4.16.1', revision: '9b4c83354e'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-13-amd64', java.version: '11.0.21'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException:
```

### Operating System

Debian 12

### Docker Selenium version (image tag)

4.16.1 (revision 9b4c83354e)

### Selenium Grid chart version (chart version)

none

**Comment by diemol** [comment]
What process inside the container is using a lot of CPU?

**Comment by matheohan** [comment]
Hi, thank you for the answer. 

However, how can I effectively check this ? (Im using docker and portainer to manage my containers)

Thanks in advance!

**Comment by diemol** [comment]
You can go inside the container and use `top`, or maybe check the portainer docs?

**Comment by matheohan** [comment]
Ok, I found it : Here are the few process that use lot of cpu (It seems that now It doesn't use that much cpu but overtime it will according to last time)



### **UID | PID | PPID | C | STIME | TTY | TIME | CMD** WITH VNC ON (I guess ? I did it by clicking again as shown previously)

`1200 | 957663 | 957643 | 28 | Jan20 | ? | 15:40:28 | /opt/google/chrome/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --enable-logging --log-level=0 --crashpad-handler-pid=197 --enable-crash-reporter=, --user-data-dir=/tmp/.org.chromium.Chromium.xnKAzz --change-stack-guard-on-fork=enable --gpu-preferences=WAAAAAAAAAAgAAAEAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAGAAAAAAAAAAYAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --use-gl=angle --use-angle=swiftshader-webgl --enable-logging --log-level=0 --shared-files --field-trial-handle=0,i,827593321017696264,686851827350985325,262144 --variations-seed-version`

`1200 | 957710 | 957644 | 29 | Jan20 | ? | 16:06:42 | /opt/google/chrome/chrome --type=renderer --crashpad-handler-pid=197 --enable-crash-reporter=, --user-data-dir=/tmp/.org.chromium.Chromium.xnKAzz --disable-nacl --change-stack-guard-on-fork=enable --first-renderer-process --no-sandbox --disable-dev-shm-usage --enable-automation --enable-logging --log-level=0 --remote-debugging-port=0 --test-type=webdriver --allow-pre-commit-input --disable-gpu-compositing --lang=en-US --num-raster-threads=3 --enable-main-frame-before-activation --renderer-client-id=6 --time-ticks-at-unix-epoch=-1699474885553884 --launch-time-ticks=6259932018370 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,827593321017696264,686851827350985325,262144 --variations-seed-version`


`1200 | 165295 | 294796 | 3 | 14:18 | ? | 00:00:20 | python3 -m websockify --web /opt/bin/noVNC/utils/../ 7900 localhost:5900`

### **UID | PID | PPID | C | STIME | TTY | TIME | CMD** WITHOUT 
I have kinda the same results which is kinda weird even if I see the cpu usage dropping a lot !

Thanks again for your help !

**Comment by diemol** [comment]
The process with the most usage is Chrome itself. Chrome uses a considerable amount of RAM and CPU, depending on what you are processing. If you think this is an error, please report it to the Chrome team.

**Comment by matheohan** [comment]
Thank for your answer. 

Yet, could you help me find out what clicking on the bottom of the LiveView window actually does ? 

Thanks in advance ! 

![image](https://github.com/SeleniumHQ/docker-selenium/assets/66723357/52acea98-93ea-48c7-a0e9-dafeb5ba2efc)

EDIT : Added an image and rephrasing the question.

**Comment by diemol** [comment]
I don't understand the question.

**Comment by matheohan** [comment]
I edited my previous answer to clarify my question, sorry.

**Comment by diemol** [comment]
That is the task bar from the Fluxbox Window manager we put on top of Ubuntu. It should do what task bars do.

**Comment by matheohan** [comment]
Ok, so it seems that reducing the application window reduce drastically the cpu usage even if I can still use selenium through python.
