### ISSUE TITLE
[🐛 Bug]: Selenium Hub request calls are occupying all the TCP ports so we are getting error as 'Only one usage of each socket address (protocol/network address/port) is normally permitted.'

### ISSUE THREAD

**Issue by patilsha** [SeleniumHQ/docker-selenium#2121]
### What happened?

We have Selenium Grid 4.16.1 used with chrome node 119
When we are running our scripts on Selenium Grid which is hosted on docker container then after some time of execution we are getting below error for each request and when type a command on command prompt on server from where the scripts executing 'netstat -aon | findstr 4444' then we see all the TCP ports are occupied by Selenium Hub requests
![Socket_Error](https://github.com/SeleniumHQ/docker-selenium/assets/50667616/f688ba14-5b8a-4050-b626-73c9a4fc8b82)

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
We use aws ecs taskdefinitions and farget to create containers for Selenium Hub and Nodes
```

### Relevant log output

```shell
---> System.Net.Http.HttpRequestException: Only one usage of each socket address (protocol/network address/port) is normally permitted. ({Hub_IP}:4444)
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
```

### Operating System

Linux containers provisioned by aws ecs

### Docker Selenium version (image tag)

4.16.1

**Comment by VietND96** [comment]
Can you share the docker-compose file that was used to start?
Is something like `--bind-host=true` or env var `SE_BIND_HOST` is enabled?

**Comment by patilsha** [comment]
@vietnd96 I'm using docker image inside aws ecs container so I'm not using any specific docker-compose file.
I haven't set this env variable, can you please elaborate what is the purpose of this env variable and how can it help to resolve above issue?
Basically the issue is, thousands of ports are getting occupied by hub Url with TIME_WAIT state, I'm not sure that is triggering it. 
I'm observing it on Grid version 4.15 and also 4.16.1 and Chrome v119 and v120

**Comment by VietND96** [comment]
@diemol, do you know about this behavior?

**Comment by diemol** [comment]
I've never seen that, but I am pretty sure it has to be related to the environment. Maybe some networking config that triggers that for some reason.

@patilsha do you get the same behavior on your own machine? What have you tried to diagnose the problem?

**Comment by patilsha** [comment]
Thanks diemol, I have checked my network configuration where we had some discrepancies after making those fixes we are not getting the above issue. I'm closing this ticket since the issue was with network configuration.
