### ISSUE TITLE
[🐛 Bug]: running selenium/standalone-chrome as user 1000

### ISSUE THREAD

**Issue by rob-bankers** [SeleniumHQ/docker-selenium#2142]
### What happened?

Hi,

The selenium/standalone-chrome, which used to run with user 1000 and group 1000, is no longer functional in release 1.20.0. It now requires initiation with user 1200 and group 1201. Is this intentional?

This is still working:

`docker run --user 1200:1201 \
           selenium/standalone-chrome:120.0`

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run --user 1000:1000 \
           selenium/standalone-chrome:121.0
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.1', 'console_scripts', 'supervisord')())
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 361, in main
    go(options)
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 371, in go
    d.main()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 72, in main
    self.options.make_logger()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1470, in make_logger
    loggers.handle_file(
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 417, in handle_file
    handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 213, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
    self.stream = open(filename, mode)
PermissionError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log'
Error: exit status 1
```

### Operating System

MacOS Rancher Desktop

### Docker Selenium version (image tag)

selenium/standalone-chrome:121.0

**Comment by VietND96** [comment]
`docker run --user 1000 selenium/standalone-chrome:121.0` with different users only, it would work.
In case both UID and GID are different, it won't work probably, since permissions scope `777` before was updated to `775` in some directories.
There was a hack to overcome mentioned in https://github.com/SeleniumHQ/docker-selenium/pull/2056#issuecomment-1874142701. Can you take a look?

**Comment by rob-bankers** [comment]
Issue solved by using 1200:1201 user and group.
