### ISSUE TITLE
Docker hub is refusing to connect a node from remote machine.

### ISSUE THREAD

**Issue by dgangwar** [SeleniumHQ/docker-selenium#215]
Command used  - 

docker run -d -p 5567:5567 -e REMOTE_HOST="http://10.52.8.39:4444" -e HUB_PORT_4444_TCP_ADDR="10.52.8.39:4444" -e HUB_PORT_4444_TCP_PORT="4444" --name firefox-debug11 selenium/node-firefox-debug:2.53.0

Hub Container logs ******************
2016-04-27 10:43:16.472:WARN:osjs.ServletHandler:qtp1897115967-410: /grid/register
java.security.InvalidParameterException: Error: Not a correct url to register a remote : 10.52.8.39:4444
    at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:433)
    at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:86)
    at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)

Node Container log ****************

Failed to read: session.screen0.iconbar.usePixmap
Setting default value
03:34:15.830 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:15.834 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:20.839 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:20.842 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:25.845 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:25.849 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:30.851 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:30.860 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:35.863 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:35.867 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:40.869 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:40.873 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:45.876 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:45.879 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:50.882 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:50.886 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:34:55.888 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:34:55.892 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
03:35:00.894 INFO - Registering the node to the hub: http://10.52.8.39:4444/grid/register
03:35:00.899 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error

**Comment by tommywo** [comment]
try changing HUB_PORT_4444_TCP_ADDR to "10.52.8.39"

**Comment by diemol** [comment]
@dgangwar are you still having this issue after trying @tommywo's suggestion with the latest images?

**Comment by diemol** [comment]
Closing this issue as we didn't get feedback from the OP.
