### ISSUE TITLE
[🐛 Bug]: opentelemetry-exporter-otlp not found on classpath

### ISSUE THREAD

**Issue by Doofus100500** [SeleniumHQ/docker-selenium#2151]
### What happened?

The problem described in this issue https://github.com/SeleniumHQ/docker-selenium/issues/1883, which was fixed by this pull request https://github.com/SeleniumHQ/docker-selenium/pull/1941/files, is occurring again.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm
```

### Relevant log output

```shell
Starting Selenium Grid Node...
2024-02-27 12:34:07,082 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-02-27 12:34:07,083 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-02-27 12:34:07,083 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
12:34:07.172 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
12:34:07.240 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
12:34:07.353 INFO [AutoConfiguredOpenTelemetrySdkBuilder.build] - Error encountered during autoconfiguration. Closing partially configured components.
12:34:07.353 ERROR [Bootstrap.runMain] - Error during execution
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
    at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: otel.traces.exporter set to "otlp" but opentelemetry-exporter-otlp not found on classpath. Make sure to add it as a dependency.
    at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:95)
    at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:67)
    at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:55)
    at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:416)
    at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:85)
    at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:59)
    at org.openqa.selenium.grid.log.LoggingOptions.getTracer(LoggingOptions.java:93)
    at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:113)
    at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:185)
    at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:247)
    at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
    at org.openqa.selenium.grid.Main.launch(Main.java:83)
    at org.openqa.selenium.grid.Main.go(Main.java:56)
    at org.openqa.selenium.grid.Main.main(Main.java:41)
    ... 6 more
Exception in thread "Thread-0" java.lang.NullPointerException
    at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

### Operating System

k8s

### Docker Selenium version (image tag)

4.18.1-20240224

### Selenium Grid chart version (chart version)

0.28.3

**Comment by VietND96** [comment]
It looks like missing SE_ENABLE_TRACING=true ?

**Comment by VietND96** [comment]
https://github.com/SeleniumHQ/docker-selenium/blob/cd49f199dc180c24a888ea5286b6664a24cdd8eb/NodeBase/start-selenium-node.sh#L105
Once SE_ENABLE_TRACING=true, classpath related to OpenTelemetry will be loaded

**Comment by Doofus100500** [comment]
I pass SE_ENABLE_TRACING like this:
```
# Custom environment variables for all components
extraEnvironmentVariables:
  - name: SE_SESSION_REQUEST_TIMEOUT
    value: "1800"
  - name: SE_ENABLE_TRACING
    value: "true"
  - name: SE_JAVA_OPTS
    value: "-Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint=https://somehost -Dotel.resource.attributes=service.name=selenium-grid-staging -Dotel.exporter.otlp.traces.compression-jar=gzip"
```

**Comment by Doofus100500** [comment]
Now I understand, it's necessary to specify for the node as well. Thank you very much!

**Comment by VietND96** [comment]
@Doofus100500, I think you no need to remember to pass extra vars to which components anymore. From `0.28.x` via `tracing.enabled` (Jaeger will be installed together) or `tracing.enabledWithExistingEndpoint` (export to your existing endpoint)
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid/templates/logging-configmap.yaml will take care
