### ISSUE TITLE
[🐛 Bug]: Unable to deploy node-docker in Kubernetes/OpenShifte

### ISSUE THREAD

**Issue by addihorn** [SeleniumHQ/docker-selenium#2162]
### What happened?

I am trying to set up a scalable lab into Kubernetes using the node-docker-Image.
To expose docker I use a small weight solution [kubedock](https://github.com/joyrex2001/kubedock) which exposes Docker in TCP-Port 2475.
Kubedock runs as a sidecar to selenium/node-docker.

When starting the pod selenium-node is getting an error with message `Unable to reach the Docker daemon at http://127.0.0.1:2475`, but in the sidecar container, I can see a connection attempt.

```
I0307 09:08:26.404490 1 main.go:29] kubedock 0.15.5-2-g02adb37 (20240305-195234) / kubedock.id=6e6919d568e5
I0307 09:08:26.406262 1 main.go:108] kubernetes config: namespace=selenium-lab, initimage=joyrex2001/kubedock:0.15.5, dindimage=joyrex2001/kubedock:0.15.5, ready timeout=1m0s
I0307 09:08:26.407491 1 main.go:160] reaper started with max container age 1h0m0s
I0307 09:08:26.407735 1 main.go:128] default image pull policy: ifnotpresent
I0307 09:08:26.407836 1 main.go:131] service account used in deployments: default
I0307 09:08:26.407906 1 main.go:135] using namespace: selenium-lab
[GIN] 2024/03/07 - 09:08:29 | 200 | 88.242µs | 127.0.0.1 | GET "/version"
[GIN] 2024/03/07 - 09:09:03 | 200 | 62.119µs | 127.0.0.1 | GET "/version"
```

When connection to the pod and trying to access the docker API via the defined URL I get following message.

```
$ curl http://127.0.0.1:2475/version
{"ApiVersion":"1.25","Arch":"amd64","BuildTime":"20240305-195234","GitCommit":"02adb37840db81f6750a9271961b7a8edd7f4909","GoVersion":"go1.21.8","MinAPIVersion":"1.25","Os":"linux","Version":"1.25"}
```
which from my understanding delivers the docker-version:
```
// Version - get version.
// https://docs.docker.com/engine/api/v1.41/#operation/SystemVersion
// GET "/version"
func Version(cr *common.ContextRouter, c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{
		"Version":       config.DockerVersion,
		"ApiVersion":    config.DockerAPIVersion,
		"MinAPIVersion": config.DockerAPIVersion,
		"GitCommit":     config.Build,
		"BuildTime":     config.Date,
		"GoVersion":     config.GoVersion,
		"Os":            config.GOOS,
		"Arch":          config.GOARCH,
	})
}
```
[(see here)](https://github.com/joyrex2001/kubedock/blob/master/internal/server/routes/docker/system.go)

Is there anything I am doing wrng, or is this setup just not supported?

Thanks

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: selenium-hub-dynamic-node
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: selenium-hub-dynamic-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium-hub-dynamic-node
    spec:
      restartPolicy: Always
      serviceAccountName: deployer
      containers:
        - name: selenium-node
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub-svc
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: '4442'
            - name: NODE_MAX_INSTANCES
              value: '2'
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: '4443'
            - name: DOCKER_HOST
              value: 'tcp://127.0.0.1:2475'
          ports:
            - containerPort: 5900
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: dynamic-selenium
              mountPath: /opt/bin/config.toml
              subPath: config.toml
          image: 'docker.io/selenium/node-docker:4.18.0-20240220'
        - name: docker-sidecar
          image: 'docker.io/joyrex2001/kubedock:latest'
          ports:
            - containerPort: 2475
              protocol: TCP
          resources: {}
          startupProbe:
            tcpSocket:
              port: 2475
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      serviceAccount: deployer
      volumes:
        - name: dynamic-selenium
          configMap:
            name: selenium-docker-dynamic-node
            defaultMode: 420
      dnsPolicy: ClusterFirst
      imagePullSecrets: []
  paused: false
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-docker-dynamic-node

data:
  config.toml: >-
    [docker]

    configs = [
        "selenium/standalone-firefox:4.18.1-20240224", '{"browserName": "firefox"}',
        "selenium/standalone-chrome:4.18.1-20240224", '{"browserName": "chrome"}',
        "selenium/standalone-edge:4.18.1-20240224", '{"browserName": "MicrosoftEdge"}'
    ]

    url = "http://127.0.0.1:2475"
immutable: false

---
```

### Relevant log output

```shell
2024-03-07 09:08:24,998 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-docker.conf" during parsing
2024-03-07 09:08:25,006 INFO RPC interface 'supervisor' initialized
2024-03-07 09:08:25,006 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-03-07 09:08:25,007 INFO supervisord started with pid 8
2024-03-07 09:08:26,013 INFO spawned: 'socat' with pid 9
2024-03-07 09:08:26,017 INFO spawned: 'selenium-grid-docker' with pid 10
Starting Selenium Grid Node Docker...
Tracing is disabled
2024-03-07 09:08:26,038 INFO success: socat entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-03-07 09:08:26,038 INFO success: selenium-grid-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-03-07 09:08:26,038 INFO exited: socat (exit status 0; expected)
09:08:26.949 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
09:08:26.956 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:08:27.147 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub-svc:4442 and tcp://selenium-hub-svc:4443
09:08:27.277 INFO [UnboundZmqEventBus.<init>] - Sockets created
09:08:28.281 INFO [UnboundZmqEventBus.<init>] - Event bus ready
09:08:28.582 INFO [NodeServer.createHandlers] - Reporting self as: http://10.129.2.97:5555
09:08:28.628 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
09:08:29.336 ERROR [Bootstrap.runMain] - Error during execution
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
	at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:181)
	at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
	at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:185)
	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:247)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:56)
	at org.openqa.selenium.grid.Main.main(Main.java:41)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
	at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
	... 14 more
Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://127.0.0.1:2475
	at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:124)
	at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:92)
	... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-03-07 09:08:29,685 INFO exited: selenium-grid-docker (exit status 1; not expected)
```

### Operating System

Kubernetes (OpenShift 4)

### Docker Selenium version (image tag)

4.18.0-20240220

**Comment by diemol** [comment]
This setup is not supported. You should check the Helm chart.
