### ISSUE TITLE
[🐛 Bug]: SE_OPTS values set are not applied to chrome pod on K8

### ISSUE THREAD

**Issue by kherath17** [SeleniumHQ/docker-selenium#2165]
### What happened?

I'm trying to apply below SE_OPTS to create a new node with defined capabilities, the pod gets created but the stereotype configs are not what I have mentioned.

Furthermore, I'm trying to forward the request received to this node pod to browser stack via a relay, how can I achieve that?
Eg:-  `--service-url`

```dockerfile
apiVersion: v1
kind: Pod
metadata:
  name: chrome-test-node
  labels:
    name: chrome-test-node
    app: chrome-test-node
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: chrome-test-node
      image: selenium/node-chrome:latest #4.13.0-20231004
      ports:
        - containerPort: 4444
      env:
        - name: GENERATE_CONFIG
          value: "false"
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"    
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"        
        - name: SE_OPTS
          value: --driver-configuration stereotype='{"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
``` 

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
via K8 deployment files
```

### Relevant log output

```shell
Node has been Added (this is without the stereotype configs mentioned)
```

### Operating System

Kubernetes - EKS

### Docker Selenium version (image tag)

4.17.0

**Comment by VietND96** [comment]
Via pod logs, do you see logs e.g `Appending Selenium options: ...` with your inputs correctly?

**Comment by kherath17** [comment]
@VietND96  Re-Correction, while I was creating the pod earlier `GENERATE_CONFIGS` was set to `true` , hence ignored what I have set

Slightly modified the pod file as below:

```dockerfile
apiVersion: v1
kind: Pod
metadata:
  name: chrome-test-node
  labels:
    name: chrome-test-node
    app: chrome-test-node
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: chrome-test-node
      image: selenium/node-chrome:latest
      ports:
        - containerPort: 4444
      env:
        - name: GENERATE_CONFIG
          value: "false"
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"    
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"        
        - name: SE_OPTS
          value: --driver-configuration display-name="chrome" stereotype='{"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
``` 

but now when I set it to false runs into below error log.

```
024-03-12 10:54:14,266 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-03-12 10:54:14,269 INFO RPC interface 'supervisor' initialized
2024-03-12 10:54:14,269 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-03-12 10:54:14,270 INFO supervisord started with pid 8
2024-03-12 10:54:15,273 INFO spawned: 'xvfb' with pid 9
2024-03-12 10:54:15,275 INFO spawned: 'vnc' with pid 10
2024-03-12 10:54:15,276 INFO spawned: 'novnc' with pid 11
2024-03-12 10:54:15,279 INFO spawned: 'selenium-node' with pid 12
2024-03-12 10:54:15,286 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --driver-configuration display-name="chrome" stereotype='{"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
Appending Selenium options: --session-timeout 300
Appending Selenium options: --heartbeat-period 30
Tracing is disabled
Selenium Grid Node configuration:
Starting Selenium Grid Node...
2024-03-12 10:54:16,329 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-12 10:54:16,329 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-12 10:54:16,329 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
10:54:16.365 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
10:54:16.378 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:54:16.613 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
10:54:16.714 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:54:17.729 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:54:18.192 INFO [NodeServer.createHandlers] - Reporting self as: http://10.133.13.151:5555
10:54:18.265 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
10:54:18.269 INFO [NodeOptions.discoverDrivers] - Looking for existing drivers on the PATH.
10:54:18.270 INFO [NodeOptions.discoverDrivers] - Add '--selenium-manager true' to the startup command to setup drivers automatically.
10:54:18.454 ERROR [Bootstrap.runMain] - Error during execution
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:181)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:185)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:247)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: '{"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
        at org.openqa.selenium.json.Json.toType(Json.java:169)
        at org.openqa.selenium.json.Json.toType(Json.java:152)
        at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$10(NodeOptions.java:434)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.openqa.selenium.grid.node.config.NodeOptions.lambda$addDriverConfigs$11(NodeOptions.java:430)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.openqa.selenium.grid.node.config.NodeOptions.addDriverConfigs(NodeOptions.java:370)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:245)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: '. Last 1 characters read: ', next 114 characters to read: {"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.209-198.812.amzn2.x86_64', java.version: '11.0.21'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:166)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:167)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:146)
        at org.openqa.selenium.json.Json.toType(Json.java:206)
        at org.openqa.selenium.json.Json.toType(Json.java:167)
        ... 30 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-03-12 10:54:18,838 INFO exited: selenium-node (exit status 1; not expected)
2024-03-12 10:54:18,839 WARN received SIGINT indicating exit request
2024-03-12 10:54:18,839 INFO waiting for xvfb, vnc, novnc to die
2024-03-12 10:54:20,842 INFO stopped: novnc (terminated by SIGTERM)
2024-03-12 10:54:21,845 INFO stopped: vnc (terminated by SIGTERM)
2024-03-12 10:54:21,845 INFO waiting for xvfb to die
2024-03-12 10:54:22,847 INFO stopped: xvfb (terminated by SIGTERM)
```

**Comment by kherath17** [comment]
**Latest Update**: managed to resolve the json parse issue now the pod is stuck at `Sending registration Event`

```dockerfile
apiVersion: v1
kind: Pod
metadata:
  name: chrome-test-node
  labels:
    name: chrome-test-node
    app: chrome-test-node
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - name: chrome-test-node
      image: selenium/node-chrome:latest
      ports:
        - containerPort: 4444
      env:
        - name: GENERATE_CONFIG
          value: "false"
        - name: SE_EVENT_BUS_HOST
          value: "selenium-hub"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"    
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"        
        - name: SE_OPTS          
          value: '--driver-configuration display-name="chrome" stereotype="{\"browserName\":\"chrome\",\"browserVersion\":\"103.0\",\"platformName\":\"Android\",\"networkname:applicationName\":\"node_1\"}"'

``` 


Log:

```
2024-03-12 12:31:11,094 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-03-12 12:31:11,097 INFO RPC interface 'supervisor' initialized
2024-03-12 12:31:11,097 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-03-12 12:31:11,097 INFO supervisord started with pid 8
2024-03-12 12:31:12,100 INFO spawned: 'xvfb' with pid 9
2024-03-12 12:31:12,103 INFO spawned: 'vnc' with pid 10
2024-03-12 12:31:12,105 INFO spawned: 'novnc' with pid 11
2024-03-12 12:31:12,107 INFO spawned: 'selenium-node' with pid 12
2024-03-12 12:31:12,114 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --driver-configuration display-name="chrome" stereotype="{\"browserName\":\"chrome\",\"browserVersion\":\"103.0\",\"platformName\":\"Linux\",\"networkname:applicationName\":\"node_1\"}"
Appending Selenium options: --session-timeout 300
Appending Selenium options: --heartbeat-period 30
Tracing is disabled
Selenium Grid Node configuration:
Starting Selenium Grid Node...
12:31:13.049 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
12:31:13.058 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
2024-03-12 12:31:13,142 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-12 12:31:13,142 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-12 12:31:13,142 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
12:31:13.233 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
12:31:13.296 INFO [UnboundZmqEventBus.<init>] - Sockets created
12:31:14.299 INFO [UnboundZmqEventBus.<init>] - Event bus ready
12:31:14.445 INFO [NodeServer.createHandlers] - Reporting self as: http://10.133.13.153:5555
12:31:14.468 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
12:31:14.469 INFO [NodeOptions.discoverDrivers] - Looking for existing drivers on the PATH.
12:31:14.470 INFO [NodeOptions.discoverDrivers] - Add '--selenium-manager true' to the startup command to setup drivers automatically.
12:31:14.539 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "103.0","networkname:applicationName": "node_1","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 4 times
12:31:14.542 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 4 times
12:31:14.581 INFO [Node.<init>] - Binding additional locator mechanisms: relative
12:31:14.758 INFO [NodeServer$1.start] - Starting registration process for Node http://10.133.13.153:5555
12:31:14.759 INFO [NodeServer.execute] - Started Selenium node 4.18.1 (revision b1d3319b48): http://10.133.13.153:5555
12:31:14.782 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:31:24.802 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:31:34.809 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:31:44.814 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:31:54.819 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:32:04.822 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:32:14.826 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:32:24.829 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

_Bckground info - Im trying to create this pod with stereotype configs having Android as Platform so I can use it to take up incoming Android requests and forward to a 3rd party vendor , how can this be achieved ? is it possible via `--service-url`?_

**Comment by VietND96** [comment]
Probably due to this `12:31:13.233 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443`
when `GENERATE_CONFIG` is `false`
`SE_EVENT_BUS_HOST` is only set to config.toml, without generating config, there is no host info pass to CLI to start Node

**Comment by kherath17** [comment]
okay but setting `GENERATE_CONFIG` to `true` ignores stereotype configs I have set

**Comment by VietND96** [comment]
I see, will have an update on this

**Comment by VietND96** [comment]
Within `GENERATE_CONFIG` is true, lets try to set stereotype via `SE_NODE_STEREOTYPE`

**Comment by kherath17** [comment]
Thank You it applied the configs , is there a possibility to set the `--service-url` similarly so that any requests pointing to this node can be forwarded to a 3rd party cloud service

**Comment by VietND96** [comment]
How about if `--service-url` passing to `SE_OPTS`?

**Comment by kherath17** [comment]
POD is created but I dont see it getting forwaded to the vendor , it gets executed within the browser pod itself

```
- name: SE_OPTS                   
  value: '--service-url https://<username>:<token>@hub-cloud.browserstack.com/wd/hub'
```

Log

```
2024-03-13 05:02:51,425 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-03-13 05:02:51,428 INFO RPC interface 'supervisor' initialized
2024-03-13 05:02:51,428 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-03-13 05:02:51,429 INFO supervisord started with pid 8
2024-03-13 05:02:52,431 INFO spawned: 'xvfb' with pid 9
2024-03-13 05:02:52,433 INFO spawned: 'vnc' with pid 10
2024-03-13 05:02:52,436 INFO spawned: 'novnc' with pid 11
2024-03-13 05:02:52,438 INFO spawned: 'selenium-node' with pid 12
2024-03-13 05:02:52,445 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Appending Selenium options: --service-url https://<username>:<token>@hub-cloud.browserstack.com/wd/hub
Appending Selenium options: --session-timeout 300
Appending Selenium options: --heartbeat-period 30
Generating Selenium Config
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Setting up SE_NODE_GRID_URL...
Tracing is disabled
Selenium Grid Node configuration:
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
drain-after-session-count = 0
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName":"chrome","browserVersion":"103.0","platformName":"Android","networkname:applicationName":"node_1"}'
max-sessions = 1

Starting Selenium Grid Node...
05:02:53.341 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
05:02:53.347 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
2024-03-13 05:02:53,469 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-13 05:02:53,469 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-13 05:02:53,469 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
05:02:53.487 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
05:02:53.554 INFO [UnboundZmqEventBus.<init>] - Sockets created
05:02:54.557 INFO [UnboundZmqEventBus.<init>] - Event bus ready
05:02:54.799 INFO [NodeServer.createHandlers] - Reporting self as: http://10.133.13.185:5555
05:02:54.842 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
05:02:54.938 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "103.0","networkname:applicationName": "node_1","platformName": "ANDROID","se:noVncPort": 7900,"se:vncEnabled": true} 1 times
05:02:54.972 INFO [Node.<init>] - Binding additional locator mechanisms: relative
05:02:55.163 INFO [NodeServer$1.start] - Starting registration process for Node http://10.133.13.185:5555
05:02:55.165 INFO [NodeServer.execute] - Started Selenium node 4.18.1 (revision b1d3319b48): http://10.133.13.185:5555
05:02:55.179 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
05:02:55.349 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
05:02:57.227 INFO [LocalNode.newSession] - Session created by the Node. Id: 18628a8c1c2889dae7c1e8f093468ee0, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 122.0.6261.69, chrome: {chromedriverVersion: 122.0.6261.69 (81bc525b6a36..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45091}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: ANDROID, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://10.133.13.185:4444/ses..., se:cdpVersion: 122.0.6261.69, se:vnc: ws://10.133.13.185:4444/ses..., se:vncEnabled: true, se:vncLocalAddress: ws://10.133.13.185:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

```

**Comment by kherath17** [comment]
Issue resolved via defining configs via a config map, closing this thanks!

**Comment by VietND96** [comment]
@kherath17, how a config.toml for relay works look like? Can you share an example here?

**Comment by kherath17** [comment]
sure @VietND96 , below is a sample .toml file 

```
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"

[node]
grid-url = "https:/<gridendpoint>/<path>"
detect-drivers = false

[relay]
# Cloud server endpoint
url = "https://<thirdpartyendpoint>/wd/hub"
status-endpoint = "/status"
# Stereotypes Configs
configs = [
  "10", '{"browserName": "chrome", "platformName": "Windows 11", "browserVersion": "116","networkname:applicationName":"bs"}'
]

```

Note - as I cheked , the toml file should always be named exactly as config.toml , if named otherwise would create an additional file in opt/selenium/ direcotry which makes the default config.toml created empty,  resulting in configurations not been applied.
