### ISSUE TITLE
[🐛 Bug]: unable to upgrade Selenium 3 to Selenium 4

### ISSUE THREAD

**Issue by andrewetobin** [SeleniumHQ/docker-selenium#2179]
### What happened?

I'm looking to upgrade Selenium from 3.141.59 to 4.1.2.

When kicking off an automated run with kubernetes, the tests are unable to run. Looks like the nodes are not able to connect. Kubernetes dashboard shows the repeated attempts to register. 
 - Sending registration event...
 
 Chrome.yaml file
```
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-chrome
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-chrome
spec:
  replicas: {{ .Values.chrome.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-chrome
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-chrome
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
        - name: {{ .Chart.Name }}-chrome
          image: {{ .Values.chrome.image.repository }}:{{ .Values.chrome.image.tag }}
          imagePullPolicy: {{ .Values.chrome.image.pullPolicy }}
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: DISPLAY
              value: ":99.0"
            - name: JAVA_OPTS
              value: "-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: "3600"
            - name: SE_NODE_MAX_SESSIONS
              value: "{{ .Values.chrome.instances }}"
            - name: SE_NODE_OVERRIDE_MAX_SESSIONS
              value: "true"
            - name: SE_NODE_GRID_URL
              value: "http://selenium-hub:4444"
            - name: SE_NODE_HOST
              value: "selenium-chrome-node"
            - name: SE_NODE_PORT
              value: "5555"
          resources:
            limits:
              cpu: {{ .Values.chrome.resources.limits.cpu }}
              memory: {{ .Values.chrome.resources.limits.memory }}
            requests:
              cpu: {{ .Values.chrome.resources.requests.cpu }}
              memory: {{ .Values.chrome.resources.requests.memory }}
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      imagePullSecrets:
        - name: docker-hub-secret
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```

ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.global.ingress.sslRedirect }}"
spec:
  rules:
  - host: selenium.{{ .Release.Namespace }}{{ .Values.global.ingress.hostPostfix }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 4444


```

selenium.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
  template:
    metadata:
      labels:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag }}
        imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
        env:
        - name: GRID_BROWSER_TIMEOUT
          value: "3400"
        - name: GRID_TIMEOUT
          value: "3600"
        ports:
        - name: selenium-hub
          containerPort: 4444
        volumeMounts:
        - name: dev-shm
          mountPath: /dev/shm
        resources:
          limits:
            cpu: {{ .Values.hub.resources.limits.cpu }}
            memory: {{ .Values.hub.resources.limits.memory }}
          requests:
            cpu: {{ .Values.hub.resources.requests.cpu }}
            memory: {{ .Values.hub.resources.requests.memory }}
      imagePullSecrets:
      - name: docker-hub-secret
      volumes:
      - name: dev-shm
        hostPath:
          path: /dev/shm

```
service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - name: "selenium-hub"
      port: 4444
      targetPort: 4444
    - name: "subscribe-events"
      port: 4443
      targetPort: 4443
    - name: "publish-events"
      port: 4442
      targetPort: 4442
  selector:
```

chart.yaml

```
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: selenium-hub
version: 0.1.0
```

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
helm delete --purge selenium-stable

# Install selenium with the adjacent selenium-values.yaml.
helm install --name selenium-stable -f selenium-values.yaml stable/selenium --namespace selenium

kubectl apply -f selenium.yml
```

### Relevant log output

```shell
Test Console log:
java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
    Build info: version: '4.1.2', revision: '9a5a329c5a'
    System info: host: 'run-ui-cust-test-dv-26541-994-d4x0f-0pk5z', ip: '10.0.11.32', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.219-164.354.amzn2.x86_64', java.version: '1.8.0_212'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors], extensions: []}}}]
    Capabilities {}
    	at com.zenplanner.ZenPlannerLocomotiveBasePartition.initDriver(ZenPlannerLocomotiveBasePartition.java:224)
    	at com.zenplanner.ZenPlannerLocomotiveBasePartition.setup(ZenPlannerLocomotiveBasePartition.java:177)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    	at org.springframework.test.context.junit4.statements.RunPrepareTestInstanceCallbacks.evaluate(RunPrepareTestInstanceCallbacks.java:64)
    	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    	at org.springframework.test.context.junit4.statements.SpringFailOnTimeout.evaluate(SpringFailOnTimeout.java:87)
    	at org.springframework.test.context.junit4.statements.ProfileValueChecker.evaluate(ProfileValueChecker.java:103)
    	at com.zenplanner.helpers.RetryRule$1.evaluate(RetryRule.java:42)
    	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.junit.runners.Suite.runChild(Suite.java:128)
    	at org.junit.runners.Suite.runChild(Suite.java:27)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    	at org.springframework.test.context.junit4.statements.ProfileValueChecker.evaluate(ProfileValueChecker.java:103)
    	at org.springframework.test.context.junit4.rules.SpringClassRule$TestContextManagerCacheEvictor.evaluate(SpringClassRule.java:190)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at com.zenplanner.helpers.PackageSuite.runChild(PackageSuite.java:121)
    	at com.zenplanner.helpers.PackageSuite.runChild(PackageSuite.java:21)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
    Build info: version: '4.1.2', revision: '9a5a329c5a'
    System info: host: 'run-ui-cust-test-dv-26541-994-d4x0f-0pk5z', ip: '10.0.11.32', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.219-164.354.amzn2.x86_64', java.version: '1.8.0_212'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors], extensions: []}}}]
    Capabilities {}
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)
    	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
    	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
    	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
    	at com.zenplanner.ZenPlannerLocomotiveBasePartition.initDriver(ZenPlannerLocomotiveBasePartition.java:219)
    	... 51 common frames omitted
    Caused by: java.io.UncheckedIOException: java.net.UnknownHostException: selenium
    	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:80)
    	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:80)
    	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
    	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
    	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
    	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:80)
    	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
    	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
    	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
    	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$6(RetryRequest.java:80)
    	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:66)
    	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
    	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
    	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
    	at org.openqa.selenium.remote.http.RetryRequest.lambda$apply$7(RetryRequest.java:80)
    	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
    	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
    	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:110)
    	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
    	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
    	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
    	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
    	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
    	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
    	... 55 common frames omitted
    Caused by: java.net.UnknownHostException: selenium
    	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
    	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
    	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
    	at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)
    	at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)
    	at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:50)
    	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
    	at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
    	at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:50)
    	at org.asynchttpclient.netty.request.NettyRequestSender.resolveAddresses(NettyRequestSender.java:364)
    	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:307)
    	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:143)
    	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:114)
    	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
    	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
    	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:249)
    	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:57)




Kubernetes dashboard logs

node:
2024-04-02 18:26:20,644 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-04-02 18:26:20,646 INFO supervisord started with pid 8
2024-04-02 18:26:21,648 INFO spawned: 'xvfb' with pid 10
2024-04-02 18:26:21,649 INFO spawned: 'vnc' with pid 11
2024-04-02 18:26:21,651 INFO spawned: 'novnc' with pid 12
2024-04-02 18:26:21,653 INFO spawned: 'selenium-node' with pid 13
2024-04-02 18:26:21,669 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-04-02 18:26:21,669 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-04-02 18:26:21,669 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-04-02 18:26:21,669 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Generating Selenium Config
Selenium Grid Node configuration: 
[events]
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"
[server]
host = "selenium-chrome-node"
port = "5555"
[node]
grid-url = "http://selenium-hub:4444"
session-timeout = "300"
override-max-sessions = true
detect-drivers = false
max-sessions = 2
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "99.0", "platformName": "Linux"}'
max-sessions = 2
Starting Selenium Grid Node...
18:26:22.511 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
18:26:22.515 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
18:26:22.699 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
18:26:22.788 INFO [UnboundZmqEventBus.<init>] - Sockets created
18:26:23.789 INFO [UnboundZmqEventBus.<init>] - Event bus ready
18:26:23.896 INFO [NodeServer.createHandlers] - Reporting self as: http://selenium-chrome-node:5555
18:26:23.916 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
18:26:23.916 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 2 concurrent sessions. Session stability and reliability might suffer!
18:26:23.917 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
18:26:23.917 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
18:26:23.917 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
18:26:23.997 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "99.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 2 times
18:26:24.008 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:26:24.263 INFO [NodeServer$1.start] - Starting registration process for node id 2b15d183-63ba-4ca8-9f47-971304ecfb11
18:26:24.264 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://selenium-chrome-node:5555
18:26:24.267 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:26:34.271 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:26:44.274 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:26:54.277 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:04.280 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:14.282 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:24.284 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:34.286 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:44.287 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:27:54.289 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:28:04.291 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:28:14.293 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
18:28:24.266 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
Logs from Apr 2, 2024 to Apr 2, 2024 UTC


hub:
2024-04-02 18:26:33,073 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2024-04-02 18:26:33,074 INFO supervisord started with pid 8
2024-04-02 18:26:34,076 INFO spawned: 'selenium-grid-hub' with pid 10
2024-04-02 18:26:35,147 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
18:26:35.166 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
18:26:35.170 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
18:26:35.651 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.0.7.250:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.0.7.250:4443]
18:26:35.955 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.0.7.250:4442 and tcp://10.0.7.250:4443
18:26:36.060 INFO [UnboundZmqEventBus.<init>] - Sockets created
18:26:37.062 INFO [UnboundZmqEventBus.<init>] - Event bus ready
18:26:39.653 INFO [Hub.execute] - Started Selenium Hub 4.1.2 (revision 9a5a329c5a): http://10.0.7.250:4444
18:26:43.455 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:26:56.722 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:27:08.740 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:27:20.757 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:27:32.790 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:27:44.806 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:27:56.825 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:28:08.849 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:28:20.864 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:28:32.876 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:28:44.923 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:28:56.936 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:29:08.954 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:29:20.967 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:29:32.981 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:29:44.995 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:29:57.009 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:30:09.025 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:30:21.044 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:30:33.058 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:30:45.076 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:30:57.089 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:31:09.102 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:31:21.114 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:31:33.132 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:31:45.144 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:31:57.159 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:32:09.171 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:32:21.184 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:32:33.197 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:32:45.226 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:32:57.265 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:33:09.277 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:33:21.287 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:33:33.300 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:33:45.312 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:33:57.338 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:34:09.350 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:34:21.362 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:34:33.373 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:34:45.388 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:34:57.399 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:35:09.422 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:35:21.434 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:35:33.445 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:35:45.455 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:35:57.467 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:36:09.489 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:36:21.506 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:36:33.519 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:36:45.531 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:36:57.541 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:37:09.553 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:37:21.564 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:37:33.580 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:37:45.590 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:37:57.601 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:38:09.611 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:38:21.695 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:38:33.706 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:38:45.723 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:38:57.735 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:39:09.745 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:39:21.778 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:39:33.790 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:39:45.804 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
18:39:57.836 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:40:09.848 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:40:21.860 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:40:33.877 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:40:45.888 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:40:57.902 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:41:09.934 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
18:41:21.945 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:41:33.961 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:41:45.980 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:41:57.996 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:42:10.007 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
18:42:23.224 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
18:42:35.236 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:42:47.245 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:43:23.216 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
18:43:35.237 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:43:47.253 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
18:44:23.215 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
```

### Operating System

4.14.219-164.354.amzn2.x86_64

### Docker Selenium version (image tag)

4.1.2

**Comment by diemol** [comment]
Could you please use recent versions of the Helm chart and let us know if the issue persists?

**Comment by andrewetobin** [comment]
I updated the selenium/Chart.yaml file to:
```
apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium grid server in Kubernetes
type: application
version: 0.2.0
appVersion: 4.1.2
```
Test run fails with this error:
Error: found in requirements.yaml, but missing in charts/ directory: selenium-hub

**Comment by andrewetobin** [comment]
> Could you please use recent versions of the Helm chart and let us know if the issue persists?

Where can I find versions of the Helm chart for Selenium 4.1.2? I've yet to find them.

**Comment by diemol** [comment]
I believe it does not exist. It was when charts were hosted on the helm repository and they got deprecated.

Why do you need such an old version? Please note we don't support old Selenium versions, so if you bump into an issue we can't do much.

**Comment by andrewetobin** [comment]
> I believe it does not exist. It was when charts were hosted on the helm repository and they got deprecated.
> 
> Why do you need such an old version? Please note we don't support old Selenium versions, so if you bump into an issue we can't do much.

We initially tried to upgrade to a more recent version. We ran into quite a few issues with dependencies and deprecated methods. We backtracked in the hope to just make the connection. 

Thanks for the info, do you have a version to recommend?  I can start working to upgrade to that version.

**Comment by diemol** [comment]
We only support the latest version, so that is the recommended one. You can always use the latest on the Grid side and move your client test code base to recent Selenium versions. If you need more help, please use the links below.
