### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.WebDriverException: Message: <empty>

### ISSUE THREAD

**Issue by tamis-laan** [SeleniumHQ/docker-selenium#2285]
### What happened?

I'm trying to run the selenium helm chart and connecting using python:

``` yaml
hub:
  image:
    repository: selenium/hub
    tag: 4.22.0
  service:
    type: LoadBalancer

videoRecorder:
  enabled: true

chromeNode:
  replicas: 2
  image:
    repository: selenium/node-chrome
    tag: 4.22.0

firefoxNode:
  enabled: false

edgeNode:
  enabled: false

ingress:
  enabled: false

```

``` python
# Configure Chrome options for headless mode
chrome_options = Options()
# chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument("--disable-popup-blocking")
chrome_options.add_argument("--disable-features=Notification")

# Allow microphone and webcam
chrome_options.add_experimental_option("prefs", {
    "profile.default_content_setting_values.media_stream_mic": 2,
    "profile.default_content_setting_values.media_stream_camera": 2,
    "profile.default_content_setting_values.geolocation": 2,
    "profile.default_content_setting_values.notifications": 2,
    "profile.default_content_setting_values.popups": 2,
    "profile.default_content_setting_values.automatic_downloads": 2
})

# Create a new instance of the Chrome driver
# driver = webdriver.Chrome(options=chrome_options)
driver = webdriver.Remote(
    command_executor="http://selenium-grid-selenium-hub.default.svc.cluster.local:4444/wd/hub",
    options=chrome_options
)
```

But I get the following error:

```
      > [test-6f444dfcc7-85wrl test] Traceback (most recent call last):
      > [test-6f444dfcc7-85wrl test]   File "/app/main.py", line 33, in <module>
      > [test-6f444dfcc7-85wrl test]     driver = webdriver.Remote(
      > [test-6f444dfcc7-85wrl test]              ^^^^^^^^^^^^^^^^^
      > [test-6f444dfcc7-85wrl test]   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
      > [test-6f444dfcc7-85wrl test]     self.start_session(capabilities)
      > [test-6f444dfcc7-85wrl test]   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
      > [test-6f444dfcc7-85wrl test]     response = self.execute(Command.NEW_SESSION, caps)["value"]
      > [test-6f444dfcc7-85wrl test]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > [test-6f444dfcc7-85wrl test]   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
      > [test-6f444dfcc7-85wrl test]     self.error_handler.check_response(response)
      > [test-6f444dfcc7-85wrl test]   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
      > [test-6f444dfcc7-85wrl test]     raise exception_class(value)
      > [test-6f444dfcc7-85wrl test] selenium.common.exceptions.WebDriverException: Message:
```

The error message non descriptive as the it's empty. 

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
#! /bin/bash

# Add docker-selenium helm repository
helm repo add docker-selenium https://www.selenium.dev/docker-selenium

# Make sure system is running properly
kubectl wait --for=condition=Ready pods --all --namespace=kube-system --timeout=300s

# Install basic grid latest version
helm upgrade --install selenium-grid docker-selenium/selenium-grid \
	-f values.yaml
```

### Relevant log output

```shell
No logs are produced by selenium hub
```

### Operating System

Minikube

### Docker Selenium version (image tag)

4.22.0

**Comment by VietND96** [comment]
When helm install (upgrade) successfully, a note displays with the Hub URL that can be accessed from outside. What is it?
Also, may I know if these values worked with the previous chart version?

**Comment by tamis-laan** [comment]
@VietND96
 
```
"docker-selenium" already exists with the same configuration, skipping
pod/etcd-minikube condition met
pod/kube-apiserver-minikube condition met
pod/kube-controller-manager-minikube condition met
pod/kube-scheduler-minikube condition met
pod/storage-provisioner condition met
Release "selenium-grid" does not exist. Installing it now.
NAME: selenium-grid
LAST DEPLOYED: Sat Jun 22 20:17:29 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Selenium Grid Server deployed successfully.
    export POD_NAME=$(kubectl get pods -n default -l "app.kubernetes.io/name=selenium-grid-selenium-hub,app.kubernetes.io/instance=selenium-grid" -o jsonpath="{.items[0].metadata.name}")
    echo "Point your WebDriver tests to http://localhost:4444/wd/hub"
    kubectl -n default port-forward $POD_NAME 4444:4444

2. Within Kubernetes cluster, you can use following Service endpoint:
        http://selenium-grid-selenium-hub.default.svc:4444
```

I changed the url to:

``` python
driver = webdriver.Remote(
    # command_executor="http://selenium-grid-selenium-hub.default.svc.cluster.local:4444/wd/hub",
    command_executor="http://selenium-grid-selenium-hub.default.svc:4444",
    options=chrome_options
)
```

I also tried `http://selenium-grid-selenium-hub.default.svc:4444/wd/hub` but in both cases same error.

BTW nothing is logged by the hub deployment when trying to connect.

**Comment by VietND96** [comment]
When you running the script on host, I don't think host could reach the DNS `selenium-grid-selenium-hub.default.svc`
Try to following steps to expose Hub to host port 4444
```
export POD_NAME=$(kubectl get pods -n default -l "app.kubernetes.io/name=selenium-grid-selenium-hub,app.kubernetes.io/instance=selenium-grid" -o jsonpath="{.items[0].metadata.name}")
kubectl -n default port-forward $POD_NAME 4444:4444
```
Then point your WebDriver tests to http://localhost:4444/wd/hub

**Comment by tamis-laan** [comment]
@VietND96 
I'm stupid but not that stupid ;-) 

No I'm running the script as a kubernetes deployment in the same default namespace. I also tested it using a port forward as you described and I get the same error message.

**Comment by VietND96** [comment]
I am not sure how the service type LoadBalancer works in Minikube. I would suggest another config that you can try
```yaml
hub:
  serviceType: NodePort
```
And in script connect to http://localhost:31444/wd/hub

**Comment by tamasfe** [comment]
I have run into this as well after bumping the chart version from `0.14.3` (yeah quite a leap).

Turns out the empty message shown by the python client is accompanied by a `401` status code because basic auth was changed to be enabled by default in the chart.

Setting the following chart value should resolve the issue:

```yaml
basicAuth:
  enabled: false
```

I don't know about the reasoning behind enabling basic auth by default, I'd not expect it, especially since it is just `admin:admin` anyway. To make it actually useful one has to be aware that the option exists, and at that point it can be enabled if needed.

**Comment by VietND96** [comment]
@tamasfe, thank you for your answer. It's correct, the basic auth is enabled by default in chart. In this case, the grid URL in binding would be
```python
driver = webdriver.Remote(
    command_executor="http://admin:admin@localhost:4444",
    options=chrome_options
)
```

**Comment by VietND96** [comment]
Exception message from the binding is improved via https://github.com/SeleniumHQ/selenium/pull/14601
