### ISSUE TITLE
[🐛 Bug]: Continue to have problem connecting to :4317

### ISSUE THREAD

**Issue by daynefiler** [SeleniumHQ/docker-selenium#2415]
### What happened?

Seems to be the same issue as #2355. This is my first time using / trying to use Selenium so I am sorry for any ignorances.

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run -d -p 4445:4444 selenium/standalone-firefox
```

### Relevant log output

```shell
2024-09-30 15:20:31 2024-09-30 19:20:31,088 INFO Included extra file "/etc/supervisor/conf.d/firefox-cleanup.conf" during parsing
2024-09-30 15:20:31 2024-09-30 19:20:31,088 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2024-09-30 15:20:31 2024-09-30 19:20:31,090 INFO RPC interface 'supervisor' initialized
2024-09-30 15:20:31 2024-09-30 19:20:31,090 INFO supervisord started with pid 8
2024-09-30 15:20:32 2024-09-30 19:20:32,098 INFO spawned: 'xvfb' with pid 9
2024-09-30 15:20:32 2024-09-30 19:20:32,100 INFO spawned: 'vnc' with pid 10
2024-09-30 15:20:32 2024-09-30 19:20:32,101 INFO spawned: 'novnc' with pid 11
2024-09-30 15:20:32 2024-09-30 19:20:32,103 INFO spawned: 'selenium-standalone' with pid 12
2024-09-30 15:20:32 2024-09-30 19:20:32,108 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-09-30 15:20:32 2024-09-30 19:20:32,108 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-09-30 15:20:32 2024-09-30 19:20:32,108 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-09-30 15:20:32 2024-09-30 19:20:32,108 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-09-30 15:20:32 Appending Selenium option: --heartbeat-period 30
2024-09-30 15:20:32 Appending Selenium option: --log-level INFO
2024-09-30 15:20:32 Appending Selenium option: --http-logs false
2024-09-30 15:20:32 Appending Selenium option: --structured-logs false
2024-09-30 15:20:32 Appending Selenium option: --reject-unsupported-caps true
2024-09-30 15:20:32 Setting up SE_NODE_GRID_URL...
2024-09-30 15:20:32 Selenium Grid Standalone configuration: 
2024-09-30 15:20:32 [network]
2024-09-30 15:20:32 relax-checks = true
2024-09-30 15:20:32 
2024-09-30 15:20:32 [node]
2024-09-30 15:20:32 session-timeout = "300"
2024-09-30 15:20:32 override-max-sessions = false
2024-09-30 15:20:32 detect-drivers = false
2024-09-30 15:20:32 drain-after-session-count = 0
2024-09-30 15:20:32 max-sessions = 1
2024-09-30 15:20:32 
2024-09-30 15:20:32 [[node.driver-configuration]]
2024-09-30 15:20:32 display-name = "firefox"
2024-09-30 15:20:32 stereotype = '{"browserName": "firefox", "browserVersion": "131.0", "platformName": "Linux", "moz:firefoxOptions": {"binary": "/usr/bin/firefox"}, "se:containerName": ""}'
2024-09-30 15:20:32 max-sessions = 1
2024-09-30 15:20:32 
2024-09-30 15:20:32 Starting Selenium Grid Standalone...
2024-09-30 15:20:32 Tracing is enabled
2024-09-30 15:20:32 Classpath will be enriched with these external jars :  --ext /external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp/1.40.0/opentelemetry-exporter-otlp-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/grpc/grpc-netty/1.65.1/grpc-netty-1.65.1.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.111.Final/netty-codec-http-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk-trace/1.40.0/opentelemetry-sdk-trace-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk-metrics/1.40.0/opentelemetry-sdk-metrics-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk-logs/1.40.0/opentelemetry-sdk-logs-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp-common/1.40.0/opentelemetry-exporter-otlp-common-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-sender-okhttp/1.40.0/opentelemetry-exporter-sender-okhttp-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.40.0/opentelemetry-sdk-extension-autoconfigure-spi-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/grpc/grpc-api/1.65.1/grpc-api-1.65.1.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-codec-http2/4.1.100.Final/netty-codec-http2-4.1.100.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/grpc/grpc-core/1.65.1/grpc-core-1.65.1.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-handler-proxy/4.1.100.Final/netty-handler-proxy-4.1.100.Final.jar:/external_jars/https/repo1.maven.org/maven2/com/google/guava/guava/32.1.3-android/guava-32.1.3-android.jar:/external_jars/https/repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.23.0/error_prone_annotations-2.23.0.jar:/external_jars/https/repo1.maven.org/maven2/io/perfmark/perfmark-api/0.26.0/perfmark-api-0.26.0.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.1.111.Final/netty-transport-native-unix-common-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/grpc/grpc-util/1.65.1/grpc-util-1.65.1.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.111.Final/netty-common-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.111.Final/netty-buffer-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.111.Final/netty-transport-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-codec/4.1.111.Final/netty-codec-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-handler/4.1.111.Final/netty-handler-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-api/1.40.0/opentelemetry-api-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk-common/1.40.0/opentelemetry-sdk-common-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-api-incubator/1.40.0-alpha/opentelemetry-api-incubator-1.40.0-alpha.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-common/1.40.0/opentelemetry-exporter-common-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/4.12.0/okhttp-4.12.0.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-sdk/1.40.0/opentelemetry-sdk-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/external_jars/https/repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar:/external_jars/https/repo1.maven.org/maven2/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/external_jars/https/repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.23/animal-sniffer-annotations-1.23.jar:/external_jars/https/repo1.maven.org/maven2/io/grpc/grpc-context/1.65.1/grpc-context-1.65.1.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-codec-socks/4.1.100.Final/netty-codec-socks-4.1.100.Final.jar:/external_jars/https/repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/external_jars/https/repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/external_jars/https/repo1.maven.org/maven2/org/checkerframework/checker-qual/3.37.0/checker-qual-3.37.0.jar:/external_jars/https/repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar:/external_jars/https/repo1.maven.org/maven2/io/netty/netty-resolver/4.1.111.Final/netty-resolver-4.1.111.Final.jar:/external_jars/https/repo1.maven.org/maven2/io/opentelemetry/opentelemetry-context/1.40.0/opentelemetry-context-1.40.0.jar:/external_jars/https/repo1.maven.org/maven2/com/squareup/okio/okio/3.6.0/okio-3.6.0.jar:/external_jars/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.9.10/kotlin-stdlib-jdk8-1.9.10.jar:/external_jars/https/repo1.maven.org/maven2/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar:/external_jars/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.10/kotlin-stdlib-1.9.10.jar:/external_jars/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.9.10/kotlin-stdlib-jdk7-1.9.10.jar:/external_jars/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.9.10/kotlin-stdlib-common-1.9.10.jar:/external_jars/https/repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.jar
2024-09-30 15:20:32 List arguments for OpenTelemetry:  -Dotel.resource.attributes=service.name=selenium-standalone -Dotel.traces.exporter=otlp -Dotel.java.global-autoconfigure.enabled=true
2024-09-30 15:20:32 19:20:32.654 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
2024-09-30 15:20:32 19:20:32.657 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
2024-09-30 15:20:33 19:20:32.999 INFO [NodeOptions.getSessionFactories] - Detected 10 available processors
2024-09-30 15:20:33 19:20:33.022 INFO [NodeOptions.report] - Adding firefox for {"browserName": "firefox","browserVersion": "131.0","moz:firefoxOptions": {"binary": "\u002fusr\u002fbin\u002ffirefox"},"platformName": "linux","se:containerName": "","se:noVncPort": 7900,"se:vncEnabled": true} 1 times
2024-09-30 15:20:33 19:20:33.034 INFO [Node.<init>] - Binding additional locator mechanisms: relative
2024-09-30 15:20:33 19:20:33.042 INFO [GridModel.setAvailability] - Switching Node e2a4ff6c-18e9-4fa3-ad2e-75f76e4e2343 (uri: http://172.17.0.2:4444) from DOWN to UP
2024-09-30 15:20:33 19:20:33.043 INFO [LocalDistributor.add] - Added node e2a4ff6c-18e9-4fa3-ad2e-75f76e4e2343 at http://172.17.0.2:4444. Health check every 120s
2024-09-30 15:20:33 19:20:33.112 INFO [Standalone.execute] - Started Selenium Standalone 4.24.0 (revision 748ffc9bc3): http://172.17.0.2:4444
2024-09-30 15:20:47 19:20:47.825 INFO [LocalDistributor$NewSessionRunnable.checkMatchingSlot] - No nodes support the capabilities in the request: []
2024-09-30 15:20:47 19:20:47.831 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "88d20bcef2de708e0021a65642ee3126","eventTime": 1727724047830305919,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4445","http.method": "POST","http.request_content_length": "124","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "libcurl\u002f8.6.0 r-curl\u002f4.3.2 httr\u002f1.4.2"}}
2024-09-30 15:20:47 
2024-09-30 15:20:52 19:20:52.819 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-09-30 15:21:09 19:21:09.598 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: NA
2024-09-30 15:21:09 Build info: version: '4.24.0', revision: '748ffc9bc3'
2024-09-30 15:21:09 System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'
2024-09-30 15:21:09 Driver info: driver.version: unknown
2024-09-30 15:21:09 19:21:09.598 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: NA
2024-09-30 15:21:09 Build info: version: '4.24.0', revision: '748ffc9bc3'
2024-09-30 15:21:09 System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'
2024-09-30 15:21:09 Driver info: driver.version: unknown
2024-09-30 15:21:09     at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:116)
2024-09-30 15:21:09     at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
2024-09-30 15:21:09     at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)
2024-09-30 15:21:09     at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
2024-09-30 15:21:09     at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:397)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:09     at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
2024-09-30 15:21:09     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:09     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
2024-09-30 15:21:09     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:09     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2024-09-30 15:21:09     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:09     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
2024-09-30 15:21:09     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-09-30 15:21:09     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-09-30 15:21:09     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-09-30 15:21:09     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-09-30 15:21:09     at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-30 15:21:09 
2024-09-30 15:21:09 19:21:09.599 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "a0fa04cb082aa734021c18a2363ea077","eventTime": 1727724069596865679,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: NA\nBuild info: version: '4.24.0', revision: '748ffc9bc3'\nSystem info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: NA\nBuild info: version: '4.24.0', revision: '748ffc9bc3'\nSystem info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:116)\n\tat org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:397)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:87)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:840)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "localhost:4445","http.method": "POST","http.request_content_length": "33","http.scheme": "HTTP","http.target": "\u002fsession\u002fNA\u002furl","http.user_agent": "libcurl\u002f8.6.0 r-curl\u002f4.3.2 httr\u002f1.4.2","session.id": "NA"}}
2024-09-30 15:21:09 
2024-09-30 15:21:12 19:21:12.843 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-09-30 15:21:15 19:21:15.965 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: NA
2024-09-30 15:21:15 Build info: version: '4.24.0', revision: '748ffc9bc3'
2024-09-30 15:21:15 System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'
2024-09-30 15:21:15 Driver info: driver.version: unknown
2024-09-30 15:21:15 19:21:15.965 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: NA
2024-09-30 15:21:15 Build info: version: '4.24.0', revision: '748ffc9bc3'
2024-09-30 15:21:15 System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'
2024-09-30 15:21:15 Driver info: driver.version: unknown
2024-09-30 15:21:15     at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:116)
2024-09-30 15:21:15     at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
2024-09-30 15:21:15     at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)
2024-09-30 15:21:15     at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
2024-09-30 15:21:15     at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:397)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:15     at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
2024-09-30 15:21:15     at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
2024-09-30 15:21:15     at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
2024-09-30 15:21:15     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:15     at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
2024-09-30 15:21:15     at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
2024-09-30 15:21:15     at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
2024-09-30 15:21:15     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-09-30 15:21:15     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-09-30 15:21:15     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-09-30 15:21:15     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-09-30 15:21:15     at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-30 15:21:15 
2024-09-30 15:21:15 19:21:15.966 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "1ebbf6f77b7ee3fbb1d7e9589b89f879","eventTime": 1727724075964113668,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: NA\nBuild info: version: '4.24.0', revision: '748ffc9bc3'\nSystem info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: NA\nBuild info: version: '4.24.0', revision: '748ffc9bc3'\nSystem info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.10.4-linuxkit', java.version: '17.0.12'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:116)\n\tat org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:397)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:87)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:360)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:840)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "localhost:4445","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002fNA\u002furl","http.user_agent": "libcurl\u002f8.6.0 r-curl\u002f4.3.2 httr\u002f1.4.2","session.id": "NA"}}
2024-09-30 15:21:15 
2024-09-30 15:21:17 19:21:17.855 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
```

### Operating System

Mac OS 14.5

### Docker Selenium version (image tag)

130.0-geckodriver-0.35-20240922

### Selenium Grid chart version (chart version)

4.24.0 (revision 748ffc9bc3)

**Comment by VietND96** [comment]
Hi, can you share the test that you executed also? I want to see steps to create RemoteWebDriver
Since I saw this message `2024-09-30 15:20:47 19:20:47.825 INFO [LocalDistributor$NewSessionRunnable.checkMatchingSlot] - No nodes support the capabilities in the request: []`

**Comment by VietND96** [comment]
I added a note to README for the resolution - https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#tracing-in-grid
