### ISSUE TITLE
[🐛 Bug]: Upgrading to selenium/standalone-chrome:127.0 Gives 'DevToolsActivePort file doesn't exist' and cannot start chrome

### ISSUE THREAD

**Issue by EuclidHeron** [SeleniumHQ/docker-selenium#2417]
### What happened?

 have the following docker file and everything works fine (I can make calls to websites, etc) with with 126.0 using headless=new . But when I upgrade to 127.0 I get an error (note session not created: DevToolsActivePort file doesn't exist).

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
Dockerfile:

ARG CHROME_VERSION=127.0

# Stage 1: Pre-built Selenium Standalone Chrome image
FROM selenium/standalone-chrome:${CHROME_VERSION} as chrome

# See https://hub.docker.com/_/amazoncorretto
# Stage 2: Use Amazon Corretto as the base image, can also do 'FROM amazoncorretto:17' to get latest
FROM amazoncorretto:17.0.11-al2
# Currently using latest corretto; if need to fix a version then do amazoncorretto:17.0.8-al2

#https://stackoverflow.com/questions/45323271/how-to-run-selenium-with-chrome-in-docker
#https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-wsl-windows-subsystem-for-linux
# Install necessary dependencies to run chrome in headless mode
RUN yum install -y libX11 libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs libXScrnSaver libXrandr alsa-lib pango atk at-spi2-atk gtk3 coreutils

# Copy Chrome and ChromeDriver from the first stage
COPY --from=chrome /usr/bin/chromedriver /usr/bin/chromedriver
COPY --from=chrome /opt/google/chrome/ /opt/google/chrome/

# Set environment variables for Chrome and ChromeDriver
ENV CHROME_BIN=/opt/google/chrome/google-chrome
ENV CHROMEDRIVER_BIN=/usr/bin/chromedriver

# In the original consulting file CHROMEDRIVER_PORT, CHROMEDRIVER_WHITELISTED_IPS, and CHROMEDRIVER_URL_BASE are not set
ENV CHROMEDRIVER_PORT 4444
ENV CHROMEDRIVER_WHITELISTED_IPS "127.0.0.1"
ENV CHROMEDRIVER_URL_BASE ''

# App Setup
EXPOSE 8080
EXPOSE 5005

# Copy application JAR into the image
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Run application
# Note timeout value should be set to be at least resourceleak.maxLifetimeMs
ENTRYPOINT ["java","-jar", "-Xmx600m", "/app.jar"]
```

I am also using:
```
        chromeOptions.addArguments("--headless=new");
        arguments.add("disable-infobars");
        arguments.add("--disable-gpu");
        arguments.add("--no-sandbox");
        arguments.add("--incognito");
        arguments.add("--disable-application-cache");
        arguments.add("--disable-dev-shm-usage");
```
```


### Relevant log output

```shell
Error is:

Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: '564b16878950', ip: '172.17.0.2'
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.16-linuxkit', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [user-agent=Mozilla/5.0 (Mac..., --disable-extensions, --disable-gpu, --no-sandbox, --incognito, --disable-application-cache, --disable-dev-shm-usage], extensions: []}, pageLoadStrategy: eager}]}]' ExceptionUtils.getStackTrace='org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: '564b16878950', ip: '172.17.0.2'
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.16-linuxkit', java.version: '17.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [user-agent=Mozilla/5.0 (Mac..., --disable-extensions, --disable-gpu, --no-sandbox, --incognito, --disable-application-cache, --disable-dev-shm-usage], extensions: []}, pageLoadStrategy: eager}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)

```
```


### Operating System

Ubuntu

### Docker Selenium version (image tag)

4.25.0

### Selenium Grid chart version (chart version)

_No response_

**Comment by VietND96** [comment]
Did it work before? Note that, in node-chrome image, we have a step to wrap google-chrome package https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeChrome/wrap_chrome_binary
Original google-chrome renamed to `/usr/bin/google-chrome-base`
And `/usr/bin/google-chrome` is the wrap script

**Comment by mikegoldy** [comment]
I am having the exact same issue. It used to work, new chrome browser is causing it to fail.

**Comment by VietND96** [comment]
I haven't reproduced with the shared Dockerfile yet. However, I see the strategy is coping `/opt/google/chrome/` and `/usr/bin/chromedriver` from source docker-selenium image.
In docker-selenium image, google-chrome is installed via `apt`. If any dependencies are in the .deb package, they will be installed together by `apt`. I guess sometime, copying chrome package is not enough.
Moreover, from chrome image v127, the base OS Ubuntu upgraded from 22.04 to 24.04 - https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.23.0-20240727 - I think this could be a reason

**Comment by VietND96** [comment]
I think you can run your built image, exec to the container and launch `google-chrome` to see what error it returned.

**Comment by EuclidHeron** [comment]
Hi @VietND96 thanks for your comment! Just to check, when executing google chrome is there any special command I should run, or just `./opt/google/chrome/google-chrome`? I am currently installing:
```
RUN yum install -y libX11 libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs libXScrnSaver libXrandr alsa-lib pango atk at-spi2-atk gtk3 coreutils
```
That used to work - are there other libraries I should install?

**Comment by EuclidHeron** [comment]
@VietND96 I ssh'd into my container and then ran the following (and got the following result):
```
bash-4.2# ./opt/google/chrome/google-chrome
/opt/google/chrome/google-chrome-base: symbol lookup error: /opt/google/chrome/google-chrome-base: undefined symbol: ippValidateAttributes
```

**Comment by EuclidHeron** [comment]
@VietND96 I also did the following if it helps:
```
Step 0:
Add 'wget' to the yum install list of where you define 'RUN yum install -y' in the Dockerfile

Step 1: get into the docker file
docker exec -it angry_matsumoto /bin/bash

Step 2
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

Step 3
run the following
bash-4.2# rpm -qp google-chrome-stable_current_x86_64.rpm --requires

warning: google-chrome-stable_current_x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 9b30acf2: NOKEY
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/usr/sbin/update-alternatives
/usr/sbin/update-alternatives
ca-certificates
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.2.5)(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
libX11.so.6()(64bit)
libXcomposite.so.1()(64bit)
libXdamage.so.1()(64bit)
libXext.so.6()(64bit)
libXfixes.so.3()(64bit)
libXrandr.so.2()(64bit)
libasound.so.2()(64bit)
libasound.so.2(ALSA_0.9)(64bit)
libasound.so.2(ALSA_0.9.0rc4)(64bit)
libatk-1.0.so.0()(64bit)
libatk-bridge-2.0.so.0()(64bit)
libatspi.so.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.11)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.16)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.18)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.25)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.5)(64bit)
libc.so.6(GLIBC_2.6)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libcairo.so.2()(64bit)
libcups.so.2()(64bit)
libcurl.so.4()(64bit)
libdbus-1.so.3()(64bit)
libdbus-1.so.3(LIBDBUS_1_3)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libdrm.so.2()(64bit)
liberation-fonts
libexpat.so.1()(64bit)
libgbm.so.1()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.3)(64bit)
libgcc_s.so.1(GCC_4.2.0)(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgtk-3.so.0()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libnspr4.so()(64bit)
libnss3.so()(64bit)
libnss3.so(NSS_3.11)(64bit)
libnss3.so(NSS_3.12)(64bit)
libnss3.so(NSS_3.12.1)(64bit)
libnss3.so(NSS_3.12.4)(64bit)
libnss3.so(NSS_3.2)(64bit)
libnss3.so(NSS_3.22)(64bit)
libnss3.so(NSS_3.3)(64bit)
libnss3.so(NSS_3.30)(64bit)
libnss3.so(NSS_3.31)(64bit)
libnss3.so(NSS_3.39)(64bit)
libnss3.so(NSS_3.4)(64bit)
libnss3.so(NSS_3.5)(64bit)
libnss3.so(NSS_3.6)(64bit)
libnss3.so(NSS_3.7)(64bit)
libnss3.so(NSS_3.9.2)(64bit)
libnssutil3.so()(64bit)
libnssutil3.so(NSSUTIL_3.12.3)(64bit)
libpango-1.0.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libpthread.so.0(GLIBC_2.3.3)(64bit)
libpthread.so.0(GLIBC_2.3.4)(64bit)
libsmime3.so()(64bit)
libsmime3.so(NSS_3.10)(64bit)
libsmime3.so(NSS_3.2)(64bit)
libudev.so.1()(64bit)
libudev.so.1(LIBUDEV_183)(64bit)
libvulkan.so.1()(64bit)
libxcb.so.1()(64bit)
libxkbcommon.so.0()(64bit)
libxkbcommon.so.0(V_0.5.0)(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
wget
xdg-utils

```

Does that help?

**Comment by mikegoldy** [comment]
I don't use docker selenium image, I use this:

```
FROM python:3.11.2-slim-bullseye

# Install tools
RUN apt-get update && apt-get install -y \
  curl \
  unzip \
  wget \
  vim

# Get chrome versions here: https://googlechromelabs.github.io/chrome-for-testing/

# install Chrome
RUN wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && apt-get install /tmp/chrome.deb -y \
  && rm -rf /var/lib/apt/lists/*

# install Chromedriver
RUN CHROMEDRIVER_VERSION=$(google-chrome --version | grep -oP '(?<=Google Chrome )[\d.]+') \
  && wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip
RUN unzip /tmp/chromedriver.zip && rm -dfr chromedriver_linux64.zip\
  && mv /chromedriver-linux64/chromedriver /usr/bin/chromedriver \
  && chmod +x /usr/bin/chromedriver


# set display port to avoid crash
ENV DISPLAY=:99
```

This used to work until google-chrome stable changed to version 129 actually

**Comment by EuclidHeron** [comment]
I was able to get it working with the following. There were two main issues:
1) I thought I was using al2023 (Amazon Linux 2023) but I was using AL2
2) I needed to add some more dependencies

```
ARG CHROME_VERSION=129.0
# Stage 1: Pre-built Selenium Standalone Chrome image
FROM selenium/standalone-chrome:${CHROME_VERSION} as chrome

FROM amazoncorretto:17.0.12-al2023
RUN yum install -y libX11 libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs libXScrnSaver libXrandr alsa-lib pango atk at-spi2-atk gtk3 nss cups wget libdrm mesa-libgbm

# Copy Chrome and ChromeDriver from the first stage
COPY --from=chrome /usr/bin/chromedriver /usr/bin/chromedriver
COPY --from=chrome /opt/google/chrome/ /opt/google/chrome/

# Set environment variables for Chrome and ChromeDriver
ENV CHROME_BIN=/opt/google/chrome/google-chrome
ENV CHROMEDRIVER_BIN=/usr/bin/chromedriver

# In the original consulting file CHROMEDRIVER_PORT, CHROMEDRIVER_WHITELISTED_IPS, and CHROMEDRIVER_URL_BASE are not set
ENV CHROMEDRIVER_PORT 4444
ENV CHROMEDRIVER_WHITELISTED_IPS "127.0.0.1"
ENV CHROMEDRIVER_URL_BASE ''

# App Setup
EXPOSE 8080

# Copy application JAR into the image
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar", "-Xmx600m", "/app.jar"]
```

**Comment by VietND96** [comment]
Thanks for your sharing. So, as I mentioned above, with this build image strategy, you have to identify and update the list of dependencies needed if there is something new in `google-chrome`.
Next time, you can verify the browser launch by starting the container, then exec to it and launching browser with a sample URL, ensuring the browser can keep running.

```bash
$ docker exec -it trusting_herschel bash
seluser@25ba535d6826:/$ google-chrome --incognito https://selenium.dev
[1121:1146:1010/130020.633617:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Created TensorFlow Lite XNNPACK delegate for CPU.
...
```
No actionable from the project origin images
