### ISSUE TITLE
[🐛 Bug]: Can't start 2 sessions

### ISSUE THREAD

**Issue by fruitoiz** [SeleniumHQ/docker-selenium#2536]
### What happened?

I opened a session in 1 script and am trying to open a session in the second, but it does not open and the script waits endlessly when I force close the script this appears:

Both scripts are the same:

script 1:
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
options = Options()
options.add_argument('--font-render-hinting=none')
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Remote(options=options, command_executor="http://localhost:4444")
```

script 2:
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
options = Options()
options.add_argument('--font-render-hinting=none')
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Remote(options=options, command_executor="http://localhost:4444")  #changing the port to 5900 does not help, I checked

```

maybe I'm doing something wrong?

Docker version 27.4.1, build b9d17ea

### Command used to start Selenium Grid with Docker (or Kubernetes)

```shell
docker run --rm -it -p 4444:4444 -p 5900:5900 --shm-size 2g --cpus="2" --memory="3g" -v /root/BOTS:/app     selenium/standalone-chromium:latest
```

### Relevant log output

```shell
15:24:42.109 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "e47c37bebc6afa549d6b8fbcaa7c64ed","eventTime": 1735140282108321128,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "249","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.27.1 (python linux)"}}


15:24:47.885 ERROR [ThrottlingLogger.doLog] - Failed to export spans. The request could not be executed. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.opentelemetry.exporter.sender.okhttp.internal.RetryInterceptor.intercept(RetryInterceptor.java:91)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
        Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:4317
                ... 21 more
        Caused by: java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnect(Native Method)
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
                at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
                at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
                at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
                at java.base/java.net.Socket.connect(Socket.java:633)
                at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
                at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
                ... 20 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 20 more
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Docker Selenium version (image tag)

4.27.0-20241204

**Comment by VietND96** [comment]
Hi, the logs not point to the issue that you want to mention. While starting the container, let's set `-e SE_ENABLE_TRACING=false` to filter out that logs.

**Comment by fruitoiz** [comment]
-e SE_ENABLE_TRACING=false
This helped to remove the warnings. But still can't create another driver when one is already working. How to fix this?

**Comment by VietND96** [comment]
What if the options just set these args?
```
options = Options()
options.add_argument('--headless=new')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
```

**Comment by diemol** [comment]
Containers have per default one session, please check the docs https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#increasing-session-concurrency-per-container
