### ISSUE TITLE
Missing Nodes in Grid Console

### ISSUE THREAD

**Issue by emoshaya-cognito** [SeleniumHQ/docker-selenium#317]
I'm trying to link node-chrome-debug to the selenium grid but nothing appears in the web ui console. I am using docker-compose to start the grid as follows:

docker-compose -f docker_selenium_grid.yml up -d

`selenium-hub:
  container_name: selenium-hub
  image: selenium/hub
  ports:
    - "4444:4444"
  volumes:
    - /var/lib/jenkins/workspace:/var/lib/jenkins/workspace
  environment:
    - GRID_TIMEOUT=500000
    - GRID_MAX_SESSION=50
    - GRID_BROWSER_TIMEOUT=600000
    - SE_OPTS=-debug

chrome:
  image: selenium/node-chrome-debug
  environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  ports:
    - 5900
  links:
    - selenium-hub
  volumes:
    - /dev/shm:/dev/shm
  volumes_from:
    - selenium-hub
`

![image](https://cloud.githubusercontent.com/assets/8818542/19543311/73c5ebe8-966e-11e6-9121-c02dc9d551af.png)

If I change to using node-chrome instead of node-chrome-debug, it does appear in the web ui console. What can I do to get the node-chrome-debug to appear in the console?

**Comment by emoshaya-cognito** [comment]
i just checked the node logs and I'm getting the following errors:

id/register
18:42:02.640 INFO - Couldn't register this node: Error sending the registration                                                                              request: The hub responded with 500:Server Error
18:42:07.643 INFO - Registering the node to the hub: http://selenium-hub:4444/grid/register
18:42:07.648 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
18:42:12.650 INFO - Registering the node to the hub: http://selenium-hub:4444/grid/register
18:42:12.654 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
18:42:17.657 INFO - Registering the node to the hub: http://selenium-hub:4444/grid/register
18:42:17.662 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error

**Comment by emoshaya-cognito** [comment]
Error log on the grid:

01:55:36.525 DEBUG - getting the following registration request  : {"class":"org.openqa.grid.common.RegistrationRequest","configuration":{"hubHost":"10.255.6.197","hubPort":4444,"id":"http://172.17.0.3:5555","capabilities":[{"browserName":"chrome","seleniumProtocol":"WebDriver","maxInstances":1,"platform":"LINUX"}],"hub":"http://10.255.6.197:4444/grid/register","nodeStatusCheckTimeout":5000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","register":true,"registerCycle":5000,"custom":{},"host":"172.17.0.3","maxSession":1,"browserTimeout":600000,"debug":false,"port":5555,"role":"node","timeout":500000}}
2016-10-20 01:55:36.525:WARN:osjs.ServletHandler:qtp1897115967-56: /grid/register
java.lang.NullPointerException
        at org.openqa.grid.common.RegistrationRequest.getNewInstance(RegistrationRequest.java:276)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:75)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

**Comment by joshstrange** [comment]
Why was this closed? @emoshaya-cognito did you find a fix? It's still throwing these errors for me.

**Comment by emoshaya-cognito** [comment]
Hi @joshstrange I solved the issue by using image version 3.0.0-dubnium for the hub and node as follows:

hub:
  image: selenium/hub:3.0.0-dubnium
  ports:
    - "4444:4444"
  volumes:
    - /var/lib/jenkins/workspace:/var/lib/jenkins/workspace
  environment:
    - GRID_TIMEOUT=500000
    - GRID_MAX_SESSION=50
    - GRID_BROWSER_TIMEOUT=600000

chrome:
  image: selenium/node-chrome-debug:3.0.0-dubnium
  ports:
    - "5900:5900"
  links:
    - hub
  volumes:
    - /dev/shm:/dev/shm
  volumes_from:
    - hub

**Comment by boyfromearth** [comment]
version 3.0.0-dubnium helped for me also!! But i still need it for version 2.53.1
