### ISSUE TITLE
Setting $GEOMETRY prevents XVFB from running

### ISSUE THREAD

**Issue by LusciousPear** [SeleniumHQ/docker-selenium#391]
## Meta -
Image(s):  node-chrome:3.0.1-fermium

Docker Version:  
Docker version 1.9.1, build a34a1d5

OS: 
Ubuntu 15.04

## Expected Behavior -
xvfb starts during "docker run"

## Actual Behavior -

Setting the environment variables in the Dockerfile:

```
ENV SCREEN_HEIGHT=1920 SCREEN_WIDTH=1080 SCREEN_DEPTH=32

```
Gives the error message ```xvfb-run: error: Xvfb failed to start``` when executing `entry_point.sh`

Using quote marks around the values, e.g. ```"1920"``` also gives the error. 

I am using ChromeDriver embedded in the jvm, not a standalone instance.

entry_point.sh:

```
#!/bin/bash
source /opt/bin/functions.sh

export GEOMETRY="$SCREEN_WIDTH""x""$SCREEN_HEIGHT""x""$SCREEN_DEPTH"

function shutdown {
  kill -s SIGTERM $NODE_PID
  wait $NODE_PID
}

if [ ! -z "$SE_OPTS" ]; then
  echo "appending selenium options: ${SE_OPTS}"
fi

SERVERNUM=$(get_server_num)

rm -f /tmp/.X*lock

xvfb-run -n $SERVERNUM --server-args="-screen 0 $GEOMETRY -ac +extension RANDR" \
  java ${JAVA_OPTS} -jar /opt/bin/project-snapshot.jar \
  ${SE_OPTS} &
NODE_PID=$!

trap shutdown SIGTERM SIGINT
wait $NODE_PID
```

**Comment by ddavison** [comment]
> Setting the environment variables in the Dockerfile:
> `ENV SCREEN_HEIGHT=1920 SCREEN_WIDTH=1080 SCREEN_DEPTH=32`

Are you actually setting these variables like this?  if so, it's not meant to run like that.  It's meant to run like:

`docker run -d --link selenium-hub:hub -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -e SCREEN_DEPTH=32 selenium/node-chrome:3.0.1-fermium`

**Comment by LusciousPear** [comment]
Thanks -- doing that causes a different error: 

```
Exception in thread "async-thread-macro-3" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at core.Driver.systemScreenshot(Driver.java:533)
	at core.Driver.systemScreenshot(Driver.java:517)
	at core.CrawlService.start(CrawlService.java:86)
	at core.CrawlService.start(CrawlService.java:44)
	at crawly.worker$start_async_consumers$fn__7312.invoke(worker.clj:28)
	at clojure.core.async$thread_call$fn__5623.invoke(async.clj:439)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "async-thread-macro-1" java.awt.AWTError: Can't connect to X11 window server using ':109' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at core.Driver.systemScreenshot(Driver.java:533)
	at core.Driver.systemScreenshot(Driver.java:517)
	at core.CrawlService.start(CrawlService.java:86)
	at core.CrawlService.start(CrawlService.java:44)
	at crawly.worker$start_async_consumers$fn__7312.invoke(worker.clj:28)
	at clojure.core.async$thread_call$fn__5623.invoke(async.clj:439)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by LusciousPear** [comment]
Update: a suggested fix was to set env var DISPLAY=:0, that did not help.

**Comment by LusciousPear** [comment]
I figured this out -- xvfb does not support screen depths > 32 bit.

**Comment by ddavison** [comment]
good to know!
