### ISSUE TITLE
Invalid selectors crash Chrome

### ISSUE THREAD

**Issue by pavelpp** [SeleniumHQ/docker-selenium#395]
## Meta -
Image(s):  
standalone-chrome-debug
Docker Version:  
3.0.1-germanium
OS: 
OSX Yosemite

When invalid selector is specified ( for example`By.xpath("//div[@class='test]")` ) then browser will crash with error:
```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'pavelp-mbp.local', ip: '192.168.26.43', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_66'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320), userDataDir=/tmp/.org.chromium.Chromium.ml3T2F}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=56.0.2924.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=15f8a89b-e1af-4389-a149-4d4096981521, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 15f8a89b-e1af-4389-a149-4d4096981521
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
  at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
  at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
  at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
  at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
```

## Expected Behavior 

1) Browser is supposed to report error like this:

```org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //div[@class='test] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//div[@class='test]' is not a valid XPath expression.
```
2) Browser should not crash

## Steps to reproduce

```driver.findElement(By.xpath("//div[@class='test]")).isDisplayed();```

**Comment by diemol** [comment]
@pavelpp I have seen this error before in some of my tests, where some quote is missing and then the whole thing breaks apart.
But this is a Selenium issue (the stack-trace tells you that), not a docker-selenium issue, I would close this issue here and open one over [there](https://github.com/SeleniumHQ/selenium/issues/new)

**Comment by pavelpp** [comment]
@diemol there was no problem when trying this with local chrome browser. Browser crashes only in docker. Will try this with the latest version and report back if it is still the case.

**Comment by diemol** [comment]
Hi @pavelpp, were you successful?

**Comment by pavelpp** [comment]
yes, it's working in the latest version. You can close it now
