### ISSUE TITLE
Selenium Hub Connections Refused

### ISSUE THREAD

**Issue by tparikka** [SeleniumHQ/docker-selenium#424]
## Meta -
Image(s):  

Docker Version:  

OS: 

I my framework uses Selenium 3.3.0 with C# bindings. My tests are driven with NUnit and I am attempting to run 6 tests concurrently. I am using docker-compose with the following YAML:

> selenium-hub:
>   image: selenium/hub:3.2.0
>   ports:
>     - "4444:4444"
>   environment:
>     - "GRID_MAX_SESSION=15"
>   shm_size: 2048MB
>   volumes:
>     - /dev/shm:/dev/shm
> 
> chrome:
>   image: selenium/node-chrome:3.2.0
>   links:
>     - selenium-hub:hub
>   shm_size: 1024MB
>   volumes:
>     - /dev/shm:/dev/shm

The volumes and shm_size values are provided to try and address the issue discussed [here](https://github.com/SeleniumHQ/docker-selenium#running-the-images) and [here](https://bugs.chromium.org/p/chromium/issues/detail?id=522853). I am starting the composition with **docker-compose up -d** and then **docker-compose scale chrome=12**.

I am intermittently running into an issue where the hub container enters a state where it is actively refusing connections. The error returned in Visual Studio 2017 is:

Test Name:	TESTNAME
Test FullName:	TESTFIXTURENAME(Chrome).TESTNAME
Test Source:	C:\source\TestAutomation\Main\Test.cs : line 27
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

```
Result Message:	
OneTimeSetUp: OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 10.10.1.10:4444
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
```

If I try to docker-compose up -d to get things started again, I get:

PS C:\SeleniumGrid\Docker> docker-compose up -d
Creating docker_selenium-hub_1

```
ERROR: for selenium-hub  Cannot start service selenium-hub: driver failed programming external connectivity on endpoint docker_selenium-hub_1 (c97a4212ace7e8f494d4876
0e3dd7a9f2751229d24acb4aa748ac5c9c34dfd58): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:4444:tcp:172.17.0.2:4444: input/output error
ERROR: Encountered errors while bringing up the project.
```

I have to entirely terminate Docker and restart it before I can run the hub again. If I run netstat -a, I get:

> Proto  Local Address          Foreign Address        State
> TCP    0.0.0.0:80             MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:135            MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:443            MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:445            MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1110           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1433           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1536           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1537           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1538           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1539           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1540           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1582           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:1591           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:2179           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:2701           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:3389           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:4155           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:5357           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:5985           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:8003           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:9000           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:9592           MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:16228          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:16279          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:16322          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:16863          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:44399          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:47001          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:49152          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:49153          MilwI-T560-TJP:0       LISTENING
> TCP    0.0.0.0:49154          MilwI-T560-TJP:0       LISTENING
> TCP    10.0.75.1:139          MilwI-T560-TJP:0       LISTENING
> TCP    10.1.1.71:139          MilwI-T560-TJP:0       LISTENING

So it appears nothing is actually listening on port 4444. Is there anything I am doing wrong with my setup, is this an issue with the hub container, or is this an issue entirely outside of the docker hub image?

## Expected Behavior -

Docker hub image supports high levels of parallel test execution.

## Actual Behavior -

At higher levels of parallel test execution, hub may crash/refuse connections.

**Comment by tparikka** [comment]
I added logs from the Docker container from an instance where the container seems to have crashed. After the crash, **docker ps** produces this result:

> PS C:\SeleniumGrid\Docker> docker ps
> CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                    NAMES
> 194972adff4f        selenium/node-chrome:3.2.0   "/opt/bin/entry_po..."   10 minutes ago      Up 10 minutes                                docker_chrome_3
> c8f8c65e8931        selenium/node-chrome:3.2.0   "/opt/bin/entry_po..."   10 minutes ago      Up 10 minutes                                docker_chrome_4
> bd6ed6141914        selenium/node-chrome:3.2.0   "/opt/bin/entry_po..."   10 minutes ago      Up 10 minutes                                docker_chrome_2
> 5764ce06f6f1        selenium/node-chrome:3.2.0   "/opt/bin/entry_po..."   10 minutes ago      Up 10 minutes                                docker_chrome_1
> d1fb08708b24        selenium/hub:3.2.0           "/opt/bin/entry_po..."   10 minutes ago      Up 10 minutes       0.0.0.0:4444->4444/tcp   docker_selenium-hub_1

While **netstat -a** shows this result:

> Active Connections
> 
>   Proto  Local Address          Foreign Address        State
>   TCP    0.0.0.0:80             MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:135            MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:443            MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:445            MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1110           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1433           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1536           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1537           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1538           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1539           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1540           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1582           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:1591           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:2179           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:2701           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:3389           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:4155           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:5357           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:5985           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:8003           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:9000           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:9592           MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:16228          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:16279          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:16322          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:16863          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:44399          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:47001          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:49152          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:49153          MilwI-T560-TJP:0       LISTENING
>   TCP    0.0.0.0:49154          MilwI-T560-TJP:0       LISTENING
>   TCP    10.0.75.1:139          MilwI-T560-TJP:0       LISTENING
>   TCP    10.1.1.71:139          MilwI-T560-TJP:0       LISTENING

So it seems as though the public facing listening port dies but the docker container is still running.

**Comment by tparikka** [comment]
This appears to be actually caused by docker/for-win#426.
