### ISSUE TITLE
NPE in standalone-chrome when setting `implicitlyWait`

### ISSUE THREAD

**Issue by phtrivier** [SeleniumHQ/docker-selenium#500]
## Meta -
Image(s):  
* standalone-node
Docker-Selenium Image Version(s):  
* 3.4.0
OS: 
* ubuntu 17.04 

## Expected Behavior -

* Start the image locally 

```
docker run -d -p 4444:4444 selenium/standalone-chrome:3.4.0-dysprosium
```

* Set env variable to test npm `selenium` package to use the image

```
export SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub
```

* Run a very basic script that just creates a driver

```
var webdriver = require('selenium-webdriver');
var chromeCapabilities = webdriver.Capabilities.chrome();
var driver = new webdriver.Builder().withCapabilities(chromeCapabilities).build();
driver.manage().timeouts().implicitlyWait(2000);
```

* The last line (setting `implicitlyWait`) triggers an NPE in the image: 

```
15:42:05.668 WARN - Exception thrown
java.lang.NullPointerException
	at org.openqa.selenium.remote.server.handler.ConfigureTimeout.setJsonParameters(ConfigureTimeout.java:39)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:99)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
```

## Actual Behavior -

It does not seem like the error prevents the test from working, but it polutes log, and I suspect it means I'm doing something wrong.

**Comment by diemol** [comment]
I was able to reproduce it both using the standalone container and also using the Selenium jar file directly, and therefore it is not a docker-selenium issue. 

That's why I created an issue in the Selenium repo: https://github.com/SeleniumHQ/selenium/issues/4221

@phtrivier, please follow that issue, I will close this one.

**Comment by bitliner** [comment]
@diemol has the fix been already included in the last versions of docker-selenium? in case, which versions?
