### ISSUE TITLE
Last Python Selenium version doesn't work with docker-selenium

### ISSUE THREAD

**Issue by marctc** [SeleniumHQ/docker-selenium#509]
## Meta
Image(s):  hub & node-firefox
Docker-Selenium Image Version(s):  >3
Python Selenium Version: >3.4
OS: Ubuntu 14.04, Ubuntu 16.04

## Actual Behavior

I have a `docker-compose` file as it's explained [here](https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose#step-1-write-the-docker-composeyml-file). I tried with the Python example of code that `Step 4` says. But the actual output when I run it is this:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    desired_capabilities=DesiredCapabilities.FIREFOX) 
  File "/home/marc/virtualenvs/puput-testing/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/marc/virtualenvs/puput-testing/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/marc/virtualenvs/puput-testing/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/marc/virtualenvs/puput-testing/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None
Stacktrace:
    at java.util.HashMap.putMapEntries (HashMap.java:500)
    at java.util.HashMap.putAll (HashMap.java:784)
    at org.openqa.selenium.remote.DesiredCapabilities.<init> (DesiredCapabilities.java:55)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:104)
    at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:67)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:841)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:543)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:1584)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1228)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:168)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:481)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:1553)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:166)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1130)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.seleniumhq.jetty9.server.Server.handle (Server.java:564)
    at org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:320)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:251)
    at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:279)
    at org.seleniumhq.jetty9.io.FillInterest.fillable (FillInterest.java:112)
    at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run (ChannelEndPoint.java:124)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:672)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:590)
    at java.lang.Thread.run (Thread.java:748)
```

However, if I run the last selenium version with `java -jar selenium-server-standalone-3.4.0.jar` it works.

I noticed this issue because the Travis CI of a OS project that I own started to failed throwing  the same above output without changing any relevant in the code:
- [passed build](https://travis-ci.org/APSL/puput/jobs/203143421#L523)
- [failed buld](https://travis-ci.org/APSL/puput/jobs/227396634#L704)

It seems that the last Python Selenium version don't work with any docker-selenium version (but it works with the standalone server). The valid combinations that worked for me were `selenium=<3.3.0` and `selenium/hub=<3.2.0`. For `selenium/hub>3.2.0` it doesn't throws you that error but the execution got freezed.

**Comment by lmtierney** [comment]
This is an issue with selenium grid, and is being worked on seleniumhq/selenium#3808

**Comment by lmtierney** [comment]
I should mention it's only in grid mode and standlone mode works fine
