### ISSUE TITLE
I got this issue

### ISSUE THREAD

**Issue by cherrym0856** [SeleniumHQ/docker-selenium#641]
org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.98 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'USL6SS9T32', ip: '10.23.92.222', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\nesr7001\AppData\Local\Temp\scoped_dir8588_25173}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=63.0.3239.84, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 62b36704d94593f49cef0f807b340784
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at com.nielsen.cloudapi.s2s.canary.browser.BrowserActions.appLogin(BrowserActions.java:55)
	at com.nielsen.cloudapi.s2s.canary.browser.BrowserTestSearchChannelAndPlay.loadConfig(BrowserTestSearchChannelAndPlay.java:64)
	at com.nielsen.cloudapi.s2s.canary.browser.BrowserTestSearchChannelAndPlay.main(BrowserTestSearchChannelAndPlay.java:47)
java.lang.IllegalStateException: Proxy server is already stopped. Cannot re-stop.
	at net.lightbody.bmp.BrowserMobProxyServer.stop(BrowserMobProxyServer.java:417)
	at net.lightbody.bmp.BrowserMobProxyServer.stop(BrowserMobProxyServer.java:396)
	at com.nielsen.cloudapi.s2s.canary.browser.BrowserTestSearchChannelAndPlay.loadConfig(BrowserTestSearchChannelAndPlay.java:99)
	at com.nielsen.cloudapi.s2s.canary.browser.BrowserTestSearchChannelAndPlay.main(BrowserTestSearchChannelAndPlay.java:47)

**Comment by diemol** [comment]
Hi @cherrym0856,

I think you are not using any of the docker-selenium images from this repo.

For example, you are using Chrome=63.0.3239.84 with ChromeDriver=2.29.461591 on Windows NT 10.0.15063 x86_64. And we don't have an image like that.

If you are having any issues with the docker images, feel free to open an issue providing enough information for us to help with it.
