### ISSUE TITLE
Capabilities for new requested session include unexpected versions of browser, Selenium

### ISSUE THREAD

**Issue by gabe-connolly** [SeleniumHQ/docker-selenium#728]
## Meta
Image(s):
node-chrome:3.11.0-dysprosium
node-firefox:3.11.0-dysprosium

Docker-Selenium Image Version(s):  
3.11.0-dysprosium

Docker Version:  
18.03.0-ce
OS: 
OSX High Sierra (10.13.4)

## Expected Behavior

I should be able to run a Behat test that requires javascript without errors between the Selenium Hub and Node(s)
## Actual Behavior
When I try to run a Behat test that requires javascript, it fails with the following error:

```
Could not open connection: Error forwarding the new session cannot find : Capabilities {browser: 
firefox, browserName: chrome, browserVersion: 9, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: Behat feature suite, selenium-version: 2.31.0, tags: [lcdockertest, PHP 7.2.4], version: 9} (Behat\Mink\Exception\DriverException)
```

When I tail the log inside my selenium-hub container, the log reads:
```
19:37:51.337 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browser: firefox, browserName: chrome, browserVersion: 9, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: Behat feature suite, selenium-version: 2.31.0, tags: [lcdockertest, PHP 7.2.4], version: 9}
19:37:51.338 INFO [RequestHandler.process] - Error forwarding the new session cannot find : Capabilities {browser: firefox, browserName: chrome, browserVersion: 9, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: Behat feature suite, selenium-version: 2.31.0, tags: [lcdockertest, PHP 7.2.4], version: 9}
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {browser: firefox, browserName: chrome, browserVersion: 9, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: Behat feature suite, selenium-version: 2.31.0, tags: [lcdockertest, PHP 7.2.4], version: 9}
	at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:153)
	at org.openqa.grid.internal.DefaultGridRegistry.addNewSessionRequest(DefaultGridRegistry.java:217)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:111)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
```

I am running my Docker Containers with docker-compose.

The error response I see when running Behat is confusing for several reasons:
* When I run inspect the docker logs for my chrome container, I see `Selenium build info: version: '3.11.0'`.  This version is expected, but makes the `selenium-version: 2.31.0` in the error message strange to see. I would expect the version to be the same throughout.
* I am not sure where `browserVersion: 9` is coming from in the error either, as that is not specified anyway, and falls way below the current versions of Chrome or Firefox I see in my containers

**Additional information:**

Behat.yml configuration
```
base_url: http://lcdockertest
browser_name: chrome
default_session: goutte
javascript_session: selenium2
goutte: ~
selenium2:
    wd_host: 'http://selenium-hub:4444/wd/hub'
```

Key bits from docker-compose.yml configuration:
```
version: '3.1'

services:
  # Set up the database container
  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql
    ports:
      - 8081:3306

  # Set up the Wordpress container
  wordpress:
    image: libertyconcepts/wp-docker
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
      - selenium-hub
      - chrome
      - firefox
    extra_hosts:
      - "${PROJECT_NAME} ${PROJECT_NAME}.localdomain:127.0.0.1"
    hostname: ${PROJECT_NAME}
    ports:
      - 80:80
      - 443:443
      - 3001:3001
      - 3002:3002

  # Selenium Testing services
  selenium-hub:
    image: selenium/hub:3.11.0-dysprosium
    container_name: selenium-hub
    ports:
      - "4444"
  chrome:
    image: selenium/node-chrome:3.11.0-dysprosium
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.11.0-dysprosium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
```

Any input here would be much appreciated!

**Comment by diemol** [comment]
Hi @gabe-connolly,

Sorry for the late reply, I can see in the sent capabilities this:
>
Capabilities {**browser: 
firefox, browserName: chrome, browserVersion: 9**, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: Behat feature suite, selenium-version: 2.31.0, tags: [lcdockertest, PHP 7.2.4], version: 9} (Behat\Mink\Exception\DriverException)

And it is not possible for docker-selenium to fulfil a capability request with two browsers and a version so old.

Please double check the configuration for the tests you are running.

Feel free to reopen if there is a bug related to the docker containers.

**Comment by gabe-connolly** [comment]
Thanks for the reply, @diemol .  Using your input, I was able to finally get my javascript tests running by modifying my behat selenium settings:

```
Behat\MinkExtension:
      base_url: http://wordpress
      browser_name: chrome
      default_session: goutte
      javascript_session: selenium2
      goutte: ~
      # https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities
      selenium2:
        browser: chrome
        wd_host: 'http://selenium-hub:4444/wd/hub'
        capabilities: { browser: chrome, browserVersion: 66.0.3359.117, version: 66.0.3359.117}
```

The two changes I had to make were:
* Add `capabilities: { browser: chrome, browserVersion: 66.0.3359.117, version: 66.0.3359.117}`
* Modify `base_url` to use `base_url: http://wordpress` (wordpress is the name of the docker web container).

What's interesting is that on another project I have running, I'm able to run Javascript tests without specify any selenium2 capabilities.  In this case though, for some reason it looks like the capabilities have to be explicitly defined, or they get the low browser versions and types from the initial error.
