### ISSUE TITLE
Timeout issues with stack - hub and firefox node

### ISSUE THREAD

**Issue by mikebski** [SeleniumHQ/docker-selenium#750]
I have the following stack file:

```
services:
  hub:
    image: selenium/hub:3.12.0-cobalt
    environment:
      SE_OPTS: '-debug'
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /dev/random
        target: /dev/random
    networks:
      selenium:
        aliases:
          - selenium-hub
  firefox:
    image: selenium/node-firefox:3.12.0-cobalt
    environment:
      HUB_HOST: 'selenium-hub'
      SE_OPTS: '-debug -host firefox-node -port 5555'
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /dev/random
        target: /dev/random
    networks:
      selenium:
        aliases:
          - firefox-node
networks:
  selenium:
    external: true
```

Here's what I see when the process starts up:

```
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | starting selenium hub with configuration:
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | {
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "host": "0.0.0.0",
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "port": 4444,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "role": "hub",
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "maxSession": 5,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "newSessionWaitTimeout": -1,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "throwOnCapabilityNotPresent": true,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "jettyMaxThreads": -1,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "cleanUpCycle": 5000,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "browserTimeout": 0,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "timeout": 30,
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    |   "debug": false
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | }
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | appending selenium options: -debug
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:48.328 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.12.0', revision: '7c6e0b3'
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:48.330 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 2018-07-05 14:09:48.847:INFO::main: Logging initialized @1695ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:49.519 INFO [Hub.start] - Selenium Grid hub is up and running
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:49.525 INFO [Hub.start] - Nodes should register to http://172.22.0.5:4444/grid/register/
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:49.527 INFO [Hub.start] - Clients should connect to http://172.22.0.5:4444/wd/hub
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.248 DEBUG [RegistrationServlet.process] - getting the following registration request  : {"class":{"enclosingConstructor":null,"annotations":[],"memberClass":false,"declaredConstructors":[null,null,null,null],"declaredFields":[null,null,null,null,null,null,null],"superclass":{"enclosingConstructor":null,"annotations":[],"memberClass":false,"declaredConstructors":[null],"declaredFields":[],"superclass":null,"canonicalName":"java.lang.Object","package":null,"protectionDomain":null,"enclosingMethod":null,"enum":false,"declaringClass":null,"synthetic":false,"constructors":[null],"declaredClasses":[],"name":"java.lang.Object","fields":[],"classLoader":null,"primitive":false,"methods":[null,null,null,null,null,null,null,null,null],"classes":[],"typeName":"java.lang.Object","declaredMethods":[null,null,null,null,null,null,null,null,null,null,null,null],"modifiers":1,"interface":false,"genericInterfaces":[],"typeParameters":[],"annotatedSuperclass":null,"array":false,"enumConstants":null,"annotatedInterfaces":[],"class":"java.lang.Class","componentType":null,"declaredAnnotations":[],"interfaces":[],"genericSuperclass":null,"localClass":false,"enclosingClass":null,"signers":null,"simpleName":"Object","anonymousClass":false},"canonicalName":"org.openqa.grid.common.RegistrationRequest","package":{"specificationVendor":"Oracle Corporation","declaredAnnotations":[],"implementationVersion":"9.4.7.v20170914","sealed":false,"annotations":[],"implementationTitle":"HttpComponents Apache HttpClient Mime","hCode":-250690871,"packages":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"specificationTitle":"HttpComponents Apache HttpClient Mime","implementationVendor":"Eclipse.org - Jetty","name":"org.openqa.grid.common","class":"java.lang.Package","specificationVersion":"3.1"},"protectionDomain":{"classLoader":null,"permissions":null,"principals":[],"codeSource":null,"class":"java.security.ProtectionDomain"},"enclosingMethod":null,"enum":false,"declaringClass":null,"synthetic":false,"constructors":[null,null,null,null],"declaredClasses":[],"name":"org.openqa.grid.common.RegistrationRequest","fields":[null,null,null],"classLoader":{"parent":null,"systemClassLoader":null,"uRLs":["file:/opt/selenium/selenium-server-standalone.jar"],"class":"sun.misc.Launcher$AppClassLoader"},"primitive":false,"methods":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"classes":[],"typeName":"org.openqa.grid.common.RegistrationRequest","declaredMethods":[null,null,null,null,null,null,null,null,null,null],"modifiers":1,"interface":false,"genericInterfaces":[],"typeParameters":[],"annotatedSuperclass":{"declaredAnnotations":[],"annotations":[],"type":null,"class":"sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl"},"array":false,"enumConstants":null,"annotatedInterfaces":[],"class":"java.lang.Class","componentType":null,"declaredAnnotations":[],"interfaces":[],"genericSuperclass":{"enclosingConstructor":null,"annotations":[],"memberClass":false,"declaredConstructors":[null],"declaredFields":[],"superclass":null,"canonicalName":"java.lang.Object","package":null,"protectionDomain":null,"enclosingMethod":null,"enum":false,"declaringClass":null,"synthetic":false,"constructors":[null],"declaredClasses":[],"name":"java.lang.Object","fields":[],"classLoader":null,"primitive":false,"methods":[null,null,null,null,null,null,null,null,null],"classes":[],"typeName":"java.lang.Object","declaredMethods":[null,null,null,null,null,null,null,null,null,null,null,null],"modifiers":1,"interface":false,"genericInterfaces":[],"typeParameters":[],"annotatedSuperclass":null,"array":false,"enumConstants":null,"annotatedInterfaces":[],"class":"java.lang.Class","componentType":null,"declaredAnnotations":[],"interfaces":[],"genericSuperclass":null,"localClass":false,"enclosingClass":null,"signers":null,"simpleName":"Object","anonymousClass":false},"localClass":false,"enclosingClass":null,"signers":null,"simpleName":"RegistrationRequest","anonymousClass":false},"configuration":{"unregisterIfStillDownAfter":60000,"role":"node","debug":false,"capabilities":[{"applicationName":"","browserName":"firefox","maxInstances":1,"moz:firefoxOptions":{"log":{"level":"info"}},"platform":"LINUX","platformName":"LINUX","seleniumProtocol":"WebDriver","server:CONFIG_UUID":"d6283805-1fa9-41ea-9ad2-66e610a57d84","version":"60.0.2"}],"remoteHost":"http://firefox-node:5555","custom":{},"nodeStatusCheckTimeout":5000,"downPollingLimit":2,"timeout":1800,"nodePolling":5000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","hub":"http://selenium-hub:4444/grid/register","port":5555,"browserTimeout":0,"host":"firefox-node","servlets":[],"enablePlatformVerification":true,"id":"http://firefox-node:5555","withoutServlets":[],"maxSession":1,"registerCycle":5000,"register":true},"description":null,"name":null}
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.337 DEBUG [BaseRemoteProxy.getNewInstance] - Using class org.openqa.grid.selenium.proxy.DefaultRemoteProxy
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.363 DEBUG [BaseRemoteProxy.setupTimeoutListener] - starting cleanup thread
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.373 DEBUG [BaseRemoteProxy$CleanUpThread.run] - cleanup thread starting...
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.386 INFO [DefaultGridRegistry.add] - Registered a node http://firefox-node:5555
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:52.403 DEBUG [RegistrationServlet.lambda$process$0] - proxy added http://firefox-node:5555
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:09:58.033 DEBUG [DefaultRemoteProxy.isAlive] - Failed to check status of node: Failed to connect to firefox-node/10.0.5.139:5555
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:10:03.056 DEBUG [DefaultRemoteProxy.isAlive] - Failed to check status of node: Failed to connect to firefox-node/10.0.5.139:5555
selenium_hub.1.i7ztibt1tk2q@linuxkit-025000000001    | 14:10:03.056 INFO [DefaultRemoteProxy.onEvent] - Marking the node http://firefox-node:5555 as down: cannot reach the node for 2 tries
^C

```

Why do I get a message like `Failed to check status of node: Failed to connect to firefox-node/10.0.5.139:5555`?  This is not a good URL

If I remove the `-host firefox-node -port 5555` I have this stack file:

```
version: "3.3"
services:
  hub:
    image: selenium/hub:3.12.0-cobalt
    environment:
      SE_OPTS: '-debug'
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /dev/random
        target: /dev/random
    networks:
      selenium:
        aliases:
          - selenium-hub
  firefox:
    image: selenium/node-firefox:3.12.0-cobalt
    environment:
      HUB_HOST: 'selenium-hub'
      SE_OPTS: '-debug'
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: bind
        source: /dev/random
        target: /dev/random
    networks:
      selenium:
        aliases:
          - firefox-node
networks:
  selenium:
    external: true
```

I get this in the log (looks OK):

```
t Mime","hCode":-250690871,"packages":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"specificationTitle":"HttpComponents Apache HttpClient Mime","implementationVendor":"Eclipse.org - Jetty","name":"org.openqa.grid.common","class":"java.lang.Package","specificationVersion":"3.1"},"protectionDomain":{"classLoader":null,"permissions":null,"principals":[],"codeSource":null,"class":"java.security.ProtectionDomain"},"enclosingMethod":null,"enum":false,"declaringClass":null,"synthetic":false,"constructors":[null,null,null,null],"declaredClasses":[],"name":"org.openqa.grid.common.RegistrationRequest","fields":[null,null,null],"classLoader":{"parent":null,"systemClassLoader":null,"uRLs":["file:/opt/selenium/selenium-server-standalone.jar"],"class":"sun.misc.Launcher$AppClassLoader"},"primitive":false,"methods":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"classes":[],"typeName":"org.openqa.grid.common.RegistrationRequest","declaredMethods":[null,null,null,null,null,null,null,null,null,null],"modifiers":1,"interface":false,"genericInterfaces":[],"typeParameters":[],"annotatedSuperclass":{"declaredAnnotations":[],"annotations":[],"type":null,"class":"sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl"},"array":false,"enumConstants":null,"annotatedInterfaces":[],"class":"java.lang.Class","componentType":null,"declaredAnnotations":[],"interfaces":[],"genericSuperclass":{"enclosingConstructor":null,"annotations":[],"memberClass":false,"declaredConstructors":[null],"declaredFields":[],"superclass":null,"canonicalName":"java.lang.Object","package":null,"protectionDomain":null,"enclosingMethod":null,"enum":false,"declaringClass":null,"synthetic":false,"constructors":[null],"declaredClasses":[],"name":"java.lang.Object","fields":[],"classLoader":null,"primitive":false,"methods":[null,null,null,null,null,null,null,null,null],"classes":[],"typeName":"java.lang.Object","declaredMethods":[null,null,null,null,null,null,null,null,null,null,null,null],"modifiers":1,"interface":false,"genericInterfaces":[],"typeParameters":[],"annotatedSuperclass":null,"array":false,"enumConstants":null,"annotatedInterfaces":[],"class":"java.lang.Class","componentType":null,"declaredAnnotations":[],"interfaces":[],"genericSuperclass":null,"localClass":false,"enclosingClass":null,"signers":null,"simpleName":"Object","anonymousClass":false},"localClass":false,"enclosingClass":null,"signers":null,"simpleName":"RegistrationRequest","anonymousClass":false},"configuration":{"unregisterIfStillDownAfter":60000,"role":"node","debug":false,"capabilities":[{"applicationName":"","browserName":"firefox","maxInstances":1,"moz:firefoxOptions":{"log":{"level":"info"}},"platform":"LINUX","platformName":"LINUX","seleniumProtocol":"WebDriver","server:CONFIG_UUID":"8f258efc-e554-4e80-a77f-4db7e0e5f7ac","version":"60.0.2"}],"remoteHost":"http://172.22.0.4:5555","custom":{},"nodeStatusCheckTimeout":5000,"downPollingLimit":2,"timeout":1800,"nodePolling":5000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","hub":"http://selenium-hub:4444/grid/register","port":5555,"browserTimeout":0,"host":"172.22.0.4","servlets":[],"enablePlatformVerification":true,"id":"http://172.22.0.4:5555","withoutServlets":[],"maxSession":1,"registerCycle":5000,"register":true},"description":null,"name":null}
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.057 DEBUG [BaseRemoteProxy.getNewInstance] - Using class org.openqa.grid.selenium.proxy.DefaultRemoteProxy
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.081 DEBUG [BaseRemoteProxy.setupTimeoutListener] - starting cleanup thread
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.104 DEBUG [BaseRemoteProxy$CleanUpThread.run] - cleanup thread starting...
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.124 INFO [DefaultGridRegistry.add] - Registered a node http://172.22.0.4:5555
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.147 DEBUG [RegistrationServlet.lambda$process$0] - proxy added http://172.22.0.4:5555
```

When I try to get a session, I get this:

```
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.124 INFO [DefaultGridRegistry.add] - Registered a node http://172.22.0.4:5555
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:13:51.147 DEBUG [RegistrationServlet.lambda$process$0] - proxy added http://172.22.0.4:5555
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:14:47.931 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: firefox}
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:14:47.940 DEBUG [ProxySet.getNewSession] - Available nodes: [http://172.22.0.4:5555]
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:14:47.943 DEBUG [BaseRemoteProxy.getNewSession] - Trying to create a new session on node http://172.22.0.4:5555
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:14:47.944 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=8f258efc-e554-4e80-a77f-4db7e0e5f7ac, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=1, moz:firefoxOptions={log={level=info}}, platformName=LINUX, version=60.0.2, applicationName=, platform=LINUX}


selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:15:56.553 DEBUG [DefaultRemoteProxy.isAlive] - Failed to check status of node: connect timed out
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:16:48.095 INFO [RequestHandler.process] - Error forwarding the new session Error forwarding the request connect timed out
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request connect timed out
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.lang.Thread.run(Thread.java:748)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | Caused by: java.net.SocketTimeoutException: connect timed out
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.PlainSocketImpl.socketConnect(Native Method)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at java.net.Socket.connect(Socket.java:589)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at okhttp3.RealCall.execute(RealCall.java:77)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:430)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.internal.TestSession.forward(TestSession.java:237)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    |  ... 34 more

```

What am I doing wrong?

After a few minutes, I get this:

```
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:18:01.653 DEBUG [DefaultRemoteProxy.isAlive] - Failed to check status of node: connect timed out
selenium_hub.1.jdyh37wc97jy@linuxkit-025000000001    | 14:18:01.654 INFO [DefaultRemoteProxy.onEvent] - Marking the node http://172.22.0.4:5555 as down: cannot reach the node for 2 tries
```

**Comment by diemol** [comment]
Hi @mikebski,

Could you please post a more complete docker-compose file? I tried it and I just got a bunch of errors. In addition, we miss all the information about the OS and how the stack is started.

Basically, please fill the template to create issues so we can check if there is something wrong.

**Comment by diemol** [comment]
Closing as we didn't get an answer. If there is still an issue, feel free to comment and reopen with a clear way to reproduce the issue.
