### ISSUE TITLE
ERROR: Tried to run command without establishing a connection

### ISSUE THREAD

**Issue by BinduDMC** [SeleniumHQ/docker-selenium#925]
This is my docker-compose:
```yaml
version: "3.7"

services:
    app:
        build:
            context: ./
        image: test_app
        volumes:
            - .:/var/code:cached
        links:
            - selenium
    selenium:
        image: selenium/standalone-firefox:3.141.59-palladium
        expose:
            - "4444"

```
I am running the tests on Travis and the tests run fine with standalone-chrome but experiencing issues running with standalone-firefox

This is my Travis - 
```yaml
sudo: required
dist: trusty
services:
    - docker
before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

before_script:
    - npm install
    - docker-compose up -d selenium

script:
    - docker-compose run app /bin/sh -c "ENVIRONMENT=prod DIRECTORY=MA npm run test -- --cucumberOpts.tagExpression='@smokeTestFR' --host selenium"
```

This is the error I am getting on Travis - 
```
ERROR: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '38dab697c4c1', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_212'
Driver info: driver.version: unknown
firefox
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR: No active session with ID 5676e28e-527a-435c-84dd-0200b1c0243e
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:38) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
(node:38) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '38dab697c4c1', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_212'
Driver info: driver.version: unknown
firefox
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR: No active session with ID cea6dabb-4fb0-42b8-8f72-5ac698ad8c25
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:51) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
(node:51) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
https://www.mon-avocat.fr/trouver/avocats/france/
https://www.mon-avocat.fr/trouver/avocats/Dijon/
https://www.mon-avocat.fr/trouver/avocats/france/divorce
https://www.mon-avocat.fr/trouver/avocats/Paris/droit-civil
ERROR: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '38dab697c4c1', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_212'
Driver info: driver.version: unknown
firefox
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR: No active session with ID 8dfe20d7-7d54-40c7-a561-1540e6949dd7
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:64) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
(node:64) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '38dab697c4c1', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_212'
Driver info: driver.version: unknown
firefox
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR: No active session with ID 0f7e0bcf-fe45-47fe-b219-c82296759a65
    at new RuntimeError (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/code/node_modules/wdio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/var/code/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/var/code/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/var/code/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
==================================================================
Number of specs: 4
Wrote xunit report "WDIO.xunit.firefox.0-0.xml" to [./test/reports/junit-results/].
Wrote xunit report "WDIO.xunit.firefox.0-1.xml" to [./test/reports/junit-results/].
Wrote xunit report "WDIO.xunit.firefox.0-2.xml" to [./test/reports/junit-results/].
Wrote xunit report "WDIO.xunit.firefox.0-3.xml" to [./test/reports/junit-results/].
Wrote json report to [./test/reports/json-results/].
Wrote json report to [./test/reports/json-results/].
Wrote json report to [./test/reports/json-results/].
Wrote json report to [./test/reports/json-results/].
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DD_e2e_tests@1.0.0 test: `node node_modules/wdio/node_modules/webdriverio/bin/wdio ./test/config/suite.cucumber.conf.js "--cucumberOpts.tagExpression=@smokeTestFR" "--host" "selenium"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DD_e2e_tests@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-07T10_47_09_464Z-debug.log
The command "docker-compose run app /bin/sh -c "ENVIRONMENT=[secure] DIRECTORY=MA npm run test -- --cucumberOpts.tagExpression='@smokeTestFR' --host selenium"" exited with 1.
Done. Your build exited with 1.
```

**Comment by ddavison** [comment]
looking at that stack trace, i don't believe the issue resides with `docker-selenium`.  it could be `wdio` or `cucumber`. i'd look into those first.
