### ISSUE TITLE
Getting Error while running .isElementDisplayed() protocol action: TypeError [ERR_UNESCAPED_CHARACTERS]: Error while trying to create HTTP request for "/wd/hub/session/ca3ddfb1ba3c7b78a02c30964e20c1c7/element/[object Object]/displayed": Request path contains unescaped characters after upgrading to palladium 

### ISSUE THREAD

**Issue by pegeokha** [SeleniumHQ/docker-selenium#927]
I just upgraded to selenium/standalone-chrome-debug:3.141.59-palladium. I started getting this error:
 Error while running .isElementDisplayed() protocol action: TypeError [ERR_UNESCAPED_CHARACTERS]: Error while trying to create HTTP request for "/wd/hub/session/ca3ddfb1ba3c7b78a02c30964e20c1c7/element/[object Object]/displayed": Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (http.js:42:10)
    at HttpRequest.createHttpRequest 
(/node_modules/nightwatch/lib/http/request.js:112:55)
    at HttpRequest.send (/node_modules/nightwatch/lib/http/request.js:191:29)
    at Promise 
(/node_modules/nightwatch/lib/transport/transport.js:208:15)
    at new Promise (<anonymous>)
    at Selenium2Protocol.sendProtocolAction 
(/node_modules/nightwatch/lib/transport/transport.js:206:12)
    at Selenium2Protocol.runProtocolAction (/node_modules/nightwatch/lib/transport/jsonwire.js:55:17)
    at Object.target.(anonymous function).definition [as isElementDisplayed] (/node_modules/nightwatch/lib/transport/actions.js:46:33)
    at Selenium2Protocol.executeProtocolAction (/node_modules/nightwatch/lib/transport/transport.js:451:48)
    at CommandInstance.checkElementVisible 
(/node_modules/nightwatch/lib/api/element-commands/_waitForElement.js:276:20)
    at CommandInstance.elementFound 
(/node_modules/nightwatch/lib/api/element-commands/waitForElementVisible.js:44:17)
    at getProtocolCommand.then.result 
(/node_modules/nightwatch/lib/api/element-commands/_waitForElement.js:258:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by pegeokha** [comment]
Was not an issue related to that release, it was a nightwatch issue

**Comment by jkilada** [comment]
What was the nightwatch issue? Seeing a similar error.

**Comment by jkilada** [comment]
Actually I think I found it: https://github.com/nightwatchjs/nightwatch/releases/tag/v1.1.12
