### ISSUE TITLE
Cannot execute cucumber scripts on latest containers xenon

### ISSUE THREAD

**Issue by mnohai-mdsol** [SeleniumHQ/docker-selenium#979]
## To Reproduce
Executing a feature file with cucumber 2.99 causes issues that previously worked with all other versions of released containers.

```
can't modify frozen String (FrozenError)
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/backtrace_filter.rb:22:in `gsub!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/backtrace_filter.rb:22:in `block in exception'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/backtrace_filter.rb:22:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/backtrace_filter.rb:22:in `exception'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:1003:in `filtered_exception'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:989:in `describe_exception_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/ast.rb:90:in `describe_exception_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/ast.rb:76:in `accept'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/ast.rb:40:in `block in accept'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/ast.rb:40:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/ast.rb:40:in `accept'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:547:in `after'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:540:in `after_test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:260:in `after_test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:99:in `after_test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/legacy_api/adapter.rb:43:in `after_test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/runtime.rb:67:in `run!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/lib/cucumber/cli/main.rb:32:in `execute!'
/usr/local/lib/ruby/gems/2.5.0/gems/cucumber-2.99.0/bin/cucumber:8:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>
```

## Expected behavior

I should be able to execute my scripts by running
```
bundle exec cucumber features/testapp/smoke_test.feature
```

## Environment
OS: macOS
Docker-Selenium image version: 3.141.59-xenon
Docker version: 2.1.0.4

**Comment by ddavison** [comment]
I'm not sure this is stemming from our containers.  This looks like a ruby `frozen_string_literal` issue.

See https://www.rubyguides.com/2016/01/ruby-mutability/ .

This might even be an issue to report to Cucumber
